### ISSUE TITLE
[Bug] Hardware encoding not working properly linux

### ISSUE THREAD

**Issue by developer-iname** [Vencord/Vesktop#1004]
### Operating System

Linux(Arch)

### Linux Only ~ Desktop Environment

Sway

### Package Type

pipewire wireplumber xdg-desktop-wlr xdg-desktop-portal mesa

### What happens when the bug or crash occurs?

Stream is unviewable

### What is the expected behaviour?

I expect discord to stream and be viewable for others.

Actual result:
Others see an infinite loading screen, or the stream is garbled mess of black and white with some visible screen elements.

On launching vesktop from the terminal i see this
ERROR:vaapi_video_decoder.cc(1225)] failed Initialize()ing the frame pool

Which I believe is the culprit, I have not found a solution, however I believe it may be that vesktop is fallbacking to software decoding. As if the person recieving the stream on the other end disables their hardware encoding, it fixes the issue.

Also, perfomance while streaming is degraded massively.

### How do you recreate this bug or crash?

1. Stream
2. Receiver sees errors
3. End Stream
4. Receiver turns off hardware acceleration
5. Stream
6. Receiver sees stream

### Debug Logs

```
ERROR:vaapi_video_decoder.cc(1225)] failed Initialize()ing the frame pool
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by mazeratibooloo** [comment]
Also having this exact same issue, I've been having it for nearly a week now. On Arch / KDE Plasma.

**Comment by Skeletonek** [comment]
Have the same issue as you but my has been closed (https://github.com/Vencord/Vesktop/issues/997)
I am having the same error in console regarding va-api drivers on my Arch Linux system (Mesa 24.3.1)

I've checked running Vesktop 1.5.4 Appimage through distrobox running Ubuntu Noble with Mesa 24.0.9 and the stream seems to be working properly there. Running natively on arch is causing the stream to be super dark for the viewers of official discord client

**Comment by mazeratibooloo** [comment]
If they plan to close this one similarly, it'd be nice to have an explanation further than marking the issue with tags and then just closing it. If it's not fixable by Vesktop and it's an issue with something else, it'd be great to know where to post an issue up about it.

**Comment by Kerko0** [comment]
Getting the same error and it seems to not matter whether the reciever is using Vesktop or the official Discord client (on Windows too). I'm using Vesktop on Linux and whenever I try screensharing it infinitely loads for the reciever. And like you explained in the repro steps I asked her to disable hardware acceleration and after that she could view the stream.

**Comment by Vendicated** [comment]
> If it's not fixable by Vesktop and it's an issue with something else, it'd be great to know where to post an issue up about it.

I don't know. It could be Chromium, Electron, Discord, your system, etc

It works flawlessly for me (rpm package on Fedora + Gnome (Wayland)) so it's definitely an issue specific to your systems

**Comment by Kerko0** [comment]
Narrowing it down further it seems to be an issue with Vesktop and X11. Since that's what I use. I switched to another discord client and screensharing worked just fine there.

**Comment by Skeletonek** [comment]
I'm using wayland and the issue is present there so it's not only X11
I'm wondering if this is connected to the mesa driver / va-api version.

Arch
```
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Mesa Gallium driver 24.3.1-arch1.3 for AMD Radeon RX 6600 (radeonsi, navi23, LLVM 18.1.8, DRM 3.59, 6.12.4-arch1-1)
```

Ubuntu Noble via Distrobox
```
vainfo: VA-API version: 1.20 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 24.0.9-0ubuntu0.3 for AMD Radeon RX 6600 (radeonsi, navi23, LLVM 17.0.6, DRM 3.59, 6.12.4-arch1-1)
```

**Comment by Kerko0** [comment]
Interesting observation though the 2.22.0 version of libva was released back in July and this issue didn't start until a few days ago for me. (should note that i also use Arch which does line up with the issue being persistent on mostly Arch systems). Either way like I said I tried a different discord client (GoofCord) and screensharing seemed to work fine so maybe that's a clue. Could do more poking around tomorrow with different scenarios if no one has any more clues by then

**Comment by mazeratibooloo** [comment]
> > If it's not fixable by Vesktop and it's an issue with something else, it'd be great to know where to post an issue up about it.
> 
> I don't know. It could be Chromium, Electron, Discord, your system, etc
> 
> It works flawlessly for me (rpm package on Fedora + Gnome (Wayland)) so it's definitely an issue specific to your systems

This is understandable. Thanks for the clarification nonetheless. My only guess is it's VA-API related since that's the error we're seeing popup. But yeah, it would appear to be unrelated. I'm gonna re-test with the Flatpak version and see if that helps.

**Comment by ZacharyVarney** [comment]
It is not just happening on there systems I'm also getting it on fully up to date CachyOS system which is (Arch) based

**Comment by Vendicated** [comment]
seems as though the vast majority of people experiencing this use Arch Linux. like Łukasz said, it might be related to a regression in the new version of *some* driver

You could also try downgrading Vesktop to [1.5.3](https://github.com/Vencord/Vesktop/releases/tag/v1.5.3) and [1.5.2](https://github.com/Vencord/Vesktop/releases/tag/v1.5.2) to see if it was a regression in electron / chromium. Both of those releases upgraded the major version of electron. Do not go lower than those versions though because otherwise it will likely mess up your Vesktop settings

**Comment by mazeratibooloo** [comment]
> seems as though the vast majority of people experiencing this use Arch Linux. like Łukasz said, it might be related to a regression in the new version of _some_ driver
> 
> You could also try downgrading Vesktop to [1.5.3](https://github.com/Vencord/Vesktop/releases/tag/v1.5.3) and [1.5.2](https://github.com/Vencord/Vesktop/releases/tag/v1.5.2) to see if it was a regression in electron / chromium. Both of those releases upgraded the major version of electron. Do not go lower than those versions though because otherwise it will likely mess up your Vesktop settings

Downgrading to 1.5.3 fixed it on my system.

**Comment by Vendicated** [comment]
then it's an electron / chromium regression. you should try creating a minimal electron reproduction app and report it to electron

**Comment by ArbitraryRenaissance** [comment]
I'm trying to downgrade, but the AppImage seems to be forcing the latest version when I run it.  I do not have auto-update enabled in my settings.

**Comment by ArbitraryRenaissance** [comment]
Okay, I ended up successfully downgrading to 1.5.2, but the issue persisted for me.

**Comment by mazeratibooloo** [comment]
I was going to add that my appimage kept updating too. Trying to downgrade the Flatpak also didn't work either. Doesn't seem too easy to downgrade.

**Comment by Kyr4l** [comment]
not only arch is affected but also OpenSUSE TW since a few weeks
screensharing is unusable, it would be nice to have a dedicated thread for all the users experiencing this problem, hunting for non-locked issues on github will make it hard for everyone to find a solution.

**Comment by ghost** [comment]
Can I use hardware acceleration when screen sharing? I use Cinnamon on Void Linux and X11. No dedicated hardware here, only integrated hardware; The device is Thinkpad T480 i5-8th gen. Thank you

**Comment by Kyr4l** [comment]
> Can I use hardware acceleration when screen sharing? I use Cinnamon on Void Linux and X11. No dedicated hardware here, only integrated hardware; The device is Thinkpad T480 i5-8th gen. Thank you

i dont think its the right place to ask such a thing, and even if it was, i don't think you'll find an answer here anyway.
