### ISSUE TITLE
[Bug] <Can't resize Vesktop on Linux>

### ISSUE THREAD

**Issue by Milli189** [Vencord/Vesktop#1006]
### Operating System

Manjaro Linux

### Linux Only ~ Desktop Environment

Gnome on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

After I open the app, I can't resize it anymore, I can only maximize it and umaximize it with the header/title bar.

This issue appeared after updating to the latest version.

See video of the issue:

https://github.com/user-attachments/assets/a71ea32e-df23-4f55-9605-d0fb8b37b056

### What is the expected behaviour?

I was able to resize vesktop until the last update

### How do you recreate this bug or crash?

1 - Open Vesktop
2 - Try to resize it

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Milli189** [comment]
so what do I do? I can't resize Vesktop from any source I install it from, both flatpak and aur packages have this issue

**Comment by MiMillieuh** [comment]
> so what do I do? I can't resize Vesktop from any source I install it from, both flatpak and aur packages have this issue

They won't bother replying... I have the same issue for more than a week but hey they'll keep closing issues without proper solutions like always... and flag as duplicate any other.

Good luck that's all... Maybe if discord gets less annoying I'll move back to the official client. I use Vesktop only cause it had better Linux support but seems that it will not be the case for the foreseeable future at this rate.

**Comment by Vendicated** [comment]
I don't have a solution. It's your system, not mine. Rendering and window management are done by Electron / Chromium and resizing itself is done by your window manager. Vesktop has 0 control over any of this behaviour. I have no clue what is wrong or how to fix it

I really don't know what you expect me to do. Yes, i will keep closing system / upstream issues like this without comment because I simply do not have anything to comment. I know as little as you, do your own research. Look it up on Google, if this is a widespread issue I'm sure many people will have reported this about chrome / chromium or other Electron apps

**Comment by Vendicated** [comment]
You could have used that time you spent typing that unnecessary comment googling your issue instead. Seriously quit being so entitled and cocky

![image](https://github.com/user-attachments/assets/abba7b2f-4efc-4f61-b2da-ec5dad7eda4b)

https://bbs.archlinux.org/viewtopic.php?id=300635
https://github.com/electron/electron/issues/44543

**Comment by Milli189** [comment]
> > so what do I do? I can't resize Vesktop from any source I install it from, both flatpak and aur packages have this issue
> 
> They won't bother replying... I have the same issue for more than a week but hey they'll keep closing issues without proper solutions like always... and flag as duplicate any other.
> 
> Good luck that's all... Maybe if discord gets less annoying I'll move back to the official client. I use Vesktop only cause it had better Linux support but seems that it will not be the case for the foreseeable future at this rate.
> 
> The only thing you can do is disable wayland via flatseal on Vesktop as it seems to be a problem with it. but like always THAT'S NOT A SOLUTION. or maybe they should remove `Linux Screenshare with sound & wayland` from the **MAIN features in the readme**

The temporary workaround I found is to go into the settings, then go into Vesktop Settings, and enable "Discord Titlebar", then you restart the app and you will be able to resize it again

**Comment by Milli189** [comment]
> You could have used that time you spent typing that unnecessary comment googling your issue instead. Seriously quit being so entitled and cocky

You know me and him as average users and not developers, we use your app, we see that something is broken in your app and we report the issue, but since we don't know the specifics of what's going on because we are not developers, since we saw the issue on your app we report it the github of your app, it's that simple.

Instead of closing issues and not saying anything, you can close them and tell them "I don't think this issue is related to Vesktop", it would give a better look of the developers of this app ;)

Also you're acting so entitled and cocky
