### ISSUE TITLE
[Bug] Vesktop lag/stutter on Wayland with Rich Presence + ozone-platform-hint=auto

### ISSUE THREAD

**Issue by Kitt3120** [Vencord/Vesktop#1009]
### Discord Account

schweren.dev

### Operating System

NixOS

### Linux Only ~ Desktop Environment

KDE Plasma 6.2.4 on Wayland 

### Package Type

nixpkg, AppImage

### What happens when the bug or crash occurs?

When using the `ozone-platform-hint=auto` command line argument, and having the Rich Presence feature enabled, Vesktop lags/stutters about every 5 seconds.

Here's a video demonstrating this: https://www.youtube.com/watch?v=YRhVis_xId8

What I found out so far:

- The lags/stutters happen only when `ozone-platform-hint=auto` is set and the Rich Presence feature is enabled
- When disabling Rich Presence, it still lags as long as Vesktop hasn't been restarted
- The lags/stutters happen around every 5 seconds, very consistently. The interval is **not** affected by system performance. It's about 5 seconds on my desktop and my laptop. But the duration of the lag depends on the system's performance. The lag is way shorter on my desktop than on my laptop.
- It does not have anything to do with 3rd party plugins. With all plugins disabled, it still happens.
- It does not have anything to do with CSS/Theme related settings. With custom css disabled, and Discord's default theme applied, it still happens.
- It does not have anything to do with GPU hardware acceleration. With hardware acceleration disabled in settings, and starting with the `disable-gpu` flag, it still happens.
- The lags can be observed visually, and in the browser devtools' "performance" section (ctrl + shift + i), like shown in the video. I recommend to record at least 10 seconds to see at least 2 lags. Lags can be seen in the performance result as "dropped frames".

My guess is that there's a 5-second timer related to the Rich Presence feature, running some task. Whatever that task does, it freezes the UI for a short moment.

### What is the expected behaviour?

Vesktop does not stutter about every 5 seconds

### How do you recreate this bug or crash?

1. Use a Wayland compositor (in my case KDE Plasma's Wayland session)
2. Run Vesktop with the `ozone-platform-hint=auto` flag
3. Enable Rich Presence (either have it enabled already or switch the setting from off to on after starting Vesktop)
4. Vesktop now lags/stutters about every 5 seconds. This is **not only when playing video** (like shown in the linked YouTube video), but also when scrolling through chats, typing a message, etc. Basically, it's periodically lagging, no matter what you're doing.

(Optional)
1. Disable Rich Presence in settings
2. Vesktop still lags until it is restarted

### Debug Logs

Unfortunately, the logs do not show anything related. The "console" tab of the browser's devtools also do not show anything useful.

```
torben@modulosaurus ~/D/Delete> ./Vesktop-1.5.4.AppImage --ozone-platform-hint=auto
Vesktop-1.5.4.AppImage installed in /home/torben/.cache/appimage-run/5186458ebe824a5f99f41f6823655e4911a2f7d806a36788445db8032399e051
Checking for update
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
Update for version 1.5.4 is not available (latest version: 1.5.4, downgrade is disallowed).

```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

#### Desktop

- CPU: AMD Ryzen 9 9950X
- GPU: AMD Radeon RX 7900 XTX
- OS: NixOS unstable / NixOS 25.05
- Desktop: KDE Plasma 6.2.4
- Drivers: Mesa drivers 24.2.6

#### Laptop
- Device: Framework 16
- CPU: Ryzen 9 7940HS
- GPU: AMD Radeon RX 7700S
- OS: NixOS unstable / NixOS 25.05
- Desktop: KDE Plasma 6.2.4
- Drivers: Mesa drivers 24.2.6

### Fedora
- Fedora Workstation v41.1.4
- GNOME Desktop v47
- Vesktop AppImage

### Manjaro
- Manjaro Linux KDE Plasma flavour (rolling release)
- KDE Plasma v6.2.4
- Vesktop AppImage

**Comment by Kitt3120** [comment]
> im gonna make a wild guess and say nixos isnt liking a process scanning /proc. arrpc does this every 5 seconds. https://github.com/OpenAsar/arrpc/blob/5aadc307cb9bf4479f0a12364a253b07a77ace22/src/process/index.js#L25

Good catch! I can try recreating this on another OS. If it's NixOS-related, I'll try to find out what exactly is causing this on NixOS.

**Comment by Kitt3120** [comment]
I wrote some JavaScript code that can be used to detect the lags. Open up the dev tools using ctrl + shift + i and paste the following JavaScript:

```javascript
function trackLags() {
  let diff = performance.now() - last;
  if (diff < 40) {
    console.log("<40ms since last frame");
  } else {
    let date = new Date();
    console.log(diff + "ms since last frame at " + date.toLocaleString("en-US"));
  }
  last = performance.now();
  if (measure) {
    window.requestAnimationFrame(trackLags.bind(this));
  }
}

function startTracking() {
  last = performance.now();
  measure = true;
  trackLags();
}

function stopTracking() {
  measure = false;
}

let last = performance.now();
let measure = false;
```

The 40ms parameter may need adjustment to your setup.
Now, start a video in Discord and run startTracking() in the console. You should see spikes every 5 seconds. Run stopTracking() to stop.

This is from my fresh Manjaro VM:
![image](https://github.com/user-attachments/assets/b3f8b2c5-4eda-42ff-b177-12df56c78c75)

This is without the `ozone-platform-hint=auto` flag. It had 3 hiccups, but those are not relevant. What's interesting is the 3791 logs <40ms over the timespan of almost a minute.
![image](https://github.com/user-attachments/assets/911f0c8a-d8dd-4b31-a1de-32c5669d624b)

**Comment by Vendicated** [comment]
system issue. try to disable hardware acceleration. nothing vesktop can fix

**Comment by Kitt3120** [comment]
I am not too sure about the system issue part. As I said, I am able to reproduce this on 3 different OSes, 2 of which are fresh installs, even using different desktops.

However, I am on your side that it may not have anything to do with Vesktop. I'll open issues on the electron and arRPC repos.

Thanks and happy holidays!

**Comment by Vendicated** [comment]
do you have any discord themes / css? if yes, disable them and see if it's fixed

before reporting it anywhere, you should first see if you can reproduce this issue in normal chrome browser visiting discord.com/app

if yes, it's most likely something wrong with your system. you could file an issue in the chromium repo, but I don't really know anyone who has similar issues so it's likely not on their side

its probably not arrpc. if you want to check, you can disable rich presence in vesktop settings and restart. that will make it not run anymore

it's hard to say, but since you're the only person thus far experiencing this, it's probably on your end

**Comment by Kitt3120** [comment]
Thanks for the recommendations. As stated in my post above, I have already tried that, and yes, it does make a difference. It's arrpc. At this point, it's out of question that it's arrpc-related. And thus, it is not reproducable by just visiting discord.com/app.

I can try out using aarpc externally and disabling Vesktop's internal arrpc. This way, I could find out if it's arrpc or Vesktop's integration of arrpc.

**Comment by yvvki** [comment]
Shouldn't this be reopened? Since it's a prevalent issue.

**Comment by Kitt3120** [comment]
fixed by https://github.com/Vencord/Vesktop/pull/1053
