### ISSUE TITLE
[Bug] Vesktop is not using the XDG Portal file picker

### ISSUE THREAD

**Issue by Lesking72** [Vencord/Vesktop#1010]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

KDE Plasma 6.2.4 Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Vesktop shows a GTK file picker, restricted to the Flatpak sandbox, instead of an XDG Portal file picker.

I believe this is not a system issue because other Flatpak programs show the correct file picker, as do non-Flatpak programs configured to use the portal. Downgrading Vesktop to the 2024-10-01 Flathub release restores the correct file picker.

### What is the expected behaviour?

Vesktop should use the XDG Desktop Portal file picker when opening files.

### How do you recreate this bug or crash?

1. Perform any action that opens a file picker, such as:
   - Attaching a file to a message using the "Upload a File" option in the message box
   - Using the Backup & Restore functions under the Vencord settings group
   - Changing your profile picture or banner
2. Incorrect file picker opens

### Debug Logs

```
Using NVIDIA on Wayland, disabling gpu sandbox
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --disable-gpu-sandbox --ozone-platform-hint=auto --enable-wayland-ime
[3:1215/204727.641848:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:1215/204727.814865:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1215/204727.814895:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

(vesktop.bin:3): Gdk-WARNING **: 20:47:58.752: Server is missing xdg_foreign support
[3:1215/204809.613620:ERROR:wayland_event_watcher.cc(47)] libwayland: warning: queue 0x1cdc00652140 destroyed while proxies still attached:

[3:1215/204809.613689:ERROR:wayland_event_watcher.cc(47)] libwayland:   wl_shm_pool#43 still attached
```

Manually granting system (and user) bus access did not resolve the file picker issue, but did stop those errors in the log. The Gdk warning appears each time the file picker opens. The libwayland lines printed when quitting Vesktop.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
electron regression. Will be fixed whenever there's a new electron version and we upgrade to it
