### ISSUE TITLE
[Bug] Vesktop won't start if there's `"type": "module"` in `$HOME/package.json`

### ISSUE THREAD

**Issue by hypeedev** [Vencord/Vesktop#1015]
### Discord Account

hypeedev

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Hyprland, Wayland

### Package Type

AppImage 1.5.4

### What happens when the bug or crash occurs?

The application gets stuck at the "Loading Vesktop..." screen. This occurs only if the module format in `$HOME/package.json` is set to "module", regardless of whether the app is launched through the app launcher or the terminal.

### What is the expected behaviour?

The application starts normally, ignoring the `package.json` file in `$HOME`.

### How do you recreate this bug or crash?

1. Create the `package.json` file in `$HOME` with content `{"type": "module"}`
2. Launch Vesktop

### Debug Logs

```
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
Gtk-Message: 22:31:27.686: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 22:31:27.686: Failed to load module "colorreload-gtk-module"
(node:48182) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/user/.config/vesktop/sessionData/vencordFiles/vencordDesktopMain.js from /usr/lib/vesktop/app.asar/dist/js/main.js not supported.
vencordDesktopMain.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename vencordDesktopMain.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/user/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at c._load (node:electron/js2c/node_init:2:16955)
    at VCDMain:15:5239
    at VCDMain:1:1027
    at On (VCDMain:15:4738)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:48182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
don't create that file it screws up all nodejs scripts in your entire home directory

**Comment by Grelo4ka** [comment]
Also just ran into this issue. Would be nice if it could be handled

**Comment by Vendicated** [comment]
yes we should but don't create that file it screws up all nodejs scripts in your entire home directory

**Comment by Vendicated** [comment]
fixed via https://github.com/Vencord/Vesktop/commit/d39c54b3ee5a2c8374af6d6586261b12e9fca489 but seriously just do not have that file
