### ISSUE TITLE
[Bug] Vesktop loads with white screen

### ISSUE THREAD

**Issue by Dwexy** [Vencord/Vesktop#1019]
### Discord Account

shithad

### Operating System

Windows 10

### Package Type

Setup exe

### What happens when the bug or crash occurs?

Loading Vesktop just gives a box with a white screen. There is no tray icon either. Have tried restarting PC and reinstalling Vesktop.
![image](https://github.com/user-attachments/assets/8e3a5524-e5fc-4987-b0c0-554dd56c3736)

### What is the expected behaviour?

For Vesktop to load and open to my home page

### How do you recreate this bug or crash?

Open the Vesktop exe

### Debug Logs

N/A

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
logs?

**Comment by kmr-ankitt** [comment]
![image](https://github.com/user-attachments/assets/dedbe920-1f0a-48fe-a5ea-d075d1ee2eec)

**Comment by Dwexy** [comment]
I can't open Vesktop for logs at all since it just gives the white box

**Comment by koutsie** [comment]
for anyone wandering out here, there's currently as of writing an discord outage:
https://discordstatus.com/incidents/41xtl5znmt2h
