### ISSUE TITLE
Snap package for Vencord 

### ISSUE THREAD

**Issue by soumyaDghosh** [Vencord/Vesktop#102]
I am creating a snap package for Vencord but can you suggest me the name, description and summary. I have thought about name as `vencord` but anything else is welcomed. The manifest is hosted here:

https://github.com/soumyaDghosh/vencord-snap

**Comment by TheKodeToad** [comment]
maybe you should ask on the Discord server?

**Comment by soumyaDghosh** [comment]
Asked it, but the reply wasn't very good. Looked more like a spam.

**Comment by lewisakura** [comment]
I think it'd be preferable if we distributed Vesktop ourselves on these platforms, but we're not interested in maintaining a Snap package at the minute.

**Comment by soumyaDghosh** [comment]
@lewisakura should I publish the snap on my own then?

**Comment by lewisakura** [comment]
We'd rather you didn't because people will come to us when it breaks and none of us will be able to provide support for it. Not just on GitHub, but on Discord too. People expect that when a package exists we will provide support for it, but in our case we don't have a clue how some of the unofficial repackages of Vencord work and we would rather do it ourselves in the future when we have a better understanding and there's more demand.

So, for the reasons above, _please don't_.

**Comment by soumyaDghosh** [comment]
> We'd rather you didn't because people will come to us when it breaks and none of us will be able to provide support for it. Not just on GitHub, but on Discord too. People expect that when a package exists we will provide support for it, but in our case we don't have a clue how some of the unofficial repackages of Vencord work and we would rather do it ourselves in the future when we have a better understanding and there's more demand.
> 
> So, for the reasons above, _please don't_.

As the snap will be simply a wrapper to the deb package. It'll not be something different. Also, snap is very immuted to these breakages, as I am seeing with `webcord`, another discord client.
https://github.com/SpacingBat3/WebCord/issues/452

Snap one doesn't have this issue. All the other package formats have this. So, I think, it's better to have the snap. And also, I can maintain your snap if you want.

**Comment by Vendicated** [comment]
> Also, snap is very immuted to these breakages, as I am seeing with webcord, another discord client. Snap one doesn't have this issue.

This is simply not true. the issues you linked is native to electron itself, so it also occurs on snap unless the snap is an older version

In any case, we will be publishing our own official snap package. Please do not make your own.

**Comment by soumyaDghosh** [comment]
> > Also, snap is very immuted to these breakages, as I am seeing with webcord, another discord client. Snap one doesn't have this issue.
> 
> This is simply not true. the issues you linked is native to electron itself, so it also occurs on snap unless the snap is an older version
> 

Snap uses a stable version of electron and every other packages. That's why, I said it's very immutable.

**Comment by soumyaDghosh** [comment]
Should I share the snap manifest with you guys? If you ever need them?

**Comment by 0x3C50** [comment]
> Should I share the snap manifest with you guys? If you ever need them?

The answer was clear enough. If need be for a snap package, I have good faith the vencord developers will be able to make their own snap setup they fully control.
