### ISSUE TITLE
[Bug] Incorrect window positioning on startup

### ISSUE THREAD

**Issue by WXAGames** [Vencord/Vesktop#1020]
### Discord Account

wxagames

### Operating System

Nobara 40

### Linux Only ~ Desktop Environment

Plasma on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

When Vesktop starts, it defaults to my primary screen, even though I've moved it to my other monitor. This was not an issue with vanilla Discord, BetterDiscord or Vencord.

### What is the expected behaviour?

I expect Vesktop to boot on the same monitor it was closed on.

### How do you recreate this bug or crash?

1. Start Vesktop
2. Move it to another screen
3. Close Vesktop
4. Reopen Vesktop

### Debug Logs

```
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
electron on wayland issue. launch with XWayland instead of Wayland and it will work fine

**Comment by Vendicated** [comment]
actually just a wayland issue because wayland doesn't let windows control their own position. thus not sure if this will ever be fixed upstream

**Comment by WXAGames** [comment]
> actually just a wayland issue because wayland doesn't let windows control their own position. thus not sure if this will ever be fixed upstream

Doesn't seem like it though, since the aforementioned versions worked perfectly fine, so shouldn't be a problem from Wayland or Electron.

**Comment by Vendicated** [comment]
**launch with XWayland instead of Wayland and it will work fine**
