### ISSUE TITLE
Can't paste images using context menu

### ISSUE THREAD

**Issue by Niterux** [Vencord/Vesktop#104]
Pasting images by right clicking and clicking "paste" doesn't work, only ctrl-v works. Pasting text works fine.
I am only using Vesktop for the alternative app, if it is issue on Vencord on regular Discord app I would not be aware because I have never used Vencord on regular Discord app.
OS: Windows 11
Stable 222963 (3d132dc) Vencord C752be4 (Vesktop V0.3.0) Electron 25.5.0 Chromium 114.0.5735.289

**Comment by Vendicated** [comment]
fixed
