### ISSUE TITLE
[Feature] Discover Overlay support

### ISSUE THREAD

**Issue by IgLocoXD** [Vencord/Vesktop#105]
It would be nice if Linux users could have Discover Overlay support 
As the name indicates, its a Overlay for Voice Chats and Server Messages for Linux (because it doesn't have one officially) It would be amazing if Discover could be supported too here.

**Comment by TheKodeToad** [comment]
It uses Discord's local RPC server - https://discord.com/developers/docs/topics/rpc

**Comment by lewisakura** [comment]
> It uses Discord's local RPC server - [discord.com/developers/docs/topics/rpc](https://discord.com/developers/docs/topics/rpc)

In which case, we can't do this because we use arRPC to provide RPC support, so this is something Discover/arRPC has to support. I'm unsure since I haven't investigated which side needs to.

**Comment by TheKodeToad** [comment]
Discover uses it

**Comment by IgLocoXD** [comment]
> > It uses Discord's local RPC server - [discord.com/developers/docs/topics/rpc](https://discord.com/developers/docs/topics/rpc)
> 
> In which case, we can't do this because we use arRPC to provide RPC support, so this is something Discover/arRPC has to support. I'm unsure since I haven't investigated which side needs to.

Discover uses both, I could make an issue in Discover github, but they said the Discord Clients developers need to enable the support.
