### ISSUE TITLE
Vencord doesnt work anymore.

### ISSUE THREAD

**Issue by u0068** [Vencord/Vesktop#107]
This morning when i opened discord it got stuck on the 'Starting...' screen. When i restarted my pc i still had the same problem.
I figured that vencord could be causing the issue so i uninstalled it and discord started up completely fine.
I reinstalled vencord hoping that it would work fine but when i opened discord, vencord was not there. I dont know whats going on.

**Comment by Vendicated** [comment]
use our support channel + wrong repo
