### ISSUE TITLE
[Bug]: No icon for the .desktop when installed with the .deb

### ISSUE THREAD

**Issue by AVOnyx** [Vencord/Vesktop#109]
Currently running Pop!_OS 22.04 LTS with the release 0.3.0 of Vencord. The .desktop does not have the Vencord icon, and displays a blank placeholder. 
![Screenshot from 2023-09-05 15-45-06](https://github.com/Vencord/Vesktop/assets/89320518/4aba25c9-a8c5-4019-8e32-0a61ab5ba5c0)

**Comment by ikaikahub** [comment]
Since its probably related, this causes vesktop on the taskbar to be a little sliver on Cinnamon 5.8.4
![Screenshot from 2023-09-27 17-31-28](https://github.com/Vencord/Vesktop/assets/124720971/cb4b4587-ceb0-4f23-9500-b9ec64ff7876)

**Comment by Vendicated** [comment]
fixed next release https://github.com/Vencord/Vesktop/commit/b9e411ac90596ef71cc78b021afff55048f9b810
