### ISSUE TITLE
Screenshare with Hardware Encoding?

### ISSUE THREAD

**Issue by spectrapulse** [Vencord/Vesktop#113]
From what I've noticed while using screenshare feels like all capturing and video encoding is done in Software.

Is it even possible to get Hardware Encoding to work with Vesktop? I'm not sure how Vesktop's Screenshare impl works and what it would possibly depend on as I've never really worked with Electron before let alone implemented anything "capture" related so it's very impressive that it works at all. But there's not really times that I'm not experiencing Frame Rate Encoding issues or other glitchy stuff you would commonly see with Software Solutions and it feels that it's pretty much almost unusable for anything that isn't mostly static content.

Is this a feature that's planned or is this something that might be a bit too ambitious?

Edit: I want to add that I'm on Windows with an NVIDIA GPU.

**Comment by lewisakura** [comment]
Vesktop uses the [native Electron media request API](https://github.com/Vencord/Vesktop/blob/94ba59afb5bf4e7d13bb3effb705278cf5e436fc/src/main/screenShare.ts#L1) like you would see on Discord Web, just with a custom UI. Discord uses their own custom native implementation on Desktop via C++ and various other black magic (similar to how OBS does it as far as I know). It's difficult to get working in any other way unless we went down the route of implementing an actually native solution for every platform, so I would argue for now this is too ambitious of a project.

**Comment by spectrapulse** [comment]
Yeah I had a feeling that would be a little bit too complex, I wonder if there would be an alternative way of tackling this. Maybe a lazy workaround would be having a RTMP server in the client which just would kind of proxy the video stream to Discord and then leaving all the "hard work" to OBS. But that would kind of just be a "hack" and maybe could be implemented in the form of a plugin which might also be useful in the first party Discord Client... But all that is outside the scope of this specific issue so I'll just mention it as food for thought.

I'll leave it open for now to hear what @Vendicated thinks, they or someone else knows an alternative way of tackling it and if not it can be closed.

**Comment by Vendicated** [comment]
there's not really anything we can change about screenshare without reimplementing it from scratch ourselves which is very out of scope of this project, sorry!
