### ISSUE TITLE
[question] Vesktop Custom install path?

### ISSUE THREAD

**Issue by DodoGames7** [Vencord/Vesktop#114]
Does Vesktop support installing with a custom path on Windows? I'm one of the people who prefer to install things to a different hard drive than the one Windows is installed in to prevent storage issues. I also need these to usually test the programs in case they do not have portable methods.

I'm aware that some people will just tell me to test the installer but i like to make sure first for reasons. Is this supported or not?

**Comment by DodoGames7** [comment]
*For some reason, i can't add labels to this opened issue so i will just put `[question]` in the title to make sense*

**Comment by Vendicated** [comment]
yes
