### ISSUE TITLE
Permissions issue screensharing on macOS

### ISSUE THREAD

**Issue by ImLvna** [Vencord/Vesktop#115]
When attempting to stream your screen, macOS prompts you to give screen share permission every time, even though it was already granted. Possible entitlements issue? 
<img width="953" alt="image" src="https://github.com/Vencord/Vesktop/assets/44179559/f573ee5c-e14a-478d-9ad3-6b0eea420ce3">
<img width="499" alt="image" src="https://github.com/Vencord/Vesktop/assets/44179559/9a09191f-7f35-491d-a65d-edbb0344a116">
<img width="555" alt="image" src="https://github.com/Vencord/Vesktop/assets/44179559/278931dc-f354-4703-9a46-e14e854e1133">
I have checked for permissions and it says granted, and the screen share handler returns the correct video stream on the electron side

**Comment by ImLvna** [comment]
<img width="867" alt="image" src="https://github.com/Vencord/Vesktop/assets/44179559/7100ce89-beec-4ff8-9f5e-720e861063da">
`granted` log being from `console.log(systemPreferences.getMediaAccessStatus("screen"));`

**Comment by Vendicated** [comment]
Fixed in https://github.com/Vencord/Vesktop/commit/c445c6194f6a0bd077bafc9e65f0aa79e2aa0945

**Comment by jacksongoode** [comment]
Still seeing this issue on the latest version (1.5.2)

**Comment by ssalggnikool** [comment]
> Still seeing this issue on the latest version (1.5.2) 

Screenshare seems to work on my end, tested with M2 mac when testing permissions for 1.5.2.

**Comment by Vendicated** [comment]
please do not necro old resolved issues

open a new issue with the proper bug report template, filling out all the necessary information. "still seeing this issue" with no further information is very meaningless
