### ISSUE TITLE
[Feature Request] Add screensharing with audio support for the linux app

### ISSUE THREAD

**Issue by kaitlynkittyy** [Vencord/Vesktop#117]
I know discord-screenaudio's solution is janky, but would it be possible in Vesktop? After all, as far as I know, electron does have support for it. (this may be false)

If so, this app could easily become the most widely used discord client on Linux lol (Wayland screen sharing, audio support, discord-client UI as opposed to discord-web, AND client mods)

**Comment by Vendicated** [comment]
electron does not have support for this, no

there are no plans to add this and I personally will not be working on this, but feel free to contribute

**Comment by kaitlynkittyy** [comment]
I thought it did lol, but I understand.

I'd love to contribute if I can make the time though!

**Comment by 65942** [comment]
There is a way to do this already using pipewire.
https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux
This is the method being used and it's already been implemented into this other client
https://github.com/maltejur/discord-screenaudio

Would be awesome if you guys could implement this so I don't have to make a choice between screensharing or using Vencord plugins.

**Comment by Cynosphere** [comment]
Vesktop uses stock Electron, which doesn't have a neutered getUserMedia. Combine that with Electron's API to get screenshare sources and fixing up the WebRTC media engine inside of Discord along with modifications to the screenshare picker to add a selection for an audio device to be used for audio sharing. Yes you would still need to setup a virtual audio input and use something like Helvum, but its better than nothing.

**Comment by kaitlynkittyy** [comment]
> Vesktop uses stock Electron, which doesn't have a neutered getUserMedia. Combine that with Electron's API to get screenshare sources and fixing up the WebRTC media engine inside of Discord along with modifications to the screenshare picker to add a selection for an audio device to be used for audio sharing. Yes you would still need to setup a virtual audio input and use something like Helvum to reroute audio, but its better than nothing.

I wonder if it would be possible to do this, but also implement the audio source selection used in discord-screenaudio, to further streamline the process. Until someone makes it auto select the audio source that is.

**Comment by Cynosphere** [comment]
> I wonder if it would be possible to do this, but also implement the audio source selection used in discord-screenaudio

No because discord-screenaudio is an entire Qt app with PipeWire API calls. Unless you want to write an entire native Node module to do the same thing.

**Comment by kaitlynkittyy** [comment]
> > I wonder if it would be possible to do this, but also implement the audio source selection used in discord-screenaudio
> 
> No because discord-screenaudio is an entire Qt app with PipeWire API calls. Unless you want to write an entire native Node module to do the same thing.

Ah, I see, thanks for explaining!

**Comment by gmankab** [comment]
my os is fedora silverblue, with gnome, pipewire and wayland

screen shares without sound

i tried both flatpak and binary version

btw discord-screenaurio shares screen with sound without any issues

**Comment by Vendicated** [comment]
stop necroing old unrelated threads.
