### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by Yeetov** [Vencord/Vesktop#118]
This shows up when loading, if you click cancel it gets stuck on the loading screen.
This happens on setup
![Image](https://github.com/Vencord/Vesktop/assets/69159547/4a91ad29-e3c8-480c-9aff-559ec18633bc)
![image](https://github.com/Vencord/Vesktop/assets/69159547/9369de36-2595-4a7c-b3d8-c68ad86c2e50)

**Comment by Yeetov** [comment]
![image](https://github.com/Vencord/Vesktop/assets/69159547/67c3cc3c-2361-4998-9714-31a41c3828fe)

**Comment by Vendicated** [comment]
no correlation. run vesktop from the terminal to get error output, it's likely related to connection issues to github ordiscord

use our support channel if u need more help
