### ISSUE TITLE
Could not synchronize settings to cloud (API returned 401). 

### ISSUE THREAD

**Issue by olivertzeng** [Vencord/Vesktop#122]
It works on the official Discord Client. Tested on Arch Linux and macOS Ventura 13.6 on stable & canary versions.

**Comment by Vendicated** [comment]
reauth

**Comment by PeeK1e** [comment]
Was scratching my head how you would do the re-auth in the Discord Client because it was a couple of months ago since I last touched it. Just leaving it here in case anyone was wondering too: 

Settings > Vencord > Cloud 
Disable and Enable the Cloud Integrations again.

**Comment by olivertzeng** [comment]
Oh I've already solved it thanks to @Vendicated but forgot coming back here lol sorry 4 that
