### ISSUE TITLE
Volume Boost feature missing

### ISSUE THREAD

**Issue by GustavRaispits** [Vencord/Vesktop#135]
If it had the possibility to raise users' volumes to over 100 I would definitely use it as an alternative to Discord. I really like the "VolumeBoost" plugin present in normal Vencord, and I would love to see it on Vesktop as well.

![KLwyFMY](https://github.com/Vencord/Vesktop/assets/34628862/ccdb77df-5815-458c-ba04-5c2a4d5154d5)

**Comment by Vendicated** [comment]
duplicate
