### ISSUE TITLE
Unable to open Plugins and Check for Updates

### ISSUE THREAD

**Issue by DyonR** [Vencord/Vesktop#136]
Opening the Plugins setting gives me this error:  
![image](https://github.com/Vencord/Vesktop/assets/16341409/0253e223-f663-4cee-b577-f789d79465ea)
  
Checking for updates via the Updater gives this error:  
![image](https://github.com/Vencord/Vesktop/assets/16341409/62c08d49-6781-48b9-b7e0-d57a700d0236)
![image](https://github.com/Vencord/Vesktop/assets/16341409/c8c04a27-5063-4335-92dc-924b228440c3)
  
  
The console throws like 850 ErrorBoundary React errors and 1000 warnings about Logger.ts:35 which are all different and too much to post. Oh yeah, and of course I did reinstall Vesktop.

**Comment by Vendicated** [comment]
use our support channel

**Comment by Gauvino** [comment]
@Vendicated support channel on the discord and does problem have been solve by any chance cause its been like a serious month with it

**Comment by DyonR** [comment]
> @Vendicated the support channel on the discord ? and does problem have been solve by any chance cause its been like a serious month with it

right click vesktop in system tray > update vencord

**Comment by Gauvino** [comment]
![Vesktop_YAY2PA67PS](https://github.com/Vencord/Vesktop/assets/68083474/4ae2f824-d997-4eb9-a7b7-b2a2e9bd9281)
Can't update because of this error even with re-installing vesktop with the latest .exe

**Comment by Gauvino** [comment]
> 
> right click vesktop in system tray > update vencord

> > @Vendicated the support channel on the discord ? and does problem have been solve by any chance cause its been like a serious month with it

**Comment by DyonR** [comment]
Update via the Windows system tray icon, next to the clock and date in Windows, right click that icon and select update
