### ISSUE TITLE
Search history is hidden

### ISSUE THREAD

**Issue by xparadoxical** [Vencord/Vesktop#138]
Often search history is useful, but Vencord hides it and I can't use it.
I tried uninstalling Vencord, and history was back with queries I've run while Vencord was installed. I installed it back and search history was hidden again.
Disabling QuickCSS doesn't fix this, so it's not an issue with my css.

```
Stable 235476 (a7cb1d5)
Vencord 9e63da6 (Standalone)
Electron 22.3.25
Chromium 108.0.5359.215
Host 1.0.9019 x86 (38122)
Windows 10 64-Bit (10.0.22621)
Installer Version: v1.3.1 (ca03a38)
```

**Comment by ImLvna** [comment]
please do not create vencord issues on the vesktop repo. no part of vencord touches searching. not a vencord issue as you have been told
