### ISSUE TITLE
vekstop has an issue with stream deck

### ISSUE THREAD

**Issue by sadanslargehole** [Vencord/Vesktop#139]
with vesktop and the [stream deck discord plugin](https://apps.elgato.com/plugins/com.elgato.discord) stream deck will cause a memory leak, and eventually crash.
i have tested this with the normal client, and it works fine.
![image](https://github.com/Vencord/Vesktop/assets/117494111/efa9364e-37a2-4e97-81bb-d2ba12411413)
let me know if you need any more info, or if this is something you can fix

Stable 235476 (a7cb1d5)
Vencord 9e63da6 (Vesktop V0.3.3)
Electron 25.8.4
Chromium 114.0.5735.289
Windows 10 64-Bit

**Comment by Vendicated** [comment]
that's an issue on their end, not ours
