### ISSUE TITLE
[Feature request] Allow to disable automatic input volume adjustment

### ISSUE THREAD

**Issue by Katzenwerfer** [Vencord/Vesktop#142]
Vesktop changes the system volume of the input device when the loudness is above a certain threshold.
I've tried to turn off this behavior, but so far, I've not found a working solution.

I thought that the `Automatic Gain Control` switch would control that, but it doesn't seem to affect it in any way.

**Comment by 1Naim** [comment]
I'd like an option to disable this as well. For the past few weeks I was so confused why the volume of my input device kept decreasing. Is this some kind of feature of Vesktop?

**Comment by Vendicated** [comment]
closing in favour of https://github.com/Vencord/Vesktop/issues/161
