### ISSUE TITLE
Error when opening Vesktop (just installed the app)

### ISSUE THREAD

**Issue by Likver** [Vencord/Vesktop#144]
i just installed the app and when i launch it this error appears.

![image](https://github.com/Vencord/Vesktop/assets/79934166/9f8f48fa-ec74-4840-92c2-f2f7b0bcf699)

Im using w8.1 if thats the problem (which at this point it wouldnt surprise me)

**Comment by Vendicated** [comment]
windows 8 is not supported. upgrade to 10 or higher

**Comment by Likver** [comment]
alr, thanks for the quick response
