### ISSUE TITLE
Restarting app automatically mutes my microphone

### ISSUE THREAD

**Issue by bl4xe** [Vencord/Vesktop#145]
Whenever I restart the App, I get muted for some reason and always have to unmute myself again

**Comment by bl4xe** [comment]
> This may be related to spotify

I do not use Spotify, could it be some other program that I'm using?

**Comment by Vendicated** [comment]
i can reproduce. it's probably a discord web thing because of permissions

**Comment by ArjixWasTaken** [comment]
.

**Comment by kaitlynkittyy** [comment]
> i can reproduce. it's probably a discord web thing because of permissions

this is what happens to me too, but it automatically unmutes upon joining a call, so is this something that was fixed, or is it in need of more research?

**Comment by PolisanTheEasyNick** [comment]
We can use Flux event `RTC_CONNECTION_STATE` and check for params.state to be `RTC_CONNECTED`. It will mean that user connected to some call. Then we can see whether we are selfMuted and if so then toggleSelfMute.

**Comment by Vendicated** [comment]
> this is what happens to me too, but it automatically unmutes upon joining a call

same here, so i'll be closing this as resolved
