### ISSUE TITLE
Minimizing and opening Vesktop again (or just opening from a short minimized state) causes the window to display a ''white flash''

### ISSUE THREAD

**Issue by Void48** [Vencord/Vesktop#146]
https://streamable.com/ntzkkv **← Screen-recording that shows the (bug/issue)**
![image](https://github.com/Vencord/Vesktop/assets/85196642/8099d1fd-0146-4ac8-a359-7765846f6cb8)

I knew it. I knew I wasn't too insane. :trollface: Anyways, I tested ArmCord and Vesktop on the same Electron version (27.0.0-Beta.2) so it's fair. ArmCord doesn't display any ''white flash'' whatsoever, but Vesktop does, and it's very annoying to look at and see it happen (even if it happens just for a split second). Usually, it's most annoying at times when I leave Vesktop minimized (unopened) for too long and then open it. In that case, I see a (possibly) slightly bigger white flash? Might be the same size, honestly not sure, but it's unexpected and plain ugly. If I do the same with ArmCord, I don't get anything like that. 

However I also want to add that I tried installing the latest ArmCord dev build, and there I can clearly see the same white flash as the one present in Vesktop, so I wonder what's happening here, but I doubt it has something to do with the Electron version because Vesktop always seemed to have this ''white flash'' even on older versions. ArmCord didn't. Surely, this can be fixed somehow, since the official Discord client looks completely fine, and the same goes for ArmCord, at least for now. 👍🏻

**btw, please ignore the server list not showing and name also being hidden. I used CSS to hide those myself. It has nothing to do with the issue.**

**Comment by Vendicated** [comment]
electron / chromium issue

**Comment by DaBluLite** [comment]
> electron / chromium issue

isn't that just a browserwindow setting?

**Comment by Vendicated** [comment]
I guess I forgot to set the disableWhiteFlash option to true

(no it isn't. you're welcome to contribute a fix if you think this is anything we can fix ourselves)
