### ISSUE TITLE
White-screen on launch.

### ISSUE THREAD

**Issue by s626ch** [Vencord/Vesktop#147]
https://github.com/Vencord/Vesktop/assets/22896890/a6c50eb5-cbce-4fb0-9cd6-4371b97769aa

See video ^^
Windows build vv
<img width="200" alt="winver_cr3OPAUTFK" src="https://github.com/Vencord/Vesktop/assets/22896890/4d92d883-33a2-438f-bb44-a3bef4c3b687">

Laptop is a MacBookPro11,5

This only happens on this laptop under Windows with Bootcamp for me, have had no issues on any of my other PCs.
I can't progress past this, and the window is non-interactive, won't recognize any clicks, etc. (every attempt to click it gets passed through to the window underneath)

**Comment by Vendicated** [comment]
please see if this is fixed on 0.4.0

**Comment by s626ch** [comment]
https://github.com/Vencord/Vesktop/assets/22896890/55444009-2113-457d-886d-cf08ceeda3e1

still occurs, also happens if ran as admin

**Comment by Vendicated** [comment]
likely an issue with your gpu driver or such. seems plausible considering how hacky your setup is. try running with the --disable-gpu flag

**Comment by bl4xe** [comment]
![image](https://github.com/Vencord/Vesktop/assets/96691738/01dc5915-0065-4135-81f8-d7394a1a1550)
I have the same exact issue. This is on my AMD Laptop, didn't yet get to verify but I believe I downloaded the 0.4.1 Update yesterday on my proper PC too without any issues. Seems weird to me as there shouldn't be any GPU driver shenanigans on a Laptop but will definitely also make sure to have another look at the install on my PC at home

**Comment by bl4xe** [comment]
https://github.com/Vencord/Vesktop/assets/96691738/ecaa6b36-af25-4fd8-9892-0dd504168f63

just noticed how the same thing applies to the web version aswell, not sure in what way that minimizes possible problem sources tho

**Comment by SophiaH67** [comment]
Hi, I'm experiencing a similar issue on windows 11 vesktop `0.4.1`. I only had this _after_ updating from `0.3.something`. I've tried updating again, uninstalling reinstalling, and patching source files; all with no luck.

My vesktop looks like this:

![image](https://github.com/Vencord/Vesktop/assets/10786212/f7370544-681d-43c0-a8f2-47717c6b553a)

The debugger does still open though, which tells me that it tried to read properties of underfined:

![image](https://github.com/Vencord/Vesktop/assets/10786212/5f7025a3-a213-44ac-88d6-abb64b76e773)

![image](https://github.com/Vencord/Vesktop/assets/10786212/8ef02232-d1c7-4799-b6ef-dfb775850dc9)

###### Solution

I could make a pr for a simple null-check, but am not aware if not having the object would have any consequences..

Thanks for your time,
Sophia

**Comment by FieryFlames** [comment]
> ![image](https://user-images.githubusercontent.com/96691738/277891267-01dc5915-0065-4135-81f8-d7394a1a1550.png) I have the same exact issue. This is on my AMD Laptop, didn't yet get to verify but I believe I downloaded the 0.4.1 Update yesterday on my proper PC too without any issues. Seems weird to me as there shouldn't be any GPU driver shenanigans on a Laptop but will definitely also make sure to have another look at the install on my PC at home



> Hi, I'm experiencing a similar issue on windows 11 vesktop `0.4.1`. I only had this _after_ updating from `0.3.something`. I've tried updating again, uninstalling reinstalling, and patching source files; all with no luck.
> 
> My vesktop looks like this:
> 
> ![image](https://user-images.githubusercontent.com/10786212/277899169-f7370544-681d-43c0-a8f2-47717c6b553a.png)
> 
> The debugger does still open though, which tells me that it tried to read properties of underfined:
> 
> ![image](https://user-images.githubusercontent.com/10786212/277899453-5f7025a3-a213-44ac-88d6-abb64b76e773.png)
> 
> ![image](https://user-images.githubusercontent.com/10786212/277899528-8ef02232-d1c7-4799-b6ef-dfb775850dc9.png)
> 
> ###### Solution
> I could make a pr for a simple null-check, but am not aware if not having the object would have any consequences..
> 
> Thanks for your time, Sophia

These are likely related to https://github.com/Vendicated/Vencord/issues/1838

**Comment by BobbyWibowo** [comment]
If you guys use a local build of Vencord with Vesktop, as in this setting below
![screenshot](https://i.fiery.me/ta3N.png)
I ended up fixing it by simply git pulling then rebuilding it said local build

Maybe the same issue with the default build? As in the updater can't trigger after latest Discord update or something, iunno

**Comment by spacebanana420** [comment]
This problem seems to be related to Discord's new update, based on the pinned issue. but I'm still going to comment this because it can be useful for debugging:

I updated to Vesktop 0.4.1 and I get a white screen. I tried deleting the GPU cache since it worked last time, no luck, so I tried deleting the rest of the cache and no luck either.

I opened settings.json and checked if transparency was to false and it was. 

I tried launching 0.4.0 and 0.3.2 but they also display a white screen now. I opened another electron application unrelated to Vesktop to see if it was again a mesa driver issue but it doesn't seem to be. I also tried with --disable-gpu

When launching vesktop, this error on the terminal is printed while I see the white screen:
```console
(node:5612) UnhandledPromiseRejectionWarning: ReferenceError: IS_EXTENSION is not defined
    at VencordDesktopMain:5:737
    at VencordDesktopMain:5:225
    at VencordDesktopMain:5:2229
    at VencordDesktopMain:5:225
    at VencordDesktopMain:5:2657
(Use `vencorddesktop --trace-warnings ...` to show where the warning was created)
(node:5612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 1.  Skipping ICD.
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 3.  Skipping ICD.
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 7.  Skipping ICD.
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 9.  Skipping ICD.
```

**Comment by ToasterUwU** [comment]
I have that same issue on Ubuntu-based Linux ( using the amd64 deb ) on 0.4.1

To fix it, I had to purge the whole installation of Vesktop and the config, then downgrade to fix it.
Just downgrading didn't fix it. So whatever is in ~/.config/VencordDesktop was part of the problem.

**Comment by HaveSomeRubicon** [comment]
Im experiencing same issue on Windows 11. Reinstalling didn't fix. I'm currently using a inter core i5 12700k and rx 6700 xt

**Comment by h7lv2** [comment]
Yep, happening to me on Fedora 38 on Wayland with both integrated Intel GPU (HD Graphics 5500 specifically) and the discrete Nvidia GPU.

But purging the dotfolder and installing 0.4.0 did help.

**Comment by DozNaka** [comment]
> I did few tests and located the file causing white screen on my client, so if you don't want to loose your session/settings to fix white screen on launch :
> 
> ON WINDOWS
> 
>     1. Make sure Vesktop is fully closed (check your taskmanager that it isn't running in background)
> 
>     2. Delete the file named vencordDesktopRenderer.css in \AppData\Roaming\VencordDesktop\VencordDesktop\vencordDist\
> 
> 
> Might work on Linux if you locate the file, try and tell us.

Fixed my Vencord on Arch Linux
`
.config/VencordDesktop/VencordDesktop/vencordDist/vencordDesktopRender.css`

**Comment by Vendicated** [comment]
All you have to do is update your Vencord install. You can do so by using the "Update Vencord" option in the Vesktop tray contextmenu (or menubar on mac), or by deleting the vencordDist folder. You'd know this if you followed our official announcement channel on the Discord Server

![grafik](https://github.com/Vencord/Vesktop/assets/45497981/e7e9b591-c421-497a-8c98-663a2e194395)

(vencordDesktopRenderer.css has absolutely nothing to do with the problem, you're just corrupting your vencord install which makes vesktop redownload and thus update it)

**Comment by Vendicated** [comment]
@s626ch since your issue has been hijacked for an unrelated problem: Feel free to open a new issue if you're still having this problem
