### ISSUE TITLE
0.3.3 portable win - Cannot use Microphone

### ISSUE THREAD

**Issue by linux-player9** [Vencord/Vesktop#148]
Downgraded to Vesktop 0.3.2 because my microphone wouldn't work on Vesktop 0.3.3.
I am using Windows 10 Professionnal 22H2 build 19045.3570 
My Microphone is a USB Tonor Q9,

Vesktop 0.3.3 was showing a message to autorize the use of my microphone, with no indications on how to do so.
Should I stick to the 0.3.2 or is there a fix ?

**Comment by Vendicated** [comment]
try 0.4.0. if it still doesn't work, there's not much that can be done from our side, since it's supposed to just work. it's likely something wrong with your system or similar. make sure you have mic permission enabled in windows settings
