### ISSUE TITLE
I can't join other people's games

### ISSUE THREAD

**Issue by Niterux** [Vencord/Vesktop#149]
it tells me I need to download discord app
![image](https://github.com/Vencord/Vesktop/assets/110568869/f44007d6-12d1-4c8f-8028-8d7c8d644dfb)

**Comment by Vendicated** [comment]
i'm not sure if implementing this is possible, as it might require some RPC api that arrpc does not implement

**Comment by Vendicated** [comment]
this depends on https://github.com/OpenAsar/arrpc/issues/18, which will most likely never be implemented
