### ISSUE TITLE
ArRPC not working after updating to V0.4.0 

### ISSUE THREAD

**Issue by verysillycat** [Vencord/Vesktop#152]
After updating to V0.4.0 ArRPC stopped working for me
relaunching didn't work
https://github.com/Vencord/Vesktop/assets/126973723/b19ca854-6471-4053-b177-f117921d2e13

clicking the retry button also didn't work.
![Vesktop_ladrOkexqo (1)](https://github.com/Vencord/Vesktop/assets/126973723/3d80c5fb-63ec-4ea6-b8e5-347781932c56)

I tried downgrading to 0.3.3, which solved the issue, confirming it only happens on 0.40
https://github.com/Vencord/Vesktop/assets/126973723/9132523b-6f0e-40ce-8d05-f5d0be60b7fe

**Comment by Vendicated** [comment]
disable the plugin it's obsolete

**Comment by verysillycat** [comment]
> disable the plugin it's obsolete
That seemed to solve my issue, Thank you!

For users having the same problem, here's how to disable it

https://github.com/Vencord/Vesktop/assets/126973723/1f5a99a6-e954-4213-be3e-81ecad212e01
