### ISSUE TITLE
Automatically determine the default audio for streaming

### ISSUE THREAD

**Issue by Rosentti** [Vencord/Vesktop#158]
Currently the streaming dialog defaults to none, and with 20 "Firefox" options to choose from things get difficult.
![image](https://github.com/Vencord/Vesktop/assets/32398752/e83f18b3-ad13-47ea-b72f-6f6106ca2601)

OS: Arch Linux
Using Release 0.4.0

**Comment by Vendicated** [comment]
the duplicates are a bug that will be fixed next update. choosing audio is actually not a simple task because electron only gives us the window title, not any more info like the app name or pid

**Comment by Rosentti** [comment]
Ah. Would it be a good idea to display the window titles in the audio section then (or is this broken)? If I have multiple firefox windows with different tabs they still only show "Firefox".

**Comment by Vendicated** [comment]
it will share audio for all Firefox instances combined. separating per window is out of scope for now

**Comment by Rosentti** [comment]
Ah. Ok then

**Comment by Cynosphere** [comment]
> it will share audio for all Firefox instances combined. separating per window is out of scope for now

Even then you can't really separate out browser audio because browsers are already multiprocess as is, audio will be streamed out of all instances no matter the window video is being captured from.

**Comment by Curve** [comment]
> it will share audio for all Firefox instances combined. separating per window is out of scope for now

Would actually be possible with the current venmic code if the user would want to tough (just mentioning it here)

**Comment by Curve** [comment]
> > it will share audio for all Firefox instances combined. separating per window is out of scope for now
> 
> Even then you can't really separate out browser audio because browsers are already multiprocess as is, audio will be streamed out of all instances no matter the window video is being captured from.

Chrome and Firefox spawn different nodes for each tab, so it should work ^^

venmic currently provides all the information required to differentiate between tabs, however the information we get from pipewire might not be sufficient enough to provide the user a sane selection based on something like tab name for example (afaik the nodes don't contain any info we could make use of to reliably get the tab name)

**Comment by Vendicated** [comment]
ill close this, since the original idea of this issue is not possible. as mentioned above, the duplicates will be gone next update
