### ISSUE TITLE
Game activity

### ISSUE THREAD

**Issue by Rosentti** [Vencord/Vesktop#159]
Game activity doesn't work. Playing Dead by Daylight for example doesn't give me the "Playing: Dead by daylight" status in servers, etc.
It seems to only work for rich presence titles.

OS: Arch Linux
Using Release 0.4.0

**Comment by Vendicated** [comment]
does it work on stock discord?

**Comment by Rosentti** [comment]
Yep

**Comment by Rosentti** [comment]
Though it sometimes picks up other strange things like pv-bwrap, pressure-vessel things and wine64-preloader. Unsure if it works on Windows.

**Comment by Rosentti** [comment]
I realized that I can just use the official client in the background to let it populate the game activity instead, and use vencord for everything else.

**Comment by Vendicated** [comment]
it works just fine on vesktop. make sure you're using up to date vencord. if you are and it still happens, please use our support channel
