### ISSUE TITLE
[Bug] Wayland-Screenshare dies on resize

### ISSUE THREAD

**Issue by she11sh0cked** [Vencord/Vesktop#162]
Screenshare stops updating the image when resizing the streamed window.

**Info:**
Ptb 239402 (d5844b3)
Vencord 544edce (Vesktop V0.4.0)
Electron 27.0.0
Chromium 118.0.5993.54
~~Windows 10 64-Bit~~ <- Thats a lie. I'm using Arch, btw.
WM: KWin (Wayland)

**Comment by Vendicated** [comment]
cannot reproduce. if anything, it's an issue with electron/chromium/your DE/WM that's out of our control

so sadly there's nothing we can do for you
