### ISSUE TITLE
Rich presence fails to connect

### ISSUE THREAD

**Issue by davawen** [Vencord/Vesktop#165]
Hi! First of all, thank you for this software and all the goodies that come with it :)  
It's so much better than the official client on linux!

I spent an embarrassingly long time looking through stack traces, only to realize that in the last update, to get rich presence you need the WebRichPresence plugin to be on 😅
```ts
/// src/renderer/index.ts:51
const arRPC = Vencord.Plugins.plugins["WebRichPresence (arRPC)"] as any as {
    handleEvent(e: MessageEvent): void;
};

VesktopNative.arrpc.onActivity(data => {
    if (!Settings.store.arRPC) return;

    arRPC.handleEvent(new MessageEvent("message", { data }));
    // Failed with "handleEvent is not a function" since the plugin wasn't loaded
    // Maybe it should test for the plugin to be loaded and print a better message
});

```

However, even after enabling the plugin, it seems the built-in arRPC instance doesn't expose the websocket bridge.
Here is the log from Vesktop:
```
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```
Which leads to:
```
WebSocket connection to 'ws://127.0.0.1:1337/' failed
```

I need to disable the builtin arRPC in the settings, and launch it separately for it to work:
```
$ node src
[arRPC > bridge] listening on 1337
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[arRPC > bridge] web connected
```

Is this only me or are other affected? Any idea on how to fix the builtin instance?

**Comment by Vendicated** [comment]
you don't need to enable the plugin. it just works without it

**Comment by davawen** [comment]
For some reason, the rpm didn't update correctly 🤨  
I deleted everything, reinstalled it and it works now!  
Sorry for the incovenience.
