### ISSUE TITLE
Popout window does not respect checked "Discord Titlebar" or unchecked "Enable Menu bar"

### ISSUE THREAD

**Issue by SpyTec** [Vencord/Vesktop#166]
![image](https://github.com/Vencord/Vesktop/assets/6598829/34c445a7-eeae-4d63-b95a-a588b6543fa8)

**Comment by ODENYGG** [comment]
Just noticed this too, i'm on a fresh Vesktop install.

**Comment by Vendicated** [comment]
should be fixed via https://github.com/Vencord/Vesktop/commit/6483b3a3d96181c9dca87abb095f94291146d161

please try again once the next vesktop version has been released (soon) and report back then
