### ISSUE TITLE
0.4.1 broke websocket connection

### ISSUE THREAD

**Issue by UwUDev** [Vencord/Vesktop#167]
Hey, i just updated vesktop from 0.4.0 to 0.4.1 but i can't use it anymore. I thought it was a discord problem because the connection to the websocket locked in the "pending" state but everything works on discord canary.

*you can see canary in the left and vesktop in the right*

![image](https://github.com/Vencord/Vesktop/assets/61664271/9b2e89b9-5ce0-477d-bc9f-ee1bb9185353)

**Comment by UwUDev** [comment]
Edit: it looks like the same issue of [#147](https://github.com/Vencord/Vesktop/issues/147) because i have a ts crash right after opening the ws
```
webpack.ts:66 Uncaught TypeError: Cannot read properties of undefined (reading 'c')
    at zs (webpack.ts:66:18)
    at set (patchWebpack.ts:41:17)
    at 970cbbe7a33192f0c7c5.js:1:111651
    at 970cbbe7a33192f0c7c5.js:1:111746
    at 970cbbe7a33192f0c7c5.js:1:112894
```

**Comment by driedpampas** [comment]
Installing 0.4.1 broke 0.3.3 and 0.4.0 for me (yes I uninstalled and installed the older versions which I know worked before, but it always stays on pending like in the ss above)

**Comment by Vendicated** [comment]
Update your Vencord. See (or follow) the announcements channel on our official discord server for more info
