### ISSUE TITLE
Stuck on white screen

### ISSUE THREAD

**Issue by Astralchroma** [Vencord/Vesktop#177]
Arch Linux (6.5.8-zen1-1-zen)
Hyprland
`vencord-desktop-git r209.19c3112-1`

**Comment by TheKodeToad** [comment]
If you update Vencord this should be fixed. Discord changed a lot of compiler settings recently which made everything :nyaboom:

**Comment by Astralchroma** [comment]
Nuked the vencord folder in .config, seems to have fixed it. I thought I had updated it because I updated the package, apparently not.
Probably leave this open for a bit so its easy for other people to find?
