### ISSUE TITLE
Swap Order of SpellCheck & Paste in Context Menu (Right Click)

### ISSUE THREAD

**Issue by phoriah** [Vencord/Vesktop#179]
Any chance we could have these re-ordered? Personally, I'm very used to "Paste" being the bottom-most option.
Vesktop:
![Vesktop](https://github.com/Vencord/Vesktop/assets/95628489/405360fb-b4db-4360-bcf7-f09a01c003da)
Discord PC:
![Discord PC](https://github.com/Vencord/Vesktop/assets/95628489/7b2f5cc7-00fa-45bc-991b-61ba1fb16a3c)

**Comment by Vendicated** [comment]
imo not a good idea, because this is a very different story once you have auto suggestions

plus you can do this with some css
