### ISSUE TITLE
Opening to a white screen

### ISSUE THREAD

**Issue by TheMenko** [Vencord/Vesktop#180]
Basically this is #177  but not fixed by doing what that person did. 
Things i tried:
1. Nuke Vencord in ~/.config/Vencord
2. Update from tray icon
Both options don't do anything. Also launching vencorddekstop from terminal does not output any logs in the terminal.
-----
Distro: NixOS
Kernel: 6.5.7-xanmod1
Gpu: AMD (mesa 23.1.7)

**Comment by lewisakura** [comment]
Vencord is not supported on Nix or NixOS officially (we do not maintain the package override), and therefore we will not provide support.

**Comment by Vendicated** [comment]
this is most likely an issue with your system. it works fine on every major distro. make sure you have your environment properly set up. you could also try running with --disable-gpu

**Comment by lylythechosenone** [comment]
Vesktop 0.4.2 (from nixpkgs master, hopefully stable soon) fixes the issue.
