### ISSUE TITLE
Screensharing doesnt work

### ISSUE THREAD

**Issue by joelschmol** [Vencord/Vesktop#181]
Opening this issue because user **index.tsx** suggested in the support channel on discord

Screensharing doesnt work for me. It never did, but I always thought vesktop didnt have it. I only realized when my friends told me they could share their screens. Using gnome on wayland, archlinux. Clicking on the share screen button does nothing at all.

Here is the output of /vencord-debug
![image](https://github.com/Vencord/Vesktop/assets/88237375/7d9cd686-a760-44e9-af88-1a1d71f63599)

Upon running vencord through the terminal, these are the logs
```
Fontconfig error: "/home/user/.config/fontconfig/conf.d/01-emoji.conf", line 1: XML declaration allowed only at the start of the document

Fontconfig error: "/home/user/.config/fontconfig/conf.d/01-emoji.conf", line 1: XML or text declaration not at start of entity
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
libva error: /usr/lib/dri/iHD_drv_video.so init failed
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[27826:1026/185038.404762:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[27826:1026/185038.406457:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[27788:1026/185050.590520:ERROR:screen_capture_portal_interface.cc(48)] Failed to request session: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
[27788:1026/185050.590634:ERROR:base_capturer_pipewire.cc(81)] ScreenCastPortal failed: 3
Error during screenshare picker Failed to get sources.
(node:27788) UnhandledPromiseRejectionWarning: TypeError: Video was requested, but no video stream was provided
    at AsyncFunction.<anonymous> (VCDMain:36:2159)
(Use `vencord --trace-warnings ...` to show where the warning was created)
(node:27788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by Vendicated** [comment]
we can't really help you with that

it's an issue with your DE, graphic driver, or similar. your stacktrace clearly shows that video init failed
`MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
libva error: /usr/lib/dri/iHD_drv_video.so init failed
`

googling the error yields https://github.com/intel/media-driver/issues/1298

try researching further and looking for fixes. make sure your drivers and kernel are up to date. try a different DE/WM, a different distro, or wayland/x11 (the opposite of whichever you use right now).

**Comment by Vendicated** [comment]
according to https://bbs.archlinux.org/viewtopic.php?id=281868, you might be able to fix it by  manually building and installing the latest intel-media-driver

**Comment by joelschmol** [comment]
I see. Thank you
