### ISSUE TITLE
[Linux/SteamOS]: Vextop hangs when launched through Steam

### ISSUE THREAD

**Issue by TauAkiou** [Vencord/Vesktop#182]
Vextop will not launch when run through Steam. It will launch in Desktop Mode through the standard UI, but it will hang and always be listed as "Running" in SteamUI. This also means that Vextop will not launch in GamepadUI (Gaming Mode) either, as running applications through Steam is required in that context.

**Comment by AAGaming00** [comment]
i'll give this a look soon, probably today.

**Comment by AAGaming00** [comment]
@TauAkiou Does it freeze on a white screen for you in game mode?

**Comment by AAGaming00** [comment]
@Vendicated you can close this now
