### ISSUE TITLE
Add FAQ re. missing audio when screen sharing on Linux

### ISSUE THREAD

**Issue by SelfMadeSystem** [Vencord/Vesktop#183]
I got Vesktop because I heard that it supported screen sharing with audio on Linux, and it does! Only problem is that it requires 2 things (AFAIK):

1. Use of PipeWire
2. glibcxx version >= 3.4.30

The former is fine, and Vesktop tells you about it when trying to screen share with audio. The latter isn't as fine, because the error it gives you when trying screen share is the same as when you don't have PipeWire, which is quite misleading. When I ran Vesktop in the terminal, I found that it wanted `glibcxx_3.4.30` which is unavailable by default on stable Ubuntu and its derivatives.

I think it would be a good idea to tell users about that as well. One way I found to get the latest version of glibc on Ubuntu is:

```bash
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```

**Comment by Vendicated** [comment]
planned actually, it'll be in the next update!

**Comment by Vendicated** [comment]
done in https://github.com/Vencord/Vesktop/commit/886d02f7c3660dfcd2c1cf508fe84fb685123cd6
