### ISSUE TITLE
No code signature on macOS

### ISSUE THREAD

**Issue by doinkythederp** [Vencord/Vesktop#184]
The fact that Vesktop does not have a code signature included in the app bundle makes it harder for users to open, marking it as "damaged" and prompting the user to delete it. Here's what that looks like:
![image](https://github.com/Vencord/Vesktop/assets/75394401/6a9413ac-2804-43f9-ab62-7e20f8c5e9c1)
Signing the app, even as an "unverified developer", will improve the user experience. I would recommend using the built in `codesign` command in CI to create an Ad Hoc (no developer account) signature:

```
codesign --force --deep --sign "-" /Applications/Vesktop.app
```

This allows the user to make an exception to macOS Gatekeeper (by right clicking on the app and clicking Open), without needing to enter the admin password or use the terminal. It also no longer prompts the user to delete the app.

![image](https://github.com/Vencord/Vesktop/assets/75394401/03f760bd-e11e-426a-875c-13015c5cede7)

This does not completely fix the issue but is definitely an improvement. I'd be willing to work on a pull request that resolves this issue.

**Comment by doinkythederp** [comment]
Looks like electron-builder has an option to to this built in. Setting "identity" to "-" should perform the same behavior as above. https://www.electron.build/configuration/mac#MacConfiguration-target

**Comment by ryanccn** [comment]
Setting `mac.identity` to `-` doesn't seem to work.

![skipped macOS application code signing reason=Identity name is specified, but no valid identity with this name in the keychain identity=- allIdentities=](https://github.com/Vencord/Vesktop/assets/70191398/5119ec62-6bed-40c9-8221-a514d8aa2015)

**Comment by Vendicated** [comment]
it does now

**Comment by PixelHir** [comment]
<img width="257" alt="image" src="https://github.com/Vencord/Vesktop/assets/7670940/349d7dd6-eae7-41d3-adf7-01926fe29ccb">
downloaded the latest dmg for arm64, macOS still refuses to accept it

**Comment by PixelHir** [comment]
<img width="822" alt="image" src="https://github.com/Vencord/Vesktop/assets/7670940/b8313ad5-b084-482a-8c92-bc17409c9e88">
<img width="576" alt="image" src="https://github.com/Vencord/Vesktop/assets/7670940/38edbb6c-a4a8-4f1d-aacd-15a7332847b6">

codesign did not work but xattr did.

**Comment by Luk4h** [comment]
Latest(1.5.2) release:
![image](https://github.com/Vencord/Vesktop/assets/78048969/dc272360-711d-443b-abfc-b9b84fe4365f)

**Comment by toasterw** [comment]
Open System Preferences > Privacy & Security > Scroll to the bottom and allow it there, then try open it again
