### ISSUE TITLE
Emoji's in names and server channels

### ISSUE THREAD

**Issue by jake770321** [Vencord/Vesktop#188]
Emoji's in names and server channels seem to use a more simplified version. Is there any way to change this?

Vesktop:
![vesktop](https://github.com/Vencord/Vesktop/assets/84999457/1731ccbe-08b5-49c1-b4c6-f19f16a7e72e)

Discord:
![discord](https://github.com/Vencord/Vesktop/assets/84999457/d2d03ea8-5ee5-4eea-97ef-2fba2e1d7131)

**Comment by 0x3C50** [comment]
seems to use the regular font for emojis, not the twemoji icons

**Comment by D3SOX** [comment]
I assume you're on Linux. It looks like your system font configuration is not correctly set up to display color emoji. What distro are you using? Maybe you just need to install a package named similar to `noto-fonts-emoji`.
It works fine for me, but I've set it up manually to use my Emoji pack of choice. <sub>(joypixels ftw)</sub>

**Comment by Vendicated** [comment]
well it's an issue with your fonts. install a proper emoji font

**Comment by jake770321** [comment]
Just an update: using the flatpak fixed this issue for me

**Comment by Raideeen** [comment]
Usually if fonts aren't correctly displayed or symbols are missing, you need to install [noto-fonts](https://archlinux.org/packages/extra/any/noto-fonts/), [noto-fonts-cjk](https://archlinux.org/packages/extra/any/noto-fonts-cjk/), [noto-fonts-emoji](https://archlinux.org/packages/extra/any/noto-fonts-emoji/) and [noto-fonts-extra](https://archlinux.org/packages/extra/any/noto-fonts-extra/).

**Comment by Vendicated** [comment]
why the hell would you necro a 2 year old resolved issue
