### ISSUE TITLE
[Feature Request] Better arRPC Integration

### ISSUE THREAD

**Issue by 2meito** [Vencord/Vesktop#190]
It would be great if we could either supply the path for or have Vesktop download arRPC into a default directory and then have it automatically start and stop as needed.

**Comment by ImLvna** [comment]
it already does that

**Comment by Vendicated** [comment]
arrpc is fully integrated, you just need to enable rich presence in settings. p0

**Comment by 2meito** [comment]
Ah, my bad. I got confused because I thought it was only just the plugin.
