### ISSUE TITLE
Ignores Equalizer APO microphone settings

### ISSUE THREAD

**Issue by hyperClink** [Vencord/Vesktop#192]
The Vesktop app seems to ignore Equalizer APO settings after joining a VC. I can open the settings and hear myself with the Equalizer APO properly processing my audio until I go into a voice channel, after this the Vesktop app starts to use unprocessed audio even after a restart.

Another audio related thing I've noticed is that it shows microphones twice in the Vesktop app, while only showing one in the official app. Not sure if that is related.
![изображение](https://github.com/Vencord/Vesktop/assets/45831360/e6a2ed26-4bac-4148-8c35-1f2d1de3785b)
![изображение](https://github.com/Vencord/Vesktop/assets/45831360/c7e20e65-c591-4cba-b2ba-bb91f993f997)

**Comment by lewisakura** [comment]
Equalizer APO is responsible for applying the voice effects. We're just taking what it's outputting. If it's not applying the effects properly there's nothing we can do.

**Comment by vasilyvaganov** [comment]
The same problem, everything is fine in the official discord client. The only thing I noticed is that equalizer apo effects don't work in chrome-based browsers when everything works in the same firefox

**Comment by lewisakura** [comment]
> The only thing I noticed is that equalizer apo effects don't work in chrome-based browsers when everything works in the same firefox

In which case, you should report the issue to the Equalizer APO developers and see if it's an issue with them or with Chromium. Discord uses a native module to handle voice, so that's most likely the reason why you aren't experiencing issues on the official client.
