### ISSUE TITLE
No desktop notifications on MacOS

### ISSUE THREAD

**Issue by t1an-xyz** [Vencord/Vesktop#193]
I just installed Vesktop 0.4.2 for MacOS (intel chip), and even though I have the notifications set to "Only use Desktop notifications when Discord is not focused," I am not getting any desktop notifications, though I do hear the ping sound. I am using MacOS Ventura 13.1.

**Comment by Vendicated** [comment]
that option has nothing to do with notifications. Make sure you have them on in discord notification settings. use our support channel if you need furtehr help
