### ISSUE TITLE
Vesktop hangs on a white screen when opening

### ISSUE THREAD

**Issue by enderpuff** [Vencord/Vesktop#196]
After update 0.4.1, the app just hangs on a white screen when I try to open it. reinstalling doesn't work, and updating also doesn't.
Platform - Linux, Wayland.
Here's what I get in the logs when opening the app through the terminal:
`(node:17256) UnhandledPromiseRejectionWarning: ReferenceError: IS_EXTENSION is not defined
    at VencordDesktopMain:5:737
    at VencordDesktopMain:5:225
    at VencordDesktopMain:5:2229
    at VencordDesktopMain:5:225
    at VencordDesktopMain:5:2657
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:17256) ReferenceError: IS_EXTENSION is not defined
    at VencordDesktopMain:5:737
    at VencordDesktopMain:5:225
    at VencordDesktopMain:5:2229
    at VencordDesktopMain:5:225
    at VencordDesktopMain:5:2657
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[Vencord] Installed React Developer Tools
(node:17256) ExtensionLoadWarning: Warnings loading extension at /home/chloe/.config/VencordDesktop/VencordDesktop/ExtensionCache/fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

[17294:1028/145626.309103:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!`

**Comment by Vendicated** [comment]
Use the "Update Vencord" option when right clicking the Vesktop tray icon. If you're on Mac, use the MenuBar. If you cannot do this, go to your config folder (%APPDATA% on windows, ~/.config on linux, ~/Library/Application Support on mac) and delete VencordDesktop/VencordDesktop/vencordDist, then restart Vesktop.
