### ISSUE TITLE
Screenshare infinitely loads if you are watching a screenshare

### ISSUE THREAD

**Issue by he3als** [Vencord/Vesktop#197]
If I'm watching a screenshare and screenshare myself, then on my end (looking at the preview) and on everyone else's end, the screenshare infinitely loads.

I can screenshare just fine if I stop watching all other screenshares first.

This is not an issue when using regular Discord with Vencord, and regular Discord without Vencord.

![image](https://github.com/Vencord/Vesktop/assets/65787561/93919fb7-7532-41dc-bf4b-f001264d162b)

## Vencord Debug Info
- Vencord: v1.6.1 • 522fdcd (Vesktop v0.4.2) - 28 Oct 2023
- Discord Branch: stable
- Client: Vesktop v0.4.2
- Platform: Win32
- GPU: NVIDIA (no iGPU)
- Outdated: false
- OpenAsar: false

### Enabled Plugins (42):
```
AlwaysTrust, BetterFolders, BetterGifAltText, BetterUploadButton, CallTimer, ClearURLs, DisableDMCallIdle, ForceOwnerCrown, MemberCount, MessageClickActions, MoreUserTags, NoF1, NoTypingAnimation, PermissionsViewer, PlatformIndicators, SendTimestamps, ShowConnections, ShowTimeouts, TypingIndicator, TypingTweaks, Unindent, UnsuppressEmbeds, UserVoiceShow, ValidUser, ViewIcons, ViewRaw, VoiceMessages, WebKeybinds
```
```
BadgeAPI, CommandsAPI, ContextMenuAPI, MemberListDecoratorsAPI, MessageAccessoriesAPI, MessageDecorationsAPI, MessageEventsAPI, MessagePopoverAPI, NoticesAPI, ServerListAPI, NoTrack, Settings, SupportHelper, WebContextMenus
```

**Comment by TheKodeToad** [comment]
This happens frequently in unmodified Discord IIRC.

**Comment by Vendicated** [comment]
nothing to do with us

**Comment by he3als** [comment]
Are there any workarounds?

**Comment by Vendicated** [comment]
tell them to restart their stream
