### ISSUE TITLE
[Feature Request] BetterVolume

### ISSUE THREAD

**Issue by Foriki** [Vencord/Vesktop#198]
It's really useful,
I haven't seen it in the plugins tab and I think it will be very useful

( https://github.com/Zerthox/BetterDiscord-Plugins/tree/master/dist/bd )

**Comment by ImLvna** [comment]
🔫

**Comment by D3SOX** [comment]
This is the repository for Vesktop, not Vencord and plugin suggestions should not be made via GitHub issues. And btw there already is https://vencord.dev/plugins/VolumeBooster
