### ISSUE TITLE
 C++ library claimed too old on current LTS distros

### ISSUE THREAD

**Issue by SSUPII** [Vencord/Vesktop#199]
As said in [here](https://gist.github.com/Vendicated/b655044ffbb16b2716095a448c6d827a), audio streaming requires libstdc++ to be 13 or higher.
Unfortunately, this makes using such feature impossible on most mainstream non-rolling release distributions like Debian 12 Bookworm and Ubuntu 22.04 LTS.
Forcing an update using packages from unstable testing releases like Debian 13 or rolling releases like Ubuntu 23.10 will extremely likely break this systems.

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/commit/ec1c719553b716afefe3f8a3e013e1f9c483142f

**Comment by Curve** [comment]
> Some slight clarification:

The current minimum requirement for venmic is GLIBC 2.36 which was released in August of 2022.

In case your system still ships an older glibc version, I'd either suggest upgrading your system or to try the (upcoming) flatpak

**Comment by SSUPII** [comment]
> > Some slight clarification:
> 
> The current minimum requirement for venmic is GLIBC 2.36 (on master) which was released in August of 2022.
> 
> In case your system still ships an older glibc version, I'd either suggest upgrading your system or to try the (upcoming) flatpak

At least Debian 12, the shipped glibc version is 2.36 exactly (https://packages.debian.org/bookworm/libc6)

Its very likely this is the case for Ubuntu 22.04 LTS too and the systems based on it.

**Comment by boobthecat** [comment]
The steam deck comes with version 2.36 and even then I get the error message 

![image](https://github.com/Vencord/Vesktop/assets/127695532/2ce9edbc-8288-4245-8d25-c871378ed1b3)
![image](https://github.com/Vencord/Vesktop/assets/127695532/7ec962f3-d946-40cb-8692-0fe1f26e20ab)

**Comment by Curve** [comment]
> The steam deck comes with version 2.36 and even then I get the error message 
> 
> ![image](https://github.com/Vencord/Vesktop/assets/127695532/2ce9edbc-8288-4245-8d25-c871378ed1b3)
> ![image](https://github.com/Vencord/Vesktop/assets/127695532/7ec962f3-d946-40cb-8692-0fe1f26e20ab)
> 
> 

As previously mentioned you need to build from master to get the lowered requirement.

Are you sure you're building from master?

**Comment by D3SOX** [comment]
I can confirm that streaming, including audio, works fine with latest master on the current Deck Stable software :)

**Comment by boobthecat** [comment]
I'm sure it is, I just don't want to get it wiped by the next update. After all, SteamOS is a distro like any other, there's no reason for it not to work.

**Comment by D3SOX** [comment]
You don't need to install files in a system directory to get a current build. I personally built the AppImage on my PC and pushed it to the Deck via KDE Connect but there will be a new release with the fixes included soon so you can just download the AppImage then.

**Comment by boobthecat** [comment]
Can you elaborate on how you did that? Anyway I think is better for me to wait for the flatpak release since updating Appimages is boring

**Comment by D3SOX** [comment]
Yeah, unless you need it now it would be easier. And yes you'd need to manually update the AppImage.

But for reference if you need it basically just clone the repo and run the package script then you'll find the AppImage inside the `dist` folder
```bash
git clone https://github.com/Vencord/Vesktop
cd Vesktop
pnpm i
pnpm package
```

**Comment by boobthecat** [comment]
Thank you

**Comment by boobthecat** [comment]
Actually I'm think I'm going to do this. Just one more thing, how can I clean uninstall it when a new version/flatpak gets released? Only thing holding me back, I'm pretty paranoid about leftovers =P

**Comment by D3SOX** [comment]
Just delete the AppImage and the config folders `~/.config/Vencord`, `~/.config/VencordDesktop`
I think that's all

**Comment by boobthecat** [comment]
Thank you kindly for the help

**Comment by boobthecat** [comment]
Do I have to install pnpm? Kinda goes back to messing with installing things that will get wiped 

```
cd Vesktop
pnpm i
pnpm package
Cloning into 'Vesktop'...
remote: Enumerating objects: 1623, done.
remote: Counting objects: 100% (788/788), done.
remote: Compressing objects: 100% (263/263), done.
remote: Total 1623 (delta 660), reused 574 (delta 524), pack-reused 835
Receiving objects: 100% (1623/1623), 694.30 KiB | 10.06 MiB/s, done.
Resolving deltas: 100% (996/996), done.
bash: pnpm: command not found
bash: pnpm: command not found
```

**Comment by D3SOX** [comment]
Did you do this directly on your Steam Deck? If yes it's probably best now to use a locally managed Node.js version for example with [nvm](https://github.com/nvm-sh/nvm) like
```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
nvm install --lts
nvm use --lts
npm i -g pnpm
```
(untested)

**Comment by boobthecat** [comment]
> As I said, I've built it on my PC and then just transferred it.

Ha! I forgot about that, sorry. That's why it failed. I will try finding another method, thanks.
