### ISSUE TITLE
Can't right click selected text

### ISSUE THREAD

**Issue by MGThePro** [Vencord/Vesktop#202]
When I right click selected text, nothing happens on the first right click

On the second right click,  the text gets unselected and the context menu opens as if no text was selected 

Stable 241602 (86f279e)
Vencord 522fdcd (Vesktop V0.4.2)
Electron 27.0.2
Chromium 118.0.5993.89

I'm on Arch Linux running KDE Plasma Wayland. The issue occured both on XWayland and running Discord in Electron's native Wayland.
Selecting text and copying via Ctrl+C works

**Comment by D3SOX** [comment]
Additionally, when trying to cut text from an input field it copies the text but doesn't delete it

https://github.com/Vencord/Vesktop/assets/24937357/ea590f68-751a-4b1d-ba34-591e7ca68b9e

I think the cause is the same, that's why I post it here

**Comment by Vendicated** [comment]
it's actually just that the WebContextMenu plugin doesn't implement this

**Comment by Vendicated** [comment]
please reopen as a feature request on https://github.com/Vendicated/Vencord
