### ISSUE TITLE
pnpm -i cannot find "node" depency

### ISSUE THREAD

**Issue by Fabxx** [Vencord/Vesktop#203]
OS: Debian GNU/Linux 12

Installed pnpm from the official website.

As soon i try to find the depencies to compile, i get the following error log:

![immagine](https://github.com/Vencord/Vesktop/assets/30447649/bb03aed3-f66b-47a7-a8b6-358fa06b8009)

**Comment by Stefanuk12** [comment]
Make sure node is installed and within your environment. I recommend to use NVM.

**Comment by Fabxx** [comment]
> Make sure node is installed and within your environment. I recommend to use NVM.

the problem tho is that there is no package for debian about node, and the official site only provides packages for windows and macOS. So where should i find the node depency for debian?

**Comment by ImLvna** [comment]
https://github.com/nodesource/distributions https://github.com/nvm-sh/nvm

**Comment by sunnniee** [comment]
https://nodejs.org/en/download/package-manager#debian-and-ubuntu-based-linux-distributions (also how do you even install pnpm without node)
