### ISSUE TITLE
Can't screenshare at all, button does nothing

### ISSUE THREAD

**Issue by MrShelbySann** [Vencord/Vesktop#204]
Pressing the screenshare button while on a call does nothing.
I'm on Arch Linux + Wayland.

OS: Arch Linux
Vencord: 522fdcd
Vesktop: 0.4.2 / Stable Branch

Error message when ran from terminal: 
```
[313011:1031/144332.440578:ERROR:screen_capture_portal_interface.cc(48)] Failed to request session: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L’interface « org.freedesktop.portal.ScreenCast » n’existe pas pour l’objet à l’emplacement /org/freedesktop/portal/desktop
[313011:1031/144332.440589:ERROR:base_capturer_pipewire.cc(81)] ScreenCastPortal failed: 3
Error during screenshare picker Failed to get sources.
(node:313011) UnhandledPromiseRejectionWarning: TypeError: Video was requested, but no video stream was provided
    at AsyncFunction.<anonymous> (VCDMain:36:2159)
(Use `vencord --trace-warnings ...` to show where the warning was created)
(node:313011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

Tried resetting the app and disabling all themes / plugins, but the issue persists.

**Comment by MrShelbySann** [comment]
Issue had nothing to do with the app, but with my xdg-desktop-portal configurations.

**Comment by EinfxchFinn** [comment]
I have the same problem. How did you fix it?

**Comment by MrShelbySann** [comment]
Hey. You can check the Aech wiki article on xdg-portal and at the very bottom, there’s a section to fix a bug with sway. It fixed my issues on Wayfire as well: https://wiki.archlinux.org/title/XDG_Desktop_Portal

**Comment by varmisa** [comment]
@MrShelbySann Sadly, but it not working for NixOS, btw armcord is work properly from box.

**Comment by sim590** [comment]
For me, it seemed like the service `xdg-desktop-portal-wlr.service` and `xdg-desktop-portal.service` were not starting by themselves. I had to enable them and then after configuring Sway as @MrShelbySann suggested, then it worked. I rebooted to see if the config was permanent and it seems like it was.

**Comment by MrShelbySann** [comment]
> For me, it seemed like the service `xdg-desktop-portal-wlr.service` and `xdg-desktop-portal.service` were not starting by themselves. I had to enable them and then after configuring Sway as @MrShelbySann suggested, then it worked. I rebooted to see if the config was permanent and it seems like it was.

Yes, that’s exactly the issue I had.
I had to declare some environment variables to make mine stick on Wayfire, but now it works.
It took a lot of fiddling to find out why those 2 services weren’t starting.

**Comment by varmisa** [comment]
For me xdg-portals are working, but vesktop, armcord, vencord, not working on NixOS stable.
