### ISSUE TITLE
Distribute a flatpak

### ISSUE THREAD

**Issue by theoparis** [Vencord/Vesktop#205]
I cannot use this on my system atm since there is no flatpak nor a musl libc tarball. It would be nice if there was a flatpak provided so that Alpine/Gentoo users could use this.

**Comment by theoparis** [comment]
My bad this is a duplicate of #29

**Comment by Vendicated** [comment]
just build from source for now

**Comment by lewisakura** [comment]
We now distribute a Flatpak: https://flathub.org/apps/dev.vencord.Vesktop
