### ISSUE TITLE
[feature request] Integrating or adding the ability to turn on adblock

### ISSUE THREAD

**Issue by siren15** [Vencord/Vesktop#210]
As we all know YouTube VC integration has a tons of ads if you don't have nitro, and I've read that even if you have nitro you get ads in some regions. 

It would be a great addition to have it either integrated into vesktop or as a plugin where we could turn on adblock for that. Wouldn't have to switch to a browser(Since ublock does block them in a browser.) for youtube vc sessions.

**Comment by Vendicated** [comment]
this is a plugin request, so the vesktop repo is not the right place
