### ISSUE TITLE
Linux/Wayland/GNOME screenshare requires source to be selected twice

### ISSUE THREAD

**Issue by taylorberg** [Vencord/Vesktop#212]
On Linux (GNOME/Wayland), screensharing seems to open up a 2 separate source selection windows:

![image](https://github.com/Vencord/Vesktop/assets/1077407/f6b5c79e-aa23-44a1-ad28-5ca127b640bd)
The first one comes up and whatever shows up here ends up as the preview image for the Screenshare modal. If I pick the audio device and hit Go Live, then another selector pops up asking me to choose a different window. Whichever one I pick here ends up being what's shared to the channel. It's as if it forgets my selection after it generates the preview image.

Worst case maybe having a button in Settings to toggle off the preview would be nice so that we don't have to dig through 2 source selector dialogs.

Just a super minor bug, thank you all so much for finally making Linux screensharing with audio convenient!!

Using Vesktop 0.4.2 + Vencord bfb48b4 + Arch + Gnome 45 + Wayland 1.22

**Comment by Vendicated** [comment]
electron issue, nothing we can do other than wait for fix unfortunately
