### ISSUE TITLE
add support for blacklisting apps for audio screenshare

### ISSUE THREAD

**Issue by nanopone** [Vencord/Vesktop#218]
usually, when i'm in a discord call, it's with my partner, and both of us deafen each other since we speak over mumble and use discord's screensharing feature to watch youtube videos or play games. 

in order to prevent having to close the screenshare and re-open a new one whenever either of us decide to do something else, we usually use the "entire system" option to capture all audio all of the time, and then i have to open helvum (pipewire patchbay) to disconnect mumble from vesktop, so that my partner can't hear himself.

i noticed that vesktop automatically excludes itself from its sound being streamed over screenshare, presumably to prevent echo from the voice chat. if vesktop has this ability, maybe there can be an option to automatically exclude *any* app the user wants (in my case, mumble)? it could maybe be a text box where you can enter the names of binaries to exclude, or even maybe a dropdown list that lists all of the current running apps and lets you pick which ones to opt out of sharing.

**Comment by Curve** [comment]
This will require a change in venmic, I will update the implementation later

**Comment by Vendicated** [comment]
when you start a screenshare there's a dropdown of audio sources to use. is mumble listed here?

if yes, we could add the exact same dropdown a second time, this time for audio to *exclude*

**Comment by Curve** [comment]
> when you start a screenshare there's a dropdown of audio sources to use. is mumble listed here?
> 
> if yes, we could add the exact same dropdown a second time, this time for audio to _exclude_

I think this is the way, venmic already supports this ^^

**Comment by Curve** [comment]
Took a while but #621 makes this possible :)
