### ISSUE TITLE
Crashes/annoying popups when Vesktop settings file is read-only

### ISSUE THREAD

**Issue by pluiedev** [Vencord/Vesktop#220]
As a NixOS user, I'm accustomed to writing config files via home-manager, which are installed as symlinks to a read-only file in the Nix store. Unfortunately, Vesktop doesn't seem to like that... Sometimes it crashes, sometimes it works just fine except when it tries to write to the config, like as shown here.

![image](https://github.com/Vencord/Vesktop/assets/22406910/180aaaaa-b772-41c2-8fa3-ba16eade363d)

I'm not that convinced that Vesktop *needs* to write to the config that often — is there any way to patch this?

**Comment by Vendicated** [comment]
nixos is not supported.

**Comment by Vendicated** [comment]
almost all software needs to persist data to the disk. im not sure what you're expecting. just don't make it readonly

**Comment by Scrumplex** [comment]
> almost all software needs to persist data to the disk. im not sure what you're expecting. just don't make it readonly

Almost all software cleanly separates user settings from application data though. Obviously you are going to need a place to cache stuff, but a settings.json shouldn't really change much beyond what the user does themselves.

Many people like to manage dotfiles in a central repo and one way of preventing drift is to make those dotfiles read-only. I don't see how NixOS is even a factor, as it's just one of many systems that work that way.

**Comment by Vendicated** [comment]
> Almost all software cleanly separates user settings from application data though

yes?
![grafik](https://github.com/Vencord/Vesktop/assets/45497981/7c4e9a8b-600a-4d8d-902c-a668bc6c8ddc)

i don't understand what you're trying to say, sorry

**Comment by Scrumplex** [comment]
> i don't understand what you're trying to say, sorry

Judging by the [interface definition of `Settings`](https://github.com/Vencord/Vesktop/blob/main/src/shared/settings.d.ts) there are several values that aren't really user settings like windows state or `firstLaunch` and `skippedUpdate`. Obviously these are gone trigger the save handler, without the user intending to.

Those would belong in separate state files preferably in `.local/share`

I would be happy to implement this and some other improvements for read-only configs myself, if you don't really want to work on it

**Comment by Vendicated** [comment]
> preferably in .local/share

no. they should be in .config, alongside the other files. putting them in a separate file is not a bad idea though. for example state.json, in the same directory as settings.json

**Comment by Vendicated** [comment]
prs welcome, just make sure to preserve backwards compatibility, for example by migrating them from the old file

**Comment by n3oney** [comment]
@pluiedev if you want a quick fix to just not have that issue you can just do this:

```nix
   environment.systemPackages = [
      (pkgs.vesktop.overrideAttrs (old: {
        patches = (old.patches or []) ++ [./readonlyFix.patch];
        postFixup = ''
          wrapProgram $out/bin/vencorddesktop \
            --add-flags "--enable-features=UseOzonePlatform --ozone-platform=wayland"
        '';
      }))
   ];
```
(also included enabling wayland in the postFixup, you can remove that if you don't need it),

where the patch file is this:
```patch
diff --git a/src/main/settings.ts b/src/main/settings.ts
index 6fad97f..dfc64e3 100644
--- a/src/main/settings.ts
+++ b/src/main/settings.ts
@@ -26,8 +26,10 @@ function loadSettings<T extends object = any>(file: string, name: string) {
 
     const store = new SettingsStore(settings);
     store.addGlobalChangeListener(o => {
-        mkdirSync(dirname(file), { recursive: true });
-        writeFileSync(file, JSON.stringify(o, null, 4));
+        try {
+            mkdirSync(dirname(file), { recursive: true });
+            writeFileSync(file, JSON.stringify(o, null, 4));
+        } catch {}
     });
 
     return store;
     ```

this will stop it from crashing when trying to write the config file. log still gets spammed with trash, but app works fine!

**Comment by SystematicError** [comment]
For Nix users running into this issue whilst trying to declaratively configure Vesktop, try using the [Nixcord](https://github.com/KaylorBen/nixcord) flake.
