### ISSUE TITLE
Showing the window through tray icon does not restore window state prior to minimizing

### ISSUE THREAD

**Issue by xparadoxical** [Vencord/Vesktop#222]
1. Maximize the window
2. Minimize it (you can also close it afterwards, doesn't matter for the end effect)
3. Click the Vesktop tray icon or use its Open action

Result: the window is now in "windowed" state - neither maximized or minimized. Looks like it's always the windowed state stored prior to maximizing and minimizing doesn't store maximized state.
Discord behavior, expected by me and present in the patch version of Vencord: the window opens as maximized.

**Comment by Vendicated** [comment]
cant reproduce, works fine for me

**Comment by xparadoxical** [comment]
```
Stable 244133 (351234d)
Vencord 86e9434 (Vesktop V0.4.3)
Electron 27.0.2
Chromium 118.0.5993.89
Windows 10 64-Bit
```
[Here's a video](https://streamable.com/0njw84) I recorded after uninstalling, deleting all vencord-related folders from %appdata% and %localappdata% and installing. Didn't touch any settings after logging in.

**Comment by dgbogi564** [comment]
> ```
> Stable 244133 (351234d)
> Vencord 86e9434 (Vesktop V0.4.3)
> Electron 27.0.2
> Chromium 118.0.5993.89
> Windows 10 64-Bit
> ```
> 
> [Here's a video](https://streamable.com/0njw84) I recorded after uninstalling, deleting all vencord-related folders from %appdata% and %localappdata% and installing. Didn't touch any settings after logging in.

It says the video has been archived. Can you upload it to youtube instead?

**Comment by Vendicated** [comment]
you can embed videos on github.

**Comment by lewisakura** [comment]
CNR + no response

**Comment by xparadoxical** [comment]
https://github.com/Vencord/Vesktop/assets/43796685/806881ee-8099-4e33-9532-95ccb6a6dece
