### ISSUE TITLE
Generic taksbar icon when using flags to enable native Wayland

### ISSUE THREAD

**Issue by CosmicHeron** [Vencord/Vesktop#225]
When starting `vencord-desktop` using flags `--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-blink-features=MiddleClickAutoscroll` to enable native Wayland support, autoscroll and to disable middle-click pasting, the client no longer has the usual VC icon in the taskbar, instead it is replaced with a generic white `W` in a yellow circle icon.

I'm running Vencord using the `vencord-desktop-git` AUR package on Arch in KDE.

Admittedly I'm not 100% if this is a general Electron issue or if the application requires additional settings to display the right icon when using Wayland.

**Comment by Vendicated** [comment]
instead of launching it from terminal, add these flags to the .desktop file or create a simple shell script at /usr/local/bin/vencord-desktop that calls the normal bin with your flags

both of those should work correctly, if not it's an issue with your DE/WM. it works fine for me on gnome

**Comment by CosmicHeron** [comment]
Turns out Plasma requires applications to have a specific property set. Found a solution [here](https://www.reddit.com/r/kde/comments/yz5o1g/how_to_make_kde_show_app_icons_instead_of_wayland/), specifically [this video](https://youtu.be/Sungl8gWU_8?si=nAyc49eGl14RFUeX&t=129) explains how to manually fix the icon to display properly.
