### ISSUE TITLE
Linux (SUSE)[AppImage] - Latest distro updates breaks Vencord?

### ISSUE THREAD

**Issue by biggestsonicfan** [Vencord/Vesktop#226]
![Screenshot_20231108_105716-1](https://github.com/Vencord/Vesktop/assets/9744201/f2042788-c66a-4c93-99fa-57a52723b0f4)

Just did a distro update and the AppImage seemed to not like this at all. Piping output and errors to a log resulted in a 400,000 line log instantly. If the cursor was moved inside the Vencord window, errors would increase exponentially.

Rolling back my distribution and things are fine again, but I did just want to send a heads up.

Log: 
[suse-appimage-vesktop-errors-081123.tar.gz](https://github.com/Vencord/Vesktop/files/13300455/suse-appimage-vesktop-errors-081123.tar.gz)

Edit: Oops, forgot some important info:
SUSE Tumbleweed with using KDE Plasma with AMD graphics

**Comment by janisslsm** [comment]
Might be from https://bugs.chromium.org/p/chromium/issues/detail?id=1442633 so this isn't something Vesktop has caused directly.
Could you try doing
`find ~/.config/ -name GPUCache -type d -exec rm -rf {} \;`
and seeing if that fixes it?

**Comment by biggestsonicfan** [comment]
That did the trick! I can't test with `0.4.3-1` because I should have just renamed the `GPUCache` folder because now I can't test the data against it.... maybe if I delete it one more time and rollback? Lemme try...

**Comment by janisslsm** [comment]
> That did the trick! I can't test with `0.4.3-1` because I should have just renamed the `GPUCache` folder because now I can't test the data against it.... maybe if I delete it one more time and rollback? Lemme try...

The bug from what I understood happens on relaunch, the gpucache gets corrupted so on new launch it's unusable

**Comment by biggestsonicfan** [comment]
Well rolling back I can't get `0.4.3` to do it again. I find it strange Vesktop functioned at all with the same broken cache before. As I can no longer test the issue (shouldn't have `rm -rf`'d ugh oops) I am closing.

**Comment by biggestsonicfan** [comment]
I spoke too soon. The first launch after update, all was well. I closed, and yes, it does happen again.

> The bug from what I understood happens on relaunch

Dead on the money. Now to test `0.4.3-1`.... yes! Even with the broken cache, `0.4.3-1` renders properly. I can swap back to `0.4.3` and still see it broken, so electron v29 was definitely the correct fix.

**Comment by janisslsm** [comment]
> I spoke too soon. The first launch after update, all was well. I closed, and yes, it does happen again.
> 
> > The bug from what I understood happens on relaunch
> 
> Dead on the money. Now to test `0.4.3-1`.... yes! Even with the broken cache, `0.4.3-1` renders properly. I can swap back to `0.4.3` and still see it broken, so electron v29 was definitely the correct fix.

Good to know. I remember seeing libdrm being mentioned as the main thing causing the corruption itself, chromium bug just makes it so corrupt cache doesn't make everything messed up.

**Comment by janisslsm** [comment]
Also alternative fix to electron 29 is running vesktop with `--disable-gpu-driver-bug-workarounds`

**Comment by biggestsonicfan** [comment]
> Also alternative fix instead of using electron 29 is running vesktop with `--disable-gpu-driver-bug-workarounds`. Could you check if it actually works?

Can confirm that also works.
