### ISSUE TITLE
Design: global hotkey for push-to-talk

### ISSUE THREAD

**Issue by libjared** [Vencord/Vesktop#227]
Some backstory:

Wayland by design does not allow an app to listen to hotkeys when you're focused on a different window. So global hotkeys don't work unless configured in KDE (systemsettings kcm_keys).
The official Discord for Linux runs on XWayland, so Discord PTT works only when focused on Discord or any X window.
So this tool was created:
https://github.com/Rush/wayland-push-to-talk-fix/
It directly listens to the uinput device, and uses xdotool to forward any relevant keypresses to X11, where Discord then picks it up, even when Discord window is unfocused.
But, this approach only seems to work for official Discord. It doesn't work for Vesktop. Vesktop does not even try to process hotkeys when unfocused or minimized.

How can we setup a global hotkey for Discord PTT? Can we set up a KDE Configuration Module such that KDE forwards the keys for us, no matter what window is focused?

**Comment by libjared** [comment]
One idea:
- make a listener process that connects to the `org.kde.kglobalaccel` DBus.
- user can now register global shortcuts via KDE systemsettings.
- when it receives the `globalShortcutPressed` signal, use a Vencord plugin to run `FluxDispatcher.dispatch({ type: "AUDIO_TOGGLE_SELF_MUTE" })` or whatever.
- that vencord plugin also disables the keybinds menu, and encourages the user to use their system settings.
- add actions to the .desktop file like how KDE Spectacle does.

**Comment by Vendicated** [comment]
#18
