### ISSUE TITLE
Improvements: Features such as on/off toggle for hardware acceleration, container permissions, and option to block third party sites. Also an About button.

### ISSUE THREAD

**Issue by pinbuck** [Vencord/Vesktop#229]
Within Webcord (<https://github.com/SpacingBat3/WebCord>) the user has a menu that is handy to have for its browser container which is accessible within the alt key menu:

https://github.com/Vencord/Vesktop/assets/96911866/ad1cf127-8b3b-432a-9b38-14a0151b950d

Some settings in WebCord are already handled by VenCord plugins such as blocking science, and typing, but most everything else is missing including what's mentioned in the title. An alt-key menu would improve Vencord by allowing the user to block most everything to increase loading speed on low end computers.

https://github.com/Vencord/Vesktop/assets/96911866/a681ac7a-669d-47cf-aa59-8aaab2a3b6c0

Lastly, one key missing item is a source code link to Vesktop itself, the best place for an application like this is a hidden alt menu.

**Comment by Vendicated** [comment]
all of these either already exist or are useless
