### ISSUE TITLE
Portable Settings

### ISSUE THREAD

**Issue by Vendicated** [Vencord/Vesktop#23]
I added a portable build in https://github.com/Vencord/Desktop/commit/6a67f07a9e506a442fb0efdae09dc28cb757a9b9, so you don't have to install it if you don't want to

However, as of now it will still write settings to AppData/Roaming. It would be cool to make it write its settings to the directoy the EXE is in or smth like that

Should be trivial by just using the `PORTABLE_EXECUTABLE_DIR` environment variable, see https://www.electron.build/configuration/nsis#portable

**Comment by viacoro** [comment]
I would like to give this a try, but I am new to contributing, so I may need some help.

**Comment by viacoro** [comment]
While attempting to get this to work, I've found out that the `PORTABLE_EXECUTABLE_DIR` variable is undefined in the portable/zip build.

So, after some research, on why this is the case, I came across this issue https://github.com/electron-userland/electron-builder/issues/3282 which states that the `PORTABLE_EXECUTABLE_DIR` variable is only available when the target is set to portable. 

This isn't true for Vesktop, as 57006e7e523d2fd19d85d0d5b185021784704a0f changed the portable target to zip and, according to the issue mentioned before, zip doesn't have any environment variables.

However, it might still be possible to tell if the installation is not portable by checking if the path of the executable contains "AppData/Local" or "/usr/bin". I don't know if this solution would cause problems, so feedback is appreciated.

**Comment by Vendicated** [comment]
> However, it might still be possible to tell if the installation is not portable by checking if the path of the executable contains "AppData/Local" or "/usr/bin". I don't know if this solution would cause problems, so feedback is appreciated.

sorry for the late reply. No, that sadly wouldn't work, because the nsis (windows) installer lets u customise the location, and different linux distros may install to different locations.

**Comment by SmilerRyan** [comment]
For me, i start `vesktop.exe` with command line paramater like ``--user-data-dir=C:\MyCustomDataFolder``, however it would be nice if the executable automatically set it to a data folder the current directory if a file exists or something like that. A custom startup_args.txt would work too, if one exists it can use them as relative paths (eg. ``--user-data-dir=Data``) do seem to work, and that would also allow having it manage its own startup work without adding my own shortcut to the startup path every time.

**Comment by MrGarlic1** [comment]
Even with a lack of environment variables, it could theoretically be determined if the install is portable by checking if the platform is windows, and then checking if the parent vesktop directory includes `Uninstall Vesktop.exe`, as that is only present on windows non-portable installs. It's a bit of a patchwork/imperfect solution, but it could be used to implement this. 

I have also noticed that on a portable install, the updater will update by installing a non-portable version.
