### ISSUE TITLE
Chinese fonts isn't working properly

### ISSUE THREAD

**Issue by wolf-yuan-6115** [Vencord/Vesktop#241]
On Fedora SilverBlue 39, the Chinese font is broken (maybe just for me)

Vesktop:
![image](https://github.com/Vencord/Vesktop/assets/58245644/1f0613b6-ccd3-4099-a5f9-7262a633343e)

Stock Discord with Vencord installed:
![image](https://github.com/Vencord/Vesktop/assets/58245644/53dfe921-7147-4d03-966d-90dba8ff2b0c)

I've tried running `fc-cache -f -v` and restarted machine several times but it doesn't work

**Comment by wolf-yuan-6115** [comment]
Maybe it's upstream issue, but I can't find any related issue

**Comment by Curve** [comment]
Does it work in discord web?
