### ISSUE TITLE
Vesktop Stream Deck Incompatibility 

### ISSUE THREAD

**Issue by EchoLWS999** [Vencord/Vesktop#243]
Immediately after using Vesktop I noticed that my games were lagging BAD. I check my task manager, and Vesktop is using 40 CPU, Stream Deck is using 20. I can fix this by either closing Vesktop or closing Stream Deck. I have the Discord plugin installed on Stream Deck.
![vesktopbug](https://github.com/Vencord/Vesktop/assets/107898744/96ddd536-746b-4a7f-9609-04996c873b07)

**Comment by Vendicated** [comment]
unlucky

**Comment by Vendicated** [comment]
there's nothing on our side that could cause this, and there is nothing we can do to fix it or help you. sorry.

**Comment by EchoLWS999** [comment]
not a problem <3 though id personally recommend adding it to the incompatibilities for the client as there are a lot of people who need some of the stream deck discord plugin functions for various reasons

**Comment by MiguVT** [comment]
![imagen](https://github.com/user-attachments/assets/6e116535-f9a4-4b46-8406-28b11e9b4b70)
No issues on my part, sharing screen rn and no problems, it should be other program like antivirus conflicting or something, can be a old issue and fixed from part of chromium, stream deck or idk
