### ISSUE TITLE
OpenSUSE Tumbleweed `libuuid` dependency

### ISSUE THREAD

**Issue by 42Willow** [Vencord/Vesktop#244]
```bash
willow@localhost:~/Downloads> sudo zypper install VencordDesktop-0.4.3.x86_64.rpm 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'libuuid' needed by the to be installed VencordDesktop-0.4.3-1.x86_64
 Solution 1: do not install VencordDesktop-0.4.3-1.x86_64
 Solution 2: break VencordDesktop-0.4.3-1.x86_64 by ignoring some of its dependencies
```
Related:

- https://github.com/BoostIO/BoostNote-App/issues/1063
- https://github.com/BoostIO/BoostNote-App/pull/1204

Appimage works well.

**Comment by biggestsonicfan** [comment]
So I'm a SUSE user as well, and SUSE actually uses `libuuid1` for this.

There's a [dummy `libuuid` community-built package](https://software.opensuse.org/package/libuuid) you can use to get through this, however. I was using the AppImage but just tested this and it works for me.
