### ISSUE TITLE
[Bug] ARRPC does not detect Wine game on Linux

### ISSUE THREAD

**Issue by boobthecat** [Vencord/Vesktop#245]
Using SteamOS 3.5.5. Latest version of Vencord installed and the ARRPC option is enabled (not the plugin).

I know this is their problem but there's a solution you guys can implement into Vencord. [Check this fork.](https://github.com/cannibalmaid/arrpc)

**Comment by Vendicated** [comment]
we will not use a random fork. open a pull request to the arrpc repo

**Comment by lewisakura** [comment]
Vencord uses upstreams, not forks. The change needs to be made in arRPC before we will implement it.

**Comment by Vendicated** [comment]
to be more precise, for us to use a fork over the original project, it has to be popular, trustworthy and well maintained.

None of these points are fulfilled by your linked fork. In fact, it is 19 commits behind the original, thus lacking important fixes and updates

If you want to see these changes in Vesktop, PR to the upstream repo
