### ISSUE TITLE
[Feature Request] Change GIF that Vencord Loads With

### ISSUE THREAD

**Issue by b-risk** [Vencord/Vesktop#25]
Writing this for a friend who asked me how to change it

**Comment by b-risk** [comment]
yes shiggy

**Comment by Vendicated** [comment]
After long consideration, this is not something we can good-heartedly support

**Comment by TheKodeToad** [comment]
You mustn't replace the shiggy.

**Comment by zt64** [comment]
@Vendicated You will do this.

**Comment by zt64** [comment]
Really though if the gifs gonna be changed it should be the Vencord icon. Personally I think it shouldn't be changed at all since it's opinionated and should be left up to the user

**Comment by RecentRunner** [comment]
> Really though if the gifs gonna be changed it should be the Vencord icon. Personally I think it shouldn't be changed at all since it's opinionated and should be left up to the user

You have to talk a way in which they understand otherwise they'll push back, dw I have an idea

***

Guys I want to be able to upload a custom Shiggy gif for the splashscreen but there's no option to change it 😔

**Comment by ImLvna** [comment]
splash.html line 36 https://shiggy.fun/api/v3/random :wowzers:
