### ISSUE TITLE
Screenshare is not working.

### ISSUE THREAD

**Issue by varmisa** [Vencord/Vesktop#251]
When I click on the ‘screenshare’ button and choose a screen or app, nothing happens. Additionally, when I click the button again, the window for selection does not open anymore.

**Comment by Vendicated** [comment]
issue with your system. pipewire capture is not working

**Comment by varmisa** [comment]
> issue with your system. pipewire capture is not working

Pipewire is working, I’ve verified its status with systemctl, and this issue does not occur with the older Flatpak version.
