### ISSUE TITLE
App crashes when trying to refresh emoji list on typing

### ISSUE THREAD

**Issue by iceeburr** [Vencord/Vesktop#259]
# Steps To Reproduce
1. Go to any channel/group/chat.
2. Start typing an emoji name. For example `:sk` (for the `:skull:` emoji)
3. Type another letter, try to delete one, etc. will make the app crash and you will be met with a white screen and sometimes a Vencord notification warning telling you the app crashed.

## What was supposed to happen?
Once continuing to type the emoji name it should refresh the list of available emojis which appears above the chat box. It shows emojis with a similar name of what you typed so you can pick the one you need.

## What actually happens?
Once you start typing again the list tries to refresh to show more relevant results of emojis, but it crashes.

### Console Logs (CTRL + SHIFT + I, WITH ReactErrorDecoder PLUGIN ENABLED)
```
WebpackModule435601:2 TypeError: s.replaceAll is not a function
    at s (c2ef546e05afb1fc662b.js:1:606802)
    at 7c1dc3a41650229f2417.js:1:350818
    at 7c1dc3a41650229f2417.js:1:354673
    at nN (7c1dc3a41650229f2417.js:1:344443)
    at 7c1dc3a41650229f2417.js:1:354478
    at rd (7c1dc3a41650229f2417.js:1:350787)
    at na.some (7c1dc3a41650229f2417.js:1:389058)
    at c2ef546e05afb1fc662b.js:1:600729
    at tp (7c1dc3a41650229f2417.js:1:332572)
    at na.filter (7c1dc3a41650229f2417.js:1:378029)
o5 @ WebpackModule435601:2
o.componentDidCatch.n.callback @ WebpackModule435601:2
aK @ WebpackModule435601:2
iX @ WebpackModule435601:2
e @ WebpackModule435601:2
eval @ WebpackModule435601:2
sR @ WebpackModule435601:2
sx @ WebpackModule435601:2
r3 @ WebpackModule435601:2
eval @ WebpackModule435601:2

WebpackModule435601:2 TypeError: s.replaceAll is not a function
    at s (c2ef546e05afb1fc662b.js:1:606802)
    at 7c1dc3a41650229f2417.js:1:350818
    at 7c1dc3a41650229f2417.js:1:354673
    at nN (7c1dc3a41650229f2417.js:1:344443)
    at 7c1dc3a41650229f2417.js:1:354478
    at rd (7c1dc3a41650229f2417.js:1:350787)
    at na.some (7c1dc3a41650229f2417.js:1:389058)
    at c2ef546e05afb1fc662b.js:1:600729
    at tp (7c1dc3a41650229f2417.js:1:332572)
    at na.filter (7c1dc3a41650229f2417.js:1:378029)
o5 @ WebpackModule435601:2
n.callback @ WebpackModule435601:2
aK @ WebpackModule435601:2
iX @ WebpackModule435601:2
e @ WebpackModule435601:2
eval @ WebpackModule435601:2
sR @ WebpackModule435601:2
sx @ WebpackModule435601:2
r3 @ WebpackModule435601:2
eval @ WebpackModule435601:2

WebpackModule435601:2 Uncaught TypeError: s.replaceAll is not a function
    at s (c2ef546e05afb1fc662b.js:1:606802)
    at 7c1dc3a41650229f2417.js:1:350818
    at 7c1dc3a41650229f2417.js:1:354673
    at nN (7c1dc3a41650229f2417.js:1:344443)
    at 7c1dc3a41650229f2417.js:1:354478
    at rd (7c1dc3a41650229f2417.js:1:350787)
    at na.some (7c1dc3a41650229f2417.js:1:389058)
    at c2ef546e05afb1fc662b.js:1:600729
    at tp (7c1dc3a41650229f2417.js:1:332572)
    at na.filter (7c1dc3a41650229f2417.js:1:378029)
```

### System Information
- OS: Arch Linux x86_64
- Kernel: 6.6.2-arch1-1
- Desktop Environment/Window Manager: Hyprland (Wayland Compositor)
- Discord: Stable 249561 (c9448e8) Vencord 6573c47 (Vesktop V0.4.3) Electron 27.0.0 Chromium 118.0.5993.54 Linux 64-Bit [Vendicated/Vencord](https://github.com/Vendicated/Vencord) ([6573c47](https://github.com/Vendicated/Vencord/commit/6573c47)) *Currently the latest build from the AUR, vesktop package was installed with `yay -S vencord-desktop-git`.*

### Notes
I stumbled upon this issue only today as of writing this, probably due to an update of the Discord client.
Notice that Discord is still quite working, you just can't see anything or do anything. You still get notifications from new messages and some plugins for example the oneko cat plugin does continue to work, just on the white window.
If anything else is needed to further resolve the issue, please ask.

#### Screenshots
![image](https://github.com/Vencord/Vesktop/assets/85520957/a47dabe2-57c2-4020-b9de-303658e18315)
![image](https://github.com/Vencord/Vesktop/assets/85520957/6276baf5-3c4f-43c1-ab10-b84de1fd7376)

**Comment by lewisakura** [comment]
discord bug, not vencord

**Comment by iceeburr** [comment]
# As of Discord Version Stable 250759 (5d4b938) this issue has been fixed and no longer persists.
