### ISSUE TITLE
[feature request] add transparency options

### ISSUE THREAD

**Issue by Earthquake125** [Vencord/Vesktop#260]
"transparent" and "macOSTranslucency" set to true in settings.json on their respective platforms.

Discord on mac (vibrancy):
<img width="1449" alt="Screenshot 2023-11-29 at 6 20 28 PM" src="https://github.com/Vencord/Vesktop/assets/59297679/25e737b5-1389-4d46-9d53-f2ac3cf5cb31">
Vesktop on mac:
<img width="1444" alt="Screenshot 2023-11-29 at 6 21 37 PM" src="https://github.com/Vencord/Vesktop/assets/59297679/c3c5c31e-c2db-428c-88f5-da682c45a564">
Discord on Linux (kwin blur):
![image2](https://github.com/Vencord/Vesktop/assets/59297679/e9ab2779-5fa7-4f26-8c80-4fd219b3919a)
Vesktop on Linux:
![image1](https://github.com/Vencord/Vesktop/assets/59297679/fa9681cd-4ab2-4faf-9714-fd40a52c796d)

**Comment by Vendicated** [comment]
it's not implemented on vesktop. that's why there's no UI for it

**Comment by ShayBox** [comment]
What do you mean? there's transparency settings at the bottom of Vesktop Settings. I can't get it to work on Windows 11 23H2 though, I've tried a few updated themes which support transparency, enabling the setting fixes the white background but doesnt show the wallpaper.

**Comment by Earthquake125** [comment]
> What do you mean? there's transparency settings at the bottom of Vesktop Settings.

correct, these options do not show up on macOS and Linux. only Windows with the Mica effect

**Comment by Earthquake125** [comment]
solution for Linux transparency, run the following in devtools console:

```Vesktop.Settings.store.transparencyOption = "epic banana"```

**Comment by ShayBox** [comment]
> What do you mean? there's transparency settings at the bottom of Vesktop Settings. I can't get it to work on Windows 11 23H2 though, I've tried a few updated themes which support transparency, enabling the setting fixes the white background but doesnt show the wallpaper.
> 
> #16 and #46
> I use Vibe through the Vibrancy extension for Visual Studio Code which works on my system.

I see, how do I get transparency working on Windows though? It doesn't seem to work other than fixing the white background when a transparent theme is applied.

Is the epic banana string for Linux specific or any string would work to enable it?

**Comment by Vendicated** [comment]
added via https://github.com/Vendicated/Vencord/commit/988435714e8b1de6e7e95885cbb5222113fb039c and https://github.com/Vencord/Vesktop/commit/b636b65e55235fde9092843a7d3f8dae02d9d720
