### ISSUE TITLE
Show as online on Desktop instead of on the Web

### ISSUE THREAD

**Issue by OsoaGH** [Vencord/Vesktop#267]
![Screenshot_20231203_165324](https://github.com/Vencord/Vesktop/assets/33041004/a5949da9-0adf-49ad-bdfa-c5c2114bd0b4)
This is me on Vesktop - it shows me as being online on the Web. Can we change this to being online on Desktop like with this person:
![image](https://github.com/Vencord/Vesktop/assets/33041004/e29d6807-f6d7-4fb8-bbcf-a3f0f4689f72)

**Comment by Vendicated** [comment]
no

**Comment by OsoaGH** [comment]
> no

fair enough
