### ISSUE TITLE
shiggy is being scaled at a non-integer

### ISSUE THREAD

**Issue by nanopone** [Vencord/Vesktop#268]
recently, shiggy was unblurred with `image-rendering: pixelated;`, but this has revealed a new problem. shiggy is not scaled at an integer of the original animations resolution, causing the pixels to be uneven. if the size was set to 100%, 200%, 300%, or any other integer, the pixels would be square, and this problem would go away. unfortunately, i don't know how to do this since i don't know how this project is structured. maybe someone else more knowledgeable could fix it? it's a fairly simple task.

![image](https://github.com/Vencord/Vesktop/assets/49787675/74f63fcb-c4d6-499b-8199-0839e6796e22)

**Comment by ryan-0324** [comment]
[shiggy.gif](https://github.com/Vencord/Vesktop/blob/e3839c35b704be20e1e4247f927dfcc181706566/static/shiggy.gif) is 64px by 64px and is currently rendered at 96px by 96px (1.5x scale). It gets its size from the width and height declarations in the following CSS rule from [static/views/splash.html](https://github.com/Vencord/Vesktop/blob/e3839c35b704be20e1e4247f927dfcc181706566/static/views/splash.html#L24-L28):
```css
img {
    width: 6em;
    height: 6em;
    image-rendering: pixelated;
}
 ```
To fix this issue, the values of the width and height declarations would have to be changed to either `64px` or `128px`.

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/commit/208158f4d1822fdec673609eb371eebe813d826b
