### ISSUE TITLE
Flatpak Vesktop Screen Sharing Not Working Under Wayland

### ISSUE THREAD

**Issue by joshuawins99** [Vencord/Vesktop#276]
The flatpak version of Vesktop does not allow for screen sharing under Wayland. The sharing portal opens and allows for a screen selection, but the screen is never shared and causes Vesktop to think a screen is being shared. This does not happen under X11.

The error that is presented in console upon trying to select a screen is:
[3:1205/225117.744585:ERROR:shared_x_display.cc(39)] Unable to open display

**Comment by Curve** [comment]
And it does work in the non-flatpak version?

**Comment by Vendicated** [comment]
this is an issue with your system. something wrong with your pipewire capturer or similar. try running from the command line and see if there's anything useful
