### ISSUE TITLE
Flatpak RPC not working

### ISSUE THREAD

**Issue by adamvaktipro** [Vencord/Vesktop#281]
**Host machine:** KDE 5.27.9 on Fedora 39 with kernel version 6.7.0-0.rc4
**Vesktop Details:**
Canary 252986 (7b09f89) 
Vencord 534ca1e (Vesktop V0.4.4)
Electron 27.1.2 
Chromium 118.0.5993.144 
Linux 64-Bit

**Issue:** In the Flatpak of Vesktop, the rich presence simply doesn't work, even though Rich Presence is enabled in the Vesktop Settings, I've tried with a lot of games that support it like A Hat in Time, Just Shapes & Beats, etc... However when I switch to the RPM package, RPC works perfectly

**Comment by Vendicated** [comment]
https://github.com/flathub/dev.vencord.Vesktop#discord-rich-presence

**Comment by forest-cat** [comment]
For me guide is not working, ive added via flatseal `xdg-run/.flatpak/dev.vencord.Vesktop:create` and `xdg-run/discord-ipc-*` to the global settings and it still did not work
