### ISSUE TITLE
Icon is blank in taskbar 

### ISSUE THREAD

**Issue by tikkamasalla** [Vencord/Vesktop#284]
![image](https://github.com/Vencord/Vesktop/assets/104959287/6e1ee064-a935-4235-99cb-57344aaf8a04)

Any way to fix this? 

thanks!

Windows 10 Pro | Version 10.0.19045 Build 19045

Installation by way of exe. 

Latest Vesktop/Vencord update. 

The icon comes back if I pin and unpin the taskbar icon, but it goes away after the app is minimized to tray etc.

**Comment by ZirixCZ** [comment]
Could you provide more info on the OS, way of installation, version

**Comment by tikkamasalla** [comment]
> Could you provide more info on the OS, way of installation, version

Windows 10 Pro | Version 10.0.19045 Build 19045

Installation by way of exe. 

Latest Vesktop/Vencord update. 

The icon comes back if I pin and unpin the taskbar icon, but it goes away after the app is minimized to tray etc. 

I have even cleared the cache and the issue persists.

**Comment by tikkamasalla** [comment]
Reinstalling has fixed the issue.
