### ISSUE TITLE
Make available as a Flatpak on Flathub

### ISSUE THREAD

**Issue by TheKodeToad** [Vencord/Vesktop#29]
Since https://flathub.org/en-GB/apps/xyz.armcord.ArmCord is there I doubt it would be problematic.

**Comment by Vendicated** [comment]
I'm personally don't have the time to maintain more packages, nor do i have the know-how for how to make flatpaks, but if anyone would like to help with this (preferably someone known in the community), that'd be nice

**Comment by komotok** [comment]
I have started working on a Flatpak version of this software, and am hoping to get a version released in a week or so. Not able to guarantee great maintenance but it will be enough to get the software running.

**Comment by MiMillieuh** [comment]
Since it wasn't really updated, I've made a flatpak https://github.com/MiMillieuh/vesktop-flatpak

It has desktop and hopefully all it need to work.

You just need flatpak builder to build it by running build.sh in the folder

As for updates, you have to edit the metainfo file with changelogs and version and the yml with the current version and url to the appimage (it's built from the appimage version so as long as the appimage version exists it should work)

**Comment by ImLvna** [comment]
The vencord team has expressed displeasure over third parties making package manager builds, especially builds that require constant attending to, like changelogs

**Comment by MiMillieuh** [comment]
> The vencord team has expressed displeasure over third parties making package manager builds, especially builds that require constant attending to, like changelogs

So I guess that issue can be closed this issue as not planned then.

**Comment by Vendicated** [comment]
No, we are interested in offering an (official) flatpak

**Comment by ImLvna** [comment]
ah, sorry for the confusion

**Comment by huanie** [comment]
> Since it wasn't really updated, I've made a flatpak https://github.com/MiMillieuh/vesktop-flatpak
> 
> It has desktop and hopefully all it need to work.
> 
> You just need flatpak builder to build it by running build.sh in the folder
> 
> As for updates, you have to edit the metainfo file with changelogs and version and the yml with the current version and url to the appimage (it's built from the appimage version so as long as the appimage version exists it should work)

Nice dropping my flatpak then. For updating the Vesktop executable itself, you can let the flathub bot do it with ``x-checker-data`` when you have it submitted there.

**Comment by MiMillieuh** [comment]
> > Since it wasn't really updated, I've made a flatpak https://github.com/MiMillieuh/vesktop-flatpak
> > 
> > It has desktop and hopefully all it need to work.
> > 
> > You just need flatpak builder to build it by running build.sh in the folder
> > 
> > As for updates, you have to edit the metainfo file with changelogs and version and the yml with the current version and url to the appimage (it's built from the appimage version so as long as the appimage version exists it should work)
> 
> Nice dropping my flatpak then. For updating the Vesktop executable itself, you can let the flathub bot do it with ``x-checker-data`` when you have it submitted there.

Honestly I'm pretty new to flatpak so if you have the expertise keep it, I might have made some errors. But it builds and run so idk...

**Comment by AtiusAmy** [comment]
> > > Since it wasn't really updated, I've made a flatpak https://github.com/MiMillieuh/vesktop-flatpak
> > > It has desktop and hopefully all it need to work.
> > > You just need flatpak builder to build it by running build.sh in the folder
> > > As for updates, you have to edit the metainfo file with changelogs and version and the yml with the current version and url to the appimage (it's built from the appimage version so as long as the appimage version exists it should work)
> > 
> > 
> > Nice dropping my flatpak then. For updating the Vesktop executable itself, you can let the flathub bot do it with `x-checker-data` when you have it submitted there.
> 
> Honestly I'm pretty new to flatpak so if you have the expertise keep it, I might have made some errors. But it builds and run so idk...

Hey! I know how and I am pretty interested to make it work! I must say though that dev.vesktop.Vesktop may not work as a valid app ID, it will work temporarily for now but we may have to change!

**Comment by Vendicated** [comment]
why?

**Comment by AtiusAmy** [comment]
> why?

apparently you have to own the domain vesktop.dev (unless you do and I'm not aware)

**Comment by Vendicated** [comment]
we own vencord.dev.

**Comment by huanie** [comment]
> > > > Since it wasn't really updated, I've made a flatpak https://github.com/MiMillieuh/vesktop-flatpak
> > > > It has desktop and hopefully all it need to work.
> > > > You just need flatpak builder to build it by running build.sh in the folder
> > > > As for updates, you have to edit the metainfo file with changelogs and version and the yml with the current version and url to the appimage (it's built from the appimage version so as long as the appimage version exists it should work)
> > > 
> > > 
> > > Nice dropping my flatpak then. For updating the Vesktop executable itself, you can let the flathub bot do it with `x-checker-data` when you have it submitted there.
> > 
> > 
> > Honestly I'm pretty new to flatpak so if you have the expertise keep it, I might have made some errors. But it builds and run so idk...
> 
> Hey! I know how and I am pretty interested to make it work! I must say though that dev.vesktop.Vesktop may not work as a valid app ID, it will work temporarily for now but we may have to change to something like io.github.vencord.Vesktop

The id is dev.vencord.Vesktop

**Comment by AtiusAmy** [comment]
> we own vencord.dev.

Alright sick!

**Comment by AtiusAmy** [comment]
@huanie I'll be working a bit on the flatpak to make it a little bit to what Flathub kinda expects (Like using icons directly from the AppImage and so on) :3

**Comment by AtiusAmy** [comment]
This might be a bit more work than I initially have hoped (if we are trying to submit it to Flathub because they kinda have a lot more requirements than "uhh it gotta work") and I'm actually kinda sleep and there's exam this week, so I'll continue this later :D

**Comment by Plarpoon** [comment]
+1 on this, I noticed you offer an RPM but it seems to be Fedora compatible only as it doesn't run on OpenSUSE.

At this point I would favor a flatpak so you don't have to rewrite a new version for any distro.

**Comment by arghanath007** [comment]
> +1 on this, I noticed you offer an RPM but it seems to be Fedora compatible only as it doesn't run on OpenSUSE.
> 
> At this point I would favor a flatpak so you don't have to rewrite a new version for every distro.

Yeah. Add Flatpak. Best and don't have to maintain many packages for different distros.

**Comment by Vendicated** [comment]
https://github.com/flathub/flathub/pull/4749

**Comment by MiMillieuh** [comment]
Cool I can delete my repo then
