### ISSUE TITLE
File upload dialog sometimes fails and reopens

### ISSUE THREAD

**Issue by TakuikaNinja** [Vencord/Vesktop#290]
Sometimes, the file upload dialog box reopens after selecting a file. File uploads only go through after that.
```
OS: EndeavourOS (Arch-based)
vencord-desktop-git r232.032b94e-1

File upload dialog uses these, iirc:
xdg-desktop-portal 1.18.2-1
xdg-desktop-portal-gtk 1.15.1-1
```

**Comment by Vendicated** [comment]
most likely an electron issue, nothing we can do. try to create a simple electron reproduction repo and opening an issue on the electron repo

**Comment by TakuikaNinja** [comment]
I may have been double clicking the upload button like it was the official desktop client. My bad :sweat:

**Comment by Vendicated** [comment]
what is that supposed to do?

**Comment by TakuikaNinja** [comment]
I was just too used to the official client requiring a double click to open the file upload dialog. I wasn't aware of the fact that Vencord changed to only need a single click.

**Comment by Vendicated** [comment]
that has nothing to do with vesktop, you just enabled https://vencord.dev/plugins/BetterUploadButton

**Comment by TakuikaNinja** [comment]
Ah, completely forgot I had that installed. Whoops!
