### ISSUE TITLE
Vesktop Flatpak does not follow cursor theme:

### ISSUE THREAD

**Issue by Blisterexe** [Vencord/Vesktop#292]
The flatpak does not follow the system theme as seen in the video (top is flatpak, bottom is .rpm showing expected behavior)
tested on fedora 39 gnome with amd gpu.
Vesktop was given the proper filesystem permissions as shown in the screenshot.
[Screencast from 2023-12-16 13-41-53.webm](https://github.com/Vencord/Vesktop/assets/128065612/2004b81e-931f-40c1-ad59-b029bd28b2ea)
![image](https://github.com/Vencord/Vesktop/assets/128065612/86f31758-6d47-4838-86fb-2e84c2e74872)

**Comment by FoxeiZ** [comment]
Check to see if the cursor theme folder exists in `~/icons`. Alternatively, use `/usr/share/icons`.

In my case, I need to override the `XCURSOR_PATH` environment variable using this command: `flatpak override --user --env=XCURSOR_PATH=~/.icons` to make the cursor change.

**Comment by Vendicated** [comment]
it should work fine https://github.com/flathub/dev.vencord.Vesktop/blob/master/dev.vencord.Vesktop.yml#L25

**Comment by Blisterexe** [comment]
Thank you! That fixed it, apologies for brigning up an issue that wasnt really one, that fix wasnt needed for my other flatpaks, so i was confused

**Comment by Vendicated** [comment]
ah. seems your cursor theme is in ~/.icons ? flatpak only uses /usr/share/icons from what i can tell. should probably re-look at the line i sent

**Comment by Blisterexe** [comment]
actually my cursor theme was in /home/blisterexe/.icons, and moving it to /usr/share/icons fixed it for me, that issue was not present in any other flatpaks except the discord flatpak
