### ISSUE TITLE
[macOS] Top action bar buttons not clickable (e.g. streamer mode notifs, server role previews, etc.)

### ISSUE THREAD

**Issue by transcoded-dot-net** [Vencord/Vesktop#293]
Using: Mac ARM Vesktop 1.4.4, with either Stable/PTB/Canary, on my Macbook Pro 13in M2, running Sonoma 14.0 Public Beta

Issue Regarding: top bars created on certain actions, such as going into streamer mode or previewing a server role

![image](https://github.com/Vencord/Vesktop/assets/116987903/8580c9df-5fa7-41ee-a9a0-f66ae858ae6f)

Issue Description: All buttons on these top bars are unclickable, with the pointer not even recognizing them as clickable.

**Comment by somehybrid** [comment]
This issue also happens on my Intel mac.

**Comment by Vendicated** [comment]
try the css in the linked pr
