### ISSUE TITLE
Clicking links in Vesktop sometimes causes my browser window to duplicate itself

### ISSUE THREAD

**Issue by sabaasa** [Vencord/Vesktop#296]
Weird bug that took me like 2 weeks to even figure out that Vesktop was causing.

I am using the latest version of Vesktop and Brave

Here's what happens (example):
I have Brave open in the background with one or more tabs open, I click on a link in Vesktop which duplicates the browser window with the same tabs open AND the link that i clicked on. 
So I am left with 2 browser windows having almost identical tabs and I have to close one of them every single time this happens and it's kinda annoying.

**Comment by sabaasa** [comment]
Can't seem to figure out what causes this to happen, sometimes it does this, sometimes it opens the link properly.

**Comment by Vendicated** [comment]
brave issue. vesktop does not control what browser or what browser window is opened

**Comment by sabaasa** [comment]
I fucking hate chromium
