### ISSUE TITLE
Something's wrong...

### ISSUE THREAD

**Issue by Milliw** [Vencord/Vesktop#297]
Have a look:
![Bildschirmfoto vom 2023-12-19 16-28-38](https://github.com/Vencord/Vesktop/assets/11760209/abc5665d-5a92-482f-91e7-60aa271d21de)
Suddenly happened (after some system updates I guess).
Tried the update function via the tray icon but did not change anything.

**Comment by Vendicated** [comment]
nothing to do with vesktop. try to disable your themes/css or reinstall

please use our support channel in the future
