### ISSUE TITLE
screensharing with audio on linux

### ISSUE THREAD

**Issue by gmankab** [Vencord/Vesktop#299]
so https://github.com/Vencord/Vesktop/issues/117 is locked as old unrelated threads

vesktop shares screen without sound

i tried both flatpak and binary versions of vesktop

and also i tried `--ozone-platform-hint=auto --enable-webrtc-pipewire-capturer`, nothing changed

discord-screenaurio shares screen with sound without any issues

my os is fedora silverblue, with gnome, pipewire and wayland

**Comment by Vendicated** [comment]
show a screen recording of you starting a screenshare that is supposed to have audio

**Comment by gmankab** [comment]
i am sorry, i didn't notice the select audio source button

by default there is no audio selected

after selecting everything works
