### ISSUE TITLE
Reply button does not work

### ISSUE THREAD

**Issue by RadovanSk** [Vencord/Vesktop#301]
When trying to reply to a user anywhere I get this error in the console
```
    Uncaught TypeError: ll.store.userList.includes is not a function
    at Object.shouldMention (index.tsx:60:50)
    at N (WebpackModule363396:2:1944)
    at onClick (WebpackModule823674:2:1903)
    at Object.eN (72054.ccb12939fa7033320d60.js:1:753910)
    at eB (72054.ccb12939fa7033320d60.js:1:754064)
    at 72054.ccb12939fa7033320d60.js:1:772373
    at re (72054.ccb12939fa7033320d60.js:1:772472)
    at rt (72054.ccb12939fa7033320d60.js:1:772886)
    at 72054.ccb12939fa7033320d60.js:1:778348
    at sE (72054.ccb12939fa7033320d60.js:1:835405)
```

I am using a nixpkgs package from NixOS on unstable channel. Replies worked fine for a while and then stopped working out of nowhere.

**Comment by Vendicated** [comment]
not a vesktop issue. please use our support channel

**Comment by RadovanSk** [comment]
> not a vesktop issue. please use our support channel

And where is that support channel? I can't seem to find it.

**Comment by Vendicated** [comment]
https://vencord.dev/discord

**Comment by AAGaming00** [comment]
![Screenshot_20231222-151424_Discord](https://github.com/Vencord/Vesktop/assets/42613600/26d3d478-9bc0-4ff8-a989-b8f7d62ca8b1)

**Comment by RadovanSk** [comment]
What's the purpose of GitHub issues then? Is everything supposed to go to the support channel or are there specifics?

**Comment by Vendicated** [comment]
development and actual proper bug reports or feature requests. non vencord developers should always first use the support channel
