### ISSUE TITLE
Ensure the .desktop file properly groups with created windows

### ISSUE THREAD

**Issue by Exponential-Workload** [Vencord/Vesktop#305]
Currently, on Linux, when you pin the Vencord Desktop `.desktop` entry to your taskbar, and launch Vencord, you get this:
![image](https://github.com/Vencord/Vesktop/assets/90570076/f3d841ee-573f-41ea-9094-4fb4ea8f9f78)
Ideally, it would instead group together with the pinned icon, as intended.

This issue can be fixed by making the `.desktop` file contain the following:
```ini
StartupWMClass=vencorddesktop
```

Currently, atleast on the AUR package for Vencord (`vencord-desktop-git`), this line reads `StartupWMClass=vencord-desktop`, which does not match the window's `WM_CLASS(STRING) = "vencorddesktop", "VencordDesktop"`; the `-` is causing this bug.

**Comment by lewisakura** [comment]
this is already the case on our end
https://github.com/Vencord/Vesktop/blob/1429815fd126d802235b1dba041d6509ea6cd312/package.json#L114
the AUR package (which we don't maintain, it is by @zt64) has an outdated desktop file

**Comment by Exponential-Workload** [comment]
ah alright, my bad - didn't know where to report the bug

**Comment by Vendicated** [comment]
https://aur.archlinux.org/packages/vencord-desktop-git is the correct place for discussion of the aur package

**Comment by alphabitserial** [comment]
@Exponential-Workload I've just left a comment on the AUR page, hopefully the maintainer updates their package soon. :smile:

**Comment by Exponential-Workload** [comment]
> @Exponential-Workload I've just left a comment on the AUR page, hopefully the maintainer updates their package soon. :smile: 

i left one too a day after making this issue, still no update - atp im tempted to just make a fork of the pkg (I'm using -git)

not sure if the pkg is considerable as abandoned yet or not
