### ISSUE TITLE
Update arRPC for Linux Wine support

### ISSUE THREAD

**Issue by SeongGino** [Vencord/Vesktop#311]
Upstream has merged the fix recently at https://github.com/OpenAsar/arrpc/pull/57 which should retroactively resolve #245

**Comment by NextWork123** [comment]
wanted to understand when the devs want to merge that :/

**Comment by Vendicated** [comment]
next update.

**Comment by NextWork123** [comment]
> next update.

Thanks for the reply! anyway great job for that client is my save for sharing and other congrats

**Comment by Vendicated** [comment]
done via https://github.com/Vencord/Vesktop/commit/18925ad5839124a17afce4d9a9a696b573abdff6

if you want it immediately, build from source. but i will make a new release very soon
