### ISSUE TITLE
Intense flickering and glitching while using app on high refresh rates

### ISSUE THREAD

**Issue by ayanokato** [Vencord/Vesktop#318]
I'm unsure if anyone else has this issue, but on my 240 Hz Omen monitor in Windows 11, the experience is extremely flickery and glitchy. To the point where it could probably be an epilepsy hazard. When I drag it onto my 70 Hz Sceptre monitor, all is well though.

My graphics driver is NVIDIA (currently 546.33)

**Comment by lewisakura** [comment]
A video or any context on what you mean would be greatly helpful, although this sounds like it might be unfixable from our end already.

**Comment by ayanokato** [comment]
https://github.com/Vencord/Vesktop/assets/116850347/8476406a-1898-4f08-9585-807e621f7c11

On my actual screen, it's worse than this, flashing black bars everywhere and even sometimes turning the entire window black, but this video successfully captures the gist of what's going on. No other client I've used has done this. Using it on my 70Hz monitor is fine though, so I'll probably keep it on there but it's almost unusably horrid to even move the cursor in on my 240Hz monitor.

**Comment by Vendicated** [comment]
likely fixed by disabling hardware acceleration. there is no good way to do this yet, but you could try running vesktop with the --no-gpu flag and see if its fixed

open %LOCALAPPDATA%, go to the VencordDesktop folder, open a terminal, drag the vesktop .exe into it, add --no-gpu and press enter

**Comment by Plarpoon** [comment]
In case it works and you want to make it permanent you can modify the shortcut on windows to always launch the application with these modified parameters like described above.

![image](https://github.com/Vencord/Vesktop/assets/40299833/cda56421-7798-412e-867f-77702074e7b9)

The short video you showed looks almost 1:1 to how the Battle.Net app behaves on Linux, another Chromium app that has some problems with hardware acceleration and looks exactly like that. That's a sync issue and at the moment there is no easy way to fix it, in that case I can only recommend patience and thank you for having posted the issue.

**Comment by kabessao** [comment]
for linux users: you can find a symlink to the desktop file in this directory: 
`/var/lib/flatpak/exports/share/applications/dev.vencord.Vesktop.desktop`
in there just add the `--disable-gpu` at the end of the `Exec=` line.

**Comment by Vendicated** [comment]
you can properly disable hardware acceleration now so this shouldnt be needed

**Comment by kabessao** [comment]
alright, just updated vesktop and disabled `Hardware Acceleration`. Now it works fine. Thank you!

**Comment by Vendicated** [comment]
closing as resolved, please reopen if you're still experiencing this issue with hardware acceleration disabled @ayanokato
