### ISSUE TITLE
Screenshare with xdg-desktop-portal-hyprland.service

### ISSUE THREAD

**Issue by P4rcev4l** [Vencord/Vesktop#323]
When I try to screenshare on Hyprland (NixOS), I get the following error continuously: 
```
[30147:0106/182551.162630:ERROR:shared_screencast_stream.cc(241)] PipeWire stream state error: no target node available
```

The following portals are loaded and active
```
$ systemctl --user list-units --type=service | grep portal
  xdg-desktop-portal-hyprland.service loaded active running Portal service (Hyprland implementation)
  xdg-desktop-portal.service          loaded active running Portal service
```

I was wondering if anyone got Vesktop with xdg-desktop-portal-hyprland to work (especially with NixOS).
Might just be a NixOS specific issue, my [flake](https://gitlab.com/4tm4n/nixos-config).

Version: 0.4.4

**Comment by Vendicated** [comment]
this is either an issue with Nix, or more likely the hyprland portal. i have seen maaany reports of hyprland users with broken screenshare

i recommend trying on gnome instead

anyway since this isn't an issue on our end, ill close this

**Comment by AAGaming00** [comment]
it works on hyprland lol nix issue or skill issue

**Comment by P4rcev4l** [comment]
> it works on hyprland lol nix issue or skill issue

Are you using xdg-desktop-portal-hyprland or xdg-desktop-portal-wlr? It works great on gnome and another person had the same problem in [this](https://github.com/Vencord/Vesktop/issues/204) thread, which is why I thought it might be a general hyprland issue. Then again they also seem to be using NixOS.

**Comment by AAGaming00** [comment]
I use the gtk and hyprland portals on an AMD gpu

**Comment by getchoo** [comment]
using gnome's desktop portal works as expected on nixos. this is most definitely an issue with hyprland's portal (or at least older versions) rather than vesktop or electron. see [this](https://github.com/NixOS/nixpkgs/issues/277230) thread for more

using upstream's flake (i.e., `xdg-desktop-portal-hyprland-git` for non-nixos users out there) or i'm guessing [v1.3.0](https://github.com/hyprwm/xdg-desktop-portal-hyprland/releases/tag/v1.3.0) should solve this

**Comment by P4rcev4l** [comment]
> using gnome's desktop portal works as expected on nixos. this is most definitely an issue with hyprland's portal (or at least older versions) rather than vesktop or electron. see [this](https://github.com/NixOS/nixpkgs/issues/277230) thread for more
> 
> using upstream's flake (i.e., `xdg-desktop-portal-hyprland-git` for non-nixos users out there) or i'm guessing [v1.3.0](https://github.com/hyprwm/xdg-desktop-portal-hyprland/releases/tag/v1.3.0) should solve this

Thanks you so much, [v1.3.0](https://github.com/hyprwm/xdg-desktop-portal-hyprland/releases/tag/v1.3.0) solved the issue. Don't know how missed [this](https://github.com/NixOS/nixpkgs/issues/277230)  :heart:
