### ISSUE TITLE
Make the loading animation window draggable

### ISSUE THREAD

**Issue by NyaomiDEV** [Vencord/Vesktop#325]
This is such a minor thing but it's bothered me enough to ask for it. I would want for the cute loading window to be dragged around with my mouse, as sometimes it's right in the middle of something I am doing. Plus, for consistency with how Discord actually does stuff, it'd be better if it was entirely draggable.

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/commit/62cf02e7b10b8c755d6f9ad26ecd2b407ae1169f
