### ISSUE TITLE
screenshare audio doesn't work with Easy Effects on process all inputs mode

### ISSUE THREAD

**Issue by slonkazoid** [Vencord/Vesktop#328]
when you start a stream with easyeffects running and "process all input streams" ticked, it will set both the mic and stream audio to Easy Effects Source

## possible fixes

- double-check the screenshare audio source is set to the correct one

- make the application name for the screenshare audio recording stream is different so it can be excluded

## workarounds
- don't use process all input streams
  - enable all apps you use manually
  - have to mess with easyeffects every time you join vc
  - obnoxious
- exclude chromium from easyeffects
  - you lose easyeffects in vesktop
  - will cost more cpu time for the extra noise reduction
  - manual
  - obnoxious
- manually switch source in pavucontrol/helvum
  - have to rewire every time you stream
  - manual
  - obnoxious
- write a script to do that
  - requires scripting knowledge
  - at least not manual
  - obnoxious
- set Easy Effects Source as your fallback source
  - set input device in Easy Effects to the actual mic
  - now muting your default mic does nothing
  - hell
  - nothing works
  - obnoxious

**Comment by Curve** [comment]
Please provide all information as required here: https://github.com/Vencord/venmic/issues/new?assignees=Curve&labels=bug&projects=&template=bug-report.yml

**Comment by Curve** [comment]
But I'd argue this is more of a EasyEffects issue than a venmic issue, but in depending on how the Node-Graph looks we might be able to workaround this

**Comment by slonkazoid** [comment]
will transfer the issue with the required information
