### ISSUE TITLE
Stream Popout only works with "Open Links in app" enabled

### ISSUE THREAD

**Issue by angahith** [Vencord/Vesktop#329]
I much prefer having the links open in my browser, but without enabling this feature, Vesktop will attempt to open stream popouts in the browser too, which obviously doesn't work.

While the feature is still experimental and you might not want to always have stream popouts open within a new Vesktop window yet until it's out of beta, it would be great to at least have an additional option specifically for stream popouts, to make them functional.

To reproduce the issue: 
- have "Open Links in app" disabled 
- join a call with a video stream 
- click "Pop Out"

**Comment by Vendicated** [comment]
fixed in https://github.com/Vencord/Vesktop/commit/38f0330eb24c778326ed930c3e2294d011758319 & https://github.com/Vencord/Vesktop/commit/6483b3a3d96181c9dca87abb095f94291146d161
