### ISSUE TITLE
[Request] Add voice status in system tray?

### ISSUE THREAD

**Issue by Noriaela** [Vencord/Vesktop#330]
Would it be possible to get these added? ![VncRAVroMJ](https://github.com/Vencord/Vesktop/assets/22671423/3d9f4a5e-1f96-4576-8c42-dcbac42ee70b) ![69Iu6WDYJi](https://github.com/Vencord/Vesktop/assets/22671423/e62696c3-967a-4ebb-9466-e9fb5990927e) ![k7ujKu8v74](https://github.com/Vencord/Vesktop/assets/22671423/92561315-c8f1-4e46-94b1-c6d90fbfdb45)

If this is already an open issue or pull request then feel free to close this.

**Comment by Vendicated** [comment]
#294
