### ISSUE TITLE
Port >100% volume feature

### ISSUE THREAD

**Issue by Vendicated** [Vencord/Vesktop#331]
Discord Desktop has a feature that lets you increase the volume of participants in voice calls above 100%, up to 200% (or even higher with the VolumeBooster plugin)

This feature is missing in Discord Web because this is not a thing in WebRTC / web media apis (discord desktop does it via discord_voice native module)

The likely solution to this is obtaining the audio streams in some way and applying a filter to them, hopefully without ruining quality too much

**Comment by D3SOX** [comment]
I've looked into the `background.js` file of the [Volume Master extension](https://chromewebstore.google.com/detail/volume-master/jghecgabfgfdldnmbfkhmffcabddioke) and it seems to use the [BaseAudioContext API](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext). It makes use of `createMediaStreamSource`, `createGain`, `createBiquadFilter`, `createAnalyser`

**Comment by AlphaCraft9658** [comment]
I think the plugin is called VolumeBooster. Why is it not part of Vesktop? Isn't it pre-patched with vanilla Vencord?

**Comment by THEGOLDENPRO** [comment]
> I think the plugin is called VolumeBooster. Why is it not part of Vesktop? Isn't it pre-patched with vanilla Vencord?

This comment explains it: https://github.com/Vencord/Vesktop/issues/58#issuecomment-1887383325

**Comment by tye-exe** [comment]
Sadly i'll have to switch from vesktop because of this issue. I'd love to use it otherwise but it makes calls unusable & i can't adjust the system volume enough to fix it.

**Comment by kaitlynkittyy** [comment]
I'm going to try and recreate it, but my main priority is screensharing

**Comment by tye-exe** [comment]
Oh, i didn't know screen sharing was an issue, it has worked perfectly for me so far.

**Comment by dotaxis** [comment]
I would love for this to be in Vesktop as well. I don't want to use Flatpak Discord but this is a necessary feature for me.

**Comment by TheAnnoyingFruit** [comment]
> I'm going to try and recreate it, but my main priority is screensharing

@kaitlynkittyy take all the time you need you have been absolutely grinding out that screen sharing work

**Comment by kaitlynkittyy** [comment]
> > I'm going to try and recreate it, but my main priority is screensharing
> 
> @kaitlynkittyy take all the time you need you have been absolutely grinding out that screen sharing work 

I've had help lol, but thanks

**Comment by MaxBosse** [comment]
Feature was merged this morning so this issue can be closed now :)

https://github.com/Vendicated/Vencord/pull/2730

**Comment by tsuza** [comment]
> Feature was merged this morning so this issue can be closed now :)
> 
> [Vendicated/Vencord#2730](https://github.com/Vendicated/Vencord/pull/2730)

It doesn't seem to be doing anything.

**Comment by CantBeLucifer** [comment]
VolumeBooster does not work for me for stream volume

Vesktop 1.6.5
Vencord [dc25c8f](https://github.com/Vendicated/Vencord/commit/dc25c8f)

<details> 
<summary>Symptom + Full plugin list</summary>
<img width="1525" height="960" alt="Image" src="https://github.com/user-attachments/assets/537ca781-2b7c-4cf2-8c7b-6d5a48e2c7fc" />
</details>

**Comment by EinfxchFinn** [comment]
> VolumeBooster does not work for me for stream volume
> 
> Vesktop 1.6.5
> Vencord [dc25c8f](https://github.com/Vendicated/Vencord/commit/dc25c8f)
> 
> <details> 
> <summary>Symptom + Full plugin list</summary>
> <img width="1525" height="960" alt="Image" src="https://github.com/user-attachments/assets/537ca781-2b7c-4cf2-8c7b-6d5a48e2c7fc" />
> </details>

Same issue for me

**Comment by Tiagoquix** [comment]
Please open a separate issue to discuss that. A closed issue is not the place for it.
