### ISSUE TITLE
I Would Like To Know Where The QuickCSS Is Located

### ISSUE THREAD

**Issue by FrostKorii** [Vencord/Vesktop#332]
I Imported Some Code From The Comfy Server (A Theme Server) And Now I Can't Even See My Discord

**Comment by FrostKorii** [comment]
I Already Tried Going Into Dev Tools But Couldn't Figure Out How To Change The QuickCSS Without Going Threw Vencord

**Comment by fres621** [comment]
Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> to open the DevTools console and paste in this code:
```js
(() => {
    Vencord.Settings.useQuickCss = false
})()
```
to disable the QuickCss

**Comment by FrostKorii** [comment]
Thank You So Much Bruv
