### ISSUE TITLE
Add a proper CSD that fits the application

### ISSUE THREAD

**Issue by MonsterObserver** [Vencord/Vesktop#333]
**Is your feature request related to a problem? Please describe.**
Electron apps on GNOME tend to use an ugly and outdated looking CSD, and so does Vesktop. There are a couple exceptions such as VSCode (opt-in) and ArmCord.

![image](https://github.com/Vencord/Vesktop/assets/114881134/a7bb215d-b9a5-42d4-91e9-41703e7ae5f1)

![image](https://github.com/Vencord/Vesktop/assets/114881134/ebefc5a1-e347-4805-b4a0-d971ff235b7f)

**Describe the solution you'd like**
I'd like the app to have a proper CSD that fits with the application, an example would be Discord on Windows, and ArmCord on Linux.

![image](https://github.com/Vencord/Vesktop/assets/114881134/0f62e01c-f785-4ecf-8e17-6aab5c63230b)

**Comment by WmeLuna** [comment]
The windows one works just fine on linux 
i used this to enable it, though itd be nice to enable this for linux devices without this stuff:
```
Vesktop.Settings.store.discordWindowsTitleBar = true
Vencord.Settings.winNativeTitleBar = true 
Vencord.Settings.frameless = true
if (navigator.platform?.toLowerCase().includes("linux")) VCDP.getPlatformClass= () => {return "platform-win"}
```
the last line just makes this part rounded (i have the snippet in a plugin so it auto applys that)
![image](https://github.com/Vencord/Vesktop/assets/46545277/8cb9a3dc-29d0-41ec-a2dc-b7a9c35c0564)

**Comment by MonsterObserver** [comment]
> The windows one works just fine on linux i used this to enable it, though itd be nice to enable this for linux devices without this stuff:
> 
> ```
> Vesktop.Settings.store.discordWindowsTitleBar = true
> Vencord.Settings.winNativeTitleBar = true 
> Vencord.Settings.frameless = true
> if (navigator.platform?.toLowerCase().includes("linux")) VCDP.getPlatformClass= () => {return "platform-win"}
> ```
> 
> the last line just makes this part rounded (i have the snippet in a plugin so it auto applys that) ![image](https://private-user-images.githubusercontent.com/46545277/296883363-8cb9a3dc-29d0-41ec-a2dc-b7a9c35c0564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNjAyMDAsIm5iZiI6MTcwNTM1OTkwMCwicGF0aCI6Ii80NjU0NTI3Ny8yOTY4ODMzNjMtOGNiOWEzZGMtMjlkMC00MWVjLWEyZGMtYjdhOWMzNWMwNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDIzMDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZjRkNWUzODk2MzEzZjkxZmQ4MzJmODZiYWZlNmZmNzg2YjJmM2E3M2IxYjBlYjc4NDIwNmMwOWQ4ZTY0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8p_y4Ru8KgSpbFTWVq8Ezy3uSLOzZyMo8Y8KDwtI6-A)

Huh, I never knew about this, I'll check it out, thanks!

**Comment by dominichayesferen** [comment]
Ideally this should be an option that is force-enabled in Wayland clients lacking xdg-decorations support, and/or having it but having the value set to FORCE CSDS, while keeping it opt-in on Wayland clients that have xdg-decorations and either set it to FORCE SSDS or APPLICATIONS DECIDE. 

That being said, by option I of course mean actually exposing it on the Vencord settings page.

**Comment by Vendicated** [comment]
added via https://github.com/Vencord/Vesktop/commit/2e4c834a909397ab9d4a853085ef49987e79ab76
![image](https://github.com/Vencord/Vesktop/assets/45497981/bd623872-e4ae-4ef6-a669-9ddca6070e3d)
