### ISSUE TITLE
Debian build has updating issues

### ISSUE THREAD

**Issue by nekolifestyle** [Vencord/Vesktop#336]
**Describe the bug**
The latest release is not updating Vesktop to the latest build

**To Reproduce**
1. Download the latest release as of now 1.5.0
2. Install build and has no errors
3. Vesktop is showing as older release 0.4.4
4. Prompt is asking to update Vesktop again

**Expected behavior**
Should update to the latest release

**Desktop (please complete the following information):**
 - OS/Distro: Linux
 - Desktop Environment (linux only): KDE
 - Version: 5.27.11

**Comment by Vendicated** [comment]
the app has been renamed. you likely have it installed with two names now. Uninstall the old VencordDesktop app
