### ISSUE TITLE
3 Vesktop installs

### ISSUE THREAD

**Issue by Bluscream** [Vencord/Vesktop#339]
![](https://i.imgur.com/MEBIVRN.png)

![](https://i.imgur.com/oFIkeQt.png)

**Comment by Curve** [comment]
`1.5.0` installs to a new path so it's normal for that to be an additional program (you can simply uninstall the old versions).

Not sure about `0.3.3` and `0.4.4` though, maybe someone else has more insight on that

**Comment by Vendicated** [comment]
... uninstall the obsolete ones?

**Comment by Bluscream** [comment]
> ... uninstall the obsolete ones?

I did and it uninstalled the new one aswell. Such a hassle for everyone just because someone wanted his ego boost...

**Comment by Curve** [comment]
> just because someone wanted his ego boost...

What?

**Comment by Vendicated** [comment]
ego boost? the app has been renamed internally, from vencorddesktop to vesktop, hence the complications.

you would know this if you cared to read the changelog.
