### ISSUE TITLE
[Linux] Using native titlebar causes wonky behaviour in child windows

### ISSUE THREAD

**Issue by NyaomiDEV** [Vencord/Vesktop#341]
**Describe the bug**
Child windows have both the client-side window decoration and the server-side window decoration. They don't obey the "Show Menu Bar" option you can configure in Vesktop. Closing a child window through the clientside close button closes the main window instead.

**To Reproduce**
I think the most straightforward approach to reproduce this is to take a look at the stream debug child window.

**Expected behavior**
Behaviour should be consistent between the main Discord window and its child windows.

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/13177694/a821389b-7125-4fca-a238-6a8b9cca0264)

**Desktop (please complete the following information):**
 - OS/Distro: Artix Linux
 - Desktop Environment (linux only): KDE Plasma 5.27.10 Wayland
 - Version: 1.5.0

**Additional context**
Not applicable

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/commit/8c007476c3843822c82b54f1b00f898be6c5db31
https://github.com/Vencord/Vesktop/commit/463cd6dc4613c709ef2ef5af534412374ef8203e
