### ISSUE TITLE
"Show My Camera" Context Menu

### ISSUE THREAD

**Issue by Janybanny** [Vencord/Vesktop#343]
**Is your feature request related to a problem? Please describe.**

On normal discord desktop, when in a call with video enabled, you can right click your own video and then click "Show My Camera" To disable/enable your camera (check screenshot below). This doesn't exist in discord web/Vesktop

![a screenshot of the context menu mentioned above on dekstop discord](https://cdn.discordapp.com/attachments/1026515880080842772/1190763446426402836/Screenshot_20231230_220654.png)

**Describe the solution you'd like**

I'd like to have that feature in Vesktop, since it's very useful to me. (Probably in the WebContextMenus Plugin)

**Describe alternatives you've considered**

- Using just normal discord for video calls (Although this sucks and is just a workaround)
- Using CSS to remove the video (I sadly don't know enough css to actually do this, but it should be possible)

**Additional context**

This is how the context menu looks on Vesktop:

![a screenshot of the same conText menu as above, but in vesktop with the option to "Show My Camera" missing](https://cdn.discordapp.com/attachments/1026515880080842772/1190763446665482270/Screenshot_20231230_220702.png)

I've asked in the veecord support channel and it was agreed that this should be possible, so I decided to add a github issue about it.

**Comment by Vendicated** [comment]
already added to vencord two weeks ago https://github.com/Vendicated/Vencord/commit/88fc15752d95881f2ba90d935c7dc5404649c806
