### ISSUE TITLE
Copying images to clipboard is not working anymore

### ISSUE THREAD

**Issue by leia-uwu** [Vencord/Vesktop#345]
maybe caused by 15a49a31e1baf1b310a73204cd54bf2f0dfe9cf8?

**To Reproduce**
1. Right click on an image
2. Click "copy image" menu item

**Expected behavior**
Image will be copied to the clipboard

**Desktop:**
 - OS/Distro: Arch linux
 - Desktop Environment: KDE Plasma Wayland
 - Vesktop git from the AUR (vencord-desktop-git package)

**Comment by Vendicated** [comment]
https://github.com/Vendicated/Vencord/commit/3d64f3da410153447bc2fd49af2d7799af993e51

**Comment by ToxicMushroom** [comment]
Not completely fixed for me unless I am somehow not using this commit yet ? 
+ Right click copy on images that are attachments works.
- Embedded images, albeit links or images inside embeds are copied as html <img ...> only according to copyq's item content viewer.
- Or when you enlarge the image inside the client it has the same behavior as embedded images.

As of the time of writing this was tested on `aur/vesktop 1.5.0-3` and `aur/vencord-desktop-git r264.0f0bddb-2` 

System:
arch
sway (wayland window manager)

**Comment by Vendicated** [comment]
that commit has not been pushed to main yet

**Comment by RSerejo** [comment]
i`m with that problem too.
