### ISSUE TITLE
I keep getting signed out when I reboot my computer

### ISSUE THREAD

**Issue by 42Willow** [Vencord/Vesktop#346]
**Describe the bug**
Upon rebooting, I am signed out of vesktop. Maybe this is something to do with not having a keyring set up?

**To Reproduce**
1. Sign in
2. Reboot
3. Start vencord
4. You're signed out

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux (AUR), also occured on OpenSUSE Tumbleweed (appimage)
 - Desktop Environment (linux only): Hyprland (Wayland)
 - Version: [e.g. 22]

**Comment by Vendicated** [comment]
reinstall vesktop

**Comment by 42Willow** [comment]
Oops, I forgot I had already made an issue for this and that was the solution - sorry.

**Comment by 42Willow** [comment]
Never mind, this still occurs randomly after a period of time, I rebooted my computer and I am prompted to log in again. Could this possibly be reopened? Could this have something to do with not having a keyring setup?

**Comment by Vendicated** [comment]
if you're being logged out still, it possibly means you're somehow running multiple vesktop processes at once. or other issues with your system. we can't really help you with that as that's more of an electron issue

**Comment by 42Willow** [comment]
Ok, thanks - I'll try to figure it out and post it here if I find a solution :+1:

**Comment by 42Willow** [comment]
![image](https://github.com/Vencord/Vesktop/assets/70784752/683b2b46-8cd4-4444-88bd-8a22d1301f5d)
Installing the `NoDevtoolsWarning` fixed the issue, which is weird - as I don't open devtools.. 

Thank you `koishukaze` for the solution
