### ISSUE TITLE
Stream popout window doesn't have window controls

### ISSUE THREAD

**Issue by ItsNiceCraft** [Vencord/Vesktop#350]
**Describe the bug**
Vencord 1.5.0 broke stream popouts. The window bar with options to close, move, maximize and minimize are missing.

**To Reproduce**
Open a stream popup

**Expected behavior**
Window bar is present

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/74358857/8c94a6c5-b3fe-4fe0-874e-698d783008c9)

**Desktop (please complete the following information):**
 - OS/Distro: Windows
 - Version: 11 22H2

Follow-up to #348

**Comment by Vendicated** [comment]
are you using the custom discord title bar? or the native system one

**Comment by ItsNiceCraft** [comment]
The native windows title bar. I have "Static Title" and "Enable Menu Bar" both set to false.

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/commit/8c007476c3843822c82b54f1b00f898be6c5db31
