### ISSUE TITLE
No AppIndicator icon on GNOME using extension

### ISSUE THREAD

**Issue by Ender-thePlayer** [Vencord/Vesktop#351]
**Describe the bug**
There is no appindicator icon using "AppIndicator and KStatusNotifierItem Support" extension on GNOME

**To Reproduce**
1. Install the "AppIndicator and KStatusNotifierItem Support by [3v1n0](https://extensions.gnome.org/accounts/profile/3v1n0)" extension
2. Open vesktop
3. No icon

**Expected behavior**
There should be an vesktop icon like other apps that have an appindicator on like on kde

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/77354434/3113217c-3f0d-47c8-a266-0f3e79e0dabb)

**Desktop:**
 - OS/Distro: Fedora 39 Linux
 - Desktop Environment (linux only): GNOME
 - Version: 45

**Additional context**
I've installed vesktop via GNOME store (Flathub)

**Comment by Vendicated** [comment]
duplicate of https://github.com/Vencord/Vesktop/issues/340
