### ISSUE TITLE
Allow custom startup animation

### ISSUE THREAD

**Issue by jxhug** [Vencord/Vesktop#352]
**Is your feature request related to a problem? Please describe.**
Basically it's a little weird opening vesktop in public places lol

**Describe the solution you'd like**
A way to customize the animation by uploading a gif alternative

**Describe alternatives you've considered**
Just use the regular discord startup animation

**Comment by Vendicated** [comment]
the world needs to see shiggy

**Comment by zt64** [comment]
destroy shiggy

**Comment by Growebis** [comment]
> destroy shiggy

I 100% agree with this.

jokes aside, i would love for it to be customizable so i can put whatever i want.

**Comment by Sqaaakoi** [comment]
can we have shoggy on startup?

**Comment by DissolveDZ** [comment]
totally agree, it's really easy to replace the gif in the static folder and recompile though

**Comment by OboTheHobo** [comment]
> totally agree, it's really easy to replace the gif in the static folder and recompile though

for people running from source sure, most users are probably using flatpak tho. And adding an option in the app would make things easier for the end user anyway.

**Comment by Vendicated** [comment]
closing in favour of https://github.com/Vencord/Vesktop/issues/667
