### ISSUE TITLE
How do I install this on steam deck?

### ISSUE THREAD

**Issue by papawheelie** [Vencord/Vesktop#356]
Hey, sorry if this is a very basic question but how do I get vesktop installed on my steam deck? I was able to download it successfully using the app image but audio streaming wasn't possible using that version, and the version that works is apparently the flatpak. How do I get the flatpak installed? I tried building from source in the konsole but that didn't seem to work, and the file from flathub just opens the discovery store and gives me an error. 

I know this is a very noob question, I'm not especially familiar with Linux but I would really like to stream my games to my friends, so any advice would be very very much appreciated! Thanks !

**Comment by Vendicated** [comment]
Use the Discovery app to install Vesktop
