### ISSUE TITLE
Adjustable Scroll Sensitvity

### ISSUE THREAD

**Issue by jake770321** [Vencord/Vesktop#357]
**Is your feature request related to a problem? Please describe.**
Scrolling sensitivity in Vesktop is a lot higher than the official client and is a bit too high for me using a touchpad (in my opinion)

**Describe the solution you'd like**
A way to adjust the scrolling sensitvity

**Comment by Vendicated** [comment]
not possible. scrolling is faster in vesktop than official app because chromium 109 heavily increased scroll speed on linux (to be similar to the speed on Windows and Mac)

you can change scroll speed per app via https://wiki.archlinux.org/title/IMWheel
