### ISSUE TITLE
[LINUX] Screenshare broadcasts microphone audio

### ISSUE THREAD

**Issue by mhkdepauw** [Vencord/Vesktop#358]
**Describe the bug**
When screensharing on Vesktop the audio from the stream also has my microphone audio in it, this makes people in the call hear you double when watching your stream.

This kind of negates the entire use of audio screen-share as you either have to be muted and then not de audible by people not watching your stream or people have to mute your stream which defeats the purpose entirely.

**To Reproduce**
1. Open Vesktop
2. Join any vc
3. screenshare an application, with that application's audio
4. Have someone else watch this stream and have you talk.
5.  They will hear you through the stream and through discord.

**Expected behavior**
Screenshare shouldn't share your microphone audio input.

**Desktop (please complete the following information):**
 - OS/Distro: Ubuntu
 - Desktop Environment (linux only): Gnome 3.36.8
 - Version: 20.04
 - installed with flatpak

**Comment by Curve** [comment]
Please transfer to [Venmic](https://github.com/Vencord/venmic) and provide the information requested there.

**Comment by mhkdepauw** [comment]
My version is 1.5.0
![image](https://github.com/Vencord/Vesktop/assets/87832202/7ed5c32e-7803-40c7-ba25-efd3de556113)

It is happening, I just tested it.
I'll look at Venmic and make an issue there tho.
