### ISSUE TITLE
Process leak from streaming

### ISSUE THREAD

**Issue by andreaskrath** [Vencord/Vesktop#359]
**Describe the bug**
I have noticed a CPU usage increase happening over time as I am streaming.

It should also be mentioned that I can feel the effect this bug has on my system, where if I am playing a game I notice the performance gradually degrading - until I restart my stream and the issue is resolved.

**To Reproduce**
1. Start streaming.
2. Wait a couple of hours.
3. Monitor CPU, and see a massive increase in the electron process.

**Expected behavior**
Streaming should not gradually increase the CPU usage of the electron process.

**Screenshots**
The following is a screenshot showing the CPU and memory usage of the electron processes just after I started streaming.
![image](https://github.com/Vencord/Vesktop/assets/70445343/ede0ab45-256d-43ed-962e-61c4927a705b)

Then there is a screenshot after 25 minutes of streaming, where the CPU usage has increased around 6%.
![image](https://github.com/Vencord/Vesktop/assets/70445343/f19502fe-7937-44da-abe8-fc464059fd5b)

*I will provide further updates on CPU usage after streaming for longer periods in due time.*

**Desktop (please complete the following information):**
 - OS/Distro: NixOS 24.05pre563471.cfc3698c31b1 (Uakari) x86_64
 - Desktop Environment: none+xsession - I use i3 version 4.23 (2023-10-29)
 - Version: 0.4.4

I know that I am not using the newest release - however, the change notes for the newest version does not mention this being fixed, so I assume this would still be an issue in the newest version; although this is something I will test at a later point.

**Additional context**
I am not 100% certain the the issue lies in Vesktop - however I never experienced these issues when I was using the standard Discord.

**Comment by Vendicated** [comment]
streaming is out of vesktops control, it's just electron/chromium api

currently, streams are sadly not hardware accelerated so that's likely where your issue comes from. hopefully we'll be able to fix that in the future, and it should help with this issue as well

see https://github.com/Vencord/Vesktop/issues/191
