### ISSUE TITLE
Unable to disable unread notification count

### ISSUE THREAD

**Issue by justin13888** [Vencord/Vesktop#362]
**Describe the bug**
On Windows, I'm unable to disable the unread notification count seen in taskbar.
![image](https://github.com/Vencord/Vesktop/assets/20733699/1212f41f-1643-40d3-82e6-9fc31a89a5f6)

I thought turning off this setting in Vesktop would work but it doesn't appear to do what I think it should do (i.e. disable unread notification count in taskbar). I can't really tell what this toggle actually does otherwise and so either this is a bug or this issue is a feature request.
![image](https://github.com/Vencord/Vesktop/assets/20733699/a42c8d52-48da-4668-b8a6-d63d7ec4db30)

**To Reproduce**
When you have

**Expected behavior**
There exists a toggle button to control whether the notification count appears or not.

As an added bonus, allow the option for "Do Not Disturb" Discord mode to automatically disable count as well.

**Desktop (please complete the following information):**
 - OS/Distro: Windows 11

**Comment by Vendicated** [comment]
vesktop settings

**Comment by justin13888** [comment]
Was the toggle that I screenshot red the button that was described? Not sure why it was closed @Vendicated because that button doesn't seem to work even after a full restart.
