### ISSUE TITLE
Vesktop not working on Windows 7

### ISSUE THREAD

**Issue by TK50P** [Vencord/Vesktop#363]
**Describe the bug**
When I run Vesktop on Windows 7 x64, it says "Entey Point Not Found"
I am not sure how about windows 8/8.1.

**To Reproduce**
1. Installed Vesktop as Administrator and All users
2. When I clicked finish
3. Error shows

**Expected behavior**
It should literally run fine, but it throws an error differently than I expected.

**Screenshots**
![Screenshot 2024-01-25 203101](https://github.com/Vencord/Vesktop/assets/127497974/9c9395e9-4462-42b1-bec5-b04db80dd684)

**Desktop (please complete the following information):**
 - OS/Distro: Windows 7 Embedded POSReady Service Pack 1 (x64)
 - Version: Vesktop 1.5.0

**Additional context**
I'm not sure what it's like for Windows 8 and 8.1. If anyone encounters this error in 8 or 8.1, please let me know.

**Comment by Vendicated** [comment]
upgrade to windows 10 or higher

**Comment by TV-Toshikawa** [comment]
You could use [VxKex](https://github.com/vxiiduu/VxKex) to run it, but this is not officially supported by Vesktop and update to Vesktop could break VxKex compatibility.

**Comment by Semanual** [comment]
Windows 8.1 and below (and even some early windows 10 versions) has already long reached [their EOL](https://endoflife.date/windows). For your own safety, do not use softwares after their EOL, especially OSes, as your security may be compromised. Security issues are not solved anymore after them. If windows 10 or above can't run well on your hardware, you may consider some linux distribution, as they are a lot more lightweight.

**Comment by TK50P** [comment]
bet, i've been ported to windows 7 with downgrading electron.
that's why build instructions exists, and even more further ported to 32-Bit windows.
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/178ec37a-c8d3-4fe0-9e60-be648f7758cd" />
