### ISSUE TITLE
visibility as desktop instead of web

### ISSUE THREAD

**Issue by moonfight1** [Vencord/Vesktop#365]
**Is your feature request related to a problem? Please describe.**
When using the platform indicators plugin, i appear as web not desktop

**Describe the solution you'd like**
To make the vesktop client be visible as desktop not web server-side 

**Additional context**
![image](https://github.com/Vencord/Vesktop/assets/156691675/b7811057-ed9a-4caa-ab6f-93c5d258a91e)

**Comment by Vendicated** [comment]
no

**Comment by riverpaper** [comment]
can we revisit this? why not make it optional as a plugin?

**Comment by nin0-dev** [comment]
vencord won’t add a potentially bannable plugin, this won’t be “revisited”
