### ISSUE TITLE
Latest update breaks Linux transparency

### ISSUE THREAD

**Issue by Earthquake125** [Vencord/Vesktop#366]
**Describe the bug**
Transparency is not working in latest Vesktop on Linux. This was working in previous versions of Vesktop via a workaround, however the option added in https://github.com/Vendicated/Vencord/commit/988435714e8b1de6e7e95885cbb5222113fb039c and https://github.com/Vencord/Vesktop/commit/b636b65e55235fde9092843a7d3f8dae02d9d720 does not seem to be working

**To Reproduce**
1. Launch Vesktop
2. Attempt to enable window transparency using Vencord settings
3. Relaunch
4. Observe transparency is not enabled

**Expected behavior**
![Screenshot_20231209_142107](https://github.com/Vencord/Vesktop/assets/59297679/2241b2ea-2d28-4804-8702-330a85d1baa8)

**Screenshots**
![Screenshot_20240127_134949](https://github.com/Vencord/Vesktop/assets/59297679/3d1f6df6-f430-4f81-a3b5-6a7661637b25)

**Desktop:**
 - OS/Distro: Arch Linux
 - Desktop Environment: KDE
 - Version: 5.27.10

**Comment by Vendicated** [comment]
it's not in the current release. build from source or wait for next release

**Comment by Earthquake125** [comment]
Thanks, I wasn't aware.
