### ISSUE TITLE
Taaho

### ISSUE THREAD

**Issue by Taahoyare** [Vencord/Vesktop#367]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Distro: [e.g. Windows / Fedora Linux / MacOs]
 - Desktop Environment (linux only): [e.g. gnome, kde, sway]
 - Version: [e.g. 22]

**Additional context**

**Comment by Curve** [comment]
I have the same issue

**Comment by RinLovesYou** [comment]
Taaho 🔥

**Comment by AAGaming00** [comment]
whar

**Comment by eightcon** [comment]
I agree👍

**Comment by PKMNPlatin** [comment]
This thread was very informative!
