### ISSUE TITLE
[Linux] ibus input is not working inside vesktop

### ISSUE THREAD

**Issue by rank-coder** [Vencord/Vesktop#368]
**Describe the bug**
On linux, ibus typing methods behave like the English US layout.

**To Reproduce**
1. Go to a message box.
2. Select an ibus typing method for a language other than English.
3. Start typing.
4. Instead of the characters of the target language, characters according to English US layout shows up.

**Expected behavior**
ibus should work normally. Appropiate characters should show up instead of the US layout characters.

**Desktop (please complete the following information):**
 - OS/Distro: Fedora Workstation 39
 - Desktop Environment (linux only): gnome
 - Version: gnome 45

**Additional context**
I think the ibus does not work with Vesktop and thats why whichever ibus method is selected always US layout works only. If you select other languages' system layout then it will do work. The problem is only with ibus.

**Comment by Vendicated** [comment]
does it work with the normal desktop app?

**Comment by rank-coder** [comment]
Yes it works with the normal Discord app. The flatpak version of the
Discord app works too.

মঙ্গল, ৩০ জানু, ২০২৪ ১:১৫ AM তারিখে V ***@***.***> লিখেছেন:

**Comment by Vendicated** [comment]
dunno if im using it correctly but it seems to work just fine

[Screencast from 2024-01-30 03-35-41.webm](https://github.com/Vencord/Vesktop/assets/45497981/63dd7ada-c3e5-4768-aae2-bfc0c430ac1f)

**Comment by Vendicated** [comment]
in any case, this is very unlikely to be related to Vesktop. it does not intercept or deal with input in any way

if it types the wrong text, that means your system is feeding it the wrong letters

**Comment by Vendicated** [comment]
like i said above, this has nothing to do with vesktop. and works fine on my machine, watch my video

replying with "same problem here :(" is not useful, what am I supposed to do with that?

try googling for solutions, running vesktop from the command line to collect console output, etc
