### ISSUE TITLE
Stuck on Loading Vesktop...

### ISSUE THREAD

**Issue by tikkamasalla** [Vencord/Vesktop#369]
**Describe the bug**
Stuck on loading screen when starting the application

**To Reproduce**
Open the application

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/104959287/f4e859f3-ce46-4141-a853-670484482aca)

**Desktop (please complete the following information):**
![image](https://github.com/Vencord/Vesktop/assets/104959287/58f72389-4b1e-40bb-9e10-1c15af444192)

**Additional context**
I tried a clean install multiple times, as well as trying the vencord repair patch tool to no avail. 

Vesktop used to work perfectly for me and just out of nowhere stopped working after an update.

**Comment by Vendicated** [comment]
you haven't provided any relevant information

run vestkop from the command line to see if there are any relevant errors

please use our support channel if you need further help

**Comment by FahadBinHussain** [comment]
I am experiencing the same issue. Vesktop is stuck at loading for 1-2 minutes, then opens with a white screen and stays white. 

![image](https://github.com/Vencord/Vesktop/assets/75292632/4802fe9a-1f6b-4f3b-b24e-7535e3023655)

**Comment by Vendicated** [comment]
> Failed to load URL: https://discord.com/app with error: ERR_CONNECTION_TIMED_OUT

your connection to discord timed out. issue on your end, nothing we can do
