### ISSUE TITLE
Stuck on DTLS connecting when connecting to a call

### ISSUE THREAD

**Issue by murl-digital** [Vencord/Vesktop#373]
**Describe the bug**

Today, when trying to join a call, vesktop will be stuck on DTLS connecting. This doesn't happen with the official client.

**To Reproduce**

1. Attempt to connect to a call on vesktop

**Expected behavior**

The call connecting properly, which it has done for me up until this point.

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux [Crystal Linux]
 - Desktop Environment: KDE 5.27.10
 - Version: latest (1.5.0 flatapak, AUR 1.5.0-15)

**Additional context**

I tested this with both the flatpak and AUR version, neither worked.

**Comment by Vendicated** [comment]
try in a chromium browser. if it happens there as well, discord issue

**Comment by murl-digital** [comment]
it happens there too, it's a discord issue sadly

**Comment by explosion025** [comment]
hey did you ever get your vencord working again? im having this very same issue now
