### ISSUE TITLE
Documentation for adding custom plugins

### ISSUE THREAD

**Issue by Latrolage** [Vencord/Vesktop#374]
**Is your feature request related to a problem? Please describe.**
Vencord has a section which lets you add custom plugins into a folder before building with pnpm. https://github.com/Vendicated/Vencord/blob/main/docs/2_PLUGINS.md but vesktop does not

**Describe the solution you'd like**
Add and document a place to put userplugins.

**Comment by Vendicated** [comment]
scroll down in vesktop settings..

**Comment by Latrolage** [comment]
I'm not sure what you're referring to. When I scroll down in the "Vesktop Settings" tab, I get a bunch of boolean check boxes but none of them are relevant. At the bottom, it lets me change the location of where it loads Vencord files but doesn't let me open the location it is currently using. I think I may be misunderstanding what you mean by "Vesktop Settings" but there is only one tab in discord's settings with the exact name " Vesktop Settings.

I can see `~/.config/VencordDesktop` in my filesystem but it isn't relevant to the what is written in https://github.com/Vendicated/Vencord/blob/main/docs/2_PLUGINS.md

**Comment by ethan-davies** [comment]
Follow the instructions, then run `pnpm build`, go to the Vesktop settings and scroll till you find this:

<img width="528" alt="image" src="https://github.com/Vencord/Vesktop/assets/80976096/cd0a4171-6ef7-49f0-93cf-aae33d2894ab">

Select the `dist` and restart your client

**Comment by x0rp01s0n** [comment]
should be in the documentary, i searched 1 hour until i found this...
