### ISSUE TITLE
Vesktop won't maintain Discord account logged in, need to relogin almost every time I open the app.

### ISSUE THREAD

**Issue by Stay1444** [Vencord/Vesktop#375]
**Describe the bug**

For some reason Vesktop is having a hard time maintaining my Discord account logged in. I'd say that probably 70%+ of times that I close the App, either closing it and opening it later, or restarting my computer, the session is lost and I have to log in again.

**To Reproduce**

1. Close the App 
2. Open It
4. Log in with Discord QR code
6. Restart eh App and the session is lost

**Expected behavior**

The account should be logged in.

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux x86_64 
 - Desktop: KDE Plasma 5.27.10
 - Version: Kernel 6.7.2-zen1

**Comment by Vendicated** [comment]
1. Don't use Devtools or enable NoDevtoolsWarning plugin
2. Don't run multiple instances of vesktop at once. Make sure there isn't one in the tray still
3. Reinstall

**Comment by saipheblue** [comment]
I had the same issue, I think I solved this be logging out on browser. Because Vesktop is behaving is another browser tab and if you are logged in two places at once it will log you out.  At least that's my assumption

**Comment by wiki-Bird** [comment]
Had the same issue on Fedora 41; can confirm that I had Discord Developer Mode on, and enabling the NoDevtoolsWarning plugin resolved everything.

**Comment by alany08** [comment]
same here, been happening since starting to use vesktop. i have the NoDevtoolsWarning plugin and Developer Mode on, but the active account always gets logged out upon resume from suspend

**Comment by wiki-Bird** [comment]
> same here, been happening since starting to use vesktop. i have the NoDevtoolsWarning plugin and Developer Mode on, but the active account always gets logged out upon resume from suspend

does this still happen when you turn developer mode off?

**Comment by martyfuhry** [comment]
This has been happening to me all of a sudden, as well. I do not have Developer Mode on and do not have any plugins. I am running the Flatpak on Pop!_OS with the new Cosmic DE.

**Comment by SIGSTACKFAULT** [comment]
Happens to me. Arch Linux, running from source. NoDevtoolsWarning didn't help

**Comment by Vendicated** [comment]
make sure you are on the latest vesktop version. if you are and it still happens, then it has nothing to do with vesktop and there's a good chance it's discord forcefully logging you out because you're tripping antispam. please use our support channel if you need further help

**Comment by SIGSTACKFAULT** [comment]
i was, in fact, not running updated vesktop. pulled, restarted vesktop, then slept and woke my computer (which would normally cause it) and it didn't happen. if i don't respond to this thread again it's probably because it worked.

**Comment by dclmao** [comment]
Had this issue as well on Void, just had to enable the NoDevtoolsWarning plugin and its working fine now. Thanks everyone.
