### ISSUE TITLE
Vesktop flatpak does not show the screen sharing dialog on Debian

### ISSUE THREAD

**Issue by AprilTheCatgirl** [Vencord/Vesktop#377]
**Describe the bug**

Vesktop does not show the screen sharing (resolution/audio) dialog on Debian when attempting to screenshare.

**To Reproduce**

1. Voice call someone
2. Click on the screensharing button
3. Click on the display/application you want to share

**Expected behavior**

A dialog should pop up with resolution/audio settings and a preview of your screen. The flatpak (with the same permission settings) seems to work when tested on Fedora Workstation 39 and openSUSE Aeon.

It also works while using the appimage, although the expected audio message comes up when you try it. 

**Desktop:**
 - OS/Distro: Debian 12 Bookworm
 - Desktop Environment: GNOME (Wayland)
 - Version: 1.5.0

**Command line output**
```
Passing the following arguments to Electron: --ozone-platform-hint=auto
[[38;2;88;101;242marRPC[0m > [38;2;254;231;92mipc[0m] listening at /run/user/1000/discord-ipc-0
[[38;2;88;101;242marRPC[0m > [38;2;235;69;158mwebsocket[0m] listening on 6463
[[38;2;88;101;242marRPC[0m > [38;2;237;66;69mprocess[0m] started
[3:0203/233353.887625:ERROR:browser_main_loop.cc(276)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[3:0203/233405.092336:ERROR:shared_x_display.cc(39)] Unable to open display
```

**Additional context**
Running Debian Stable with no backported packages. I am wondering if there is any special permission or environment variable I need for this to work on Debian.

**Comment by Vendicated** [comment]
something wrong with your system. nothing we can do

**Comment by Vendicated** [comment]
> It also works while using the appimage, although the expected audio message comes up when you try it.

by that do you mean on the same system as where it doesnt work inside flatpak? the permissions are set up correctly so it should just work..

**Comment by AprilTheCatgirl** [comment]
> > It also works while using the appimage, although the expected audio message comes up when you try it.
> 
> by that do you mean on the same system as where it doesnt work inside flatpak? the permissions are set up correctly so it should just work..

Yes

**Comment by RattletraPM** [comment]
> something wrong with your system. nothing we can do

FWIW this seems to happen on fresh installs of both Debian 12 (stable at the time of writing) and 13 (testing): screensharing seems to work fine using Vencord's Flatpak release under X11, however trying to do the same under Wayland doesn't work at all, resulting in the same error @AprilTheCatgirl posted.

On the other hand, screensharing under Wayland with Vencord's native .deb package works flawlessly in Debian 13, while 12 has a libstdc++6 version that's too old for venmic in its repos.

**Comment by TheDrifter363** [comment]
I'm going to add on to this. On Debian 12, Bookworm, and using the latest flatpak, screensharing doesn't work. Get that same "unable to open display". I'm using KDE with wayland. Using the 1.5.0 deb version of flatpak, screensharing works fine. I can't use the later versions of vesktop, since Debian's libstdc++ is too old. Just wanted to post my issues too, hope it helps.
