### ISSUE TITLE
Hide vencord

### ISSUE THREAD

**Issue by moonfight1** [Vencord/Vesktop#381]
**Is your feature request related to a problem? Please describe.**
So yk these servers that ban for client modding?

**Describe the solution you'd like**
A plugin that can disable quickcss and all themes (online or local) on the push of a keybind

**Describe alternatives you've considered**
https://discord.com/channels/1015060230222131221/1028106818368589824/1097491379854266368 this is a link to a css snippet that hides a lot of Vencord things 

**Additional context**

**Comment by Vendicated** [comment]
this is the vesktop repo..
