### ISSUE TITLE
Flatpak arRPC stopped working

### ISSUE THREAD

**Issue by s-liwka** [Vencord/Vesktop#382]
**Describe the bug**

arRPC stopped working (it worked before). I am not using the plugin but the switch in Vesktop settings. I did follow the guide at https://github.com/flathub/dev.vencord.Vesktop

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux
 - Desktop Environment (linux only): GNOME
 - Version: 45.3

**Command line output**

Run vesktop from the command line. Include the relevant command line output here:
```
$ flatpak run dev.vencord.Vesktop
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:0208/234213.885259:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 23:42:14.381: Failed to load module "xapp-gtk3-module"
Gtk-Message: 23:42:14.382: Failed to load module "appmenu-gtk-module"
Gtk-Message: 23:42:14.410: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:42:14.411: Failed to load module "canberra-gtk-module"
[3:0208/234214.433907:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0208/234214.433997:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```

**Additional context**
![image](https://github.com/Vencord/Vesktop/assets/116428267/f9a6032e-2c0c-4ebd-9ab8-a15ea02a98ee)

**Comment by Vendicated** [comment]
the workaround works fine with VSCode and other apps. you either did not do it correctly or it's an issue with your script

we can't help you with some third party script

**Comment by s-liwka** [comment]
Well, it used to work but suddenly i cant use RPC from any app including vscodium. I haven't changed anything with the workaround.

```
$ cat ~/.config/user-tmpfiles.d/discord-rpc.conf 
L %t/discord-ipc-0 - - - - .flatpak/dev.vencord.Vesktop/xdg-run/discord-ipc-0
```

```
$ systemctl status systemd-tmpfiles-setup
● systemd-tmpfiles-setup.service - Create Volatile Files and Directories
     Loaded: loaded (/usr/lib/systemd/system/systemd-tmpfiles-setup.service; static)
     Active: active (exited) since Wed 2024-01-31 11:44:52 CET; 1 week 1 day ago
       Docs: man:tmpfiles.d(5)
             man:systemd-tmpfiles(8)
   Main PID: 442 (code=exited, status=0/SUCCESS)
        CPU: 55ms
```

**Comment by kelbazz** [comment]
One solution that worked for me was to enable the activity toggle plugin and enable the activity from the button
