### ISSUE TITLE
Autostart does not work when launching with non packaged electron

### ISSUE THREAD

**Issue by PotatoCider** [Vencord/Vesktop#383]
**Describe the bug**

Enabling "Start With System" in "Vesktop Setttings" generates a `~/.config/autostart/vencord.desktop` file which runs electron28 on startup without any arguments:

```
Exec=/usr/lib/electron28/electron
```

This causes the the default Electron app to open, not Vesktop.

**To Reproduce**

1. Enable "Start With System" in "Vesktop Setttings"
2. Notice that  `~/.config/autostart/vencord.desktop` file is created with `Exec=/usr/lib/electron28/electron` line
3. Reboot
4. Default Electron app is started

**Expected behavior**

Vesktop should run.

**Screenshots**

`$ less ~/.config/autostart/vencord.desktop` :
![image](https://github.com/Vencord/Vesktop/assets/28196972/0b8a993b-be85-45d6-b16c-e11643ec6f6b)

Default Electron App that runs on startup:
![image](https://github.com/Vencord/Vesktop/assets/28196972/197feebf-ff57-4767-aa37-22478988fd9d)

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux `6.7.4-zen1-1-zen`
 - Desktop Environment: KDE Plasma
 - Version: `1.5.0-1` on arch repos

**Comment by PotatoCider** [comment]
Related: #273

**Comment by PotatoCider** [comment]
After digging further, it seems that the `vesktop-bin` in the AUR repository is using a [`vesktop.sh` script](https://aur.archlinux.org/cgit/aur.git/tree/vesktop.sh?h=vesktop-bin) which runs electron on the `app.asar` file directly, which is  probably unsupported for guys. Seems like it is an issue with the AUR package.

Would it better to use `Exec=${process.argv.join(' ')}` [instead of `process.execPath`](https://github.com/Vencord/Vesktop/blob/6993b2a7d445c3a3d44978c643ef8ae7d0c85e63/src/main/autoStart.ts#L31) for this?

**Comment by Vendicated** [comment]
indeed this is an issue when launching Vesktop with your own electron instead of our packaged binary

(this is technically not supported but) this needs fixing from our end, argv would indeed be the correct solution

**Comment by Vendicated** [comment]
fixed via https://github.com/Vencord/Vesktop/commit/44627b4cd469de32860f8f72f1168543e9ceda9d, you'll have to toggle it off and back on to apply the fix
