### ISSUE TITLE
RPC works not with Flatpak

### ISSUE THREAD

**Issue by Jak2k** [Vencord/Vesktop#385]
**Describe the bug**

RPC is not working with flatpak.

**To Reproduce**

1. Install [this vs-code extension](https://github.com/iCrawl/discord-vscode)

**Expected behavior**

I expect RPC to work the same as in the official client.

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Distro: Fedora Linux
 - Desktop Environment (linux only): KDE
 - Version: stable 264913 (ae72f64)

**Command line output**

Run vesktop from the command line. Include the relevant command line output here:
```
Passing the following arguments to Electron: --ozone-platform-hint=auto
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```

**Additional context**

The extension says `Encountered following error while trying to login: Error: Could not connect`

**Comment by Vendicated** [comment]
https://github.com/flathub/dev.vencord.Vesktop?tab=readme-ov-file#discord-rich-presence

**Comment by Jak2k** [comment]
Would it be possible to make this a one-click thing from within the app?

**Comment by Vendicated** [comment]
no. that would defeat the entire point of flatpak's isolation and thus isn't possible

**Comment by Jak2k** [comment]
This is a pity, because as a user it is not clear why RCP does not work. This could be too big a hurdle for Linux beginners in particular. Perhaps a note at the point where RPC would normally be displayed would be helpful.

**Comment by forest-cat** [comment]
For me guide is not working, ive added via flatseal `xdg-run/.flatpak/dev.vencord.Vesktop:create` and` xdg-run/discord-ipc-*` to the global settings and it still did not work

**Comment by JusPLP** [comment]
> For me guide is not working, ive added via flatseal `xdg-run/.flatpak/dev.vencord.Vesktop:create` and` xdg-run/discord-ipc-*` to the global settings and it still did not work

The current workaround does not work.
Use 'xdg-run/discord-ipc-0' instead of 'xdg-run/discord-ipc-*'.

**Comment by Novantric** [comment]
same here. Or maybe games like tf2 just dont work with aRPC?

**Comment by forest-cat** [comment]
> same here. Or maybe games like tf2 just dont work with aRPC?

For me it definitely worked before when i used vesktop installed native by my package manager. Ig its not a bug, its a privacy feature now :)
