### ISSUE TITLE
White screen after install

### ISSUE THREAD

**Issue by valiray** [Vencord/Vesktop#387]
**Describe the bug**

After installing vesktop a small white box appears for a second then the top bar disappears and the program just stays like that

**To Reproduce**

1. Download and install vesktop 
2. After running the installer try to launch the program 
3. The program is unable to find quickCss.css and locks up

**Expected behavior**

The program fully runs and is useable 

**Screenshots**

It’s inconvenient for me to get a screenshot on my setup but if you really want one I can get it

**Desktop (please complete the following information):**
 - OS/Distro: windows 10 and 11
 - Version: [e.g. 22]

**Command line output**

Run vesktop from the command line. Include the relevant command line output here:
```
(node:1732) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\admin\AppData\Roaming\vesktop\settings\quickCss.css'
(Use `Vesktop --trace-warnings ...` to show where the warning was created)
(node:1732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```

**Comment by Vendicated** [comment]
delete %APPDATA%/Vesktop and try again

**Comment by valiray** [comment]
Same result, unable to fine quickCss.css

**Comment by valiray** [comment]
Also the setting folder is not being created

**Comment by Vendicated** [comment]
it has nothing to do with quickcss. please use our support channel for further help because this has nothing to do with development

**Comment by valiray** [comment]
> it has nothing to do with quickcss. please use our support channel for further help because this has nothing to do with development

I did and it got ignored and buried, it’s whatever tho

**Comment by ManicQuinn** [comment]
Same problem, did you ever figure it out?

**Comment by valiray** [comment]
> Same problem, did you ever figure it out?

i just gave up on using vesktop after essentially being told to fuck off by the dev :P

**Comment by Vendicated** [comment]
you know that's not true. I just told you to move this to support because it's a you issue and a lot more info than what you provided is necessary to know what's wrong or why this happens.

**Comment by Veynam** [comment]
Hello, first time trying to use Vesktop, im getting the same issues, after Loading Besktop I just get a big white screen. Shame, was really looking forwards to using this app
