### ISSUE TITLE
MacOS ARM — "Vesktop.app" is damaged and can't be opened.

### ISSUE THREAD

**Issue by k1nomoto** [Vencord/Vesktop#389]
**Describe the bug**

Unable to open on macOS

[**Screenshots**](https://i.imgur.com/32v8v8K.png)

**Desktop (please complete the following information):**
 - OS: macOS (ARM) 14.0

**Comment by Vendicated** [comment]
not a vesktop issue.

**Comment by k1nomoto** [comment]
> The solution is to run `xattr -cr /Applications/Vesktop.app` which should fix it.

thanks
