### ISSUE TITLE
When popping out active stream, unable to move window.

### ISSUE THREAD

**Issue by sekuza009** [Vencord/Vesktop#390]
**Describe the bug**

If you're in an active call and attempt to pop out the window to move to another screen, the window is unable to be dragged. It can however be moved if you do Win + Shift + Left Arrow or Win + Shift + Right Arrow.

**To Reproduce**

1. Start a call.
2. Have other person start screen sharing.
3. Attempt to pop out window for screensharing.

**Expected behavior**

Be able to move the popped out stream around freely.

**Desktop (please complete the following information):**
 - OS/Distro: Windows 10 Pro
 - Version: 22H2

**Comment by Vendicated** [comment]
cannot reproduce. 

[Screencast from 2024-02-18 16-55-29.webm](https://github.com/Vencord/Vesktop/assets/45497981/88261762-844d-4612-961a-0670be0e0304)

**Comment by sekuza009** [comment]
It seems to be a windows exclusive issue, as the window on Discord that you pop the stream out on has no title, and you can't move it.

**Comment by Vendicated** [comment]
already fixed ages ago but i forgot to released it. will make a release very soon

**Comment by Vendicated** [comment]
Fixed in 1.5.1

**Comment by Fletch64** [comment]
Hello! Just wanted to state that I'm having this issue now on Arch Linux as well! It seems to be correlated to the User Interface Discord Title Bar setting being enabled. Now, the pop-up has nothing you can drag around the window.
