### ISSUE TITLE
Vesktop doesn't support Windows PowerToys FancyZones

### ISSUE THREAD

**Issue by naomieow** [Vencord/Vesktop#391]
**Describe the bug**

Vesktop doesn't respect FancyZones properly, it snaps correctly to location but doesn't resize. Discord desktop app does respect them.

**To Reproduce**

1. Download PowerToys
2. Enable FancyZones
3. Use FancyZones by holding shift while moving window

**Expected behavior**

Vesktop window should resize to the FancyZone.

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/79906167/2ef05079-1d01-44f9-b4b9-1ada3ee7e49c)
Both windows here were snapped to the same zone, Discord being the un-themed one in the background and has correctly snapped to the zone.

**Desktop (please complete the following information):**
 - OS/Distro: Windows
 - Version: 23H2 22631.3007

**Command line output**
No output

**Comment by MadelineMaid** [comment]
alternative solution: just dont use fancy zones

**Comment by naomieow** [comment]
> alternative solution: just dont use fancy zones

Super useful solution 🙄

**Comment by naomieow** [comment]
> i'm inclined to say this is actually a fancyzones issue but i'm not sure, i don't use the feature myself personally and the default windows snapping works fine.
> 
> does it work if you use the native titlebar rather than the discord one on vesktop?

Using the native titlebar allows FancyZones to work but native snapping completely breaks for me. The fullscreen button is completely grayed out and dragging the window to the sides of the screen does nothing. The native Windows 11 window management bar at the top of the screen also does not show up and nor does it when hovering the fullscreen button (as it is grayed out).
![image](https://github.com/Vencord/Vesktop/assets/79906167/f635426d-2124-4e19-9400-7d7008c3c2c0)
Grayed out fullscreen button with native titlebar

**Comment by lewisakura** [comment]
turn off transparency

**Comment by naomieow** [comment]
> turn off transparency

Ahh that worked, wonder why that causes it 🤔

**Comment by Vendicated** [comment]
https://www.electronjs.org/docs/latest/tutorial/window-customization#limitations
