### ISSUE TITLE
Different name for the source output when in voice chats to prevent muting the wrong application.

### ISSUE THREAD

**Issue by m2neral** [Vencord/Vesktop#392]
Basically since there are no global keybinds I'm muting the index from `pacmd list source-outputs` that has the name "Chromium input" using awk and grep.
I was wondering if it would be possible to have the source output name be "Vesktop input" or something similar so that in the case of multiple "Chromium input"s I don't have to mute each one individually.

**Comment by Vendicated** [comment]
no
