### ISSUE TITLE
Spotify Controls with DJ picks

### ISSUE THREAD

**Issue by AftmostSeeker80** [Vencord/Vesktop#393]
Whenever I'm listening to the DJ picks on Spotify and I have the program closed, I use the Spotify Controls plugin to skip songs, which is great and all, but it's missing some little features/details.

What I would like to happen is that, when DJ picks are enabled, the Shuffle and Repeat buttons become greyed out, since they cannot be used, and a new button pops out, allowing users to "get some other DJ picks", as the Spotify button itself says.

I am aware another solution is to just ignore the icons and click on the skip button a few times until the picks have changed, but I feel like this might be a nice little detail/addition to the already existing plugin.

**A disclaimer**
I have no idea whether this is possible to detect from the Spotify API/connection, and if it isn't feel free to close this issue!
Also, I wasn't sure whether to post this in the plugin request form because... well, it's not a new plugin, so I posted it here.

**Some images**
The current Spotify Controls plugin panel while DJ picks are enabled
![vc](https://github.com/Vencord/Vesktop/assets/55350217/70a12f07-d679-4873-8b8d-f0759237fa31)

Spotify: Shuffle & Repeat button are greyed out because they cannot be used, DJ picks button is on the right
![spoty](https://github.com/Vencord/Vesktop/assets/55350217/250949a3-b415-4fa7-9d90-dcadacf6551d)

A little edit of the current Spotify Controls plugin panel (DJ picks enabled), similar to Spotify's
![vc-edit](https://github.com/Vencord/Vesktop/assets/55350217/fd829076-5910-4bdf-915f-ec34e0f8d48c)

**Comment by Vendicated** [comment]
i am assuming this is not possible but i have no clue what dj mode even is

maybe it is possible

**Comment by AftmostSeeker80** [comment]
DJ mode (or DJ picks) is an Ai generated song queue made by Spotify based off your musical tastes, your area and some other criteria that I don't know of. 
It works by presenting the next category of songs/artists with a sort of TTS voice, in which music doesn't play as if it's paused - although it isn't - and then actually play the music. There are usually 4-5 songs for each category, after which it repeats from the TTS part. 
If it can help detecting DJ mode, the songs are mixed, meaning they don't start from 0:00 and change automatically as time goes on.
As for the button in the Discord UI, I don't know if it's actually possible to implement it

**Comment by Vendicated** [comment]
well wrong repo, this is vesktop
