### ISSUE TITLE
Channel topic pop-out on click does not work. 

### ISSUE THREAD

**Issue by sudo-nano** [Vencord/Vesktop#394]
### Describe the bug

On both the Discord app and website, clicking on the topic of a channel will pop out a window in the center of your discord that displays the topic. This is necessary to read topics longer than the space after the channel name, as these topics are abbreviated until popped out. 

### To Reproduce

1. Open any server
2. Open a channel with a topic 
3. Click on the topic at the top of the client
4. Topic does not pop out 

### Expected behavior

Topic pops out when 

### Screenshots
Image of expected channel pop up:
<img width="489" alt="Screenshot 2024-02-16 at 14 20 45" src="https://github.com/Vencord/Vesktop/assets/63484662/6adb4d53-a87a-4aab-bcb6-60835f835e19">

### Desktop (please complete the following information):
 - OS/Distro: Mac OS Sonoma 14.2.1
 - Desktop Environment (linux only): N/A
 - Version: stable 267220 (6b16dbc)
 - Hardware: M1 MacBook Air (2020)

**Command line output**

Run vesktop from the command line. Include the relevant command line output here:
```
open Vesktop.app
(produces no output)
```

**Additional context**

None.

**Comment by Vendicated** [comment]
cannot reproduce and you have given 0 relevant info. possibly a theme issue. use our support channel if you need help

**Comment by sudo-nano** [comment]
The issue is present with and without a theme in use. I filled out all the information on your bug report template, what other information is supposed to be included?
