### ISSUE TITLE
Unable to drag and drop files onto a chat when using Vesktop

### ISSUE THREAD

**Issue by sbeve72** [Vencord/Vesktop#397]
Dragging and dropping a file from the file explorer or any other window doesn't work (only happens if you Alt + Tab to the Vesktop Window)

**To Reproduce**
1. Open any Discord channel or chat
2. Open another window such a chrome window or the file explorer on your OS
3. Drag a file or a piece of text from the new window and switch to Discord (by the means of alt + tabbing)
4. Watch the cursor go wild/something strange happen other than the pop up that says to release the dragged file appear. It appears as if someone is holding down the `Tab` key.

**Expected behavior**
4. A pop-up confirming the existence of a file under the cursor should appear that simply asks you to release the mouse button

**Screenshots**
[Screencast from 2024-02-18 00-36-03.webm](https://github.com/Vencord/Vesktop/assets/65838896/2d3d7838-d4a2-4d13-a975-b6405cf79aa5)

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux (Zen Kernel)
 - Desktop Environment (linux only): Gnome 45.4, Mutter
 - Version: 1.5.0

**Command line output**
## Nothing special here
```
$ vesktop 
[243577:0218/003950.907634:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[243577:0218/003950.911182:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[243577:0218/003950.920159:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Additional context**
The pop-up does appear but it disappears and a blue keyboard-navigation style cursor appears to be running across the screen as if someone has held down the Tab key.

**Comment by Vendicated** [comment]
try to run in xwayland

also make sure vesktop has access to the file (likely won't if using flatpak)

**Comment by sbeve72** [comment]
How would i do that? How do I change that flag?

**Comment by sbeve72** [comment]
Tried appending that flag through the terminal with the following command
```vesktop --ozone-platform-hint=x11```, and no it's not a wayland issue
