### ISSUE TITLE
Custom CSS does not apply to popout windows

### ISSUE THREAD

**Issue by naomieow** [Vencord/Vesktop#399]
**Describe the bug**
Custom CSS does not apply to popout windows

**To Reproduce**

1. Apply a custom theme
2. Join a VC
3. Pop out the VC
4. Open the VC chat
5. See error

**Expected behavior**

The theme is applied

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/79906167/64692d20-e671-420b-a176-890dc3fb4403)

**Desktop (please complete the following information):**
 - OS/Distro: Windows 11
 - Version: 23H2 22631.3007

**Command line output**
No relevant output

**Additional context**
Am using GlazeWM but it happens in normal Windows window manager as well.

**Comment by Vendicated** [comment]
this indeed is more appropriate for the Vencord repo. currently, we don't inject into popout windows
