### ISSUE TITLE
Unable to screenshare 10 bit screen

### ISSUE THREAD

**Issue by Kagukara** [Vencord/Vesktop#400]
**Describe the bug**

When I go to screenshare with my screen that is set to 10 bit on hyprland, nothing happens. If you go to click to screenshare again the button no longer works and you need to restart vesktop.

**To Reproduce**

Steps to reproduce the behaviour:
1. Make sure your screen is 10 bit. 
Run in the terminal (Replace `DP-1` with your monitors port):
```bash
sudo find /sys/kernel/debug/dri | grep DP-1 | grep bpc | sudo xargs head -n-0
````
3. If `=> /sys/kernel/debug/dri/0000:0c:00.0/DP-1/max_bpc <==` outputs `10` you can move onto the next step, otherwise you need to set your monitor to 10 bit.
4. Run `vesktop`.
5. Go into a voice channel and start a screenshare with the 10 bit screen.
6. Nothing happens.
7. Try to screenshare again.
8. Nothing happens.
9. Close `vesktop`

**Expected behaviour**

When I select the 10 bit screen for screensharing it should select the screen, popup the "SCREENSHARE" settings, and  when "Go Live" is clicked a screenshare should have started.

**System Information:**
- OS: Arch Linux
- Kernel: 6.7.5-arch1-1
- DE: Hyprland (Tag: v0.35.0-63-g13d98548)
- Vesktop Version: stable 267220 (6b16dbc)

**Command line output**

Run vesktop from the command line. Include the relevant command line output here:
```
[6958:0221/031806.739839:ERROR:shared_screencast_stream.cc(241)] PipeWire stream state error: no more input formats
[6958:0221/031806.739859:ERROR:shared_screencast_stream.cc(204)] PipeWire remote error: no more input formats
```

**Additional context**

Capturing a 10 bit screens in obs-studio is possible because of this commit: https://github.com/obsproject/obs-studio/pull/6247/commits/a7e40df595f2c26666f0c9cef413838c9214d516, would it be possible to enable screensharing of 10 bit screens in vesktop?

**Comment by Vendicated** [comment]
not possible. screensharing is powered by chromium/electron, we have no control over it.
