### ISSUE TITLE
Feature request: change application icon to better resemble Discord

### ISSUE THREAD

**Issue by Yasand123** [Vencord/Vesktop#401]
I take 2-3 seconds every time I want to find the application in the taskbar or systray due to the VC icon. I think it would be better to at least make the icon resemble Discoed's icon somewhat so it's easier to spot at a glance.

**Comment by Vendicated** [comment]
i don't understand the use case. just change the launcher icon yourself

**Comment by Vendicated** [comment]
well in the case of the systray

**Comment by Ermageeerd** [comment]
> well in the case of the systray it would indeed require a change from us, so that's fair

maybe bundle it in a similar way as changing the loading screen?

**Comment by skyli91** [comment]
![Képernyőkép 2024-02-28 193433](https://github.com/Vencord/Vesktop/assets/7442913/12138252-28a8-487f-92e2-4637391811e6)
Systray for me is barely even recognisable...

**Comment by pigsflew** [comment]
Here:
![vesktop 512px PNG](https://github.com/Vencord/Vesktop/assets/868821/ab6249bf-2667-46c4-8b97-d01ebfcd5cba)
![vesktop SVG](https://github.com/Vencord/Vesktop/assets/868821/a87ffce3-43e5-46e5-a337-006637da0fbb)

And here's the [Ico file](https://drive.google.com/file/d/1yJc-OqWRcOK2ptvW4wOlfmF1wmLGy0XZ) with a bunch of embedded sizes. I manually edited the smaller size icons so they'd be *somewhat* reasonable.

[Vesktop Icon Sizes.zip](https://github.com/Vencord/Vesktop/files/14719341/Vesktop.Icon.Sizes.zip)

**Comment by Aeternitae** [comment]
Here's a quick and dirty mockup as a replacement of the round discord icon I made as an alternative, just to try and help and throw another idea out there.

![mockup](https://github.com/Vencord/Vesktop/assets/157359060/e1349af5-ad90-4b5e-bf02-5f0392e2ff4d)

**Comment by nin0-dev** [comment]
tbh blurple doesn't go that well with the vencord logo

mac/linux gay vesktop logo should definitely be ported over to windows tho, could be nice

**Comment by justin13888** [comment]
I actually quite like the current logo for Vesktop on FlatHub

![image](https://github.com/Vencord/Vesktop/assets/20733699/4e3138cb-81ba-4d3c-b03a-c1457cdf7087)

Unfortunately, it's the normal one on the Windows version for example....

![image](https://github.com/Vencord/Vesktop/assets/20733699/cf1aa3e0-d433-4255-9770-9a7549ca35c7)

Question: @Vendicated Why aren't all the Vesktop versions using the one on FlatHub? Perhaps at least give the option for the background?

**Comment by nin0-dev** [comment]
i believe that it's for platform consistency, mac / linux icons usually have a background colour, while windows usually has icons with a transparent background

**Comment by justin13888** [comment]
> i believe that it's for platform consistency, mac / linux icons usually have a background colour, while windows usually has icons with a transparent background 

Hmm mind sharing some examples of applications that have intentionally transparent background? Most apps I use are cross platform and share the same logo across platforms

**Comment by Vendicated** [comment]
the rainbow icon was originally only meant for mac, created by a contributor specially for it

it also looks way better on gnome, so we decided to also use it on Linux

___

> Perhaps at least give the option for the background?

you can just change it yourself. create a shortcut to vesktop then right click > properties and change the icon

**Comment by toasterw** [comment]
> Hmm mind sharing some examples of applications that have intentionally transparent background? Most apps I use are cross platform and share the same logo across platforms
Discord has a circular icon on windows but follows the macos convention of squares with rounded edges

**Comment by tiagorangel2011** [comment]
> > i believe that it's for platform consistency, mac / linux icons usually have a background colour, while windows usually has icons with a transparent background
> 
> Hmm mind sharing some examples of applications that have intentionally transparent background? Most apps I use are cross platform and share the same logo across platforms

vs code, native explorer, native paint, native calculator, (also most native apps) git, firefox, and inno installer are some I can quickly remember of.

**Comment by justin13888** [comment]
> > > i believe that it's for platform consistency, mac / linux icons usually have a background colour, while windows usually has icons with a transparent background
> > 
> > 
> > Hmm mind sharing some examples of applications that have intentionally transparent background? Most apps I use are cross platform and share the same logo across platforms
> 
> vs code, native explorer, native paint, native calculator, (also most native apps) git, firefox, and inno installer are some I can quickly remember of.

are you talking about macos, windows, or some linux DE?

**Comment by justin13888** [comment]
> the rainbow icon was originally only meant for mac, created by a contributor specially for it
> 
> but it also looks way better on gnome, so we decided to also use it on Linux
> 
> > Perhaps at least give the option for the background?
> 
> you can just change it yourself. create a shortcut to vesktop then right click > properties and change the icon

Fair enough. Imo, the rainbow logo is better because it's just hard to see the outline of the transparent one while in the taskbar for both light and dark mode in Windows. It's not really a big deal though. Perhaps if it's feasible, making the icon programatically user swappable would appease the feature request and most people. But then, I'm not sure what's involved with Electron to do that

**Comment by justin13888** [comment]
For reference, would you mind sharing where is the original rainbow Vesktop icon used for the Mac, Linux and Vesktop GitHub repo? @Vendicated

**Comment by Vendicated** [comment]
closing in favour of https://github.com/Vencord/Vesktop/issues/667

**Comment by tiagorangel2011** [comment]
> > > > i believe that it's for platform consistency, mac / linux icons usually have a background colour, while windows usually has icons with a transparent background
> > > 
> > > 
> > > Hmm mind sharing some examples of applications that have intentionally transparent background? Most apps I use are cross platform and share the same logo across platforms
> > 
> > 
> > vs code, native explorer, native paint, native calculator, (also most native apps) git, firefox, and inno installer are some I can quickly remember of.
> 
> are you talking about macos, windows, or some linux DE?

windows.
