### ISSUE TITLE
Can't stream on Arch Hyprland

### ISSUE THREAD

**Issue by Kartikey2011yadav** [Vencord/Vesktop#402]
I am using Hyprland on arch and am unable to start stream on vencord, share your screen button seems to be not working properly.
the popup which use to appear before doesn't show up anymore.
does any one know how to work it out...

**Comment by Vendicated** [comment]
hyprland issue. update

**Comment by rurigk** [comment]
@Kartikey2011yadav This a xdg-desktop-portal-hyprland issue 
You probably have leftover files, search for my post on this on the hyprland discord

**Comment by Kartikey2011yadav** [comment]
Thanks, i figured it out now it's working
