### ISSUE TITLE
[Linux] Multi language spell checking is not working

### ISSUE THREAD

**Issue by pixmacfy** [Vencord/Vesktop#405]
**Describe the bug**

OS language is set to English, and has both English and French enabled for spell checking.

French is correctly detected on Discord, but not on Vesktop, even when Vesktop's language is set to French.

OS is Arch Linux on KDE Wayland, and uses hunspell spell checking packages

**Additional context**

Spell check language is set in `index.ts` with `VesktopNative.spellcheck.setLanguages(window.navigator.languages);`.

Hardcoding `["fr-FR"]` works, and logging `window.navigator.languages` only outputs `en-US`, so I suspect that the `languages` property is not working the same way on Linux as it does on Windows/macOS, and Vanilla Discord potentially uses another method to detect the system' spell checking languages.

However I didn't find any proper solution.

**Comment by Vendicated** [comment]
`window.navigator.languages` should contain all locales you have configured on your system. double check that you have properly configured them

**Comment by pixmacfy** [comment]
`locale -a` gives me the following output, even after rerunning `locale-gen`

```
C
C.utf8
en_US.utf8
fr_FR.utf8
POSIX
```

However, adding French in `Regional Settings > Region & Languages > Language` under English via KDE System Settings sets the `$LANGUAGE` env variable to `en_US:fr` and fixes the problem.

`window.navigator.languages` is now properly populated with both languages, and spell checking works as intended.

I must warn that KDE recommends against using other languages with English as the top priority, even if this is not causing me any issue at the moment. I'm also surprised vanilla Discord doesn't have this issue, but at least this is a working solution for Vesktop.

**Comment by Vendicated** [comment]
not sure how to fix this. i don't think there is a standardised way to choose multiple locales at once in linux, so we have no way of finding out your preferred locales

`locale -a` might work on Arch and such where you only generate the ones you're personally gonna use, but on "user friendly" distros like ubuntu it will have all locales pre-included. For me on fedora, it lists 873 lines. So this is definitely not viable

the way the official discord app does it is that they have their own library that detects language of text, then they dynamically update the spellcheck locale to whatever language you're typing in. (this is why sometimes spellcheck won't kick in until you type a few words)

but this is also really insane and i don't really want to do that...

**Comment by Vendicated** [comment]
i guess we could let you manually choose locales you would like?

**Comment by D3SOX** [comment]
> `window.navigator.languages` should contain all locales you have configured on your system. double check that you have properly configured them

It looks like this is different on Vesktop when compared to other browsers

![image](https://github.com/Vencord/Vesktop/assets/24937357/a3ea51b9-2ea5-492d-9fa4-c0a79a7fb393)

**Comment by meekah7** [comment]
Why not make that context menu entry a regular button to open a new window with a scrollable and searchable list of the languages? Makes it much less insane, but I have no idea how difficult that is to implement. Personally, I'd be happy with this context sub-menu from your screenshot.

**Comment by Vendicated** [comment]
i just did it like this now, implemented via https://github.com/Vencord/Vesktop/commit/f232cfc3c81e42fc054ca3f3fdd5a65166fc7692

![image](https://github.com/Vencord/Vesktop/assets/45497981/5ae9e86a-1e00-45d0-9df3-be3ae8d35821)
