### ISSUE TITLE
[macOS] Universal Binary 

### ISSUE THREAD

**Issue by Unichy** [Vencord/Vesktop#406]
It would be nice if Vesktop had a single Universal Binary app for macOS. It would take away some confusion for average users since most macOS apps are distributed as Universal Binaries. Since it's architecture independent, it makes sharing across systems a lot easier. Compared to Vesktop, the official client — which is Universal — is only ~150MB larger.  

If this isn't possible, making the installation instructions for macOS a bit more informative in the readme would be a good compromise.

**Comment by Vendicated** [comment]
> making the installation instructions for macOS a bit more informative in the readme would be a good compromise

1. this will stop being an issue once we add Vesktop to the vencord.dev site, because it can obtain your architecture from your browser to provide the right download
2. feel free to contribute README documentation improvements

**Comment by Unichy** [comment]
I know I posted this ages ago, but I have some concerns.

Last time I checked, there was no way for a website to get the architecture of a machine unless we’re talking about the user agent string. In that case, Apple Silicon Macs will pretend to be Intel Macs for privacy.

There’s also the issue of users moving between systems. If a user were to transfer their data from an Intel Mac to an Apple Silicon Mac, they would be none the wiser that there is an ARM version for this app. Also, in the off chance that someone wants to share the app through AirDrop having a universal binary comes in handy.

**Comment by Vendicated** [comment]
> Last time I checked, there was no way for a website to get the architecture of a machine

```js
await navigator.userAgentData.getHighEntropyValues([ "architecture", "bitness" ]);
```

```js
const canvas = document.createElement('canvas');
try {
  gl = canvas.getContext('webgl') || canvas.getContext('experimental-webgl');
  debugInfo = gl.getExtension('WEBGL_debug_renderer_info');
  console.log("vendor", gl.getParameter(debugInfo.UNMASKED_VENDOR_WEBGL))
  console.log("renderer", gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL))
} catch (e) {
}
```

**Comment by Unichy** [comment]
Okay, did not know that was a thing 😅, but my point still stands about it’s more convenient for users moving between computers.

**Comment by Vendicated** [comment]
done via https://github.com/Vencord/Vesktop/commit/9e3d83a2ee3a05cf84040e84ef53252ae7e29a96

**Comment by Git-North** [comment]
This is an absolutely horrible change. While this does make it "less confusing" for the avarage consumer. It also increases ram and battery consumption by adding an extra translation layer and also makes it impossible to use the app without Rosetta2 (the said abstarction layer) Rosetta2's purpose is to be a helper while transitioning to the new arm64 architecture. Not to be a replacement for the arm64 binaries.
