### ISSUE TITLE
Clicking on a notification should take you to the message

### ISSUE THREAD

**Issue by LelouBil** [Vencord/Vesktop#409]
**Is your feature request related to a problem? Please describe.**
Clicking on a notification currently just focuses the Vesktop window, but clicking on a notification means I'm interested in it's content.

**Describe the solution you'd like**
The Vesktop window opening on the page of the message that triggered the notification.

**Describe alternatives you've considered**
Manually moving to the correct channel after vesktop opens

**Comment by Sqaaakoi** [comment]
this sounds a lot like an upstream discord issue that needs to be fixed

**Comment by Vendicated** [comment]
cannot reproduce. even if i could, it would be a discord issue, not a vesktop issue
