### ISSUE TITLE
Vesktop 1.5.0 Mac ARM64 is damaged.

### ISSUE THREAD

**Issue by GamerPROPlayER5** [Vencord/Vesktop#410]
Vesktop 1.5.0 for ARM64 on Mac is described as "damaged" when attempting to open application.

**To reproduce:**
Downloading either the Vesktop 1.5.0 ARM64 Mac .dmg or the .zip, then dragging Vesktop into the Applications folder, then opening it opens a pop-up that says "Vesktop is damaged and can't be opened. You should move it to the bin." And does not open

**Expected behaiour:**
Opening Vesktop app should open and show up as an "apple" app in activity monitor.

**Screenshots:**
<img width="277" alt="Screenshot 2024-02-28 at 2 43 45 pm" src="https://github.com/Vencord/Vesktop/assets/137789432/8c62cc62-563c-493e-b149-baee1b8c9f93">
<img width="257" alt="Screenshot 2024-02-28 at 2 46 17 pm" src="https://github.com/Vencord/Vesktop/assets/137789432/32539cc6-ffaf-4337-8d1a-242c82bc82dd">

**Additional context**
I'm on MacOS 13.6.4
The Intel version of Vesktop works just fine, But a bit laggy.

**Comment by Vendicated** [comment]
https://www.google.com/search?q=fix+app+is+damaged

**Comment by GamerPROPlayER5** [comment]
Thank you it worked.
