### ISSUE TITLE
Mica transparency option disables the rounded corners

### ISSUE THREAD

**Issue by s-k-y-l-i** [Vencord/Vesktop#411]
**Describe the bug**

Mica transparency setting disables the rounded corners in Vesktop settings.
It also removes the shadows around the window frame. And also the window frame.

**Expected behavior**

It should not change the corner rounding, only enable Mica transparency.

**Screenshot**
![image](https://github.com/Vencord/Vesktop/assets/7442913/8ca1529a-25c6-4371-a607-239721aba9ff)
![image](https://github.com/Vencord/Vesktop/assets/7442913/8b774d8f-ec84-453d-8eb6-cdc7a086019d)

**Desktop (please complete the following information):**
 - OS/Distro: [ Windows ]
 - Version: [ 1.5.0 ]

**Comment by Vendicated** [comment]
we have no control over this behaviour, sorry
