### ISSUE TITLE
Fractional scaling on KDE+Wayland breaks viewport scale

### ISSUE THREAD

**Issue by Wilker-uwu** [Vencord/Vesktop#412]
**Describe the bug**

Window size improperly scales while transitioning between monitors of different scales, causing both the window size and the click positions to mismatch.

**To Reproduce**

- on KDE loaded with Wayland, have at least 2 neighboring desktop spaces.
  - at least one of them needs to have a scale other than 100% (video example uses 70~75%)
- simply drag the window between the monitors

**Expected behavior**

window should maintain its relative size, allowing for manual resize of the window if there's a need.

**Screenshots**

[alt: a video demonstrating the problem, comparing Vesktop window behavior and two other different behaviors from other engines ran by Alacritty and OBS, respectively.](https://github.com/Vencord/Vesktop/assets/10854855/16a49df0-6b72-4003-b6f6-dd0273601768)

**Desktop (please complete the following information):**
 - OS/Distro: Fedora Linux 39
 - Desktop Environment (linux only): KDE 5.27.10, Wayland
 - Version: Vesktop 1.0.0 via Flatpak

**Command line output**

N/A (no logging related to window sizing is made).

**Additional context**

this is not an isolated case for Vesktop itself.  as shown in the attached video, this issue also happens in other forms of window rendering. similar issues can be found in OBS, but the window sizing problem also happens in Speech Note (a text-to-speech tool), and the click mismatch can be seen in some applications serving as a front-end for web pages such as the case with Vesktop.

**Comment by NyaomiDEV** [comment]
https://github.com/Vencord/Vesktop/assets/13177694/e2f75464-f687-43c7-9610-7f185df47de3

4k on left (150%), and 1440p on right (100%). Plasma 5.27.10 on Wayland on Artix Linux.

I think your distro is borked.

**Comment by Wilker-uwu** [comment]
i'm not talking about the pixel resolution, both screens in my case are 1080p. the difference is the GUI scale set to anything other than 100%.
![alt: A screenshot of the Display settings. there is a red square outline highlighting the relevant setting which reads "Scale ... 70%". the interface is in portuguese.](https://github.com/Vencord/Vesktop/assets/10854855/9512b0cf-eab8-42a6-877c-3fb0092b6a20 "A screenshot of the Display settings. there is a red square outline highlighting the relevant setting which reads "Scale ... 70%". the interface is in portuguese.")

**Comment by NyaomiDEV** [comment]
> i'm not talking about the pixel resolution, both screens in my case are 1080p. the difference is the GUI scale set to anything other than 100%.

The issue here is not with Vencord, but with your configuration. A correctly configured Plasma setup will take scale into account, like it does on my system. Mind you, I do have two differently dense displays, for which the window size should be adapted on the fly. It is density here, but essentially the same thing happens: the pixel resolution gets increased or decreased based on which display I am about to move the window, so that it looks consistent.
