### ISSUE TITLE
Big text, when deleted with the plugin MessageLogger enabled, isn't highlighted red

### ISSUE THREAD

**Issue by Steakchop** [Vencord/Vesktop#414]
When deleting an enlarged text, e.g. "# abcdefg," the deleted, logged message isn't highlighted in red.

**To Reproduce**

1. Type and send enlarged text using a hashtag and space, for example: "# message"
2. Delete the message while the plugin "MessageLogger" is enabled
3. Observe the error, and optionally toggle "Deleted Highlight" in the context menu to observe the option's ineffectuality

**Expected behavior**

The deleted, enlarged text will be highlighted in red, as exemplified in regular-sized text

![highlighted](https://github.com/Vencord/Vesktop/assets/99525753/56f89dbd-457a-4f88-97f7-edcfd41320f3)

**Screenshots**

![image 1](https://github.com/Vencord/Vesktop/assets/99525753/1b7fecf8-6413-4661-8d03-e9cdf1d8d150)
![image 2](https://github.com/Vencord/Vesktop/assets/99525753/851ca892-2ef6-4872-83f0-c4aaaba46dab)
![image 3](https://github.com/Vencord/Vesktop/assets/99525753/a794ba2a-04c6-46d7-aab0-5d2038d3f28b)

**Desktop (please complete the following information):**

 - OS/Distro: Windows
 - Version: 22H2

**Additional context**

This issue is very minor.

The context menu option "Toggle Deleted Highlight" doesn't produce any observable result. Tabbing out and back in doesn't fix the issue, nor does switching channels (or DMs) within the app.

**Comment by Vendicated** [comment]
this is the vesktop repo.
