### ISSUE TITLE
Vesktop battery drain on laptop

### ISSUE THREAD

**Issue by DreamingCuttlefish** [Vencord/Vesktop#415]
**Describe the bug**

When running vesktop on my laptop with an amd iGPU and amd dGPU, vesktop runs on the dGPU and consequently uses a lot of battery.

**To Reproduce**

1. Open Vesktop on a dual gpu laptop
2. Observe status of gpu (in my case through supergfxctl+switcherooctl)
3. See it is enabled, and see increased power consumption in powertop
4. Close Vesktop
5. Observe status of gpu and see it is now disabled

**Expected behavior**

I would expect this to run automatically on the integrated GPU as it is not a game or super graphics-intensive program (or at least provide the option to do so)

**Screenshots**

![Screenshot_20240301_163742](https://github.com/Vencord/Vesktop/assets/129349057/416bfbb4-64bd-4c13-be2d-191aea64d186)

**Desktop (please complete the following information):**
 - OS/Distro: Fedora 39
 - Desktop Environment (linux only): KDE
 - Version: Vesktop v1.5 (Flatpak)

**Command line output**

Run vesktop from the command line. Include the relevant command line output here:
```
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:0301/163413.064382:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0301/163415.775307:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0301/163415.775350:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```

**Comment by Vendicated** [comment]
try running vesktop with the `--force_low_power_gpu` command line flag or disable hardware acceleration in vesktop settings

**Comment by DreamingCuttlefish** [comment]
> try running vesktop with the `--force_low_power_gpu` command line flag or disable hardware acceleration in vesktop settings

Thanks for the suggestion. Running the flag didn't do anything, but disabling hardware acceleration does work, however it makes discord very slow. Is there any workaround for this? This doesn't happen on any other discord client like webcord or armcord or the official discord client.

**Comment by Vendicated** [comment]
this flag might have to be passed from code. are you able to build from source using the instructions in the README?

try adding this code below this line https://github.com/Vencord/Vesktop/blob/main/src/main/index.ts#L36
```js
app.commandLine.appendSwitch('force_low_power_gpu')
```

and see if it works

**Comment by soulsoiledit** [comment]
A little late, but I had the same issue with power consumption. Adding `--force_low_power_gpu` still does not work for me, but adding that line did allow the dGPU to suspend.

**Comment by tacsist** [comment]
Experiencing the same problem, flags do nothing. Could we get a fix/change so the flags do sth without changing the source code?
