### ISSUE TITLE
Login required after app is suspended

### ISSUE THREAD

**Issue by dwonderg** [Vencord/Vesktop#416]
**Describe the bug**

After windows11 comes out of sleep mode, Vesktop requires accounts to be logged into again. Vesktop also does not keep state of other discord accounts the user has signed into.

**To Reproduce**

1. Use Vesktop on Windows 11
2. Leave Vesktop open
3. Place Windows in sleep mode
4. Wake Windows from sleep mode
5. Vesktop reconnects to the login screen for the first discord account username.

**Expected behavior**

Vesktop doesn't require logging in after sleep mode, and Vesktop remembers and keeps login state for all running discord accounts

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Pro
 - Version: 1.5.0

**Comment by Sqaaakoi** [comment]
can you reproduce this with the NoDevtoolsWarning plugin enabled?

**Comment by Sqaaakoi** [comment]
> > can you reproduce this with the NoDevtoolsWarning plugin enabled?
> 
> a third party plugin? will try...

NoDevtoolsWarning is a first party Vencord plugin..?

**Comment by Vendicated** [comment]
If you are using Devtools (if you dont know what this means, you dont), enable NoDevtoolsWarning

otherwise reinstall

**Comment by dwonderg** [comment]
> If you are using Devtools (if you dont know what this means, you dont), enable NoDevtoolsWarning
> 
> otherwise reinstall / make sure you dont have multiple instances running

I am trying out the NoDevToolsWarning plugin for a day

**Comment by dwonderg** [comment]
Adding that plugin fixed the issue.
