### ISSUE TITLE
Vesktop won't open on Pop!_OS

### ISSUE THREAD

**Issue by caitlynrw** [Vencord/Vesktop#417]
**Describe the bug**

Vesktop not launching on Pop!_OS 22.04

**To Reproduce**

1. Installed Vesktop from Pop!_Shop or Flatpak CLI
2. Attempt to open
3. Observe

**Expected behavior**

Vesktop boots as per normal

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Distro: Pop!_OS 22.04
 - Desktop Environment (linux only): GNOME
 - Version: 

**Command line output**

Run vesktop from the command line. Include the relevant command line output here:
```
bwrap: execvp startvesktop: No such file or directory
```

**Additional context**

It was previously working, after moving around my `/home` partition it no longer does.

**Comment by Vendicated** [comment]
issue on your end. try to reinstall
