### ISSUE TITLE
Feature request: Switching from Electron to Tauri

### ISSUE THREAD

**Issue by imide** [Vencord/Vesktop#419]
**Is your feature request related to a problem? Please describe.**
Yes. Electron is incredibly heavy and eats RAM like an American eats, well, anything. Switching to a lighter, faster and just better backend like Tauri would provide performance boosts, less usage of resources, and more.
**Describe the solution you'd like**
If Vesktop switches to Tauri, annoying bugs such as the occasional error when opening the app without internet would be fixed, along with just being lighter, faster, and allowing for the possibility of a mobile app of Vesktop (with the death of vendetta :(...)  

**Describe alternatives you've considered**
sticking with electron, but electron is annoying lol.

**Additional context**
Mobile app support is coming in Tauri V2.

**Comment by lewisakura** [comment]
Tauri fixes none of the issues you have described, plus requires a significant amount of rewriting of Vesktop and potentially Vencord to accomplish.

> Electron is incredibly heavy and eats RAM like an American eats, well, anything.

So does Tauri. Yes, it's reduced, but it's still using WebViews which are still going to be Chromium-based most of the time, so there isn't really much of an improvement.

> annoying bugs such as the occasional error when opening the app without internet would be fixed

This is a minor issue in the app that will be fixed. This isn't Electron's fault.

> along with just being lighter, faster, and allowing for the possibility of a mobile app of Vesktop

This won't happen for many reasons, one of which being that Discord Web support on mobile is quite atrocious.

**Comment by Vendicated** [comment]
fyi there is already a vencord mobile app but it's borderline unusable: https://github.com/Vencord/Vendroid

**Comment by AAGaming00** [comment]
also tauri uses webkit on linux meaning nvidia wayland users will suffer to https://megastutter.org/
