### ISSUE TITLE
fcitx5 support?

### ISSUE THREAD

**Issue by Kellen-wq** [Vencord/Vesktop#420]
**Describe the bug**
fcitx doesn't work, I can't write in any language other than english even if I run a vesktop with the relevant arguments.

**To Reproduce**
1. install fcitx5
2. check[ guide for electron apps](https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron)
3. run vesktop with /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
4. languages have started to change, but you still can't write in languages other than English.

**Expected behavior**
Change of languages is possible, IME popup appears in the right place

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux
 - Desktop Environment (linux only): Hyprland, wayland
 - Version: vesktop 1.5.0

**Command line output**

Run vesktop from the command line. Include the relevant command line output here:
```
top dev.vencord.Vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
Using NVIDIA on Wayland, disabling gpu sandbox
Passing the following arguments to Electron: --ozone-platform-hint=auto --disable-gpu-sandbox

(vesktop.bin:3): Gdk-WARNING **: 11:09:09.468: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[3:0303/110909.502334:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[3:0303/110909.502347:ERROR:select_file_dialog_linux_portal.cc(285)] Failed to read portal version property
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```

**Comment by pluiedev** [comment]
I think this is not a Vesktop bug, actually, it's just Hyprland being very shoddy with IMEs in Chromium apps. I *think* I found a fix for this at some point, but after every problem disappeared when I switched back to KDE, I seriously doubt it has anything to do with the apps and everything to do with how Hyprland implements the various text input protocols

**Comment by Vendicated** [comment]
if you read the console output you shared, you'll notice that it's not actually passing the flag you --enable-wayland-ime flag you specified.

this might be an issue specific to the flatpak wrapper script, where it's not correctly forwarding user flags

try on a non flatpak version of vesktop to see if it works there

**Comment by Kellen-wq** [comment]
> I think this is not a Vesktop bug, actually, it's just Hyprland being very shoddy with IMEs in Chromium apps. I _think_ I found a fix for this at some point, but after every problem disappeared when I switched back to KDE, I seriously doubt it has anything to do with the apps and everything to do with how Hyprland implements the various text input protocols
> 
> EDIT: See more about how to fix this issue at https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland, though your mileage may dramatically vary. I think I tried a combination of `--gtk-version=4` and `--enable-wayland-ime` and that worked for Chromium but not Vesktop. Maybe try forcing GTK4?

i use portable chromium without any runtime parameters and fcitx5 in it works stably without errors




> if you read the console output you shared, you'll notice that it's not actually passing the flag you --enable-wayland-ime flag you specified.
> 
> this might be an issue specific to the flatpak wrapper script, where it's not correctly forwarding user flags
> 
> try on a non flatpak version of vesktop to see if it works there

yes i installed the aur package and it works without any settings. but if i still put `--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime` it also stops printing other languages. so i will use this way for now, thanks.

**Comment by fsworld009** [comment]
Just want to add that I'm runnning EndeaviorOS (Arch linux based), with Flatpak Vesktop 1.5.1 and fcitx5 5.1.8-1 installed from pacman, I'm able to use IMEs inside the app with the flag

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop --enable-wayland-ime
```

So the bug about chromium flags not being passed mentioned in previous replies might have been fixed.

**Comment by ScarletLovell** [comment]
`--enable-wayland-ime` doesn't appear to work for me, neither does forcing GTK4? I seem to have a very specific issue with this and the logs for Vesktop don't seem to tell me much about what's happening:

```
Passing the following arguments to Electron: --ozone-platform-hint=auto
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```
Is there any other logs I can provide to support this issue? I've been at it for about an hour or two now just trying to force it to work but it does not; however, all other apps seem to work just fine.

**Comment by thewikt** [comment]
Having the same issue, Vesktop seems to ignore the `--enable-wayland-ime` command. I'm using the Flatpak package on Arch Linux with Plasma 6.1.1 & fcitx5 configured for Japanese input. 
Other Electron applications have no issues with using the IME, including the standard Discord package from the Arch repo.

**Comment by G2-Games** [comment]
Can confirm I'm experiencing this issue with fcitx5 configured for Japanese input on Fedora 40 with Plasma 6.1.1.
The issue does not occur in any other electron application through Flatpak, and passing the `--enable-wayland-ime` works if the application is launched manually, but it is ignored in the `.desktop` file.

**Comment by tduck973564** [comment]
I'm experiencing this using the .rpm package. No set of arguments or lack thereof actually works.

**Comment by tduck973564** [comment]
Well it works through xwayland, running electron as Wayland just doesn't work at all, same for the vanilla client

**Comment by Vendicated** [comment]
this is not a vesktop issue. input is handled entirely by electron and chromium. vesktop has 0 control over it

**Comment by tduck973564** [comment]
> this is not a vesktop issue. input is handled entirely by electron and chromium. vesktop has 0 control over it

Is it? The chromium browser works fine through Wayland. The Youtube Music client I'm using also works fine under wayland. It's just Vesktop and the actual Discord client that don't work when running under Wayland, they have to be run under XWayland for IME to work.
