### ISSUE TITLE
Cannot exit fullscreen on macOS

### ISSUE THREAD

**Issue by Imzxhir** [Vencord/Vesktop#422]
**Describe the bug**

There is no button on macOS to exit fullscreen once entered. By this, I mean there is no button in the top left to get out of fullscreen once entered.

**To Reproduce**

1. Open Vesktop on macOS
2. Click on the green button in the top left
3. You will be in fullscreen, but will not be able to get out of it.

**Expected behavior**

There should be a button to exit fullscreen like most macOS apps.

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/98621617/8a13bee3-2f3b-4358-be4c-a65cc06dc221)

I tried to screenshot the traffic light buttons when on fullscreen, but for some reason macOS hides them from the screenshot.

**Desktop (please complete the following information):**
 - OS/Distro: macOS
 - Version: 12.7.3

**Command line output**

I ran Vesktop from the cli by running ```open -a Vesktop.app```, but that did not show any logs from the app.

**Additional context**

You can exit fullscreen by reopening the app and that causes Vesktop to not be in fullscreen anymore, but the whole window is maximised rather than being the window size it was before going into fullscreen.

**Comment by lockieluke** [comment]
you need to go to the top

**Comment by HAHALOSAH** [comment]
![image](https://github.com/Vencord/Vesktop/assets/67280050/aa73afd2-f54b-46ee-8c5a-9159a79ca300)
cannot reproduce

**Comment by ssalggnikool** [comment]
@Imzxhir Can you provide more details on if you're able to exit fullscreen by moving your cursor on the top edge of the screen? Because when you do so the titlebar is supposed to appear like this
![image](https://github.com/Vencord/Vesktop/assets/97859147/2ff5767b-201f-4e06-abaa-b30daaa13e38)

**Comment by ssalggnikool** [comment]
Also, you can use `ctrl + cmd + f` to exit fullscreen.

**Comment by Imzxhir** [comment]
It seems that I cannot reproduce this bug anymore. I think I remember trying to go to the top to exit fullscreen, but this menu didn't appear when reporting the bug. Anyway, I think I will close this issue since it can't be reproduced and it has been fixed.
