### ISSUE TITLE
Cannot mark folders as read

### ISSUE THREAD

**Issue by Imzxhir** [Vencord/Vesktop#423]
**Describe the bug**

I noticed that you cannot mark folders as read on Vesktop, compared to the official Discord app where marking folders as read works.

**To Reproduce**

1. Make sure you have a channel that you have not read and is in a folder
2. Right click on that folder
3. You will notice that the 'Mark Folder As Read' button is greyed out when it should be clickable

**Expected behavior**

The 'Mark Folder As Read' button should be clickable.

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/98621617/84bb3592-63c6-4e7b-b182-2a105d8fc426)

**Desktop (please complete the following information):**
 - OS/Distro: macOS
 - Version: 12.7.3

**Command line output**

I ran Vesktop from the cli by running ```open -a Vesktop.app```, but that did not show any logs from the app.

**Additional context**

None

**Comment by Sqaaakoi** [comment]
have you tried making sure there is a guild to be marked as read?

also this probably has nothing to do with vesktop at all??

**Comment by Imzxhir** [comment]
Yes. The folder I want to mark as read actually has a server that I want to make as read but when I try to mark it, it does not work.

**Comment by Vendicated** [comment]
nothing to do with vesktop.
