### ISSUE TITLE
Flickering App Window

### ISSUE THREAD

**Issue by LexMinus** [Vencord/Vesktop#425]
**Describe the bug**

Screen flickering after opening a pop-up, as in full user profiles

This bug is happening after upgrading plasma from 5 to 6

The "flickering" is the user profile disappearing quickly then coming back

This issue seems to happen around 5 seconds after opening the full user profile pop-up

**To Reproduce**

Select user from server member list
Open the profile fully by selecting the profile image
Wait around five seconds
Elements disappear and reappear in quick succession

**Desktop (please complete the following information):**
 - OS/Distro: Garuda Linux
 - Desktop Environment (linux only): Plasma 6.0.1

**Comment by Vendicated** [comment]
try to disable hardware acceleration

**Comment by LexMinus** [comment]
Plasma 6 upgrade swapped my compositor to wayland instead of x11, runs perfectly on x11!
