### ISSUE TITLE
Crash upon opening a server

### ISSUE THREAD

**Issue by nicco1690** [Vencord/Vesktop#427]
**Describe the bug**

Upon opening the app and clicking on any server, Vesktop crashes, briefly shows the Discord crash screen, then the whole window goes white (except for notifications) and requires a reload to continue. This behavior continues no matter how many times you reload.

It is worth noting that the "white screen" portion sometimes doesn't happen, and it simply stays on the Discord error screen.

**To Reproduce**

1. Open Vesktop
2. Click on a server from the side panel
3. See error
4. (the following is optional) Click reload
5. Error appears immediately without user input

**Expected behavior**

I expected Vesktop to show me the last channel that I was in from the server that I clicked on.

**Screenshots**

![20240308_15h05m35s_grim](https://github.com/Vencord/Vesktop/assets/78063037/87d3ee17-0ca4-410e-9f4d-db8dcb273fb7)

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux
 - Desktop Environment (linux only): Sway
 - Version: `vesktop-git 1.5.0.r15.g777a0e83-1`, all other packages are latest from Pacman

**Command line output**

```
[52246:0308/145818.507768:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[52246:0308/145827.816843:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[52246:0308/145903.245606:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```
Note that these outputs are the only outputs, however they may be unrelated. No new logs appear when the error occurs.

**Additional context**

For some reason, even when on the same version as yesterday, when the expected behavior happened, the bug occurs.

**Comment by Vendicated** [comment]
provide error logs obtained via ctrl shift i

**Comment by nicco1690** [comment]
The log file can be found [here](https://github.com/Vencord/Vesktop/files/14542884/canary.discord.com-1709929614812.log)

**Comment by nicco1690** [comment]
Issue solved - not sure what actually fixed it but the crash no longer occurs.

**Comment by Vendicated** [comment]
because nookies already fixed it and you updated / have auto update enabled. it was a crash related to RoleColorEverywhere, because discord changed something about how their internals work.

https://github.com/Vendicated/Vencord/commit/992533245bc08ccaac258aaca803d362942dde74
