### ISSUE TITLE
@vencord/venmic@3.3.2 doesn't let you build with windows

### ISSUE THREAD

**Issue by verticalsync** [Vencord/Vesktop#437]
**Describe the bug**

Trying to link the package `@vencord/venmic@3.3.2` since typescript can't find module returns this

**To Reproduce**

1. Install packages
2. Run `npm link @vencord/venmic`
3. Receive error

**Expected behavior**

Build just fine for windows.

**Desktop:**
 - OS/Distro: Windows 11
 - Version: 23H2 22631.2506

**Command line output**

Running `npm link @vencord/venmic`

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @vencord/venmic@3.3.2: wanted {"os":"linux"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  linux
npm ERR! notsup Actual os: win32

npm ERR! A complete log of this run can be found in: C:\Users\nyx\AppData\Local\npm-cache\_logs\2024-03-12T08_37_50_464Z-debug-0.log
```

**Video**

There's another thing with line endings I guess as well.  
Video: https://streamable.com/olwk7n (too big file size for github)

**Comment by Vendicated** [comment]
this issue makes no sense. why are you trying to link it? simply don't.

also, we use pnpm, not npm.

**Comment by verticalsync** [comment]
> this issue makes no sense. why are you trying to link it? simply don't.
> 
> also, we use pnpm, not npm.

tests fail anyways

**Comment by Vendicated** [comment]
if you get errors with line endings, it means you configured your git or editor wrong. issue on your end.

tests will fail for the venmic file but just ignore it, it doesn't matter

**Comment by verticalsync** [comment]
> if you get errors with line endings, it means you configured your git or editor wrong. issue on your end.
> 
> tests will fail for the venmic file but just ignore it, it doesn't matter

Ran it in cmd, git not configured other than just being authorized, line endings give like 4000 errors in tests before u run lint:fix
