### ISSUE TITLE
Screen share on Wayland

### ISSUE THREAD

**Issue by ClaytonTDM** [Vencord/Vesktop#442]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to swotch from Xorg to Wayland to screenshare on Vesktop.
**Describe the solution you'd like**
Add screen share (and optionally audio support) using PipeWire if Wayland is detected.
**Describe alternatives you've considered**
I've considered WebCord, but it doesn't seem to work.
**Additional context**
Apps like OBS have integrated PipeWire support.

**Comment by ClaytonTDM** [comment]
Doesn't seem to work for me

**Comment by Sqaaakoi** [comment]
_do you have xdg desktop portal installed???_

also, what de/compositor are you usign

**Comment by ClaytonTDM** [comment]
not completely sure. i'm using wayland (experimental) on linux mint

**Comment by ClaytonTDM** [comment]
just checked, yes i do.

**Comment by Atemo-C** [comment]
> not completely sure. i'm using wayland (experimental) on linux mint

Wayland support on Linux Mint is still currently highly experimental and prone to breakage. Make sure to run a stable version of provided software before issuing such bug reports, and bugs related to Linux Mint itself should be reported to the Linux Mint project.
