### ISSUE TITLE
Scrollbar Arrows Remain Despite Gecko "scrollbar-width" Set to "thin"

### ISSUE THREAD

**Issue by D-Maxwell** [Vencord/Vesktop#449]
**Describe the bug**

I am glad #433 has been fixed, and quickly at that. Vesktop is now mostly usable, despite a lot of plugins not being compatible ; regardless, there is still one thing bugging me.

As it would seem, Vesktop has --long ? (I've been stuck on ~0.4.x for a long time somehow)-- shifted to Gecko for its renderer, and as such, it listens to Gecko properties. This is the case for any kind of customisation related to scrollbars.

For some quite troubling reason, setting the `scrollbar-width` property to `thin` --which works flawlessly on most other external Gecko based browsers-- does not get rid of the two tiny arrow indicators on each end of a scrollbar ; and instead decreases their size.

**To Reproduce**

Set `scrollbar-width` to `thin` on any scrollable element.

**Expected behavior**

As there is no property on Gecko related to those indicator elements in particular, I would like for the default behaviour to be consistent with that of other browsers' implementations.

Perhaps this is a bug in the embedded browser|renderer that Vesktop ships ?

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/98100481/7a89a963-71f3-4978-b326-308c779e8258)

**Desktop (please complete the following information):**
 - OS/Distro: Windows10
 - Version: 22H2

**Additional context**

**Comment by Vendicated** [comment]
vesktop uses electron aka chromium. not gecko

see #438

**Comment by D-Maxwell** [comment]
> vesktop uses electron aka chromium. not gecko
> 
> see #438

I apologise, as I hadn't realised those Gecko specific properties had just been added to Chromium. 
My bad.

**Comment by Vendicated** [comment]
no worries, it's a bit confusing that chrome added support for these properties after all the years of using the :-webkit-* pseudo elements to be fair :P
