### ISSUE TITLE
Cannot create bo with format= R_8 and usage=SCANOUT_CPU_READ_WRITE src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unkown or not supported format: 538982482

### ISSUE THREAD

**Issue by laycookie** [Vencord/Vesktop#450]
**Describe the bug**

Whenever starting Vesktop and connecting to a voice channel the console becomes covered in the following error. (It does not pop up once but instead it gets logged about every miliscond)
```
Cannot create bo with format= R_8 and usage=SCANOUT_CPU_READ_WRITE src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unkown or not supported format: 538982482
```

**To Reproduce**
Launch Vesktop trough the console with the command `vesktop`

**Expected behavior**
Have a clean console

**Screenshots**
![20240315_15h48m09s_grim](https://github.com/Vencord/Vesktop/assets/80195126/0e06be53-14e5-4b83-8c53-fec42254d132)

**Desktop (please complete the following information):**
 - OS/Distro: NixOS
 - Desktop Environment: Hyprland
 - Version: Not sure I just installed from with nix-os pkgs.

**Comment by Vendicated** [comment]
is there actually an issue or are you just annoyed with the console output?

**Comment by laycookie** [comment]
@Vendicated Ya I'm mostly annoyed with the output, however this might be a problem if some other error will pop up because it will just get carried away in the stream off those errors.

**Comment by Vendicated** [comment]
well that output is by electron/chromium. you can use something like grep to filter it out
