### ISSUE TITLE
Support for disabling auto-idle

### ISSUE THREAD

**Issue by ItsDrike** [Vencord/Vesktop#451]
**Is your feature request related to a problem? Please describe.**
After some time of not interacting with the vesktop window, my discord status automatically changes to "Idle". That's annoying because I sometimes want to be able to look at a message I just received, which means interacting with the client, but without giving away that I've actually looked at the message, by my status changing.

**Describe the solution you'd like**
It'd be great if there was a setting in vesktop to allow disabling the auto-idle feature.

**Describe alternatives you've considered**
I could of course just set my status to idle, and remain like that even while I'm active. However I don't like this solution. I simply prefer my status being "online".

**Comment by Vendicated** [comment]
just manually go idle or go invisible

**Comment by ItsDrike** [comment]
The whole point of this is to avoid that. But okay, I've made a plugin request for this instead: https://github.com/Vencord/plugin-requests/issues/199
