### ISSUE TITLE
Implement a search bar.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Vencord/Vesktop#454]
1.	#### **Is your feature request related to a problem? Please describe.**

	Finding specific configuration toggles can be incredibly difficult without prior knowledge of where they are.

	For instance, locating where the system autostart option was (for https://github.com/Vencord/Vesktop/issues/455#issue-2190649280) was unintuitive.
	
1.	#### **Describe the solution you'd like.**

	Add a search bar to Settings.
	
1.	#### **Describe alternatives you've considered.**

	Better yet, implement this in https://github.com/Vendicated/Vencord.git:

	> https://discord.com/channels/1015060230222131221/1026515880080842772/1218895628365729823
	
1.	#### **Additional context.**

	1.	> https://discord.com/channels/1015060230222131221/1026515880080842772/1218897155524268042
	1.	https://github.com/Vencord/Vesktop/issues?q=label%3Aenhancement+search returned 0 results of relevance.

**Comment by Vendicated** [comment]
i don't think this would make a lot of sense to have, unless it also could search discord's settings. but that's not feasible because we have no control over them and most of their pages are lazy loaded. we would have to force load those chunks and parse their code to figure out what options they have

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Vencord/Vesktop/issues/454#issuecomment-2002454775

Is that infeasibly difficult? You make a good point about the benefits of lazy loading, but we could only poll the entire settings content when the search bar is focussed. I think that's how some other services get the advantages of both.

**Comment by Vendicated** [comment]
well this is not an appropriate place for tracking this. perhaps it could be part of the BetterSettings plugin, https://github.com/Vencord/plugin-requests

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Vencord/Vesktop/issues/454#issuecomment-2067702123

@Vendicated, transferring to https://github.com/Vencord/plugin-requests/issues/new?assignees=&labels=&projects=&template=request.yml consequently.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Vencord/Vesktop/issues/454#issuecomment-2067786731

@Vendicated, transferred to https://github.com/Vencord/plugin-requests/issues/379#issue-2254730907.
