### ISSUE TITLE
How to configure RPC?

### ISSUE THREAD

**Issue by LarveyOfficial** [Vencord/Vesktop#456]
So far, I've found Vesktop an amazing alternative to the Discord client on Arch, especially since it supports screen sharing on Wayland.

My main problem I have found, is that games do not show up in RPC, only applications to natively support it (So far I've only gotten Cider to work with it). But whenever I launch a game on Steam, RPC does not pick it up.

 I was wondering if there is a way to configure it, similar to how regular discord does, where you can select a currently running executable to show in RPC.

**Comment by LarveyOfficial** [comment]
Its come to my attention that there is a difference between RPC and regular activities.

Is there a way to configure Vesktop to be able to display current activities, or does it only support RPC?

**Comment by LarveyOfficial** [comment]
I have found this: https://github.com/JustTemmie/steam-presence,

Has solved my issues.

**Comment by Abro61209** [comment]
Thanks for sharing. Works really well with vesktop (non-flatpak version). This is much cleaner anyway than me having to go into discord settings and rename all my games or disable all the compatibility wrappers that vanilla discord detects.
