### ISSUE TITLE
Changing the logo on Flathub

### ISSUE THREAD

**Issue by Loutheqt** [Vencord/Vesktop#459]
Hello, I would like the logo to be changed on Flathub/Flatpak.

The Linux and Windows logo are different, I don't mind them being different but I do mind the use of the rainbow colours which in current age represent a ideology I myself don't agree with.

I would like politics seperate and a different logo.

**Comment by AAGaming00** [comment]
cope

**Comment by Sqaaakoi** [comment]
cope

**Comment by Sqaaakoi** [comment]
> Hello, I would like the logo to be changed on Flathub/Flatpak.
> 
> The Linux and Windows logo are different, I don't mind them being different but I do mind the use of the rainbow colours which in current age represent a ideology I myself don't agree with.
> 
> I would like politics seperate and a different logo.

mods lobotomise this user wait they already did that themselves

**Comment by Vendicated** [comment]
this is some true snowflake behaviour 
![cope](https://github.com/Vencord/Vesktop/assets/45497981/a5713e2e-cbf8-4d0f-bd9b-516fe2499843)

**Comment by platonictf** [comment]
> Hello, I would like the logo to be changed on Flathub/Flatpak.
> 
> The Linux and Windows logo are different, I don't mind them being different but I do mind the use of the rainbow colours which in current age represent a ideology I myself don't agree with.
> 
> I would like politics seperate and a different logo.

can we kill them please

**Comment by AAGaming00** [comment]
mods crush his skull
