### ISSUE TITLE
Flatpak: Vencord stops accepting mouse inputs if you drag a photo or file into it

### ISSUE THREAD

**Issue by AmyRoxwell** [Vencord/Vesktop#462]
**Describe the bug**

Trying to drag a file into vencord will make any mouse inputs to stop working and the application will only accept keyboard inputs until you fully quit and open it again

**To Reproduce**

1. Drag any file into vencord
2. Try to click anything

**Expected behavior**

being able to drag the file into vencord without mouse inputs dropping completely 
**Screenshots**

**Desktop (please complete the following information):**
Distro: EndeavoursOS
DE: KDE
Version: Latest flatpak ([6e36381](https://github.com/Vendicated/Vencord/commit/6e36381))

**Command line output**

```
[amyroxwell@amyroxwell-b450mds3h ~]$ flatpak run dev.vencord.Vesktop
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:0319/130925.777246:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 13:09:26.034: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:09:26.034: Failed to load module "canberra-gtk-module"
[3:0319/130926.067852:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0319/130926.067889:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started

```

**Additional context**

None

**Comment by ikaikahub** [comment]
I noticed this same thing happened to me on both vesktop and brave while using ozone-platform-hint auto. It seems to be a chromium on wayland issue. Using the flag --ozone-platform-hint=x11 should make it use xwayland

**Comment by AmyRoxwell** [comment]
> --ozone-platform-hint=x11

I tried to use that flag, but sadly the program doesn't load and spits this error

```
[amyroxwell@amyroxwell-b450mds3h ~]$ flatpak run dev.vencord.Vesktop --ozone-platform-hint=x11
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:0320/003745.013391:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0320/003745.240095:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
[3:0320/003745.240108:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
/app/bin/startvesktop: line 14:     3 Segmentation fault      (core dumped) zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
```

**Comment by DAPOTTIS** [comment]
Having the same issue here, Endeavour OS + KDE as well, when Vesktop is forced to use Wayland rather than XWayland, I get the same issue of not being able to click anything after dragging in a file. Happens on both the flatpak and the native versions of the app, so it might be a KDE issue or Electron issue.

**Comment by Vendicated** [comment]
iirc you can't drag files from locations the flatpak doesn't have access to. you could try giving the vesktop flatpak full host access (for example via flatseal). it doesn't access any files it shouldn't anyway

in any case this issue is caused by some dependency or your desktop environment or whatever so this is a wontfix simply because we have no control. try isolating the issue and reporting to whatever is causing it (possibly chromium or electron or whatever)

**Comment by DAPOTTIS** [comment]
> iirc you can't drag files from locations the flatpak doesn't have access to. you could try giving the vesktop flatpak full host access (for example via flatseal). it doesn't access any files it shouldn't access anyway
> 
> in any case this issue is caused by some dependency or your desktop environment or whatever so this is a wontfix simply because we have no control. try isolating the issue and reporting to whatever is causing it (possibly chromium or electron or whatever)

Decided to try to narrow it down, seems like a KDE issue. Launched the flatpak version on Wayfire and it worked fine. Might have to report this to KDE

**Comment by AmyRoxwell** [comment]
> iirc you can't drag files from locations the flatpak doesn't have access to. you could try giving the vesktop flatpak full host access (for example via flatseal). it doesn't access any files it shouldn't access anyway
> 
> in any case this issue is caused by some dependency or your desktop environment or whatever so this is a wontfix simply because we have no control. try isolating the issue and reporting to whatever is causing it (possibly chromium or electron or whatever)

Try checking this outside of kde and it works just fine, so probably just a silly kde issue.

**Comment by FluffyPuppyKasey** [comment]
I know this issue has been closed as completed, and marked as upstream, BUT this also happens on KDE 6.1.3 running on Fedora 40, using the RPM version of Vesktop, forced to run in Wayland mode using `ELECTRON_OZONE_PLATFORM_HINT=auto` (which imo should've been default) to fix dragging and dropping, and copying and pasting just straight up not working. So I'm not exactly sure it's upstream, and rather something to do with Vesktop itself, seeing as other Electon apps work perfectly fine

**Comment by Vendicated** [comment]
it's indeed an upstream issue. there's nothing we can do. and there's a reason chromium doesn't enable the option by default

**Comment by FluffyPuppyKasey** [comment]
> @FluffyPuppyKasey THIS IS AN ELECTRON ISSUE UPDATE YOUR ELECTRON!!!!! 💥💥

Electron is up to date as far as I can tell

**Comment by FluffyPuppyKasey** [comment]
> it's indeed an upstream issue. there's nothing we can do. and there's a reason chromium doesn't enable the option by default

As far as I've been able to tell Chromium itself has enabled the flag for a few years at this point. Electron hasn't

**Comment by FluffyPuppyKasey** [comment]
> @FluffyPuppyKasey THIS IS AN ELECTRON ISSUE UPDATE YOUR ELECTRON!!!!! 💥💥

Just checked, it's a little behind (from March of this year)
