### ISSUE TITLE
Can't screenshare on Wayland

### ISSUE THREAD

**Issue by LarveyOfficial** [Vencord/Vesktop#465]
**Describe the bug**

No idea why, but recently screensharing has stopped working completely.
I tried running the in the console using this command: `vesktop %U --enable-features=UseOzonePlatform --ozone-platform=wayland` and I got the following output when screensharing: 
```
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-03-21 22:14:43.962] [venmic] [warning] [patchbay] (bind) failed to bind 121 ("PipeWire:Interface:Port"): no global 121
```
**To Reproduce**

1. Start Vesktop with either `vesktop %U`or `vesktop %U --enable-features=UseOzonePlatform --ozone-platform=wayland`
2. Start screenshare in a call
3. See infinite loading

**Expected behavior**

Screen sharing should work

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/39219859/efc81993-f103-4fc8-99d7-ab2cac9acdb2)

**Desktop (please complete the following information):**
 - OS/Distro: EndeavourOS Linux
 - Desktop Environment (linux only): KDE
 - Version:  plasma-desktop 6.0.2-4

**Command line output**

```
vesktop %U --enable-features=UseOzonePlatform --ozone-platform=wayland
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
Gtk-Message: 22:11:50.041: Failed to load module "appmenu-gtk-module"
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-03-21 22:12:27.548] [venmic] [info] [patchbay] (get) running venmic 3.3.2
[2024-03-21 22:12:27.552] [venmic] [info] [patchbay] (add_global) found metadata: 41
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-03-21 22:14:43.962] [venmic] [warning] [patchbay] (bind) failed to bind 121 ("PipeWire:Interface:Port"): no global 121
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
```

**Additional context**
This used to work, unsure what happened.

**Comment by Vendicated** [comment]
![image](https://github.com/Vencord/Vesktop/assets/45497981/7e8be4d7-ae6b-4e72-aa96-fd734965728d)

**Comment by LarveyOfficial** [comment]
@Vendicated Could you explain/help me with understanding why it suddenly does not work? I'd like to get it working again but can't seem to get it to work....

**Comment by Vendicated** [comment]
no because i have no idea since i dont use kde, sorry. but many kde users seem to be having this issue so it seems to be a change with kde. you have to debug it yourself

**Comment by LarveyOfficial** [comment]
nvm, rebooting fixed it

**Comment by stankovictab** [comment]
From my experience I can't start a stream while watching someone else's stream - exiting out of it and starting the stream up again fixes it
