### ISSUE TITLE
transparency only works if another window is behind vesktop

### ISSUE THREAD

**Issue by TheRsKing** [Vencord/Vesktop#466]
**Describe the bug**
when i turn on transparency in vesktop, it only works if another window is behind vesktop, otherwise it is displayed with strange bugs or it is simply black
[transparency-bug.webm](https://github.com/Vencord/Vesktop/assets/130909958/5467d7c9-34db-4927-8522-5af851f43ea7)

**To Reproduce**
1. switch to wayland
2. activate transparency with a matching theme
3. notice that the transparency only works in front of another window

**Expected behavior**
complete transparency 

**Desktop**
 - openSUSE Aeon
 - gnome
 - bug tested with gnome 45 and gnome 46
 - wayland
 - newest vesktop and vencord version

**Command line output**
nothing related to the problem

**Comment by TheRsKing** [comment]
do not want to disturb but could you give me an explanation for the closing

**Comment by Vendicated** [comment]
> please do not open issues with the following issues
> - purely graphical glitches

issue with electron / chromium / your desktop environment / your gpu / whatever on your end. vesktop has no control over these things

**Comment by TheRsKing** [comment]
as this is a problem with the flatpak i have now opened a new issue at the flatpak repo

**Comment by TheRsKing** [comment]
i was told that it is an upstream issue, i think this is not the case as the appimage works with the transparency

**Comment by lewisakura** [comment]
"you were already told upstream that this bug is out of our control", i.e. you were told here that we can't fix it because graphical issues are not within our control

if it happens with the flatpak only, then there is something wrong with your setup of flatpak, and you should start there by looking at your graphics drivers and the like, but we can't help you further
