### ISSUE TITLE
Spellcheck options and suggestions are infinitelly added to the context menu

### ISSUE THREAD

**Issue by braiam** [Vencord/Vesktop#468]
If I misspell something, right clicking should give me the common XCV options, suggestions, and the spellchecker. The spellchecker however are added ad infinitum. I can see the scrollbar still growing while the context menu is still open. It follows the same pattern: "spell suggestions", "Add _word_ to dictionary", "Enable Spellcheck". Those three groups repeat over and over while the context menu is open. If I hover the pointer over one, every instance of it gets highlighted. I can't click "Enable Spellcheck" to disable it. I couldn't find an option on configurations to do the same. If I bring up the context menu without clicking a word, "Enable Spellcheck" is the only thing that gets repeated.

1. Right click on the input chat box
2. See as your vertical scroll slider shrinks away

![image](https://github.com/Vencord/Vesktop/assets/1323412/67ed140a-4752-4430-b5c9-01fb28d8de5c)

 - Debian Testing XFCE

**Comment by Vendicated** [comment]
update vencord.

**Comment by braiam** [comment]
I can't update vencord, because it is the last version. https://github.com/Vencord/Vesktop/releases/download/v1.5.1/vesktop_1.5.1_amd64.deb

**Comment by Vendicated** [comment]
vencord != vesktop
