### ISSUE TITLE
Problem to download assests when using Appimage

### ISSUE THREAD

**Issue by LCRERGO** [Vencord/Vesktop#469]
**Describe the bug**

The Appimage version of Vesktop tries to fetch a few assets from the Vencord repository at the start of the application. What happens when I try to start the application is that it keeps the loading screen loading forever.

**To Reproduce**

Simply start the application using the appimage, or with the command `pnpm start` when using the git version.

**Expected behavior**

Should get into the login screen.

**Screenshots**

![Screenshot from 2024-03-26 20-05-58](https://github.com/Vencord/Vesktop/assets/36491033/ad0c7271-f37e-40ad-aed1-414b03d7b051)

**Desktop (please complete the following information):**
 - OS/Distro: [Debian GNU/Linux trixie/sid x86_64]
 - Desktop Environment (linux only): [gnome]
 - Version: [44.9]

**Command line output**

```
# cat log.txt

(node:107040) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/lcr/.config/vesktop/settings/quickCss.css'
(Use `vesktop.bin --trace-warnings ...` to show where the warning was created)
(node:107040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[107040:0326/193828.399012:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopRenderer.css.map. Gonna retry with backoff.
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopRenderer.js. Gonna retry with backoff.
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopRenderer.js.LEGAL.txt. Gonna retry with backoff.
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopRenderer.js.map. Gonna retry with backoff.
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopMain.js. Gonna retry with backoff.
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopMain.js.LEGAL.txt. Gonna retry with backoff.
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopPreload.js. Gonna retry with backoff.
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopMain.js.map. Gonna retry with backoff.
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopPreload.js.map. Gonna retry with backoff.
Failed to fetch https://github.com/Vendicated/Vencord/releases/download/devbuild/vencordDesktopRenderer.css. Gonna retry with backoff.
```

**Additional context**

I've tracked down the bug into the line 33 of the file `src/main/utils/http.ts`. But since I don't know TS very well I haven't been able to fix it.

**Comment by Vendicated** [comment]
issue on your end. your internet / system is having issues. specifically, it's running into `SEC_ERROR_UNKNOWN_PKCS11_ERROR`

you seem to be on debian unstable (trixie) so there's likely your issue.

`[107040:0326/193828.399012:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018`
