### ISSUE TITLE
[WIndows11] VeskTop (portable) doesn't open up

### ISSUE THREAD

**Issue by MrNamelessKnight** [Vencord/Vesktop#474]
The Vesktop doesn't open up, just only this error appears: 
![image](https://github.com/Vencord/Vesktop/assets/47192068/265f72fb-1289-45dc-9155-103e2e42c253)

and Vesktop appears on my task manager as background process:
![image](https://github.com/Vencord/Vesktop/assets/47192068/d60a40f5-9bc3-4ba5-a63e-e27840ff9c2e)
but not as hidden icon

**Comment by Vendicated** [comment]
is this fixed now?
