### ISSUE TITLE
Add auto cache cleaner

### ISSUE THREAD

**Issue by EndermanCo** [Vencord/Vesktop#476]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I am facing a series of problems in my Discord client, which can be solved by clearing the client cache.

**Describe the solution you'd like**
I think there should be an option that automatically clears the client cache if it is enabled.

**Describe alternatives you've considered**
nothing

**Additional context**
nothing

**Comment by Vendicated** [comment]
no. this is an awful solution for something that should be fixed the proper way instead

https://xyproblem.info
