### ISSUE TITLE
Krisp AI noise supression does not work

### ISSUE THREAD

**Issue by Semanual** [Vencord/Vesktop#479]
**Describe the bug**

Krisp AI noise suppression is not working properly

**To Reproduce**

1. Join a discord call (or test microphone at "voice and video" configurations)
2. Set krisp as your noise suppression option
3. Microphone is still as noisy as when it is disabled

**Expected behavior**

Noise suppression eliminates all noise (or at least most noise, at least the same as discord's original client)

**Desktop (please complete the following information):**
 - OS/Distro: Linux Mint
 - Desktop Environment: Cinnamon
 - Version: 21.3

**Command line output**
(Not sure if any of these is relevant for the case, but this was the entire output)
```
[3:0330/223723.944814:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
Gtk-Message: 22:37:24.156: Failed to load module "xapp-gtk3-module"
[3:0330/223724.199824:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[3:0330/223724.199848:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
```

**Comment by Nano-Ocelot** [comment]
I can't be sure when this started happening but it definitely used to work as expected but I noticed the past few weeks or more that it's not working.

**Comment by Vendicated** [comment]
this is most likely a stock discord issue, so there isn't anything we can do about it

**Comment by Semanual** [comment]
@Vendicated so, should I open this issue somewhere else? or there's just nothing no one can do about it anyway?

**Comment by Vendicated** [comment]
open vanilla discord in your browser and see if it works there. if it doesn't, it's a discord issue and there's nothing we can do

**Comment by Semanual** [comment]
yeah, in vanilla discord it works, I made sure that it did before opening this issue

**Comment by DozNaka** [comment]
Flatpak vesktop krisp noise supression also does not work but stock discord flatpak does.

**Comment by saddle196883** [comment]
On my machine, Krisp does not work on Vencord (installed via .rpm on Fedora 39) but works on stock Discord on the same machine.

**Comment by THEGOLDENPRO** [comment]
I can also reproduce this on 1.5.1. When I find the time I'll try and test a bunch of older versions.

**Comment by DozNaka** [comment]
I have noticed that Krisp noise suppression does not work on web discord on Firefox, same behavior as seen on Vesktop
it seems that it is a Discord issue

**Comment by rehashedsalt** [comment]
I'm starting to lean that way too. Discord Flatpak seems to initialize Krisp at application launchtime while Vesktop and Chromium both fail to initialize Krisp at VC join.

Plus some guys on Reddit complained their Discord desktop broke on Windows at about the same time this issue was filed.

**Comment by ILOVEPIE** [comment]
There's a signature check that the Krisp module does to verify discord has not been modified. I have a signature-scan based patch (meaning that it does the patch at runtime and is update-resistant) for this but might need some help with getting it working with electron better as it seems to make electron a bit unstable.

**Comment by Vendicated** [comment]
the web app loads krisp as wasm module, while the desktop uses a native node module for it. that's why I asked whether it works in web browser. whether it works on discord desktop is irrelevant, because vesktop also uses the wasm module. or rather, vesktop doesn't even handle krisp itself, it's just purely discord that does it

**Comment by ILOVEPIE** [comment]
> the web app loads krisp as wasm module, while the desktop uses a native node module for it. that's why I asked whether it works in web browser. whether it works on discord desktop is irrelevant, because vesktop also uses the wasm module, just like web. or rather, vesktop doesn't even handle krisp itself, it's just purely discord that does it

ah i thought they were referring to the desktop app.

**Comment by Vendicated** [comment]
discord's web krisp code is broken. there is nothing we can do except wait and pray they fix it soon

![image](https://github.com/Vencord/Vesktop/assets/45497981/bdc5a5e4-cf74-469d-b822-050bc6104cf9)
![image](https://github.com/Vencord/Vesktop/assets/45497981/7682deff-c3e0-4087-8c32-b2aea158d7be)

**Comment by Vendicated** [comment]
here's a plugin that fixes the error until discord fixes it themselves. untested cause i'm too lazy to test audio quality, idk if it actually works or not

```js
import { Devs } from "@utils/constants";
import definePlugin from "@utils/types";

export default definePlugin({
    name: "KrispFix",
    description: "description",
    authors: [Devs.Ven],
    required: true,

    patches: [{
        find: "KrispSDK:init",
        replacement: {
            match: /=exports;/,
            replace: "=arguments[1];"
        }
    }]
});
```

**Comment by Nano-Ocelot** [comment]
> here's a plugin that fixes the error until discord fixes it themselves. untested cause i'm too lazy to test audio quality, idk if it actually works or not
> 
> ```js
> import { Devs } from "@utils/constants";
> import definePlugin from "@utils/types";
> 
> export default definePlugin({
>     name: "KrispFix",
>     description: "description",
>     authors: [Devs.Ven],
>     required: true,
> 
>     patches: [{
>         find: "KrispSDK:init",
>         replacement: {
>             match: /=exports;/,
>             replace: "=arguments[1];"
>         }
>     }]
> });
> ```

Where do I put this? Where are the other plugins located? I can't seem to find the folder.

**Comment by Sqaaakoi** [comment]
> > here's a plugin that fixes the error until discord fixes it themselves. untested cause i'm too lazy to test audio quality, idk if it actually works or not
> > ```js
> > import { Devs } from "@utils/constants";
> > import definePlugin from "@utils/types";
> > 
> > export default definePlugin({
> >     name: "KrispFix",
> >     description: "description",
> >     authors: [Devs.Ven],
> >     required: true,
> > 
> >     patches: [{
> >         find: "KrispSDK:init",
> >         replacement: {
> >             match: /=exports;/,
> >             replace: "=arguments[1];"
> >         }
> >     }]
> > });
> > ```
> 
> Where do I put this? Where are the other plugins located? I can't seem to find the folder.

Follow https://github.com/Vendicated/Vencord/blob/main/docs/1_INSTALLING.md until you get to the `pnpm build` step

Add the file into `src/userplugins/` (you may have to create the folder)

Run `pnpm build`

Instead of using `pnpm inject` you should go to Vesktop Settings and change the folder to the dist folder created inside the directory after building

**Comment by Nano-Ocelot** [comment]
This appears to be fixed upstream at this point.

**Comment by x0rp01s0n** [comment]
broken again for me at least
