### ISSUE TITLE
[Chrome | Vencord Web] arRPC doesn't display

### ISSUE THREAD

**Issue by IntNinja** [Vencord/Vesktop#482]
arRPC doesn't display what i'm doing on vencord web(chrome)
i did enable the node server, it shows bridge connected but i don't see any activity on  my profile even if i open youtube and stuff

**Comment by IntNinja** [comment]
> Ensure your adblock isn't interfering. With uBlock Origin, you'll have to disable "Block Outside Intrusion to LAN" list.

![image](https://github.com/Vencord/Vesktop/assets/116146426/08b778ca-9ff2-4aa8-ab7e-5757e178f58a)
it's not blocking anything, nor i have any filter that's "Block Outside Intrusion to LAN"

**Comment by Vendicated** [comment]
vesktop has nothing to do with vencord web
