### ISSUE TITLE
Add non-nitro 5fps 1080p screensharing to avoid potential bans

### ISSUE THREAD

**Issue by notune** [Vencord/Vesktop#484]
**Is your feature request related to a problem? Please describe.**
I tried vesktop as it's being advertised as a lightweight discord client without having to worry about potential issues with discord's TOS. But then I noticed that by default, we can stream in higher resolution then 720p even if I am not having any nitro subscription. This could be easily detected by discord and I think this could lead to my account being banned. But I still want to stream my screen in 1080p with 5ps (I don't need more) just like in the official discord client.

**Describe the solution you'd like**
I would like the nitro streaming options to be disabled by default and a 5fps option for 1080p streaming.

**Describe alternatives you've considered**
Using the official discord client.

**Additional context**
-

**Comment by Vendicated** [comment]
there is no ban risk

**Comment by notune** [comment]
> there is no ban risk

How can you be so sure about that? I think this could easily be detected serverwise, I mean it's normally a paid feature after all. 

Also I think this would be really easy to implement. We just would need to add the 5 to the fps list and maybe do a UI adjustment.

**Comment by Vendicated** [comment]
if discord wanted to ban us, we'd all be gone immediately. doesn't matter if you use nitro screenshare or not. but they have no reason to do that, they'll just lose users

**Comment by Vendicated** [comment]
what's the point of 😕 reacting? i was simply stating how it is. yes, they could detect streaming with a quality you're not supposed to. but they could also just push code that detects vencord and other client mods. in fact, they already have such code. it detects betterdiscord, vencord, and a few other mods. but it is only used to disable error reporting for such devices and for nothing else

discord has nothing to gain and so much to lose by banning people who use mods. millions of people do. a large proportion of which are discord's most avid users, and thus much more likely to be a nitro subscriber. if they banned us, they would receive a lot of backlash and lose many active users

there is virtually no risk in streaming with higher resolutions than you normally can. and if you still are worried about it, you should probably not be using a mod in the first place

**Comment by notune** [comment]
Yeah you are absolutely right. My reaction was not meant to be provocative in any way. Sorry if it happened to be somewhat provocative for you. It was more of a reaction that I was not satisfied with the possibility of 5fps being disregarded completely. I mean in my opinion it would be a great option, even if it's hidden somewhere in the settings for rare users of 5fps like me. Just so that I would feel better not using any potential bandwidth that I am not paying for. I agree with you that the probability of being banned is low, but I think that using an option that is advertised for paying customers is a higher violation of the tos, then simply using another client just so we can get a faster and more privacy friendly experience.

**Comment by kaitlynkittyy** [comment]
> Yeah you are absolutely right. My reaction was not meant to be provocative in any way. Sorry if it happened to be somewhat provocative for you. It was more of a reaction that I was not satisfied with the possibility of 5fps being disregarded completely. I mean in my opinion it would be a great option, even if it's hidden somewhere in the settings for rare users of 5fps like me. Just so that I would feel better not using any potential bandwidth that I am not paying for. I agree with you that the probability of being banned is low, but I think that using an option that is advertised for paying customers is a higher violation of the tos, then simply using another client just so we can get a faster and more privacy friendly experience.

Even with that being something that could be added, the current implementation of the stream API is broken. The resolution isn't properly applied so no matter what, the stream matches the resolution of the monitor/application that it is capturing.

**Comment by notune** [comment]
> And on top of that yet again, the bandwidth is nothing to worry about as of right now. That same broken API limits it so much that streams don't even properly reach 10fps on most systems.

I see. Thanks for clarifying.
