### ISSUE TITLE
[LINUX] somehow exceeded the API rate limit? 

### ISSUE THREAD

**Issue by YoruNoKen** [Vencord/Vesktop#485]
**Describe the bug**

It first started with me not being able to view messages in servers/DMs. Tried restarting and it didn't fix so I decided to reinstall.
After I reinstalled it prompted me to login, and I can't log in. so I tried running it through the command line, and it says that I've been rate limited.
This bug only happens on Vesktop and not on the web version of Discord.

**To Reproduce**

I don't know how to reproduce, it just happened while I was doing something else.

**Expected behavior**

I should not be rate limited (didn't even know that could happen on a normal user.)

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/69751661/e0274490-7021-4738-ac5a-6ce33f87a40d)
![image](https://github.com/Vencord/Vesktop/assets/69751661/5b588555-d5f8-451a-9cc2-1b7205411ee6)

**Desktop:**
 - OS/Distro: [e.g. Windows / Fedora Linux / MacOs]
 - Desktop Environment (linux only): KDE Plasma6.0.2 X11
 - Version: [e.g. 22]

**Command line output**

```
yoru@ ~$ vesktop
Gtk-Message: 18:42:50.900: Failed to load module "appmenu-gtk-module"
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
AppUpdater: Failed to check for updates
 Error: Got non-OK response for https://api.github.com/repos/Vencord/Vesktop/releases/latest: 403 rate limit exceeded
{"message":"API rate limit exceeded for [IP ADRESS]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

    at yi (VCDMain:29:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ct (VCDMain:39:4326)
```

**Additional context**

I was doing nothing related to Discord while this happened.

**Comment by Vendicated** [comment]
you're rate limited from github, not discord. it doesn't matter just ignore it

**Comment by YoruNoKen** [comment]
> it doesn't matter just ignore it
That's cool, but I can't use the app.
I guess I have to wait about an hour? The docs say the rate limit for unauthorized requests is 60 per hour.
