### ISSUE TITLE
[Linux] Screensharing is Laggy when a game is open

### ISSUE THREAD

**Issue by skoody** [Vencord/Vesktop#487]
**Describe the bug**
when screensharing with a game open then the screensharing is lagging 

**To Reproduce**
1. open Vesktop
2. Start Screensharing
3. Open a Game

**Expected behavior**
that the screensharing is not laggy

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Distro: [Arch Linux x86_64]
 - Desktop Environment (linux only): [KDE x11]
 - Kernel Version: [6.8.2-zen2-1-zen]

**Comment by Luca99iscool1** [comment]
I also have this issue
OS/Distro [Arch Linux x86_64]
Desktop Envrioment: Hyprland
Kernel Version: 6.8.2-zen2-1-zen
