### ISSUE TITLE
Clarity on how/where Vesktop differs from Vencord

### ISSUE THREAD

**Issue by abraxas86** [Vencord/Vesktop#488]
**Is your feature request related to a problem? Please describe.**
I can't seem to find anywhere in the git that breaks down where or how Vesktop differs from differs from Vencord.  Is it Vencord with better Linux/Wayland support? No idea, that's the vibe I get but it's not made clear anywhere.

**Describe the solution you'd like**
Something in the Readme that makes it clear what this offers that Vencord doesn't.

**Describe alternatives you've considered**
I've checked Google and Reddit and can't seem to find anything that breaks down the difference.  Maybe I'm overlooking something?

**Comment by abraxas86** [comment]
I read over this a few times before making my post.  Nothing really answers the question of "why Vesktop?"

The first point is that vencord is pre-installed. To me, that says "you can skip the step of manually having to patch Discord with Vencord".

The second point states it's more lightweight and faster than Discord, but doesn't mention if it's also more lightweight and faster than if I were to just download Discord and then patch it with Vencord myself.

The third point is about Screensharing in Wayland, which I assume is broken if you patch Discord with Vencord?

The last point is that it offers better privacy over Discord, but no mention of if the level of privacy is also better than Discord after it has been patched by Vencord.


I guess reading between the lines, Vesktop is a completely custom build of the Discord binary, as opposed to a Discord binary that has had some extra stuff hacked in?

**Comment by kaitlynkittyy** [comment]
> I read over this a few times before making my post. Nothing really answers the question of "why Vesktop?"
> 
> The first point is that vencord is pre-installed. To me, that says "you can skip the step of manually having to patch Discord with Vencord".
> 
> The second point states it's more lightweight and faster than Discord, but doesn't mention if it's also more lightweight and faster than if I were to just download Discord and then patch it with Vencord myself.
> 
> The third point is about Screensharing in Wayland, which I assume is broken if you patch Discord with Vencord?
> 
> The last point is that it offers better privacy over Discord, but no mention of if the level of privacy is also better than Discord after it has been patched by Vencord.
> 
> I guess reading between the lines, Vesktop is a completely custom build of the Discord binary, as opposed to a Discord binary that has had some extra stuff hacked in?

That last sentence sums it up, but I can answer some questions. Patching the official Discord app with Vencord doesn't make it faster, it just adds features, so yes, vesktop is more lightweight and faster. Screensharing in Wayland is entirely broken on almost every Discord client I've tried, especially native. Above that, streaming with audio is entirely limited to vesktop, as Venmic is only supported by vesktop. Vesktop uses the actual desktop portals approach to resolve this. The privacy difference is the same as native Discord + Vencord, as both use Vencord's noTrack plugin. The only possible difference is that we know for a fact that vesktop doesn't track anything, as it's open source.

If there's anything I got wrong, please let me know, but this should be a good summary.

**Comment by abraxas86** [comment]
Good enough for me.  Thanks!
