### ISSUE TITLE
[Ubuntu] Randomly breaking up and disconnecting when on wifi.

### ISSUE THREAD

**Issue by Yeetcoeschann7** [Vencord/Vesktop#490]
**Describe the bug**

Vesktop has worked fine for me in the past, and still works fine if I use ethernet or my old Brostrend USB wifi adapter, but I recently got a new wifi card to use instead of the adapter, as it's much faster and I only have ethernet available to me around 70% of the time due to my housing situation. When I use vesktop and enter a call with this new wifi card, the other person in the call will constantly break up, wont hear me while I hear them, and eventually the call will disconnect, booting me out of the call into the discord loading screen.

**To Reproduce**

1. Open vesktop
2. Join a private call with a friend
3. Immediately the bottom left reads "RTC Connecting", then "DTLS Connecting" for a short time, then "Voice Connected".
4. You should now be connected in a call, but the other person breaks up or cuts out for several seconds at a time at random short intervals.
5. Eventually, usually after a minute or two, the bottom left says "Disconnected" instead of "Voice Connected". At this point, I'm sometimes still able to hear the other person in the call but they can't hear me.
6. After the disconnect, I will be reconnected after a few seconds or after a loading screen. Either way, the process either now repeats from step 3, or gets stuck on "DTLS Connecting" perpetually.

**Expected behavior**

1. Open vesktop
2. Join a private call with a friend
3. Immediately or after less than a second the bottom left reads "Voice Connected".
4. You should now be connected in a call, the other person should sound clear, and you should retain connection to the call until you intentionally hang up.

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/48604047/8c22678c-43ae-4402-be0b-4913fb1f02f5)
When I was testing it this time to get the command line output, I got this INCREASED API LATENCY message I'd never gotten before:
![image](https://github.com/Vencord/Vesktop/assets/48604047/d70af5a2-f968-4020-abe5-92d42ddcc045)

**Desktop (please complete the following information):**
 - OS/Distro: [Xubuntu]
 - Desktop Environment (linux only): [xfce]
 - Version: [23.10]

**Command line output**

```
~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:0407/162238.478650:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0407/162238.813727:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0407/162238.813796:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started

(vesktop.bin:3): libnotify-WARNING **: 16:24:33.592: Running in confined mode, using Portal notifications. Some features and hints won't be supported

```

**Additional context**

- I have no problems when using base discord or browser discord, but obviously I can't stream with audio.
- Discord-Screenaudio has the same issues described here
- My new [wifi card](https://www.amazon.com/dp/B07ZV2CJL2?psc=1&ref=ppx_yo2ov_dt_b_product_details) has no issues whatsoever on any apps, games, websites, etc. besides Vesktop and Discord-Screenaudio, and my connection is significantly faster than my old [adapter](https://www.amazon.com/BrosTrend-600Mbps-Wireless-Internet-AC2/dp/B01GC8XH0S/ref=sr_1_8?crid=1Z09FYF9O9QTP&dib=eyJ2IjoiMSJ9.5TdnYMoV0sd8i72jyY0MgtLJ98f3Xf7_kcrso5MAAVXVpNUqKAWZIaaU1R7iYUjvNbWWFNdMGxBoK8JHjfI6tqDjTitQb1aEK7F7sD3oWaEHtMmNFZtCNFd7S-GDtAPEfssDyatxynUgFh4YxfGjh2J2_6765NObWxssr4YjT7akGo9XN7UcqB0nJXlZshbs60zlZBF6PeJz4WTjKsMtVcGyOwRWa2PMRCIz80vjQ2I.ppfoY-jVZylyly3SP_yX5KCYibj4k0k4MK_DaZ09wHs&dib_tag=se&keywords=brostrend+adapter&qid=1712522283&sprefix=brostrend+adapte%2Caps%2C100&sr=8-8).
- Vesktop and Vencord are fully updated to the newest versions
- I have no plugins or themes enabled except the plugins enabled by default.

Network info in case it helps(currently had my wifi on and ethernet unplugged):
```
Network:
~$ inxi -Nnz
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi
  IF: wlo1 state: up mac: <filter>
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: enp34s0 state: down mac: <filter>
  IF-ID-1: ham0 state: unknown speed: 10000 Mbps duplex: full mac: <filter>
```

I apologize if I've anything isn't formatted correctly or has already been answered, as I don't have to submit github issues frequently. If you need more info let me know!

**Comment by Vendicated** [comment]
sorry but i dont think there is anything we can do for you. this is an issue with either your internet / network stack, or some dependency, or even discord itself

stuff like this is very much out of our control

my best advice is try reinstalling vesktop

**Comment by Yeetcoeschann7** [comment]
> sorry but i dont think there is anything we can do for you. this is an issue with either your internet / network stack, or some dependency, or even discord itself
> 
> stuff like this is very much out of our control
> 
> my best advice is try reinstalling vesktop

I forgot to put it on the initial post, but I have already tried reinstalling Vesktop multiple times from different sources to no avail. I also mentioned that the exact same issue happens with Discord-Screnaudio, but also that everything works fine with base Discord. So I assume the problem must come from something that Vesktop and Discord-Screenaudio have in common, but stock Discord doesn't. Hopefully this helps.
