### ISSUE TITLE
Vesktop crashing when screensharing.

### ISSUE THREAD

**Issue by LMS5413** [Vencord/Vesktop#493]
**Describe the bug**

Discord crashes when I try to click on screenshare, specifically when reading audio drivers.

**To Reproduce**

**Expected behavior**

Read all drivers.

**Screenshots**

https://github.com/Vencord/Vesktop/assets/58144443/9188cd4c-4cac-4462-9c22-ebbaf3320ac4

**Desktop (please complete the following information):**
 - OS/Distro: Linux Mint
 - Desktop Environment (linux only): Cinnamon
 - Version: 22.04

**Command line output**

```
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[Vencord] Installed React Developer Tools
(node:7187) Extens

ionLoadWarning: Warnings loading extension at /home/lms5413/.config/vesktop/ExtensionCache/fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

(Use `vesktop --trace-warnings ...` to show where the warning was created)
[2024-04-09 13:16:37.199] [venmic] [info] [patchbay] (get) running venmic 3.3.2
```

**Comment by Vendicated** [comment]
dupe of #471, https://github.com/Vencord/venmic/issues/18
