### ISSUE TITLE
exiting from vesktop displays an error

### ISSUE THREAD

**Issue by hhoneeyy** [Vencord/Vesktop#494]
**To Reproduce**

1. Go to the vesktop icon in the arrow tray thing
2. Right click on vesktop
3. Press exit

**Expected behavior**
Error shows with 1/5 chance of popping up

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/86309103/1569d9c5-964d-4c32-a6a7-6eadc097af7e)

**Desktop (please complete the following information):**
 - OS/Distro: Windows 11
 - Version: 23H2

**Comment by Vendicated** [comment]
cant repro

**Comment by hhoneeyy** [comment]
> cant reproduce

idk what should i do

**Comment by Vendicated** [comment]
does this still happen on the latest version? if yes, please provide more info, especially command line output of vesktop

**Comment by hhoneeyy** [comment]
> does this still happen on the latest version? if yes, please provide more info, especially command line output of vesktop

hasn't happened for a long time now, thanks anyway.

**Comment by lewisakura** [comment]
please provide command line logs (run vesktop from terminal) and more information, like v asked you before

**Comment by hhoneeyy** [comment]
> please provide command line logs (run vesktop from terminal) and more information, like v asked you before

not sure how to do that

**Comment by lewisakura** [comment]
since you're on windows:
- open `cmd.exe`
- drag and drop the vesktop shortcut into the window
- run that
- copy and paste the output when you recreate the error

**Comment by hhoneeyy** [comment]
> since you're on windows:
> 
>     * open `cmd.exe`
> 
>     * drag and drop the vesktop shortcut into the window
> 
>     * run that
> 
>     * copy and paste the output when you recreate the error

but the error happens randomly, do i have to keep doing this until it does?

**Comment by lewisakura** [comment]
unfortunately, yes. you can clear the console by running `cls` after each attempt

**Comment by hhoneeyy** [comment]
> unfortunately, yes. you can clear the console by running `cls` after each attempt

damn, alr thanks

**Comment by hhoneeyy** [comment]
finally happened 
![image](https://github.com/user-attachments/assets/93fdfc71-dead-4e86-90ba-c888e2f5a78e)

**Comment by hhoneeyy** [comment]
gave up and installed discord.

**Comment by Vendicated** [comment]
it might be arrpc and could happen if there is a presence update the moment you close discord
