### ISSUE TITLE
uninstalling vesktop

### ISSUE THREAD

**Issue by szentigrad3** [Vencord/Vesktop#496]
**Describe the bug**

when i uninstall vesktop the screenshare portal stays active on normal discord

**To Reproduce**

uninstall and screenshare still installed

**Expected behavior**

normal discord sharing window

**Screenshots**

![Screenshot_20240411_213622](https://github.com/Vencord/Vesktop/assets/5462780/571d8a47-2b0e-468d-afcb-e34bf682fc65)

**Desktop (please complete the following information):**
 - OS/Distro: Linux
 - Desktop Environment (linux only): kde

**Comment by Vendicated** [comment]
?
