### ISSUE TITLE
Context menu is inconsistent with the desktop version

### ISSUE THREAD

**Issue by SandeMC** [Vencord/Vesktop#498]
Context menu on desktop:
![image](https://github.com/Vencord/Vesktop/assets/70141395/22c9d6f6-a72a-4066-b256-463f5af0faee)
Context menu on vesktop:
![image](https://github.com/Vencord/Vesktop/assets/70141395/2e7015ce-cd32-4b48-8151-88b6f0a0f7b8)

(literally unusable i want paste on the bottom)

**Comment by Curve** [comment]
Is the Context Menu also different on Web?

**Comment by SandeMC** [comment]
it pops up browser's native context menu in browser for me

**Comment by Vendicated** [comment]
fixed via https://github.com/Vencord/Vesktop/commit/f232cfc3c81e42fc054ca3f3fdd5a65166fc7692

![image](https://github.com/Vencord/Vesktop/assets/45497981/bffcc86b-8602-45ce-b585-eaf964a2d186)

**Comment by SandeMC** [comment]
based
