### ISSUE TITLE
Venmic fails to retrieve audio sources despite me running pipewire (Flatpak)

### ISSUE THREAD

**Issue by atlrvrse** [Vencord/Vesktop#500]
**Describe the bug**
Venmic fails to start despite me running pipewire

**To Reproduce**
Go to a voice channel
Open the screenshare menu

**Expected behavior**
Screenaudio working as normal

**Screenshots**
![2024-04-12T14:46:40,008419641-04:00](https://github.com/Vencord/Vesktop/assets/82827754/f2ef89b0-db3d-42c4-8ae2-6afafb17c6b5)

**Desktop (please complete the following information):**
 - OS/Distro: Void Linux
 - Desktop Environment: Sway

**Command line output**

```
[3:0412/143754.250214:ERROR:shared_x_display.cc(39)] Unable to open display
'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-04-12 14:37:56.467] [venmic] [error] could not create core or registry
Failed to initialise venmic. Make sure you're using pipewire Error: Failed to create patchbay instance
    at Ga (VCDMain:31:4930)
    at VCDMain:31:5259
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78183)
    at WebContents.emit (node:events:514:28)
```

**Comment by Curve** [comment]
Please post with debug logs enabled, see: https://github.com/Vencord/venmic?tab=readme-ov-file#-debugging

**Comment by Curve** [comment]
> [2024-04-12 14:37:56.467] [venmic] [error] could not create core or registry

This is a pretty bad sign, not sure what happens here

**Comment by atlrvrse** [comment]
> Please post with debug logs enabled, see: https://github.com/Vencord/venmic?tab=readme-ov-file#-debugging
```
[3:0412/150123.133389:ERROR:shared_x_display.cc(39)] Unable to open display
'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-04-12 15:01:24.330] [venmic] [debug] [patchbay] (has_pipewire) pulse-server is "pulseaudio (on pipewire 1.0.3)"
[2024-04-12 15:01:24.333] [venmic] [error] could not create core or registry
Failed to initialise venmic. Make sure you're using pipewire Error: Failed to create patchbay instance
    at Ga (VCDMain:31:4930)
    at VCDMain:31:5259
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78183)
    at WebContents.emit (node:events:514:28)
```

**Comment by Curve** [comment]
Ah shoot this might require a Rohrkabel debug build to get proper info.

I'll take a look when I'm back home ^^

**Comment by atlrvrse** [comment]
Venmic works on the appimage

**Comment by Curve** [comment]
> Venmic works on the appimage, maybe it's an issue with the flatpak?

Interesting, maybe some sort of permission issue? Have you allowed access to the host audio to the Flatpak? (Should happen automatically unless tampered with through flat-seal or similar)

**Comment by atlrvrse** [comment]
> > Venmic works on the appimage, maybe it's an issue with the flatpak?
> 
> Interesting, maybe some sort of permission issue? Have you allowed access to the host audio system to the Flatpak? (Should happen automatically unless tampered with through flat-seal or similar)

![2024-04-12T16:28:55,545552426-04:00](https://github.com/Vencord/Vesktop/assets/82827754/89c12f4c-0e89-45ac-90b3-df595b4a5367)

**Comment by Curve** [comment]
The creation fails either [here](https://github.com/Curve/rohrkabel/blob/master/src%2Fcore.cpp#L171) or [here](https://github.com/Curve/rohrkabel/blob/master/src%2Fregistry.cpp#L55) so it's almost certainly not a venmic / rohrkabel issue.

Especially when it works in the AppImage, it seems like a Flatpak issue, I'm not too familiar with the Flatpak, maybe someone more intimate with it can help out?

**Comment by atlrvrse** [comment]
hey i

**Comment by dclipca** [comment]
I had to actually install `pipewire-pulse`.

To enable Pipewire with PulseAudio support on Linux Mint, you need to install Pipewire and configure it to handle audio instead of the default PulseAudio. Here’s a step-by-step guide on how to do it:

Update Your System: Before starting, ensure your system is up-to-date.
```
sudo apt update
sudo apt upgrade
Install Pipewire: You need to install Pipewire and the PulseAudio compatibility layer.
```
```
sudo apt install pipewire pipewire-pulse pipewire-audio-client-libraries
```
Disable PulseAudio: To prevent conflicts, disable PulseAudio from starting automatically.
```
systemctl --user mask pulseaudio
systemctl --user stop pulseaudio.socket
systemctl --user stop pulseaudio.service
```
Enable Pipewire: You need to enable the Pipewire media session and the Pipewire PulseAudio server.
```
systemctl --user enable pipewire pipewire-pulse
systemctl --user start pipewire pipewire-pulse
```
Check the Status: To verify that Pipewire is running, you can check its status.
```
systemctl --user status pipewire pipewire-pulse
```
Test Audio Output: Ensure that your audio is functioning correctly. You can test this by playing audio through any media player or using command-line tools like aplay or paplay.
Reboot (Optional): While not always necessary, rebooting can ensure all changes are correctly applied and that Pipewire starts correctly on boot.

**Comment by apprehensions** [comment]
As i run a custom linux system with no elogind, this is what i had to do:
`
flatpak run --env=XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR --filesystem=$XDG_RUNTIME_DIR dev.vencord.Vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland
`

**Comment by sequencerr** [comment]
https://github.com/Vencord/Vesktop/issues/500#issuecomment-2094367152

This actually helped me and resolved for both appimage and flatpak installations. Can flatpak recipe be possibly changed to fix host somehow? Or leave notices in this repository about sound server? Because I have PulseAudio on Debian by default. It took some time to research and reading logs like 
```js
[2025-01-08 22:14:51.456] [venmic] [warning] [patchbay] (get) pipewire was not detected as main audio server
[2025-01-08 22:14:51.458] [venmic] [error] could not create core or registry
Failed to instantiate venmic Error: Failed to create patchbay instance
    at oo (VCDMain:15:5589)
    at VCDMain:15:5991
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87037)
    at WebContents.emit (node:events:518:28)
Error during screenshare picker Aborted
```

```js
[2025-01-08 22:29:20.058] [venmic] [warning] [patchbay] (get) pipewire was not detected as main audio server
[W][13952.374514] pw.conf      | [          conf.c:  939 try_load_conf()] can't load config client.conf: No such file or directory
[E][13952.374554] pw.conf      | [          conf.c:  963 pw_conf_load_conf_for_context()] can't load default config client.conf: No such file or directory
[2025-01-08 22:29:20.059] [venmic] [error] could not create core or registry
Failed to instantiate venmic Error: Failed to create patchbay instance
    at oo (VCDMain:15:5589)
    at VCDMain:15:5991
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87037)
    at WebContents.emit (node:events:518:28)
```
while in app there just empty dropdown (zero select options)
