### ISSUE TITLE
I have an idea for the discord game overlay that may make it possible. 

### ISSUE THREAD

**Issue by Ermageeerd** [Vencord/Vesktop#502]
Have a title barless and frameless electron window that would check for user set games/apps, and if it detects one,  start acting like the game overlay! otherwise, show nothing but a transparent png.

**Comment by AAGaming00** [comment]
better idea would probably be a gamescope overlay but i think it's better that another app handle this and vesktop just enables the OVERLAY rpc event

**Comment by Grafaffel** [comment]
Duplicate of https://github.com/Vencord/Vesktop/issues/444

**Comment by Ermageeerd** [comment]
> Duplicate of #444

Oh, I'll close this then since I didn't see that one!
