### ISSUE TITLE
[Linux] Audio source problem

### ISSUE THREAD

**Issue by end3r-man** [Vencord/Vesktop#503]
**Describe the bug**

not getting pipewire audio source but when streaming its getting audio source

**To Reproduce**

1. open vesktop
2. join a channel

**Expected behavior**

getting audio source from pipewire just how the streaming window get or add a option in voice setting to pick audio source

**Desktop (please complete the following information):**
 - OS/Distro: Arch linux
 - Desktop Environment: Sway
 - Version: 2024.04.01

**Comment by Curve** [comment]
I'm not sure what you mean, can you please elaborate further?

**Comment by end3r-man** [comment]
while im just listing in a channel my input is not detected but when im streaming my screen its get audio source, also that screen share selection window have a option to select audio source, but settings > voice & video > input selecting is disabled or in my case

**Comment by end3r-man** [comment]
https://github.com/Vencord/Vesktop/assets/138782482/97bab075-f9a9-414c-a22a-d8a01fe477ad

**Comment by Curve** [comment]
The audio selected when starting the screenshare is audio that will be shared alongside the stream and is not intended to be used as a microphone.

**Comment by end3r-man** [comment]
check the video

**Comment by Curve** [comment]
> check the video

I did, please re-read my message

**Comment by end3r-man** [comment]
> The audio selected when starting the screenshare is audio that will be shared alongside the stream and is not intended to be used as a microphone.

yep thats correct but its not getting my mic input

**Comment by Curve** [comment]
> > The audio selected when starting the screenshare is audio that will be shared alongside the stream and is not intended to be used as a microphone.
> 
> yep thats correct but its not getting my mic input

You don't have a microphone. Scrcpy is an application you're sharing audio from - not an actual microphone

**Comment by end3r-man** [comment]
do have a mic

**Comment by Curve** [comment]
> do have a mic

What is the output of `pw-cli ls Device`?

**Comment by end3r-man** [comment]
pw-cli ls Device
	id 46, type PipeWire:Interface:Device/3
 		object.serial = "46"
 		factory.id = "14"
 		client.id = "45"
 		device.api = "alsa"
 		device.description = "Raven/Raven2/Fenghuang HDMI/DP Audio Controller (PRIME B450M-A Motherboard)"
 		device.name = "alsa_card.pci-0000_07_00.1"
 		device.nick = "HD-Audio Generic"
 		media.class = "Audio/Device"
	id 47, type PipeWire:Interface:Device/3
 		object.serial = "47"
 		factory.id = "14"
 		client.id = "45"
 		device.api = "alsa"
 		device.description = "Family 17h/19h HD Audio Controller (PRIME B450M-A Motherboard)"
 		device.name = "alsa_card.pci-0000_07_00.6"
 		device.nick = "HD-Audio Generic"
 		media.class = "Audio/Device"

**Comment by Curve** [comment]
And what is the output of `pw-cli ls Node`?

**Comment by end3r-man** [comment]
id 28, type PipeWire:Interface:Node/3
 		object.serial = "28"
 		factory.id = "10"
 		priority.driver = "20000"
 		node.name = "Dummy-Driver"
	id 29, type PipeWire:Interface:Node/3
 		object.serial = "29"
 		factory.id = "10"
 		priority.driver = "19000"
 		node.name = "Freewheel-Driver"
	id 32, type PipeWire:Interface:Node/3
 		object.serial = "54"
 		factory.id = "13"
 		client.id = "45"
 		node.description = "BLE MIDI 1"
 		node.name = "bluez_midi.server"
 		media.class = "Midi/Bridge"
	id 48, type PipeWire:Interface:Node/3
 		object.serial = "48"
 		factory.id = "10"
 		client.id = "45"
 		priority.session = "100"
 		priority.driver = "1"
 		node.name = "Midi-Bridge"
 		media.class = "Midi/Bridge"
	id 51, type PipeWire:Interface:Node/3
 		object.serial = "59"
 		object.path = "alsa:pcm:1:front:1:capture"
 		factory.id = "18"
 		client.id = "45"
 		device.id = "47"
 		priority.session = "2009"
 		priority.driver = "2009"
 		node.description = "Family 17h/19h HD Audio Controller (PRIME B450M-A Motherboard) Analog Stereo"
 		node.name = "alsa_input.pci-0000_07_00.6.analog-stereo.2"
 		node.nick = "ALC887-VD Analog"
 		media.class = "Audio/Source"
	id 52, type PipeWire:Interface:Node/3
 		object.serial = "58"
 		object.path = "alsa:pcm:1:front:1:playback"
 		factory.id = "18"
 		client.id = "45"
 		device.id = "47"
 		priority.session = "1009"
 		priority.driver = "1009"
 		node.description = "Family 17h/19h HD Audio Controller (PRIME B450M-A Motherboard) Analog Stereo"
 		node.name = "alsa_output.pci-0000_07_00.6.analog-stereo"
 		node.nick = "ALC887-VD Analog"
 		media.class = "Audio/Sink"
	id 65, type PipeWire:Interface:Node/3
 		object.serial = "1977"
 		factory.id = "6"
 		client.id = "92"
 		client.api = "pipewire-pulse"
 		application.name = "Chromium input"
 		node.name = "Chromium input"
 		media.class = "Stream/Input/Audio"
	id 66, type PipeWire:Interface:Node/3
 		object.serial = "1756"
 		client.id = "101"
 		client.api = "jack"
 		node.description = "ray-patch_to_osc"
 		node.name = "ray-patch_to_osc"
 		media.type = "Audio"
 		media.category = "Duplex"
 		media.role = "DSP"
	id 70, type PipeWire:Interface:Node/3
 		object.serial = "2006"
 		client.id = "128"
 		node.name = "electron"
 		media.class = "Stream/Input/Video"
	id 82, type PipeWire:Interface:Node/3
 		object.serial = "2003"
 		client.id = "57"
 		node.name = "xdg-desktop-portal-wlr"
 		media.class = "Video/Source"
	id 86, type PipeWire:Interface:Node/3
 		object.serial = "1990"
 		factory.id = "6"
 		client.id = "92"
 		client.api = "pipewire-pulse"
 		application.name = "Chromium input"
 		node.name = "Chromium input"
 		media.class = "Stream/Input/Audio"
	id 98, type PipeWire:Interface:Node/3
 		object.serial = "1815"
 		factory.id = "6"
 		client.id = "138"
 		client.api = "pipewire-pulse"
 		application.name = "scrcpy"
 		node.name = "scrcpy"
 		media.class = "Stream/Output/Audio"
	id 131, type PipeWire:Interface:Node/3
 		object.serial = "1964"
 		factory.id = "18"
 		client.id = "83"
 		node.name = "vencord-screen-share"
 		media.class = "Audio/Source/Virtual"
	id 135, type PipeWire:Interface:Node/3
 		object.serial = "1998"
 		factory.id = "6"
 		client.id = "113"
 		client.api = "pipewire-pulse"
 		application.name = "Chromium"
 		node.name = "Chromium"
 		media.class = "Stream/Output/Audio"

**Comment by Curve** [comment]
Interesting, this should be detected as a microphone: `Family 17h/19h HD Audio Controller (PRIME B450M-A Motherboard) Analog Stereo`, it not showing up seems to be either a Discord or Electron issue though

**Comment by end3r-man** [comment]
> Interesting, this should be detected as a microphone: `Family 17h/19h HD Audio Controller (PRIME B450M-A Motherboard) Analog Stereo`, it not showing up seems to be either a Discord or Electron issue though

so its a bug or something a issue right??

**Comment by PolisanTheEasyNick** [comment]
What's the output of `pw-cli info 51`?

**Comment by end3r-man** [comment]
id: 51
	permissions: rwxm-
	type: PipeWire:Interface:Node/3
*	input ports: 0/0
*	output ports: 2/65
*	state: "running"
*	properties:
*		alsa.card = "1"
*		alsa.card_name = "HD-Audio Generic"
*		alsa.class = "generic"
*		alsa.device = "0"
*		alsa.driver_name = "snd_hda_intel"
*		alsa.id = "ALC887-VD Analog"
*		alsa.long_card_name = "HD-Audio Generic at 0xfcc80000 irq 63"
*		alsa.name = "ALC887-VD Analog"
*		alsa.resolution_bits = "16"
*		alsa.subclass = "generic-mix"
*		alsa.subdevice = "0"
*		alsa.subdevice_name = "subdevice #0"
*		api.alsa.card.longname = "HD-Audio Generic at 0xfcc80000 irq 63"
*		api.alsa.card.name = "HD-Audio Generic"
*		api.alsa.path = "front:1"
*		api.alsa.pcm.card = "1"
*		api.alsa.pcm.stream = "capture"
*		audio.channels = "2"
*		audio.position = "FL,FR"
*		card.profile.device = "0"
*		device.api = "alsa"
*		device.class = "sound"
*		device.id = "47"
*		device.profile.description = "Analog Stereo"
*		device.profile.name = "analog-stereo"
*		device.routes = "3"
*		factory.name = "api.alsa.pcm.source"
*		media.class = "Audio/Source"
*		node.description = "Family 17h/19h HD Audio Controller (PRIME B450M-A Motherboard) Analog Stereo"
*		node.name = "alsa_input.pci-0000_07_00.6.analog-stereo.2"
*		node.nick = "ALC887-VD Analog"
*		node.pause-on-idle = "false"
*		object.path = "alsa:pcm:1:front:1:capture"
*		priority.driver = "2009"
*		priority.session = "2009"
*		factory.id = "18"
*		clock.quantum-limit = "8192"
*		client.id = "45"
*		node.driver = "true"
*		factory.mode = "split"
*		audio.adapt.follower = ""
*		library.name = "audioconvert/libspa-audioconvert"
*		object.id = "51"
*		object.serial = "59"
*		node.max-latency = "16384/48000"
*		api.alsa.period-size = "1024"
*		api.alsa.period-num = "32"
*		api.alsa.headroom = "32"
*	params: (9)
*	  3 (Spa:Enum:ParamId:EnumFormat) r-
*	  1 (Spa:Enum:ParamId:PropInfo) r-
*	  2 (Spa:Enum:ParamId:Props) rw
*	  4 (Spa:Enum:ParamId:Format) rw
*	  10 (Spa:Enum:ParamId:EnumPortConfig) r-
*	  11 (Spa:Enum:ParamId:PortConfig) rw
*	  15 (Spa:Enum:ParamId:Latency) rw
*	  16 (Spa:Enum:ParamId:ProcessLatency) rw
*	  17 (Spa:Enum:ParamId:Tag) rw

**Comment by Curve** [comment]
This looks like either an audio server problem (some sort of issue with pipewire-pulse?) or an electron problem to me

**Comment by Curve** [comment]
https://github.com/Vencord/Vesktop/issues/440#issuecomment-2024432873 seems related

**Comment by end3r-man** [comment]
> [#440 (comment)](https://github.com/Vencord/Vesktop/issues/440#issuecomment-2024432873) seems related

yep the same

**Comment by Curve** [comment]
> > [#440 (comment)](https://github.com/Vencord/Vesktop/issues/440#issuecomment-2024432873) seems related
> 
> yep the same

I'll close this in favor of #440 then :)

The "workaround" described here will no longer work with #509 merged, as selecting venmic as a microphone should have never been possible in the first place

**Comment by VisigothiCheeta** [comment]
Did you ever manage to fix this? I'm having practically the same issue. I use my old phone as a mic in my pc.

It works on regular Discord because I can send the scrcpy output into a playback device whose volume is set to 0 (my display) and then use the monitor of that device as an input device in Discord.

It does not work in Vesktop as the feature of using monitors as input in voice chat is apparently purposefully disabled.

**Comment by end3r-man** [comment]
> Did you ever manage to fix this? I'm having practically the same issue. I use my old phone as a mic in my pc.
> 
> It works on regular Discord because I can send the scrcpy output into a playback device whose volume is set to 0 (my display) and then use the monitor of that device as an input device in Discord.
> 
> It does not work in Vesktop as the feature of using monitors as input in voice chat is apparently purposefully disabled.

nope
