### ISSUE TITLE
[FEATURE] Ability to change app Icon

### ISSUE THREAD

**Issue by ItxWeird** [Vencord/Vesktop#505]
**Is your feature request related to a problem? Please describe.**
No. Basically I just want to be able to change the Vesktop logo that appears in the taskbar and tray

**Describe the solution you'd like**
Anyways the point is I wish I could change the vesktop logo to something else wether it be the discord logo or some silly little meme

**Describe alternatives you've considered**
Not too sure? I don't see and alternative way of doing this unless vesktop changes the default icon which would just be stupid

**Additional context**
If it wasn't clear what I was talking about, just look at the following screenshots but if they were vesktop, that is what I wish could be implemented
![image](https://github.com/Vencord/Vesktop/assets/62679764/e10bafa9-aa62-40ef-83ae-64ffedbb3159)
![image](https://github.com/Vencord/Vesktop/assets/62679764/654a58ac-9486-4b86-9e5b-9a797fdcf06e)

**Comment by Semanual** [comment]
You actually can do it yourself (at least for the taskbar part), if in windows you can create a link, go to properties, change the link icon and fix the link in the taskbar, if in linux you can go to properties and just change the icon.

**Comment by zamonary1** [comment]
> You actually can do it yourself (at least for the taskbar part), if in windows you can create a link, go to properties, change the link icon and fix the link in the taskbar, if in linux you can go to properties and just change the icon.

Main point of vesktop is to improve linux experience, because of that it should bee implemented in source.
Also, i really like the idea of changing this gay logo to something less political.

**Comment by ItxWeird** [comment]
> You actually can do it yourself (at least for the taskbar part), if in windows you can create a link, go to properties, change the link icon and fix the link in the taskbar, if in linux you can go to properties and just change the icon.

Whilst yes this works, it more or a work-around more than an actual fix to the problem.

**Comment by Vendicated** [comment]
the worst thing ever happened: someone thought i might be gay

**Comment by thecatontheceiling** [comment]
this issue is completely idiotic

opening discord in front of a friend and them seeing shiggy shigging her tail for .5 seconds is a lot more awkward than an app logo lmao, adding an option to disable/customize this would be actually useful

**Comment by thecatontheceiling** [comment]
or I guess you could also just... get friends that don't think you're gay because you use a client mod? lol

**Comment by Sqaaakoi** [comment]
> @Vendicated I'm quite disappointed with your reply. You labeled my comment as "abuse", yet your own comment appears far more disrespectful and inappropriate.
> 
> I've been using the Vesktop app for several months now, but enforcing a gay logo with that peculiar loading animation without an option to disable it should be deemed as "abuse".
> 
> Please realize that imposing LGBT content onto people and disparaging comments like yours won't foster acceptance or tolerance towards the LGBT community. Instead, it's likely to have the opposite effect.
> 
> You're harming yourself by your own choice.

if it bothers you because of your internal homophobia then you are welcome to remove it yourself lol
vee isnt just gonna listen to a blatant troll account because "muh app icon has rainbow = gay!!!!!!"
vencord is literally made by queer people too btw :)

**Comment by ItxWeird** [comment]
Let me restate what my initial issue said. 

I simply just want a way to change to icon and the loading screen. I am _not_ offended by the current icon and loading screen, it would just be nice to customize and personalize it but in Vesktops current state, it's difficult to do.

Ya'll need to stop being so political over a damn logo.

**Comment by Cynosphere** [comment]
> Unfortunately, the authors are blinded by their greatness of being gay.

And you're blinded by being insecure. Not by the fact you're picking the fight but by the fact you're doing it on a throwaway, coping and seething over 6 colors.

And yet we're the smaller people here?

**Comment by Vendicated** [comment]
enough clowning around

noone is forcing an icon on you, you can just not use the app if you don't like it. i like the icon, so i accepted the pull request that added the icon. it's not being changed, go cope i guess

ps: someone else's identity is not 'politics', you're just a little snowflake that gets mad at a rainbow on their screen. don't be such a loser

**Comment by zamonary1** [comment]
> enough clowning around
> 
> noone is forcing an icon on you, you can just not use the app if you don't like it. i like the icon, so i accepted the pull request that added the icon. it's not being changed, go cope i guess
> 
> ps: someone else's identity is not 'politics', you're just a little snowflake that gets mad at a rainbow on their screen

In defence, i can totally understand that you might have project burnout, but doesn't vencord position itself as a solution that is superior to discord? Maybe we should really add this feature to users?

**Comment by TheRsKing** [comment]
without making political judgements, anyone who wants to change the icon can simply use [libremenu](https://flathub.org/apps/page.codeberg.libre_menu_editor.LibreMenuEditor)

**Comment by Mikilio** [comment]
Maybe that belongs in a new issue, but I would like the tray icon to indicate when there is a notification. Seems like a useful feature for many.

**Comment by PolisanTheEasyNick** [comment]
> Maybe that belongs in a new issue, but I would like the tray icon to indicate when there is a notification. Seems like a useful feature for many. Putting it hear because discords icon actually does that.

Will be in #517

**Comment by Vendicated** [comment]
closing in favour of https://github.com/Vencord/Vesktop/issues/667

**Comment by ItxWeird** [comment]
> excludes; in window assets, controllable via css and the app icon(read https://github.com/Vencord/Vesktop/issues/505, DEs provide methods of achieving this).
From #667 
Does not solve this issue as for OSes without DEs (aka windows).

**Comment by ItxWeird** [comment]
> Windows has a DE called "Windows Shell" you can easily change icons. Google it

I know that, I mean an actual useful and customisable DE, sure you may be able to change shortcut icons, but changing actual executable icons is more of a hastle and in this case doesn't actually change the icon in the task bar.

**Comment by ItxWeird** [comment]
Can we stop creating work arounds for the issue and actually develop a fix...
