### ISSUE TITLE
Segmentation fault on startup

### ISSUE THREAD

**Issue by vproper** [Vencord/Vesktop#508]
After updating Arch to the latest packages, Vesktop stopped working, and just segfaults

**To Reproduce**

1. Open Vesktop
2. Wait for it to load
3. Watch it crash with a segfault

**Expected behavior**
Vesktop working
![изображение](https://github.com/Vencord/Vesktop/assets/79580818/6ed7f734-1449-43f9-a3c2-e067b52cbe1e)

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux
 - Desktop Environment (linux only): Plasma 6
 - Version: Rolling release

**Command line output**
![изображение](https://github.com/Vencord/Vesktop/assets/79580818/802e85b1-f55f-493a-917b-578d52b4eebe)

**Additional context**

**Comment by sull324** [comment]
Same issue,updated to latest electron.,launch then seg fault. Not sure why the bug is already closed?.

**Comment by NextWork123** [comment]
@Vendicated reopen that we have all that issue it can be electron too but atleast we need to investigate no?

**Comment by Vendicated** [comment]
https://github.com/electron/electron/issues/41839
