### ISSUE TITLE
Vesktop Crashes with Segfault when the app loses focus

### ISSUE THREAD

**Issue by Ethee** [Vencord/Vesktop#510]
**Describe the bug**

When vesktop loses window focus the app crashes.

**To Reproduce**
1. Open Vesktop
2. Change window focus

**Expected behavior**
Vesktop properly loses focus, but does not crash.

**Desktop:**
 - OS/Distro: EndeavorOS
 - Desktop Environment (linux only): KDE6

**Command line output**

```
$ vesktop
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
zsh: segmentation fault (core dumped)  vesktop
```

**Additional context**
I had just updated my system, which included a package update for vesktop and electron. When I initially opened the app it said Vencord had an update as well. Unsure how related these things are.

**Comment by PolisanTheEasyNick** [comment]
Try to install Vesktop from [vesktop-bin](https://aur.archlinux.org/packages/vesktop-bin) AUR package. Looks like default package uses system electron and you updated to newly released 30 version on which we have seg faults in unknown yet reason.

**Comment by Ethee** [comment]
Apologies, I only just realized this is now a duplicate of issues opened 6 hours ago (I didn't expect something so new to be closed already). Based on the comments in those threads you have claimed the issue does not lie with Vesktop, but instead an upstream dependency (so Electron?) How can we be certain the issue lies there and not in the implementation? I'm not seeing any issues for other apps having a similar problem. Which means it must be unique to Vesktop's implementation somehow.

**Comment by Ethee** [comment]
> Try to install Vesktop from [vesktop-bin](https://aur.archlinux.org/packages/vesktop-bin) AUR package. Looks like default package uses system electron and you updated to newly released 30 version on which we have seg faults in unknown yet reason.

Ah, thank you, this indeed solved the issue.
