### ISSUE TITLE
Screenshare is not detecting apps that are running

### ISSUE THREAD

**Issue by nizeyoral** [Vencord/Vesktop#515]
I cant stream my games nor other applications in Vesktop and its not my "desktop environment" since it works perfectly fine with stockdiscord and vencord and also other discord mods.
I can only stream my desktop / the entire screen.

**Comment by TheRsKing** [comment]
Should be fixed by https://github.com/Vencord/Vesktop/pull/489

**Comment by nizeyoral** [comment]
> Should be fixed by #489

Wdym should be fixed? Im running the latest version and its not working.

**Comment by PolisanTheEasyNick** [comment]
I do not believe this will be fixed by #489.
Screensharing uses system's `xdg-desktop-portal` call for capturing the stream. If you can't see your applications in system (portal) picker that means that problems with portal, not with Vesktop.
Maybe you migrated from different DE and not installed right `xdg-desktop-portal`? For example, for KDE check whether `xdg-desktop-portal-kde` installed and so on.

**Comment by nizeyoral** [comment]
> I do not believe this will be fixed by #489. Screensharing uses system's `xdg-desktop-portal` call for capturing the stream. If you can't see your applications in system (portal) picker that means that problems with portal, not with Vesktop. Maybe you migrated from different DE and not installed right `xdg-desktop-portal`? For example, for KDE check whether `xdg-desktop-portal-kde` installed and so on. Please provide more info about your current DE and system.

Im running vesktop on windows 10, not linux. Is this an windows issue then? But why should this be broken on windows but got fixed on linux?
I think I will just stick to vencord then, thats too much nosebleeding for me LOL

**Comment by Vendicated** [comment]
please use the proper bug report template

**Comment by PolisanTheEasyNick** [comment]
> Im running vesktop on windows 10, not linux. Is this an windows issue then? But why should this be broken on windows but got fixed on linux? I think I will just stick to vencord then, thats too much nosebleeding for me LOL

It's anyway not Vesktop issue because we Vesktop use Electron's [desktopCapturer.getSources()](https://github.com/Vencord/Vesktop/blob/main/src/main/screenShare.ts#L18) call, which itselfs uses proper system calls for choosing screen.

**Comment by nizeyoral** [comment]
@Vendicated The bug report template sucks. But this is one way to ignore not working features I guess, since these features seems to be broken for other users aswell LOL?

@PolisanTheEasyNick It must be Vesktops bug, since it works with stock discord, vencord, betterdiscord without problems. Even with discord portable.
But im not here to argue or smth, its just strange that nobody is fixing this stuff, since its obviously broken lol?

**Comment by Vendicated** [comment]
lol fuck off with your entitlement. if you want help, use the proper form
