### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by 384000** [Vencord/Vesktop#516]
**Describe the bug**
Clicking the "A Vencord update available!" notification makes the whole window blank. Another issue I found while I tried to investigate is that the "Vencord" settings on the left is gone.

**To Reproduce**
1. Open Vesktop
2. Wait a few seconds before the notification appears
3. Click on the notification

**Expected behavior**
It should show me the changelog and the option to update.

**Screenshots**
![Screenshot from 2024-04-18 00-28-34](https://github.com/Vencord/Vesktop/assets/161776779/15fb36bf-927e-460c-96d4-70eeb993f22f)

https://github.com/Vencord/Vesktop/assets/161776779/5da4d63e-7b96-4c6d-823b-ce5d2af48e85

**Desktop (please complete the following information):**
 - OS/Distro: Ubuntu 23.10
 - Desktop Environment (linux only): GNOME

**Command line output**

```
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:0418/001715.745676:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0418/001716.073546:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0418/001716.073594:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started

(vesktop.bin:3): libnotify-WARNING **: 00:17:28.415: Running in confined mode, using Portal notifications. Some features and hints won't be supported
```

**Additional context**
I don't know if it's relevant, but the exact version of Vesktop I'm running is:
Stable 285561 (e592eef)
Vencord 0f5a75 (Vesktop V1.5.1)
Electron 29.1.1
Chromium 122.0.6261.111

I'm using the latest version available from flathub.

**Comment by JustAPotota** [comment]
Just happened to me as well. The plugins I have enabled seem to still be working fine, but all the Vesktop/Vencord-related settings menus are gone.

**Comment by Vendicated** [comment]
Right click vesktop tray > update vencord

or `rm -rf ~/.config/vesktop/vencordDist`
