### ISSUE TITLE
Attempting to update Vencord by toast interaction causes Vesktop to freeze

### ISSUE THREAD

**Issue by nissa-seru** [Vencord/Vesktop#530]
**Describe the bug**

Clicking on the "A VENCORD UPDATE IS AVAILABLE!" toast at the bottom-right of the Vesktop window causes the Vesktop window to become blank and nonresponsive; this does not resolve after waiting several minutes. Closing and restarting Vesktop enables it to become responsive, yet the toast reappears shortly after opening (suggesting that the update was not successfully applied. The app responds identically if the update is triggered from a native Windows toast.

![Screenshot 2024-04-21 043530](https://github.com/Vencord/Vesktop/assets/119150866/8429869e-c847-413b-861a-89ecd6968e4e)
![Screenshot 2024-04-21 043340](https://github.com/Vencord/Vesktop/assets/119150866/c5420285-ddd2-42c9-aba5-fc9b69d3ea7f)

**To Reproduce**

1. When the "A VENCORD UPDATE IS AVAILABLE!" toast appears, click it as you would to view the update.

**Expected behavior**

Vencord app updates and returns to an interactable state following the update.

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Distro: Windows 11 Pro
 
stable 286349 (4b5188e)

**Command line output**

cd'ing to "C:\Users\Nissa\AppData\Local\vesktop" and running the "vesktop" command opens the Vesktop app. Let me know if something else is needed.

**Additional context**

See screenshots for visuals.

**Comment by M1koyan** [comment]
The settings page is also missing all the Vencord settings tabs
![image](https://github.com/Vencord/Vesktop/assets/129828046/dd469648-c94f-47c8-b40e-d6f2e793050f)

**Comment by Vendicated** [comment]
duplicate #516 #519 #522
