### ISSUE TITLE
Vesktop segment fault a few seconds of launching.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [Vencord/Vesktop#532]
**Describe the bug**
Recently (a few days ago) everytime I launch Vesktop it seems to segment fault a few seconds after. I am on Arch Linux using this [aur package](https://aur.archlinux.org/packages/vesktop) and all my packages are up to update. *I think* this started to occur after an update but I'm really not certain what update and if it did.

```
[goldy@jassim-desktop ~]$ vesktop
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[13435:0421/115440.161689:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[13435:0421/115440.174361:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[13435:0100/000000.791500:ERROR:broker_posix.cc(41)] Recvmsg error: Connection reset by peer (104)
Segmentation fault (core dumped)
```

The "GetVSyncParametersIfAvailable" errors seem to be mentioned in this issue https://github.com/electron/electron/issues/32760 idk if it's related.

**To Reproduce**

1. Open Vesktop from your application launcher or command line with `vesktop`.
2. Wait for a moment to see if it closes and segment faults.

**Expected behavior**
I expect the application to stay open and be useable just like it's always been.

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/66202304/e5eed48d-7a4e-4203-8f90-42c904e31fb3)

It launches then after a few seconds, **crash**.

![image](https://github.com/Vencord/Vesktop/assets/66202304/3234334c-5093-4811-a531-5e3dc6dc060e)

**Desktop:**
 - OS/Distro: Arch Linux
 - Desktop Environment (linux only): KDE Plasma 6.0.4
 - Version: Kernel 6.8.7-arch1-1

**Command line output**

```
[goldy@jassim-desktop ~]$ vesktop
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[13435:0421/115440.161689:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[13435:0421/115440.174361:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[13435:0100/000000.791500:ERROR:broker_posix.cc(41)] Recvmsg error: Connection reset by peer (104)
Segmentation fault (core dumped)
```

**Additional context**
Don't have any more thanks but let me know if there's anything else you would like to know about my system. Feel free to ping me many times, I'm here to help resolve a potential bug for everyone else.

**Comment by CaptaiNiveau** [comment]
I had the same issues and figured out a temporary fix, wanted to report the issue rn.

Basically I fixed this by downgrading the electron package to version 29 (using the downgrade script). Now both Vesktop and Vesktop-git (from chaotic-aur) are working again.

Electron 30 seems to introduce some issue that has to be taken care of.

**Comment by Vendicated** [comment]
duplicate. not supported.

**Comment by THEGOLDENPRO** [comment]
> I had the same issues and figured out a temporary fix, wanted to report the issue rn.
> 
> Basically I fixed this by downgrading the electron package to version 29 (using the downgrade script). Now both Vesktop and Vesktop-git (from chaotic-aur) are working again.
> 
> Electron 30 seems to introduce some issue that has to be taken care of.

Ah, thank you for that information. I'll downgrade to electron 29 and give it a try.

**Comment by CaptaiNiveau** [comment]
> duplicate. not supported.

Totally fair, I get why. Sadly it wasn't immediately obvious to me while searching for this issue and I forgot to check closed issues (github doesn't display them by default and normally stuff like this is an open issue).
Just a suggestion, maybe keep an issue open for your own sanity with a short explanation and fix (install flatpak version) so that users don't open unnecessary issues.

No need to do this, just a humble suggestion ^^

**Comment by THEGOLDENPRO** [comment]
> > I had the same issues and figured out a temporary fix, wanted to report the issue rn.
> > 
> > Basically I fixed this by downgrading the electron package to version 29 (using the downgrade script). Now both Vesktop and Vesktop-git (from chaotic-aur) are working again.
> > 
> > Electron 30 seems to introduce some issue that has to be taken care of.
> 
> Ah, thank you for that information. I'll downgrade to electron 29 and give it a try.

This worked btw, thanks.
