### ISSUE TITLE
Hardware acceleration not working

### ISSUE THREAD

**Issue by LemuelDayrit** [Vencord/Vesktop#536]
i try to disable hardware acceleration then restart vesktop then it didnt disable because i have supergfx in the system tray it shows that my dgpu is active. can someone know how to fix that

**Comment by AAGaming00** [comment]
force xwayland

**Comment by LemuelDayrit** [comment]
how?

**Comment by Takkar170** [comment]
For AppImages:

env -u WAYLAND_DISPLAY ./(app_name).AppImage

For flatpak applications:

Download Flatseal from flathub, change permissions of your application or game in Flatseal to remove the "Wayland" socket. In my experience, in versions of KDE lower than 5.23, you might need to disable "fallback-x11" socket as well.
