### ISSUE TITLE
Vesktop-specific Settings Menus are Missing and Causes Update Notification Click Failures

### ISSUE THREAD

**Issue by ThisNekoGuy** [Vencord/Vesktop#538]
**Describe the bug**

Upon launching Vesktop, I get the update notification but clicking on it wipes the window blank and doesn't actually take me to the update menu. Thinking this was strange, I killed the process (`killall vesktop.bin`) then re-opened Vesktop and went to the settings menu. However, when I went there, I noticed that the Vesktop menu entries were all missing somehow. My guess is, the notification is trying to take me to the update menu but then silently fails because it stopped existing for some reason.

**To Reproduce**

1. Install the Vesktop flatpak (if not installed, I already had it installed for a while already)
2. Run Vesktop
3. Get update notification
4. Click it
5. Kill the `vesktop.bin` process (if you want to see the missing menu entries)
6. Relaunch Vesktop
7. Go to settings
8. Search for Vesktop setting menus

**Expected behavior**

**Screenshots**

![Screenshot_20240423_224345-1](https://github.com/Vencord/Vesktop/assets/28468662/c2bea710-d915-4530-b0f8-ca93265caf95)

**Desktop (please complete the following information):**
 - OS/Distro: Gentoo Linux
 - Desktop Environment (linux only): KDE Plasma 6
 - Version: Rolling Release, LLVM17-compiled, OpenRC

**Command line output**

```
env PULSE_LATENCY_MSEC=120 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop
```

**Additional context**

N/A

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/issues?q=is%3Aissue+sort%3Aupdated-desc+update+settings

**Comment by ThisNekoGuy** [comment]
@Vendicated Found your comment about `rm -rf ~/.var/app/dev.vencord.Vesktop/config/vesktop/vencordDist` (thanks) but it would be helpful if there was some default plugin that catches this and notifies the user or something, if possible.
Clearly this is a common issue, as you've pointed out, and I can only imagine it'll continue to pop-up. :/
