### ISSUE TITLE
WebContextMenu for the text box that doesn't appear

### ISSUE THREAD

**Issue by thetundraterror** [Vencord/Vesktop#539]
**Describe the bug**

Whenever I try right clicking the text box, the context menu doesn't appear. Right-clicking literally anything else brings up the appropriate menu.

**To Reproduce**

I have no clue; others who use Vesktop don't have this issue

**Expected behavior**

When I right click the text box, a context menu should appear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Distro: [e.g. Windows / Fedora Linux / MacOs]
 - Desktop Environment (linux only): [e.g. gnome, kde, sway]
 - Version: [e.g. 22]

EndeavourOS
KDE

**Command line output**

```
[arRPC > ipc] not available, trying again (attempt 1)
[arRPC > ipc] listening at /run/user/1000/discord-ipc-1
[arRPC > websocket] 6463 in use!
[arRPC > websocket] listening on 6464
[arRPC > process] started
[52121:0423/232316.299705:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[52121:0423/232316.305842:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[52121:0423/232316.315771:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Additional context**

I have tried the AUR, Flatpak, and AppImage versions to no avail.

**Comment by Vendicated** [comment]
update vencord & vesktop to latest version

**Comment by Koishukaze** [comment]
I had this issue, see if legacy chat input is enabled in the accessibility settings

**Comment by thetundraterror** [comment]
> I had this issue, see if legacy chat input is enabled in the accessibility settings

Turning off Legacy Chat Input does seem to resolve it, even thought I VASTLY prefer Legacy Chat Input.
