### ISSUE TITLE
Linux Vesktop Window doesn't recover from file drag-and-drop

### ISSUE THREAD

**Issue by cybik** [Vencord/Vesktop#541]
**Describe the bug**

Note that the underlying system IS quirky. That being said, normal discord *does not* show this behaviour.

The moment I drag /something/ from outside of Discord into the window, like an image I want to share in chat, Vesktop disables mouse input inside the window until the app is relaunched (`tray icon > Relaunch` makes this quick, but it's still a chore)

**To Reproduce**

0. Use Linux
1. Enable Discord window decorations via Vesktop Settings > User Interface > Discord Titlebar
2. Drag a file into Discord/Vesktop to share in chat

Now you can't click anywhere in discord, mouse input is functionally disabled. Keyboard works fine.

**Expected behavior**

I should be able to continue clicking things in the app and have the app actually function as normal.

**Screenshots**

[Made a video to show it.](https://youtu.be/blinua-B90U)

**Desktop (please complete the following information):**
 - OS/Distro: PikaOS, a Pop_OS/Ubuntu derivative at the moment
 - Desktop Environment (linux only): KDE
 - Version: Vesktop latest

**Command line output**

```
vesktop --enable-features=UseOzonePlatform,WaylandWindowDecorations,VaapiVideoDecoder --ozone-platform=wayland 
[obs-vkcapture] Init Vulkan 1.4.9 (64bit)
[obs-vkcapture] Init Vulkan 1.4.9 (64bit)
[obs-vkcapture] DRM format modifier support not available
[obs-vkcapture] missing device extension: VK_EXT_external_memory_dma_buf
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[Vencord] Installed React Developer Tools
(node:110273) ExtensionLoadWarning: Warnings loading extension at /home/cybik/.config/vesktop/ExtensionCache/fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

(Use `vesktop --trace-warnings ...` to show where the warning was created)
```

**Additional context**

Other hardware details:
* Using an nVidia RTX3080 GPU
* Using the nVidia drivers
* Using the Wayland windowing server instead of Xorg

**Comment by SimplyTadpole** [comment]
I have the same issue.

Using Fedora Kinoite 39 and the latest version of Vesktop. On an AMD RX 570.

**Comment by CosmicHeron** [comment]
I've been experiencing this as well (using the `vesktop` AUR package). Can also be reproduced by clicking on an image in a Discord chat, dragging and immediatelly releasing, the mouse cursor will be stuck in the grab mode. Afaik the only way to recover is to relaunch Vesktop.

**Comment by nexy7574** [comment]
+1 on Fedora 40 with Wayland, installed via Flatpak. Step 1 of the original issue isn't even required in my case, all of those options are unchecked. Simply dragging an dropping a file (in my case, usually a screenshot/PNG from a Spectacle notification) into the main window attaches the file to the message, and I can use Discord normally, just with no mouse control.

**Comment by cybik** [comment]
The simplest workaround to this is copy-pasting the image itself into the chat field, as it pastes as an image file, but that doesn't fix the underlying issue.

**Comment by Sqaaakoi** [comment]
sounds like a chromium upstream issue, i often find that native wayland chromium apps just explode whenever you drag anything, so it could be related to that

**Comment by nexy7574** [comment]
> sounds like a chromium upstream issue, i often find that native wayland chromium apps just explode whenever you drag anything, so it could be related to that

I mean, my chromium browser still does drag and drop fine, and I'm yet to encounter this with other electron apps  :shrug:

**Comment by Vendicated** [comment]
are you running via native wayland? drag and drop is really fucked with that. try using XWayland instead

either way this is upstream somewhere

**Comment by OzzyHelix** [comment]
I'm having this problem too drag and dropping files of any kind brings vesktop into a state that requires restarting the app it is very annoying for the record I am using the flatpak version of the app

**Comment by cybik** [comment]
> are you running via native wayland?

Yes indeed. Xwayland is actually causing my setup some grief so I try to *not* use it as much as possible.

**Comment by Sqaaakoi** [comment]
> > are you running via native wayland?
> 
> Yes indeed. Xwayland is actually causing my setup some grief so I try to _not_ use it as much as possible.

chromium under xwayland has annoying problems
chromium under native wayland also has annoying problems

solution: pick the one which has the least issues

**Comment by OzzyHelix** [comment]
I am using actual wayland there is no X compatibility in my system to my knowledge I'd like to get this fixed but idk if its a matter if disinterest by the maintainer or if its an upstream problem with electron/chromium

**Comment by OzzyHelix** [comment]
I looked at the shell script in the AUR package and it appeared to use the system electron package I thought that was strange the flatpak works and your less likely to end up with an electron version mismatch using the flatpak

**Comment by OzzyHelix** [comment]
for those on Arch I would recommend using the https://aur.archlinux.org/packages/vesktop-bin `vesktop-bin` package it seems to have a specified electron version and if all else fails just use the flatpak

**Comment by OzzyHelix** [comment]
I went a head and confirmed that installing vesktop-bin fixed my problem with drag and drop
git clone the repo
makepkg -i and let it compile and it should work fine

**Comment by cybik** [comment]
@D3SOX somehow `--enable-features=UseOzonePlatform,WaylandWindowDecorations,VaapiVideoDecoder --ozone-platform-hint=x11` looks like it kinda sorta works. Will report back if it goes to hell.
