### ISSUE TITLE
Microphone cannot be enabled, constant popups saying audio device has been changed

### ISSUE THREAD

**Issue by Maxnoobbie123** [Vencord/Vesktop#547]
**Describe the bug**
While using the Vesktop App, I am unable to turn on my microphone and the popup that shows redirects me to instructions on how to enable the microphone on the Chrome Browser. Another related bug is that Occasionally a popup will say a new audio device has been connected when I tab out. Vesktop is not shown in settings when trying to give microphone access.

**To Reproduce**

1. Use the vesktop app as expected
2. Try to enable microphone
3. Have poput for denied microphone access

**Expected behavior**

Microphone access is given and I am able to use the microphone as normal.

**Screenshots**

<img width="439" alt="image" src="https://github.com/Vencord/Vesktop/assets/74038847/25856b69-9fb3-4525-af81-ee7591e329dd">

**Desktop (please complete the following information):**
 - OS/Distro: MacOS
 - Version: 1.5.1

**Command line output**

```
paste inside these backticks
```

**Additional context**

**Comment by RayBytes** [comment]
I can also vouch for this, just started getting the same error.

**Comment by PolisanTheEasyNick** [comment]
Try version 1.5.2-alpha1 from tag releases. There was some work with MacOS permissions.
