### ISSUE TITLE
Resizing window on wayland crashes Vesktop

### ISSUE THREAD

**Issue by CogumeloDoZap** [Vencord/Vesktop#549]
**To Reproduce**
1. Open Vesktop
2. Resize the window
3. Vesktop crash

**Screenshots**

 Wayland
https://github.com/Vencord/Vesktop/assets/95929538/c61b32dc-54f4-41da-befc-32c8ba7b0e18

 X11
https://github.com/Vencord/Vesktop/assets/95929538/82a73233-176a-4e60-a166-a059012d0dec

**Desktop (please complete the following information):**
 - OS/Distro: ArchLinux(experienced same error on fedora and Void)
DE: Gnome 46

**Comment by Vendicated** [comment]
make sure you're using electron 29, not 30
