### ISSUE TITLE
Enable native Wayland support

### ISSUE THREAD

**Issue by TheSilverFoxes** [Vencord/Vesktop#550]
I'm on Fedora 40 with GNOME, is there a way to enable Wayland support through the settings without having to run Vesktop with ` --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland ` flag?
Thank you.

**Comment by Vendicated** [comment]
no, and all of these flags are obsolete, just use `--ozone-platform-hint=auto`

duplicate of #342
