### ISSUE TITLE
Move "Enable Spellcheck" option

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#553]
**Is your feature request related to a problem? Please describe.**
My feature request is related to right-clicking in the chat box.

![image](https://github.com/Vencord/Vesktop/assets/30274161/d223a263-d363-4407-a77b-2c4837937d31)

**Describe the solution you'd like**
I would like to have the "Enable Spellcheck" option to be placed under "Send Messages Button" (above "Paste"). This makes it more practical to right-click and paste, since the closest option to mouse right-click currently is "Enable Spellcheck".

**Describe alternatives you've considered**
Move the option to "Vesktop Settings" inside Discord's user settings.

**Additional context**
No additional context.

**Comment by Thespikedballofdoom** [comment]
I don't really know why it got moved and don't like it so
`#textarea-context-vcd-spellcheck-enabled{
    padding:0px;
    display:none
    }`
