### ISSUE TITLE
[Question] what is the update delay usually between upstream and the flatpak?

### ISSUE THREAD

**Issue by CurrentSubset68** [Vencord/Vesktop#558]
based off previous update cycles, how long does it usually take for the flatpak to be updated? just curious.

**Comment by TheRsKing** [comment]
Normally 1-3 days. 1.5.2 only needs to be merged now

**Comment by CurrentSubset68** [comment]
would it be possible to add this in the readme file?

**Comment by Vendicated** [comment]
however long until the flatpak is updated and then the update is built & approved. there is no eta, just be patient
