### ISSUE TITLE
Default screen sharing quality to 720p 30 FPS

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#559]
**Is your feature request related to a problem? Please describe.**
I would like the default stream quality to be the maximum possible (1440p 60 FPS).

**Describe the solution you'd like**
Make the default 1440p 60 FPS. Currently, it is 1080p 60 FPS.

**Describe alternatives you've considered**
Add an option or plugin to customize the default values.

**Additional context**
I'm not sure anything above 720p 30 FPS works for non-Nitro members.

**Comment by PolisanTheEasyNick** [comment]
> 1440 this would be a waste of bandwith and/or system resources.

If user picked 1440 and display resolution is 1920 then Discord just will not go up to 1440 for streaming, it will stick at 1920.
About this enhancement, I believe the best way will be on first start up propose to user his display resolution (or just propose 1920 for not overcomplicating code) and then just save it to user settings store for future reuse at stream starting.

**Comment by lennoxlotl** [comment]
> > 1440 this would be a waste of bandwith and/or system resources.
> 
> If user picked 1440 and display resolution is 1920 then Discord just will not go up to 1440 for streaming, it will stick at 1920. About this enhancement, I believe the best way will be on first start up propose to user his display resolution (or just propose 1920 for not overcomplicating code) and then just save it to user settings store for future reuse at stream starting.

For usability reasons it would probably still better to just auto-detect the actual resolution, especially to avoid confusion.

**Comment by Tecnio** [comment]
Yeah I agree with @lennoxlotl.

**Comment by PolisanTheEasyNick** [comment]
Yep, sorry, I meant 1080 in my message above.
About non-nitro I think that client will set resolution to whatever user picked but in non- boosted server call bitrate would be limited to 4000 kbit/s iirc, so resolution (or FPS in `content-hint: "detail"` mode) will be auto downscaled by WebRTC negotiations to fit into 4000 kbit/s bitrate. Need more tests about non-nitro stuff, though.

**Comment by Vendicated** [comment]
i think much better than this suggestion would be to just remember the last value the user chose
