### ISSUE TITLE
[Bug] Icons from other programs do not show up on topbar when Vencord is running (Mac)

### ISSUE THREAD

**Issue by trademark-living-his-best-life** [Vencord/Vesktop#56]
The bug happens when you have Vencord running, any icons that are supposed to show up from external apps don't show up until you quit out of Vencord. (I feel like this partially happens because you can't Hide Vencord)

Here's a video of me using Mac's built in screen recorder (which also has an icon for the topbar) before and after closing Vencord.

https://github.com/Vendicated/Vencord/assets/45497981/00fd0328-fac7-459d-b1df-ad38db9b468e

**Comment by trademark-living-his-best-life** [comment]
Updated to 0.2.7, I still have this same issue...

**Comment by Vendicated** [comment]
should be fixed in 0.2.8, please reopen if still an issue

**Comment by trademark-living-his-best-life** [comment]
Thanks! Works now
