### ISSUE TITLE
The issue that prevents users from starting streams while watching another stream persists.

### ISSUE THREAD

**Issue by Tecnio** [Vencord/Vesktop#560]
**Describe the bug**
When a user is attempting to start a screen share while watching someone else's screen share, the stream will get stuck in a loading loop. This issue was apparantly fixed by kaitlynkittyy's merge requests however still persists after updating to 1.5.2.

**To Reproduce**
1. Join a voice channel in a server.
2. Watch another users stream by clicking "Watch Stream".
3. Attempt to start a screen share at any setting.

**Expected behavior**
The stream to successfully start instead of getting stuck loading. 

**Screenshots**
![Screenshot from 2024-05-01 21-12-03](https://github.com/Vencord/Vesktop/assets/50290580/39550fb1-a0f2-469c-8ab6-024b499ac7e9)

**Desktop (please complete the following information):**
 - OS/Distro: Fedora Linux
 - Version: 40
 - Desktop Environment (linux only): GNOME

**Command line output**

```
[67460:0501/211440.939755:ERROR:screencast_portal.cc(367)] Failed to start the screen cast session.
[67460:0501/211440.939771:ERROR:base_capturer_pipewire.cc(81)] ScreenCastPortal failed: 2
Error during screenshare picker Failed to get sources.
(node:67460) UnhandledPromiseRejectionWarning: TypeError: Video was requested, but no video stream was provided
    at AsyncFunction.<anonymous> (VCDMain:24:2158)
(Use `vesktop --trace-warnings ...` to show where the warning was created)
(node:67460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[67521:0501/211444.289233:ERROR:vaapi_video_decoder.cc(1242)] failed Initialize()ing the frame pool
'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-05-01 21:14:48.337] [venmic] [info] [patchbay] (get) running venmic 3.4.2
[2024-05-01 21:14:48.340] [venmic] [info] [patchbay] (handle) found default metadata: 37
[2024-05-01 21:14:48.340] [venmic] [info] [patchbay] (meta_update) speaker name: "alsa_output.pci-0000_2d_00.4.analog-stereo"
'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
```

**Additional context**

The issue seems to be happening with other friends using Vesktop.

**Comment by kaitlynkittyy** [comment]
> That's Discord's bug which is reproducible even in Windows Web to Windows Web streaming, so we can't do anything about it. While debugging, I found out that while watching another stream and creating new stream, the MediaStream is not assigns in conn.input so without fixes from Discord's side we can't do anything. Here is created connection for stream without MediaStreams objects at .input.desktop and .input.stream: ![image](https://private-user-images.githubusercontent.com/39007846/327200286-38aad844-1a7d-4d4c-b787-b2ac992e7f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjU2MjcsIm5iZiI6MTcxNDY2NTMyNywicGF0aCI6Ii8zOTAwNzg0Ni8zMjcyMDAyODYtMzhhYWQ4NDQtMWE3ZC00ZDRjLWI3ODctYjJhYzk5MmU3ZjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE1NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNTY2NGQzYjFkNTkyNzEwYWRjZTA5ZDkzNjk1ZThhMjgyMzk2MTNlODkyMGM2ZWYzMDVlMjgxMjRiMTU0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fb1o-ewNdBL1vMmFSSTW5-Rx4kpcX-txvg88sdFInt8) And here is how it should look: ![image](https://private-user-images.githubusercontent.com/39007846/327200430-25a1c06a-6b51-4123-95a0-c36743836ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjU2MjcsIm5iZiI6MTcxNDY2NTMyNywicGF0aCI6Ii8zOTAwNzg0Ni8zMjcyMDA0MzAtMjVhMWMwNmEtNmI1MS00MTIzLTk1YTAtYzM2NzQzODM2Y2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE1NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNDY1NmU2ZTg4Y2JkYTk3M2M2ZjgwYmM3MDBiZjc4YjU1ZjljZjRiYmJlODhhMTBjOTViMzljNjNhYzUwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1SWj4Or6XkpYilRnhiNs2pYVZAqFxYwXX1Elv3287mY) I already reported that to Discord Support but I do not believe that they will do something about it. As temporary workaround you should manually rechange window after starting stream.

maybe until then, we could add a workaround that checks if a stream exists from another user, and automagically applies the stream twice to bypass the issue?

**Comment by S3nsh1r0** [comment]
If that is not too complicated to do, then yeah. is it then good to push it as an Dev. setting in Vencord?

**Comment by pixL404** [comment]
Hi, what is the current status of this issue? 

Screen sharing is not working for me on NixOS (Wayland Session) with the version `1.5.2`

**Comment by Tecnio** [comment]
Issue is resolved.

**Comment by alothings** [comment]
@Tecnio how was the issue resolved? I have the same issue.

Fedora/XFCE
Issue: During a group call on the Study Together channel, I can't focus on some cameras, sometimes. It is very random. It seems to be when the groups are large (15+ people). When there is only 4 people streaming their cameras, I have no issues focusing on someone.

**Comment by Tecnio** [comment]
It was fixed in a Vesktop update and I haven't had this issue ever since. However there still seems to be a related issue where some screenshares get stuck on the loading and randomly not load but I have no information, nor know the cause so I can't exactly open a bug report about it.
