### ISSUE TITLE
No Vencord menu

### ISSUE THREAD

**Issue by Miko0187** [Vencord/Vesktop#567]
**Describe the bug**

I wanted to change some vencord settings but the menu is gone

**To Reproduce**

Just open the app ig? Idk how to reproduce

**Expected behavior**

Vencord options should be available.

**Screenshots**

![grafik](https://github.com/Vencord/Vesktop/assets/113242324/d5c05cc9-1d83-436a-8719-816729c1da47)
![grafik](https://github.com/Vencord/Vesktop/assets/113242324/9fc0838e-e70b-40cf-aafb-d3aceae2264e)

**Desktop (please complete the following information):**
 - OS/Distro: Arch Linux
 - Desktop Environment (linux only): kde
 - Version: kde6

**Command line output**

```
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```

**Comment by Miko0187** [comment]
wdym duplicate

**Comment by kaitlynkittyy** [comment]
a lot of users have reported the same issue, please check other issues before making a new one. But just to save you the time, right click tray icon > update vencord
