### ISSUE TITLE
Add a new option to change the tray icon used by Vesktop

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#571]
Hi there. I would like to have a command-line flag or GUI option to change the icon used by Vesktop on the system tray. For the GUI, it could be something together with the "Tray Icon" option in "Vesktop Setttings".

My reasoning for this request is because I personally prefer to use original Discord icons.
To clarify, I'm not requesting to add Discord icons inside Vesktop itself. What I'm requesting is to let the user choose custom icons from their PC directly.

For the app itself, I can do it using the `.desktop` file on my DE (KDE Plasma), but I can't modify the VC icon due to it being hardcoded in Vesktop itself. (I could, but I would have to recompile the program, and that's not very convenient when updating.)

Context of this issue: see issues #448 and #570.

One thing that I'm not sure is about having `static.ico` and `static.png`. If I could modify Vesktop's tray icon, which extension would I have to use? Or would I need to have both file extensions for two copies of the same image? I think it would be interesting to use only `.ico` or `.png` to make it simpler (if needed).

Thanks in advance to all contributors, and a special thanks to Vendicated for having a very friendly behavior.

![image](https://raw.githubusercontent.com/Vencord/Vesktop/main/static/shiggy.gif)

**Comment by Vendicated** [comment]
adding this feature would be fairly trivial, one would just need to get the user preference, check if it exists, and then adjust the path passed here

https://github.com/Vencord/Vesktop/blob/a66af353f776a5544bec85147366fb26b9b2bf32/src/main/mainWindow.ts#L124

**Comment by MrGarlic1** [comment]
I plan on working on this tomorrow with a GUI file select option in vesktop settings. Just need to familiarize myself with the project first :)

**Comment by scoliono** [comment]
#505 and #506 are worth mentioning too, for a third party client which is all about customization it's ironic that the devs shut down any discussion about changing the assets.

**Comment by Cynosphere** [comment]
> it's ironic that the devs shut down any discussion about changing the assets.

Both issues were either started as or ended with harassment which is why. The time spent wasted arguing, someone could've just made a PR for it already.

**Comment by scoliono** [comment]
It seems to me like both issues were started in good faith. No one has addressed why 506 was immediately closed.

**Comment by AAGaming00** [comment]
> It seems to me like both issues were started in good faith. No one has addressed why 506 was immediately closed.

did anybody ask

**Comment by Cynosphere** [comment]
> On Windows, you can right-click and change the icon, and I believe that applies to the task bar as well.

This is misleading. This only changes the shortcut's icon in the taskbar and does not reflect changes in the system tray (the point of this issue) and a multitude of other places, especially if the app has a dynamic icon for notifications or such.

**Comment by padgriffin** [comment]
> On Linux, depending on your desktop environment, you can edit `/usr/share/applications/vesktop.desktop` (at least on KDE Plasma) and change the `Icon` line to point to an icon name from your icon pack, or to point to a PNG or ICO file directly.

If you're using the Flatpak version, you can find it at `/.local/share/applications/dev.vencord.Vesktop.desktop`.

I hate that I have to do this but I am LGBTQ myself, I just prefer the original Discord logo over the VC in my dock. If someone could point me to a pride ico file for the original logo it would be much appreciated. I tried using ones meant for MacOS but they were too small for some reason.

**Comment by ItxWeird** [comment]
> On Windows, you can right-click and change the icon, and I believe that applies to the task bar as well.

(Bit of context, I'm the original poster of #505 )

I'm not quite sure what you mean here. Do you mean to right click on the shortcut? If so I think this would work but I personally prefered using the portable version of vesktop and just running the exe. Having an icon changed baked into vesktop would make it easier for all users to change the icon on any platform

**Comment by Axenide** [comment]
I'd like to have this feature. Maybe having the option to change it to the original Discord icon, or at least something *similar*, but also having the option to upload a custom one.

**Comment by satk0** [comment]
Instead of having too much customization, I would go with a simple: `Turn off cuteness` option that changes the icon and the loading gif to a rigid alternative.

**Comment by ThatOverPowered** [comment]
As temp workaround, is possible to setup a custom icon using the [gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator) extension.
![imagen](https://github.com/Vencord/Vesktop/assets/50776804/53b6b4ed-cce9-40ea-a7ea-e6d7fb5f4a46)

**Comment by Commenter25** [comment]
The above workaround will break if you have any other Electron-based app placing a tray icon, such as Signal. All of them will have the same icon. Perhaps if there's a way to make it report a unique ID, this would help as a stopgap solution.

**Comment by Vendicated** [comment]
closing in favour of https://github.com/Vencord/Vesktop/issues/667
