### ISSUE TITLE
[Bug] Drag and drop breaks mouse control in vesktop

### ISSUE THREAD

**Issue by coinkillerl** [Vencord/Vesktop#578]
### Discord Account

CoinKillerL

### Operating System

CachyOS Linux

### Linux Only ~ Desktop Environment

KDE Wayland

### What happens when the bug or crash occurs?

Dragging a dropping a file (for example, an image) completely breaks mouse input for vesktop, making the app only usable with keyboard navigation in wayland native mode. This does not happen on XWayland.

### What is the expected behaviour?

Mouse input works fine after dragging and dropping a file

### How do you recreate this bug or crash?

1. Drag and drop a file onto vesktop.

### Debug Logs

```
Nothing
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/issues?q=is%3Aissue+drag+and+drop
