### ISSUE TITLE
[Bug] Small empty space between taskbar and Vesktop

### ISSUE THREAD

**Issue by sergiohzph** [Vencord/Vesktop#579]
### Discord Account

sergiohzph

### Operating System

Windows 11

### What happens when the bug or crash occurs?

![image](https://github.com/Vencord/Vesktop/assets/138529583/09130578-3175-4cf4-955d-4e65f5abbdad)
As you can see, there's an small space between Vesktop and the taskbar.

### What is the expected behaviour?

It should stay docked in fullscreen, not in a windowed mode with that little space, which you can use to resize the whole Vesktop window, so that it looks like this... a bit weird.
![image](https://github.com/Vencord/Vesktop/assets/138529583/ed33ae3f-a5e7-4f60-b2f1-2534b2a66fca)

### How do you recreate this bug or crash?

By selecting the following settings: 
![image](https://github.com/Vencord/Vesktop/assets/138529583/d284c678-0aa2-45b1-9672-fbfd083aa607)
![image](https://github.com/Vencord/Vesktop/assets/138529583/b785e4d3-0840-4e8b-b978-29bdddc7c5d5)
And closing and re-opening Vesktop.

### Debug Logs

```
[arRPC > ipc] listening at \\?\pipe\discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[Vencord] Installed React Developer Tools
(node:2120) ExtensionLoadWarning: Warnings loading extension at C:\Users\Sergio\AppData\Roaming\vesktop\ExtensionCache\fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
make sure you don't have "Enable window transparency" enabled in vencord settings

if that's not it, nothing we can do
![image](https://github.com/Vencord/Vesktop/assets/45497981/69daf03f-f8e2-4b64-8920-5f924f145e01)
