### ISSUE TITLE
Port >100% volume feature from Discord Desktop

### ISSUE THREAD

**Issue by InfectedGriffon** [Vencord/Vesktop#58]
vc user volume only goes up to 100% for some reason ??? ven plz fix

vesktop:
![vesktop](https://github.com/Vencord/Vesktop/assets/79546684/7d5738c0-43b7-4a94-bd07-e15fe8746646)

discord+vencord:
![discord](https://github.com/Vencord/Vesktop/assets/79546684/ee48c9ab-9756-4970-aff3-534f7236b5a6)

**Comment by Vendicated** [comment]
i don't think this is possible

**Comment by Vap0r1ze** [comment]
ya i think this can happen i'll give it a shot later

**Comment by Vendicated** [comment]
@Vap0r1ze do

**Comment by Chedski** [comment]
bump, the lack of this + volumebooster not existing is making it hard to hear my quiet friends :(

**Comment by Vendicated** [comment]
i recommend putting everyone on 50% and just making vesktop louder, then you can just put individual people higher

**Comment by Rika-TH** [comment]
putting everyone on 50% without a global toggle option sounds like a surefire way to get blasted when you join somewhere you haven't been before/people you haven't set to 50% before

that is a viable bandaid though, used that before on base discord

**Comment by ArjixWasTaken** [comment]
> putting everyone on 50% without a global toggle option sounds like a surefire way to get blasted when you join somewhere you haven't been before/people you haven't set to 50% before
> 
> that is a viable bandaid though, used that before on base discord

Maybe a plugin that sets the default volume level would fix this issue.

**Comment by Chedski** [comment]
how is audio output for vcs handled by discord web? if the volume can be changed there's probably a volume value it's changing and i'm fairly sure you can increase the volume of both audio elements and web audio api above 1

**Comment by lewisakura** [comment]
> how is audio output for vcs handled by discord web? if the volume can be changed there's probably a volume value it's changing and i'm fairly sure you can increase the volume of both audio elements and web audio api above 1

discord web uses the standard browser audio apis in contrast to how discord desktop works. you have to apply gain to the media to make it work on web, audio levels >100% don't exist in the web audio api nor on media elements for good reason. until the plugin is updated to support this it'll only be supported on discord desktop

**Comment by Vendicated** [comment]
closed in favour of https://github.com/Vencord/Vesktop/issues/331
