### ISSUE TITLE
Question about app.asar

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#580]
### Content

Hi there.

First of all, I'm using this blank issue template because this is a question, and not a bug report or a feature request.

So, my question is: I found that Vesktop uses (or seems to use) an `app.asar` file, found in `/opt/Vesktop/resources/app.asar`.

Considering the file size (16 megabytes), is this the official Discord client `app.asar`? If so, would it be possible to replace it with OpenAsar or somehow integrate it with Vesktop?

I have seen #112, but I am making this issue to make it clear for me and maybe for future other people.

My question is in which parts Vesktop's `app.asar` is different or similar to the official one used by Discord.

Thanks in advance.

**Comment by Vendicated** [comment]
no. it's just vesktop's code. it has 0 similarity with discord's code. you cannot use openasar

**Comment by Interpause** [comment]
another interesting idea then would be if you could reduce the code size of app.asar to beat openASAR. but when i took a look at openASAR's github, i realised that dude is a madlad they don't even have a package.json and their toolchain is shell scripts. hard to beat that kind of minimalism
