### ISSUE TITLE
[Bug] Vesktop opens share-picker multiple times

### ISSUE THREAD

**Issue by myryk31415** [Vencord/Vesktop#583]
### Operating System

OpenSUSE Tumbleweed

### Linux Only ~ Desktop Environment

Hyprland

### What happens when the bug or crash occurs?

When pressing screen-sharing multiple popus open in this order (next one opens when selecting something):
1. hyprland-share-picker
2. Discord/Vesktop screenshare popup for quality etc
3. hyprland-share-picker
4. hyprland-share-picker

If I select the same screen 3 times in hyprland-share-picker it streams as expected, otherwise the stream opens after the Discord popup but doesn't load.

### What is the expected behaviour?

Selecting a screen once should probably be enough.

### How do you recreate this bug or crash?

1. open Vesktop
2. join voicecall
3. select screen sharing
4. now the popups open one after another

### Debug Logs

Idk what I should log, I could provide dbus-monitor if that helps.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by AAGaming00** [comment]
As a temporary workaround, tick "allow a restore"

**Comment by zbigniewpaczynski** [comment]
Same thing happens on Arch with KDE

**Comment by Vendicated** [comment]
issue with your desktop environment / chromium

**Comment by Different-Name** [comment]
Has anyone made an upstream issue for this? I believe it is chromium and not the desktop environment issue, as OBS has no problems

**Comment by myryk31415** [comment]
Thx! ig that should have been done a while ago. Also great username

**Comment by Different-Name** [comment]
Not a bug with chromium or desktop environment

https://issues.chromium.org/issues/354537406#comment13

> This is also expected. You have to use "Allow restore token" to avoid the second portal dialog. This is because you first get a portal dialog to pick a screen/window to share for the preview dialog and once you confirm, you get another portal dialog to pick a screen/window for the web page itself. For that reason we use the restore token to avoid the second portal dialog and show the same content on the web page that was selected for the preview dialog. OBS doesn't do that, because it works differently.

A picker prompt is created by Vesktop for the `SCREENSHARE` menu, to display the preview
The stream settings are confirmed and then only a second dialogue should be created for the stream itself

The third dialogue should not occur (in my opinion at least). I would assume that it is because discord is creating a preview somewhere in the background resulting in the following:

1. Picker for sharescreen preview
2. Picker for internal sharescreen preview
3. Picker for actual sharescreen

Discord in browser generates two prompts as expected, though I have issues with Discord in browser, and the calls wont connect properly (stream never loads), so cannot verify this isn't upstream at Discord

@Vendicated

**Comment by Different-Name** [comment]
I'll also add that this is why `allow restore token` solves the problem, if you want both the preview and the stream itself to be the same stream, enable it - though I wonder if there's a way to default it

OBS doesnt require multiple pickers as it handles streams differently, I assume it's using the same stream for the preview and the stream itself. Unfortunate that Chromium doesn't take this approach, needing two pickers

**Comment by Different-Name** [comment]
I just got this three times in a row on google meet on brave, so likely not at all a Vesktop issue. This can remain closed, sorry for the ping. Just an unfortunate situation all around that wont be fixed upstream as it is "intended" behaviour

**Comment by myryk31415** [comment]
Happens in Firefox + discord webapp too. Kinda stupid even if it is "intended". Well /shrug

**Comment by glitchplaysgames714** [comment]
hey im having this same issue did you manage to fix this?

**Comment by glitchplaysgames714** [comment]
ticking allow restore token does not work

**Comment by Florararie** [comment]
Can confirm as of July 19th this behavior is present currently in spite of `Allow Restore Token` being ticked.

I have this as the contents of my `~/.config/hypr/xdph.conf`

```
screencopy {
    allow_token_by_default = true
}
```

The behavior is *NOT* present in the official Discord package. Nor in the browser, OBS, or anything else I tried.

This seems to only appear in *Vesktop* specifically.

**Comment by Florararie** [comment]
If any information is needed on the matter, please direct me to what you need and I will be more than happy to provide if I am able to do so.

**Comment by pedro-anthony** [comment]
Working on my machine as of version 1.6.5-1, only need to select once on XDPH for screen share to begin.

allow_token_by_default set to true in xdph.conf

**Comment by Florararie** [comment]
> Working on my machine as of version 1.6.5-1, only need to select once on XDPH for screen share to begin.

Now works as intended as of latest system update so the issue is no longer present for me as well.

Damn thee Chromium lol
