### ISSUE TITLE
[Bug] Rich Presence does not work with Proton

### ISSUE THREAD

**Issue by Sollace** [Vencord/Vesktop#584]
### Operating System

Manjaro

### Linux Only ~ Desktop Environment

KDE

### What happens when the bug or crash occurs?

When running a steam game that uses Proton, Vesktop does not pick that up for rich presence. Native steam games work fine, and normal steam is able to detect all steam games with or without Proton.

### What is the expected behaviour?

Self-explanatory

### How do you recreate this bug or crash?

1. Install Vesktop
2. Install Steam
3. Install Crab Champions through steam
4. Play the game

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by PolisanTheEasyNick** [comment]
By default Vesktop uses arrpc for game detection. Seems like arrpc supports Crab Champions, but in some reason does not detects it in Linux. Can you send how game executable named while started using proton?

**Comment by Vendicated** [comment]
works on my machine with overwatch, also running in proton. make sure you're on vesktop 1.5.2 and try to check the game's command line to make sure it's not weird.

if the game has native rich presence support (a custom one with stuff like match info, join, etc), then it's not possible for arrpc to handle that, you need to run a [bridge](https://github.com/0e4ef622/wine-discord-ipc-bridge) in the same wineprefix 

![image](https://github.com/Vencord/Vesktop/assets/45497981/f357509e-39db-4827-9b61-ec74ce978816)

![image](https://github.com/Vencord/Vesktop/assets/45497981/7e53f181-9f3b-4458-8b56-adef2f1f0927)

**Comment by Sollace** [comment]
> By default Vesktop uses arrpc for game detection. Seems like arrpc supports Crab Champions, but in some reason does not detects it in Linux. Can you send how game executable named while started using proton?

@Vendicated 
Game's command-line arguments are the default. Using Proton Experimental and a fresh reinstall of Vesktop from yesterday.

![image](https://github.com/Vencord/Vesktop/assets/6429283/aa2c7944-e505-4580-b8d0-f7d31e3060d8)

(screenshot in windowed mode so I can capture both at once)
![image](https://github.com/Vencord/Vesktop/assets/6429283/ee47ac60-03a7-4953-b751-811524e8e942)

**Comment by Sollace** [comment]
![image](https://github.com/Vencord/Vesktop/assets/6429283/aa75cb69-3b7b-42bb-8ed4-1ee3f9dcfa63)

**Comment by Sollace** [comment]
Rich Presence is enabled in Vesktop settings.

![image](https://github.com/Vencord/Vesktop/assets/6429283/40bfacbf-24aa-4a5a-b703-f4eaae8b2a4c)

I don't know if I need to add the rich presence arpc plugin, but when I do it displays this banner:

![image](https://github.com/Vencord/Vesktop/assets/6429283/b060e46f-335b-4d30-9d87-8e3af4ab5f5f)

**Comment by Sollace** [comment]
Also using steam tinker launch with the ipc bridge running still does not work (I tried all of this before).


![image](https://github.com/Vencord/Vesktop/assets/6429283/43895869-86c4-4a58-8c3b-fba944d2696c)

**Comment by Sollace** [comment]
Playing a native game that doesn't require proton for contrast.
![image](https://github.com/Vencord/Vesktop/assets/6429283/91603159-83d5-4a20-a0d3-d8f007a3dbfd)

**Comment by Vendicated** [comment]
try running [arrpc](https://github.com/OpenAsar/arrpc) manually and see if it works. if not, report it on their repo

**Comment by Sollace** [comment]
Does not work with arrpc running either, so I guess I'm taking it upstream.

**Comment by Sollace** [comment]
Fresh reinstall of the flatpak 1.5.2, confirmed it is running arrpc and plugin is enabled:
![image](https://github.com/Vencord/Vesktop/assets/6429283/6710daba-01b1-45ab-893c-fdfc60a1ec90)

Works when I have arRPC running standalone
![image](https://github.com/Vencord/Vesktop/assets/6429283/68155747-1930-4175-94ba-9b26a13985a3)

**Comment by Sollace** [comment]
Alright, I figured out that it's a sandbox issue. The AUR version works so I'm going to be using that from now on.

Specifically the 1.5.2-2 AUR `vesktop` package (for anyone reading this). `vesktop-git`, `vesktop-bin`, and the vesktop flatpak all seem to be broken.

![image](https://github.com/Vencord/Vesktop/assets/6429283/b885afa7-57f7-4acc-9236-203da17497bb)

**Comment by jon-torres** [comment]
> Alright, I figured out that it's a sandbox issue (of the flatpak). The AUR version works so I'm going to be using that from now on.
> 
> Specifically the 1.5.2-2 AUR `vesktop` package (for anyone reading this). `vesktop-git`, `vesktop-bin`, and the vesktop flatpak all seem to be broken.
> 
> ArRPC plugin is not required.
> 
> ![image](https://private-user-images.githubusercontent.com/6429283/328528201-b885afa7-57f7-4acc-9236-203da17497bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTYyOTksIm5iZiI6MTcyMzgxNTk5OSwicGF0aCI6Ii82NDI5MjgzLzMyODUyODIwMS1iODg1YWZhNy01N2Y3LTRhY2MtOTIzNi0yMDNkYTE3NDk3YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTM0NjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmU2MWI3NTljYWVmZmUzYWRkYTA2ZDY5MGJjMDM0NzVmODkwNDg3NWMxOGExZTM5OTkzZDViMTkzMmQ2MTViNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yHcnuxyugqeT4ygEfkvpJ4K4o5M5QCzDPAzCBIZodzA)

I have it installed with the .deb (1.5.3) on ubuntu 22 and I cannot get it to recognize Waven (running with proton experimental). The steps are the same as of the op running with `/usr/bin/vesktop --enable-features=UseOzonePlatform --ozone-platform=x11`.
