### ISSUE TITLE
Vesktop not passing through audio

### ISSUE THREAD

**Issue by zazFe** [Vencord/Vesktop#586]
### Discord Account

Keeping to self

### Operating System

Debain 12 (Bookworm)

### Linux Only ~ Desktop Environment

KDE (Wayland)

### What happens when the bug or crash occurs?

i try to start a screenshare which is able to show my screen but no audio passes through at all. I have also tried on launching it with commands specifically with this command which showed me a few errors when screensharing. Side note the screenshare portal also opens up twice before screensharing.

Command: "vesktop %U --enable-features=UseOzonePlatform --ozone-platform=wayland"

### What is the expected behaviour?

Screenshare is able to share screen but not pass through audio.

### How do you recreate this bug or crash?

Starting screenshare

### Debug Logs

these are the errors i was talking about when i used the command

![error](https://github.com/Vencord/Vesktop/assets/117706109/5eadf4fb-3159-4bbc-bddf-df762672548c)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Sqaaakoi** [comment]
sounds like `libc6` package in Debian 12 isn't new enough, try using the flatpak

**Comment by zazFe** [comment]
hey sorry for the late response figured out a few new things, you're right that library is out of date so i went to the flatpak but now i have issues with wayland and X11 as this error now comes up.

 
![error2](https://github.com/Vencord/Vesktop/assets/117706109/83c2bfc3-1749-4e8f-b153-9144690d9b2d)

**Comment by SoulInfernoDE** [comment]
I am using the [AppImage](https://github.com/Vencord/Vesktop/releases/download/v1.5.2/Vesktop-1.5.2.AppImage) and thats working fine but i cannot start  a screenshare (hangs) when i install the VC directly and that seems related to the glibc, too.

You need to set the appimage to executeable to run it though.

**Comment by Curve** [comment]
Please read the note in the Screenshare Dialog, your systems glibc / c++ runtime is too old.

**Comment by Curve** [comment]
> but i cannot start a screenshare (hangs) when i install the VC directly and that seems related to the glibc, too.

This is probably #616
