### ISSUE TITLE
Custom launch arguments

### ISSUE THREAD

**Issue by SmilerRyan** [Vencord/Vesktop#588]
### Discord Account

SmilerRyan

### Motivation

Related to issue #23, I'd like to be able to set custom launch arguments for Vesktop without having to make a custom shortcut of Vesktop with my arguments, such as changing the data directory, auto start options, and others. It would also allow the Portable version to be able to be even more portable, by not relying on an extra file on the system (outside the installation directory) for portable builds.

### Solution

Create a launch_arguments.txt file that is built along with all versions of Vesktop.
Portable versions can have the default argument ``--user-data-dir=Data`` as default.
All other versions can have an empty file, and users can manually edit this as they like.

### Alternatives

Another alternative is to not include this file, and in the code just check if this file exists and use the arguments provided.

### Additional context

Here is a mockup of how a portable version would look if arguments were set to put the data folder with the vesktop installation.

I would tag this enhancement instead of bug, however I don't see any option to change this. I think GitHub automatically tagged this as a bug for me.
![image](https://github.com/Vencord/Vesktop/assets/14893385/249479b3-0156-4841-b78d-fc4eb4c9c5b4)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
your use case seems to just be a portable data dir for portable installs

the logic for portable installs just needs to be fixed to use like `DirectoryOfVesktopExe/data`, it doesnt make much sense outside of portable installs imo

**Comment by SmilerRyan** [comment]
Correct, my use case is to be able to store the data with the application itself, making it use a fixed data directory if it exists.
Not only does this help isolate data more, it also makes running multiple instances and backups easier for me as well.

**Comment by Vendicated** [comment]
since the main motivation has been resolved now, i will be closing this. like i said, there is no good way to do this in a cross platform way
