### ISSUE TITLE
Windows 8.1 does not work

### ISSUE THREAD

**Issue by TheCoolerMS3** [Vencord/Vesktop#59]
![image](https://github.com/Vencord/Vesktop/assets/62806964/c12e2f52-e04d-441a-ba34-40a3b6226f77)

I know Windows 8.1 is old, but as the official Discord client may not support it for much longer, so it would be pretty sick if Vencord was able to get it working again

**Comment by Vendicated** [comment]
Not supported. Upgrade to Windows 10+
