### ISSUE TITLE
[Bug] Rich presence doesn't work at all on OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by Lyvelion** [Vencord/Vesktop#593]
### Discord Account

lyvelion

### Operating System

OpenSuse Tumbleweed

### Linux Only ~ Desktop Environment

KDE

### What happens when the bug or crash occurs?

I previously used Vencord itself, which does not display the game status correctly. I read on reddit that Vesktop allows you to use Rich Presence. I installed the flatpak version [also tried appimage]. When you start the game, nothing happens - no status appears. I tried with games using Proton and with native ones.

 I haven't checked too many things because I've been using Linux for a short time and I don't know where to start, only that the Rich Presence option is enabled in Vesktop settings.

### What is the expected behaviour?

I expect Rich Presence to appear on my profile and in the bottom left corner of Vesktop app after starting the game

### How do you recreate this bug or crash?

1. Start Vesktop app on OpenSuse Tumbleweed
2. Enable Rich Presence in Vesktop options
3. Play any game 

### Debug Logs

Console says it works but I don't think so :(
![Zrzut ekranu_20240508_214407](https://github.com/Vencord/Vesktop/assets/169302470/ee03aeb0-7d6f-4fb2-9d14-6c6ba07f53eb)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
https://github.com/flathub/dev.vencord.Vesktop?tab=readme-ov-file#discord-rich-presence
