### ISSUE TITLE
[Bug] All graphical elements appear pixelated on 200% scaling

### ISSUE THREAD

**Issue by coolkys** [Vencord/Vesktop#595]
### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

Gnome on Wayland

### What happens when the bug or crash occurs?

All graphical elements(text, icon, images, buttons etc.) appear pixelated, as if it were being rendered at 1080p and naïvely enlarged, not scaled, leading to visible pixelation of all elements.
![image](https://github.com/Vencord/Vesktop/assets/26796959/c079eb4d-7bef-4d1b-9069-3d45618163df)
![Screenshot from 2024-05-09 21-41-52](https://github.com/Vencord/Vesktop/assets/26796959/485bb61e-4519-4645-823c-d416361dc8e6)
[Image 1, 2: Vesktop appearing pixelated]

![image](https://github.com/Vencord/Vesktop/assets/26796959/35f0ed92-0147-4cc2-9724-d10df5731cbf)
![image](https://github.com/Vencord/Vesktop/assets/26796959/d7ceaa49-3b13-434d-a9ce-2f3c6637fb67)
[Image 3, 4: Reference; Discord, taken at same resolution and size]

### What is the expected behaviour?

I expect graphical elements to appear properly scaled, without any pixelation.

### How do you recreate this bug or crash?

I am using the official Flatpak version of Vesktop, version 1.5.2
My setup is as follows: 7700X/7900XTX, two 4K monitors, resolution set to 4K and scaling at 200%
Launch the app. Both the loading card and the main application suffers from the same symptom.

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by coolkys** [comment]
Hi, my bad for not reading the instructions; How may I be able to disable GPU acceleration? It should be under User Settings>Advanced but unfortunately I'm not seeing the option there.

**Comment by Vendicated** [comment]
inside vesktop settings! unsure if that'll fix it though, it might just be an issue with your DE/wayland

either way this is out of our control since rendering is done by chromium
