### ISSUE TITLE
[Bug] window goes offscreen

### ISSUE THREAD

**Issue by LunarcatOwO** [Vencord/Vesktop#597]
### Discord Account

LunarcatOwO

### Operating System

Windows 11

### What happens when the bug or crash occurs?

if i close vesktop (end it ccompleatly) while its on a second screen then disconnect that screen the next time I start vesktop it will just go off screen and is unable to be retrived

### What is the expected behaviour?

Expect vesktop to snap back on to main screen.

### How do you recreate this bug or crash?

close vesktop (end it ccompleatly) while its on a second screen then disconnect that screen the next time I start vesktop it will just go off screen and is unable to be retrived

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```
Do not have any

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by LunarcatOwO** [comment]
and the only way to retrieve the window is by using alt+space to open a windows menu to select move and use the arrow keys to move vesktop back to main window

**Comment by MrGarlic1** [comment]
I was able to reproduce this issue on Windows 10 using a laptop and external display. It appears that Windows does not have a check to prevent apps from starting out of bounds, which Vesktop will attempt to do if the display is removed.
