### ISSUE TITLE
[Bug] Vesktop crash upon startup

### ISSUE THREAD

**Issue by Glitchitee** [Vencord/Vesktop#599]
### Discord Account

Glitchite

### Operating System

Debian

### Linux Only ~ Desktop Environment

Wayland and X11 were tried.

### What happens when the bug or crash occurs?

A few seconds upon booting it crashes. No matter if I uninstall or delete all the prior data. 

### What is the expected behaviour?

I expect it to open and not close automatically

### How do you recreate this bug or crash?

Install vesktop. I assume on Debian with Plasma X11 or Wayland.

### Debug Logs

```
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:0510/154207.163089:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0510/154207.406331:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0510/154207.406378:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(node:3) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/k/.var/app/dev.vencord.Vesktop/config/vesktop/settings/quickCss.css'
(Use `vesktop.bin --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
please share the entire stacktrace and show a screen recording

**Comment by Glitchitee** [comment]
> please share the entire stacktrace and show a screen recording

I uh figured it out. I installed the wrong one somehow by accident. ^^;
