### ISSUE TITLE
"Failed to connect to arRPC, is it running?"

### ISSUE THREAD

**Issue by ValerianSan** [Vencord/Vesktop#60]
As the title describe. Fresh installation of Vencord client on windows 11. The client keep sending the title message at top border of the screen and clicking Retry doesn't change anything. Relaunching Vencord isn't either.

Any idea how to fix this ?

Thanks per advance.

![image](https://github.com/Vencord/Vesktop/assets/9287378/2394aa7e-0d08-4b51-9875-62771e0ce5b4)

**Comment by ValerianSan** [comment]
Ah, I forgot to mention, I made the server running and everything asked to make arRPC running through node. Presence is detected with the right application within the powershell prompt of arRPC but Vesktop still fails to connect.
![image](https://github.com/Vencord/Vesktop/assets/9287378/83a22c7e-62ae-4172-9204-79602510f273)

**Comment by Vendicated** [comment]
dont run arrpc separately. it's included

**Comment by ValerianSan** [comment]
Well, I tried to run it separatly because the included version doesn't work somehow, even with a fresh installation.

**Comment by Eidenz** [comment]
Same issue, fresh install of Vesktop and I get "Failed to connect to arRPC, is it running?" even though I did not install arRPC separately.

**Comment by x4132** [comment]
I have this same issue. Launching from terminal confirms arrpc is running, and detects processes.

**Comment by Jeymen** [comment]
Same issue here!

**Comment by SuperCater** [comment]
Encountering the same issue here a fresh install just today. Verified using nestat that vesktop is in fact using the port for it however it just fails to connect.
![image](https://github.com/Vencord/Vesktop/assets/84566931/bc493dce-1311-475a-954c-8eed5bb5f2f0)

**Comment by UwUDev** [comment]
I have the same issue on widows 10 (1809), i just installed it and vesktop is listening on 1337.
But it perfecly works on fedora 38
![image](https://github.com/Vencord/Vesktop/assets/61664271/5bc5e2ff-b78d-45db-aa64-13e4ee90d3b2)

**Comment by Vendicated** [comment]
Fixed in https://github.com/Vencord/Vesktop/commit/0d93e08e99046549c4583f04c865ffd70107c712

**Comment by PoorPocketsMcNewHold** [comment]
> dont run arrpc separately. it's included

Is it? Because it is still refusing to connect until I actually launch arrpc separately from Vesktop. On Vencord A9e67e2 (Vesktop V0.4.2)

**Comment by ryanccn** [comment]
It is no longer included. Disable the plugin and turn on **Rich Presence** in Vesktop settings and it should work fine.

**Comment by PoorPocketsMcNewHold** [comment]
> The WebSockets server is no longer included. Disable the plugin and turn on **Rich Presence** in Vesktop settings and it should work fine.

Alrighty. However, despite your attempts at explaining that the arrpc Vencord plugin needs to be explicitly disabled, I think a note on the Vesktop settings to ask you to specifically disable the plugin, or a specific hack to “disable” this plugin to appear in Vesktop might be needed, to prevent further confusion. 
_Or you could say it's a skill issue from me, but I'm certain others will follow, especially coming from ArmCord or WebCord._

**Comment by Vendicated** [comment]
you were never supposed to enable the plugin in the first place. there is no reason for us to disable it on vesktop or to add a note, you should just not enable it unless you plan to run your own arrpc.
