### ISSUE TITLE
[Bug] vesktop starting offscreen

### ISSUE THREAD

**Issue by LunarcatOwO** [Vencord/Vesktop#604]
### Discord Account

LunarcatOwO

### Operating System

Windows 11

### What happens when the bug or crash occurs?

#597 samething is still happening

### What is the expected behaviour?

not to go offscreen

### How do you recreate this bug or crash?

same as #597 

### Debug Logs

N/A

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by LunarcatOwO** [comment]
it still is a bug 💀

**Comment by Vendicated** [comment]
it hasn't been published yet. if you want it early, you need to build the latest main branch from source

please do not open duplicate issues, you can just comment on the previous one

**Comment by AAGaming00** [comment]
because there was no new release yet
