### ISSUE TITLE
[Bug] High Memory Usage

### ISSUE THREAD

**Issue by Lythium4848** [Vencord/Vesktop#605]
### Discord Account

lythium4848

### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

KDE 6 on Wayland - Running vesktop under native wayland using `--enable-features=UseOzonePlatform --ozone-platform=wayland` launch args

### What happens when the bug or crash occurs?

Vesktop uses extremely high amounts of memory
![image](https://github.com/Vencord/Vesktop/assets/62567544/ca00e209-b3bf-490c-bbd5-a3516a4e06ce)

### What is the expected behaviour?

Vesktop to not be using large amounts of memory

### How do you recreate this bug or crash?

Unknown - Was screensharing in a vc at the time and regular discord use

### Debug Logs

```
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
can't reproduce. not a vesktop issue
