### ISSUE TITLE
[Bug] Vesktop is unable to send full desktop screenshots in chat.

### ISSUE THREAD

**Issue by Shell1010** [Vencord/Vesktop#608]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

KDE

### What happens when the bug or crash occurs?

When attempting to send a screenshot of my entire desktop, it states "Upload Failed... Something went wrong". When checking the networking tab it responds with a 400 Bad Request upon trying to send the message. This only applies when trying to capture an entire window.

### What is the expected behaviour?

I expect Vesktop to just send the message containing the image.

### How do you recreate this bug or crash?

1. Screenshot the entire window
2. Attempt to send a message with the image
3. Responds with 400 Bad Request and your message does not send

### Debug Logs

There are no errors when starting Vesktop from the command line.
```
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```

It uses the usual endpoint, using a POST request.
`/channels/channel-id-here/messages`

This is the json payload.
```json
{
   "content":"",
   "nonce":"1240725038756265984",
   "channel_id":"1228784357989417011",
   "type":0,
   "sticker_ids":[
      
   ],
   "attachments":[
      {
         "id":"0",
         "filename":"image.png"
      }
   ]
}
```
This is the Json Response data.
```json
{
    "message": "Invalid Form Body",
    "code": 50035,
    "errors": {
        "attachments": {
            "0": {
                "_errors": [
                    {
                        "code": "ATTACHMENT_NOT_FOUND",
                        "message": "Attachment data not found"
                    }
                ]
            }
        }
    }
}
```

I am able to send screenshots/images that are not my entire window. And I have found that when I am able to successfully send messages with those screenshots I'm guessing it tries to upload those images to discord first via the `/channels/channel-id-here/attachments` with a POST request. 

The json payload holds
```json
{
   "files":[
      {
         "filename":"image.png",
         "file_size":106086,
         "id":"10",
         "is_clip":false
      }
   ]
}
```

It then responds with some json data, stating the upload url with an upload id in the query parameter, in which the client should send the files to and also the filename and id. Next the client sends a OPTIONS to the url and then a PUT request to the same url with the image data.

However, I find that these steps are not taken when trying to upload the a screenshot of my entire window. The file size is about 2mb and I am able to easily send 2mb and higher images via discord, and this for some reason seems to be an issue with just me taking a screenshot of my window.

I apologise for writing so much I am not sure what to usually provide so I tried to give as much detail as possible, please ask if there is any extra information required.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by PolisanTheEasyNick** [comment]
Thank you for detailed description! Can you try to reproduce it in stock discord web in browser?

**Comment by Vendicated** [comment]
not a vesktop issue. all web code including uploads is handled by discord
