### ISSUE TITLE
[Bug]: Screensharing does not support HDR

### ISSUE THREAD

**Issue by VelvetToroyashi** [Vencord/Vesktop#61]
👋🏽 When using screensharing, if HDR is enabled on a monitor, the entire screen becomes unavailable for screensharing. When selecting a window running on the monitor with HDR, the output is a black screen while focused, but the preview does work correctly when tabbed out.

Enabling HDR *while* screensharing also seems to have no effect (that is to say, HDR can be enabled, and enabling it does not cause the black screen).

HDR off:
![image](https://github.com/Vencord/Vesktop/assets/42438262/6ead4a85-bbf8-43c5-9708-ce4bb1775f34)

HDR on:
![image](https://github.com/Vencord/Vesktop/assets/42438262/6ca35003-e471-4454-8a0e-c0fc77edd5b8)

**Comment by Vendicated** [comment]
does this work correctly on Discord desktop?

**Comment by VelvetToroyashi** [comment]
Unless Discord broke it recently, yes.

**Comment by Vendicated** [comment]
since we just use electron's api to get your screens, this is likely an electron limitation. though I can't find any issues regarding this on Google

**Comment by VelvetToroyashi** [comment]
Quite peculiar. Suppose I have a weekend deep dive; I'll let you know if I stumble upon anything.

**Comment by l-zeuch** [comment]
This appears to be further upstream than just Electron. A quick search
on the Chromium bug tracker render quite a few results related to HDR
colour mapping issues, which I assume a black screen is a symptom of.

https://bugs.chromium.org/p/chromium/issues/list?q=component%3AInternals%3EGPU%3EVideo%3EHDR&can=2
