### ISSUE TITLE
[Bug] Juttering when mousing over web browser being streamed

### ISSUE THREAD

**Issue by stawze** [Vencord/Vesktop#611]
### Discord Account

@stawz

### Operating System

EndeavourOS

### Linux Only ~ Desktop Environment

Plasma on Wayland

### What happens when the bug or crash occurs?

The video jutters when moving the mouse around on the screen, causing an unpleasant viewing experience.

### What is the expected behaviour?

Smooth video unaffected by mouse movements

### How do you recreate this bug or crash?

1. Enter a voice channel
2. Start streaming
3. Select the web browser window or screen in the portal pop-up
4. Start streaming and moving the mouse over the window

https://github.com/Vencord/Vesktop/assets/90922963/5d4f6ce0-31fc-47cd-bd48-5b05524bdbb2

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by PolisanTheEasyNick** [comment]
Will be fixed here: https://issues.chromium.org/issues/333945842
And then we must wait for electron to use this fixed version of chromium and use this electron version in Vesktop.

**Comment by stawze** [comment]
Thank you @PolisanTheEasyNick. It's good to know that there is a path to solving this issue. I'll close this issue now.
