### ISSUE TITLE
[Bug] Receiving push notifications while the application is open in a chat

### ISSUE THREAD

**Issue by ETJAKEOC** [Vencord/Vesktop#612]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

KDE Plasma 6

### What happens when the bug or crash occurs?

I receive a push notification on my phone

### What is the expected behaviour?

I should not be getting push notifications when I'm sitting in the fucking chat on my desktop

### How do you recreate this bug or crash?

Just use the application

### Debug Logs

```
You don't get logs, fix your shit program.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
don't be so rude. this is freely available and free of charge software developed by people in their free time, have some respect to maintainers

you have been blocked and reported to github.
