### ISSUE TITLE
[Bug] Uploading files by Drag & Drop renders Vesktop unresponsive

### ISSUE THREAD

**Issue by GuardianLiarus** [Vencord/Vesktop#614]
### Discord Account

Liarus

### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

KDE 6.0.4 - Wayland

### What happens when the bug or crash occurs?

When uploading a file via Drag & Drop, the files are added to the message, but the client becomes unresponsive to the mouse, it cannot interact with the discord client until it is closed and restarted (ctrl + r does not fix the issue)

### What is the expected behaviour?

Ability to upload files without the client becoming unresponsive

### How do you recreate this bug or crash?

Use KDE 6 with Wayland
Drag and drop a file into the discord client, in my case i use a .txt file.

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by k26pl** [comment]
are you using flatpak? If yes, the file you are trying to upload is probably not in a directory that discord can access. Ether add vesktop permissions to access that dir or use the file picker appearing after using plus button

**Comment by GuardianLiarus** [comment]
> are you using flatpak? If yes, the file you are trying to upload is probably not in a directory that discord can access. Ether add vesktop permissions to access that dir or use the file picker appearing after using plus button

Yes i am, i did think of that and the issue happens no matter where the file is.

As for the file picker, it works just fine, the bug report is only for drag and drop.

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/issues?q=is%3Aissue+drag+and+drop+
