### ISSUE TITLE
[Bug] Blinding white light in Dark Mode

### ISSUE THREAD

**Issue by vikingnope** [Vencord/Vesktop#617]
### Operating System

MacOS Sonoma 14.5

### What happens when the bug or crash occurs?

There is a blinding white light on pop ups and texts. No theme is applied.

<img width="182" alt="Screenshot 2024-05-22 at 10 22 00" src="https://github.com/Vencord/Vesktop/assets/81376423/5859bc24-4270-465a-ad18-03247ba963b3">

<br/><br/>

<img width="1118" alt="Screenshot 2024-05-22 at 10 22 16" src="https://github.com/Vencord/Vesktop/assets/81376423/8c6c74d1-cb94-492c-a1ef-6a2f0634272a">

<br/><br/>

<img width="1123" alt="Screenshot 2024-05-22 at 10 22 40" src="https://github.com/Vencord/Vesktop/assets/81376423/cee98484-ccee-4057-bb07-3cd962a90e4a">

### What is the expected behaviour?

Should be dark mode normally.

### How do you recreate this bug or crash?

1. Have MacOS
2. Open Vesktop
3. Open a server and find a message and hover over it.

### Debug Logs

```
N/A
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by rozbrajaczpoziomow** [comment]
![image](https://github.com/Vencord/Vesktop/assets/58668179/8abe59b1-e3da-47e0-b318-b3f866d170cb)
![image](https://github.com/Vencord/Vesktop/assets/58668179/32792fb2-c71d-4f34-a125-4bcd9b89c9ca)
without the nitro theme applied (i.e. on clean dark mode) it also doesn't happen
/shrug

**Comment by rozbrajaczpoziomow** [comment]
are you sure you don't have any quickcss or themes on?

**Comment by vikingnope** [comment]
I just fully reinstalled and left settings sync off, and it seems to be working fine now, any ideas because I would like to have settings sync on.

**Comment by rozbrajaczpoziomow** [comment]
probably some theme / quickcss you have on?

**Comment by vikingnope** [comment]
Will close this since its "me only" issue and check on my main pc when I get home, thank you for your help :)
