### ISSUE TITLE
[Linux][X11] Audio Sinks as Stream Input

### ISSUE THREAD

**Issue by Yoshi72** [Vencord/Vesktop#619]
### Discord Account

apostle_of_floof

### Motivation

When selecting an audio source for a screen share, you can only select "Entire System" or individual apps.
Entire Audio obviously isn't exactly the greatest choice when using sinks, as it even connects the sinks discord is piped into (meaning viewers will hear themselves in the stream).
![Entire System](https://github.com/Vencord/Vesktop/assets/8786791/fe02aac7-3807-45d5-af73-792b2d2e496a)

The second option of selecting individual apps isn't working as great either. Some apps/games just don't appear in the list (E.g. Rabbit and Steel), and some other games take ALL nodes related to the game, including input/microphone nodes.
![Helldivers](https://github.com/Vencord/Vesktop/assets/8786791/5b7b8c9e-b6db-43c9-a89d-2d627db80586)

### Solution

Enable selecting audio sinks and/or indidivual devices as audio source for streams, similar to how it works in discords voice settings.

### Alternatives

I tried manually setting the connections in qpwgraph, but starting a new stream/changing the audio source will reset all connections, forcing me to manually set/remove each connection again. Exclusive Mode fixes this issue, but forces you to connect new nodes manually to devices and such.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Curve** [comment]
>Entire Audio obviously isn't exactly the greatest choice when using sinks, as it even connects the sinks discord is piped into (meaning viewers will hear themselves in the stream).

Not entirely sure what you mean. The entire desktop audio option explicitly excludes vesktop.

> and some other games take ALL nodes related to the game, including input/microphone nodes.

We explicitly only select nodes that are not input nodes afaicr

> Enable selecting audio sinks and/or indidivual devices as audio source for streams, similar to how it works in discords voice settings.

This is in theory already possible as venmic supports that behavior - It is just not exposed in the UI

**Comment by Curve** [comment]
Thanks for the dumps and clarification!

This is really a rather unusual setup, I think simply adding some sort of "export" mode would be best here.
However, I'll see if I can find a way to fix the Helldivers Issue or if Helldivers simply does bad audio managing (same for Rabbit and Steel)

**Comment by Curve** [comment]
[Screencast_20240531_003330.webm](https://github.com/Vencord/Vesktop/assets/37805707/ef27874f-d3f5-4408-8e8e-26fa5bf1369e)

(Sorry for the bad quality, blame Spectacle)

This is how the granular selection of #621 looks, which should give you enough free-room to select the specific audio device you want to stream from :)

**Comment by pallaswept** [comment]
OP's method of handling audio is what's known as "mix bussing". I do the same, and you'll probably find it common among those recording or streaming or performing live. Thought I'd leave a keyword here for search engines in case anyone wants to read into it. Hope that's helpful, and big thanks to everyone who helped add this to vencord!

> should give you enough free-room to select the specific node you want to stream from :)

Looks good! I worry I might break the UI if there's a few dozen nodes in that dropdown? Sorry I haven't read into the widget set you're using. I'd offer to test the fork, but I've a few other outstanding screensharing bugs with KDE, so my machine is not a stable test platform right now. My apologies. I figured it's probably best to just ask :)

**Comment by Curve** [comment]
> OP's method of handling audio is what's known as "mix bussing". I do the same, and you'll probably find it common among those recording or streaming or performing live. Thought I'd leave a keyword here for search engines in case anyone wants to read into it. Hope that's helpful, and big thanks to everyone who helped add this to vencord!
> 

Thanks for the keyword! This will definitely be useful for a new settings description :)

> Looks good! I worry I might break the UI if there's a few dozen nodes in that dropdown? Sorry I haven't read into the widget set you're using. I'd offer to test the fork, but I've a few other outstanding screensharing bugs with KDE, so my machine is not a stable test platform right now. My apologies. I figured it's probably best to just ask :)

I think the dropdown will just scroll but will test it to make sure :)

**Comment by Curve** [comment]
![image](https://github.com/Vencord/Vesktop/assets/37805707/ca289d86-e272-4175-ad31-e86c80e1c0cb)

Yep, gets a scroll bar in the dropdown

**Comment by Curve** [comment]
I've now added a lot of settings that should hopefully improve the audio streaming for people leveraging "mix bussing".  
See #621 for more information :)

I hope the new settings are as helpful as I hope them to be, as I could not test this on a real mix bussing setup, however, I tried to simulate to my best ability and took very helpful data from the provided pw-dump ^^

**Comment by pallaswept** [comment]
Nice! Thanks mate.

**Comment by AAGaming00** [comment]
> [Screencast_20240531_003330.webm](https://github.com/Vencord/Vesktop/assets/37805707/ef27874f-d3f5-4408-8e8e-26fa5bf1369e)
> 
> (Sorry for the bad quality, blame Spectacle)
> 
> This is how the granular selection of #621 looks like, which should give you enough free-room to select the specific node you want to stream from :)

This really shouldn't be closing the dropdown on each click, that's bad UX

**Comment by Curve** [comment]
> This really shouldn't be closing the dropdown on each click, that's bad UX

Thanks for bringing this up, I wanted to fix that yesterday but forgot :D

**Comment by pallaswept** [comment]
Just had the first chance to try this in 1.5.3 and I have to say, this is amazing, really, really well done. It seems simple and easy to use, just like before... and has hidden magic powers, with all of the filtering toggles I wish everything had. What a great UX. Bravo. Thanks!

**Comment by Curve** [comment]
> Just had the first chance to try this in 1.5.3 and I have to say, this is amazing, really, really well done. It seems simple and easy to use, just like before... and has hidden magic powers, with all of the filtering toggles I wish everything had. What a great UX. Bravo. Thanks!

Thanks for the kind words :D

**Comment by Enovale** [comment]
Is disabling the "Ignore Input" setting supposed to allow for selecting a microphone device? I want to include my microphone when streaming Lethal Company but I can't figure out any way to include the device in vesktop. Using qpwgraph causes crackling so I can't use that.

**Comment by Curve** [comment]
> Is disabling the "Ignore Input" setting supposed to allow for selecting a microphone device? I want to include my microphone when streaming Lethal Company but I can't figure out any way to include the device in vesktop. Using qpwgraph causes crackling so I can't use that.
> 
> EDIT: I also can't seem to use sinks either even if i turn off all the ignore flags

You are not intended to actually select sinks or devices as options, the toggles are meant to prevent unintentional sharing of them when selecting entire desktop audio

**Comment by Curve** [comment]
> Using qpwgraph causes crackling so I can't use that.

qpwgraph is not to blame here, it's probably an issue with your audio configuration

**Comment by Curve** [comment]
> Is disabling the "Ignore Input" setting supposed to allow for selecting a microphone device? I want to include my microphone when streaming Lethal Company but I can't figure out any way to include the device in vesktop. Using qpwgraph causes crackling so I can't use that.

Selecting a device to share is now possible on main
