### ISSUE TITLE
Screenshared Stream Stutters when moving the mouse cursor

### ISSUE THREAD

**Issue by Cherryda** [Vencord/Vesktop#622]
### Discord Account

robotta_cherry

### Operating System

Fedora 40
Nvidia GTX 1060, 555 driver (happens from 535 to 555 in all my testing) 

### Linux Only ~ Desktop Environment

KDE Plasma, Wayland

### What happens when the bug or crash occurs?

The behavior occurs when screensharing with audio (I haven't checked without audio) 

The stream constantly stutters as long as I'm moving my cursor. 

### What is the expected behaviour?

I expect the stream to perform as usual, despite if the cursor is moving or not. 

### How do you recreate this bug or crash?

1. Launch Vesktop
2. Start a stream, preferably with audio
3. Move your mouse while looking at the stream preview
4. Stutters should occur

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by PolisanTheEasyNick** [comment]
It is a known bug of Chromium WebRTC streaming, for which i already created [bug report](https://issues.chromium.org/issues/333945842).
Actually it is fixed but we need to wait for Chromium devs to finally merge it, wait for new Chromium release, then wait for Electron to bump this new Chromium release and then we can use this Chromium without slutters on mouse move in Vesktop.

**Comment by oengelha** [comment]
I got the same issue. Will this be on Discord to implement new electrion version or on Vencord/Vesktop?

**Comment by PolisanTheEasyNick** [comment]
> I got the same issue. Will this be on Discord to implement new electrion version or on Vencord/Vesktop?

It will be on Electron side firstly and then on Vesktop side to pick newer Electron version.

**Comment by oengelha** [comment]
Thank you for the explanation!

**Comment by Cherryda** [comment]
> The fix has finally arrived in the stable version of Electron 31. I think it's time to pick new Electron version on Vesktop side. I rebuilt Vesktop using system Electron and it completely fixed issue

That's great to hear. Is the Vesktop team interested in updating to Electron 31? For many, this is the final remaining screen sharing issue, so this fix would be ideal to have.

**Comment by Vendicated** [comment]
should be fixed via https://github.com/Vencord/Vesktop/commit/1a4d173bb40bd2d5d5003cd8d42373cc1ec0f16b, which will we available in the next release
