### ISSUE TITLE
[Bug] Window Maximize / Layout Snapping disabled when window Transparency is Enabled.

### ISSUE THREAD

**Issue by furSUDO** [Vencord/Vesktop#623]
### Discord Account

sudo

### Operating System

Windows 11

### What happens when the bug or crash occurs?

![image](https://github.com/Vencord/Vesktop/assets/56691830/166c0115-7631-4df8-b412-d81d8dd4981c)

When any of the `Transparency Options` are enabled under `Vesktop Settings`, you are no longer able to use the maximize window button, nor are you able to snap the Vesktop window to any of the snap layouts, as seen below:

![image](https://github.com/Vencord/Vesktop/assets/56691830/972dae73-2a51-45f7-8db7-930f1b7fffa7 'Maximize window button disabled')

### What is the expected behaviour?

Operational maximize window button when any window transparency option is selected.

### How do you recreate this bug or crash?

1. Enable a window `Transparency Option`
2. Try maximize the window

### Debug Logs

n/a

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
it's either or
