### ISSUE TITLE
[Bug] Vesktop is unable to open links in my browser if my desktop environment is set to KDE via the env variable

### ISSUE THREAD

**Issue by AstralPhnx** [Vencord/Vesktop#626]
### Operating System

Linux, Fedora Silverblue

### Linux Only ~ Desktop Environment

Gnome on Wayland

### What happens when the bug or crash occurs?

It's kind of hard to sum this one up in the title so I'll explain it here in more detail

With specifically the native version of Vesktop, if I pass the following two environment variables to it in order to get tray notifications working under GNOME, it becomes unable to open any links I click in my browser, clicking a link just results in nothing happening.

Said Environment variables are:
XDG_CURRENT_SESSION=KDE
XDG_CURRENT_DESKTOP=KDE

These are used to force electron to properly talk to libunity for system tray notifications as mentioned in issue number 298.

Under GNOME, for some reason setting these variables makes Vesktop entirely unable to open my browser, but only when I'm using the native version, the same arguments passed to the flatpak version do not seem to cause this problem.

For reference, I am using Firefox in a Flatpak.

I can only imagine this is due to Vesktop trying to tap a different XDG portal when you force the DE like that to make notifications work but I cannot be entirely sure. 

### What is the expected behaviour?

Clicking on a link in chat should open that link in my web browser, instead nothing happens

### How do you recreate this bug or crash?

1. Install the Vesktop native RPM on a Silverblue based system
2. Set the environment variables of XDG_CURRENT_SESSION=KDE and XDG_CURRENT_DESKTOP=KDE
3. Launch Vesktop
4. Try to click a link, it will not open in the web browser.

### Debug Logs

```
astralphnx@fedora:~$ env XDG_CURRENT_SESSION=KDE XDG_CURRENT_DESKTOP=KDE /opt/Vesktop/vesktop --ozone-platform-hint=auto %U
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started

```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
opening links is handled entirely by electron / chromium so there's not really anything we can do. we just tell it to open the link, what it does under the hood is up to it. usually it'll just use xdg-open. what happens if you try to feed the same env vars to xdg-open?

it honestly seems kinda expected that lying about your desktop environment causes it to have wrong behaviour like this, likely trying to use some KDE specific API, so I'm not even sure this could be considered a bug

either way, you'll have to figure out where exactly this is breaking (like i said try raw xdg-open, then chromium, electron...) and open an issue there (although once again with faking your DE they might just slap you with an invalid + wontfix)

**Comment by Vendicated** [comment]
there you go. xdg-open tries to use KDE specific programs

```
❯ XDG_CURRENT_SESSION=KDE XDG_CURRENT_DESKTOP=KDE xdg-open https://github.com/Vendicated/Vencord/issues/1943
/usr/bin/xdg-open: line 622: kfmclient: command not found
/usr/bin/xdg-open: line 501: test: : integer expression expected
/usr/bin/xdg-open: line 502: test: : integer expression expected
/usr/bin/xdg-open: line 503: test: : integer expression expected
```

**Comment by AstralPhnx** [comment]
> there you go. xdg-open tries to use KDE specific programs
> 
> ```
> ❯ XDG_CURRENT_SESSION=KDE XDG_CURRENT_DESKTOP=KDE xdg-open https://github.com/Vendicated/Vencord/issues/1943
> /usr/bin/xdg-open: line 622: kfmclient: command not found
> /usr/bin/xdg-open: line 501: test: : integer expression expected
> /usr/bin/xdg-open: line 502: test: : integer expression expected
> /usr/bin/xdg-open: line 503: test: : integer expression expected
> ```

Figures, I had a hunch that might have been what was happening. I imagine the reason the flatpak works is because it's able to easily just install the KDE XDG portal as part of the runtimes so everything just works but natively the system is looking for the XDG KDE portal and not finding it so it's backfiring. 

This wouldn't really be an issue if Electron/Discord (not sure which one is the offender here) for some reason still didn't rely on libunity of all things to handle stuff like taskbar icons and stuff (an especially weird choice considering the sheer age of LibUnity now and the fact it seems to have entirely ceased development) but what can do you in the end? Linux users just get that second class citizen treatment.

Cheers for the help anyway, sorry for the not so useful issue report
