### ISSUE TITLE
[Bug] Flatpak Notifications fail to open chat when clicked on

### ISSUE THREAD

**Issue by cncz42** [Vencord/Vesktop#628]
### Operating System

Arch Linux Latest

### Linux Only ~ Desktop Environment

Plasma 6 Wayland

### What happens when the bug or crash occurs?

Clicking on notifications sent by the client simply focuses the app without changing chat channels to where the notification was sent. This behavior is the same as running the default discord client via flatpak but probably more likely to get fixed here tbh.

### What is the expected behaviour?

Clicking on a notification should open the chat channel which the message was sent from.

### How do you recreate this bug or crash?

1. Install vesktop via flathub on plasma 6 wayland
2. Click on a message notification

### Debug Logs

```
no relevant output
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
that's interesting, that should not happen. Could you please verify that this behaviour only happens on the vesktop flatpak, and not on a host install?

**Comment by cncz42** [comment]
Yes, aur version works fine on my system. I also tested the flatpak on gnome 3 and didn't have issues with notifications. It seems like this is a plasma 6 issue.

**Comment by Vendicated** [comment]
can't repro on GNOME, so yes this seems to be a system issue. nothing we can do unfortunately

**Comment by this-is-just-con-tribute** [comment]
Same, I freaking hate it. I'm on nobara.

**Comment by Duckrinium** [comment]
on Plasma 6 myself, I found now-deleted r/flatpak post mentioning same issue with "Discord", though not if it's modded or not.
they do explain that it either won't do anything upon click or would focus the window but not focus the channel.

**Comment by layershock** [comment]
I've noticed that it works just fine when running through XWayland

**Comment by Boxersteavee** [comment]
I'm experiencing this too on Fedora 41 KDE. I suspect it's a permission issue or something...

**Comment by Vendicated** [comment]
No. It's a system issue, just like I said. It works flawlessly on GNOME, it is likely just an issue with Plasma. There is nothing we can do, just like I said.

You can verify this by opening DevTools (`CTRL` + `Shift` + `I`) and running the following script to create a Notification:
```js
new Notification("hi").onclick = () => console.log("clicked")
```
Clicking this Notification should print `clicked` to the console. If it doesn't, your System's Notification implementation is broken.

**Comment by Vendicated** [comment]
https://bugs.kde.org/show_bug.cgi?id=501244
