### ISSUE TITLE
[Bug] Dragging a file into the window makes app unresponsive

### ISSUE THREAD

**Issue by Solyphonous** [Vencord/Vesktop#630]
### Discord Account

Solyphonous

### Operating System

EndeavorOS

### Linux Only ~ Desktop Environment

KDE Plasma 6.0.5 Wayland

### What happens when the bug or crash occurs?

When trying to drag and drop a file from dolphin into discord, the file will appear in the little attachments box, but all buttons within the app will become unclickable until a restart of the app. Voice calls and typing still work, everything just becomes unclickable. Hovering over buttons also does not trigger the pointer icon to appear.

### What is the expected behaviour?

The expected behavior is for buttons to continue working!

### How do you recreate this bug or crash?

1. Drag file into discord from dolphin
2. Buttons no work :-(

### Debug Logs

N/A - Performing steps to achieve bug produces no abnormal logs

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [x] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/issues?q=is%3Aissue+sort%3Aupdated-desc+drag+is%3Aclosed
