### ISSUE TITLE
[Feature request] Make spellcheck be disabled for all possible contexts when disabled

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#633]
### Motivation

![image](https://github.com/Vencord/Vesktop/assets/30274161/2d2fe1b7-5165-4f5a-83c0-114ea5ca7a92)

Spellcheck, when disabled, is only disabled in the chat window. It is not disabled in other parts of the app. This is an Electron feature.

### Solution

https://www.electronjs.org/docs/latest/tutorial/spellchecker/

https://github.com/electron/electron/blob/main/docs/tutorial/spellchecker.md

The solutions seems to be a preference flip. But I understand this may undesirable by default, so I would like to request new special code to synchronize the value of the Spellcheck option from the chat window to also apply to the app globally.

### Alternatives

I don't think any alternative would fit.

### Additional context

I don't like red underlines appearing when I did not commit any typo :(

*Office intensifies*

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
our current code just uses Discord's SpellCheckStore class and toggles its state, so all the other spellcheck logic is handled by Discord

i'm not sure if changing Discord's behaviour is a good idea. Perhaps this would be better as a Vencord plugin since the behaviour is identical on Discord Desktop app

**Comment by Vendicated** [comment]
it is possible. closing as out of scope
