### ISSUE TITLE
[Bug] Sharescreen buttons not highlighting properly 

### ISSUE THREAD

**Issue by Destroyer47** [Vencord/Vesktop#637]
### Discord Account

destroyer47

### Operating System

Manjaro Linux (KV: 6.6.32-1)

### Linux Only ~ Desktop Environment

KDE (X11)

### What happens when the bug or crash occurs?

While the share-screen feature works correctly (even better than vanilla client because of linux sound capture), for some odd reason, the stream settings GUI buttons aren't highlighting blue correctly (like the other GUI buttons in discord or vesktop). Instead, the buttons highlight themselves as the same color as the background which is difficult to differentiate from the unselected options (same color as background, but slightly darker).
(Screenshot of the menu: https://cdn.discordapp.com/attachments/1090330520090595328/1246494095497760838/unknown.png?ex=665c9797&is=665b4617&hm=3039206cd0e4694dfe028c8cf5a6a52df336f391d004e18050439a947fd42a42&)

### What is the expected behaviour?

Share-screen GUI buttons for stream settings should be highlighting themselves blue like it did a week ago, or like the vanilla client, or any other GUI button that highlights blue.
(working example image: https://dl.flathub.org/media/dev/vencord/Vesktop/308ba4f58960e9e47efcbb130fc760b5/screenshots/image-2_orig.png)

### How do you recreate this bug or crash?

1. Launch Vesktop (Both light and dark GUI settings are affected)
2. Join a VC of any kind
3. Open up 'share your screen' and select a source of any kind (Screen 1, Screen 2, etc...)
4. Notice how the stream settings GUI buttons are not highlighting the proper color blue, and instead, are highlighted the same color as the background color as the menu, while the unselected are highlighted a slightly darker shade of whatever the GUI tone is. Meaning, dark/light GUI tone will have the selected options the same shade of color as the background menu color, and the unselected options will be a slightly darker tone than the background color of the menu.
5. I even switched from the official flatpak version to the AUR version (and back) to see if it would make a difference, which it didn't since both AUR and FlatPak versions are affected. I doubt this was a setting on my end, since launching the regular discord app and opening up screenshare menu reveals that only vesktop was affected. Also, everything is up to date, and I haven't really altered any significant setting in the last week or two.

### Debug Logs

    ~  vesktop                                                                                  ✔ 
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[2024-06-01 13:42:18.168] [venmic] [info] [patchbay] (get) running venmic 3.4.2
[2024-06-01 13:42:18.174] [venmic] [info] [patchbay] (handle) found default metadata: 35
[2024-06-01 13:42:18.174] [venmic] [info] [patchbay] (meta_update) speaker name: "alsa_output.pci-0000_0e_00.4.iec958-stereo"
    ~                                                                                ✔  1m 17s  

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
already fixed via https://github.com/Vencord/Vesktop/commit/7fe79b629ead44e6d781378d8c59db04dd73ceb8
