### ISSUE TITLE
[Feature request] When screen-sharing, "Audio source" should have a default value

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#638]
### Motivation

Currently, "Audio source" doesn't have any option pre-selected.

### Solution

It should be "None" or "Entire System" by default, and this option should be required to start the stream (currently, it is not).

### Alternatives

Try to match the selected app for "Audio source", but that would require extra work which I don't think it's necessary. IIRC default Discord client doesn't let you select the audio source, and will stream only the selected app sound (or all system sounds (except itself) if entire screen is selected).

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Curve** [comment]
> Try to match the selected app for "Audio source",

This is impossible due to electron limitations currently.
