### ISSUE TITLE
[Bug] arRPC problem.

### ISSUE THREAD

**Issue by troyw1987** [Vencord/Vesktop#642]
### Discord Account

troyw1987

### Operating System

Windows 11

### What happens when the bug or crash occurs?

**"Failed to connect to arRPC, is it running?" in top of screen.**
When I press retry, this error outputs in console:
`WebSocket connection to 'ws://127.0.0.1:1337/' failed: ` `(index.tsx:80)`

Line in source from the error `(index.tsx:80)`:
`ws = new WebSocket("ws://127.0.0.1:1337"); // try to open WebSocket`

Output from the running arRPC server in powershell:
```
PS C:\Users\troyg\OneDrive\Desktop\OSS\git\arrpc> node src
[arRPC] arRPC v3.4.0
[arRPC > bridge] listening on 1337
[arRPC > ipc] not available, trying again (attempt 1)
[arRPC > ipc] listening at \\?\pipe\discord-ipc-1
[arRPC > websocket] 6463 in use!
[arRPC > websocket] listening on 6464
[arRPC > process] started
```

Full screenshot:
![image](https://github.com/Vencord/Vesktop/assets/45113942/87707ae3-7fdc-4974-ad20-5372625a1a42)

### What is the expected behaviour?

I expect for arRPC to connect with Vesktop.

### How do you recreate this bug or crash?

1. Install node from their latest install @ https://nodejs.org/en/download/prebuilt-installer
2. Run Vesktop w/ these plugins:
![image](https://github.com/Vencord/Vesktop/assets/45113942/381a6f1e-2e4d-49ad-8ff0-48f34c0ef0ba)

3. Git clone the arRPC server and run with node src

### Previously shown:
![image](https://github.com/Vencord/Vesktop/assets/45113942/3b5cd0c8-1dfd-4ab8-8936-e9cb1b196de1)
![image](https://github.com/Vencord/Vesktop/assets/45113942/fb4d56e1-9a5c-41b0-bf73-98ef1bdcc18c)
![image](https://github.com/Vencord/Vesktop/assets/45113942/8c843bd7-fa2e-43ee-841a-ff3fa1c1426a)

### Apps running on ports 1337, 6463 and 6464:

**1337:**
![image](https://github.com/Vencord/Vesktop/assets/45113942/c9d422c2-6261-40a7-84d1-abc309bf752c)
 
 
 
**6463:**
![image](https://github.com/Vencord/Vesktop/assets/45113942/235da50b-bd2a-4ee4-a463-47f2f6c1bc7c)
 
 
 
**13048:**
![image](https://github.com/Vencord/Vesktop/assets/45113942/c1a0b773-c701-4ae9-ab92-5599e6c21496)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by troyw1987** [comment]
If this is a arRPC thing, let me know so I can clone this bug report to them.

Au Revoir.

**Comment by Vendicated** [comment]
don't run arrpc yourself. vesktop already comes with it out of the box

**Comment by retroDEG** [comment]
> don't run arrpc yourself. vesktop already comes with it out of the box

the one out of the box does not work on linux, it only works if i run it myself

**Comment by Vendicated** [comment]
false. if you are using flatpak, you need to grant sandbox permissions.

use our support channel if you need help
