### ISSUE TITLE
[Bug] Noise Reduction

### ISSUE THREAD

**Issue by Shrimp6387** [Vencord/Vesktop#644]
### Operating System

Windows 10

### What happens when the bug or crash occurs?

Noise Reduction/Krisp is not working, did try to turn it on and off multiple time.

### What is the expected behaviour?

Noise reduction working.

### How do you recreate this bug or crash?

1. Turned on Noise Reduction
2. Did background noise like breathing, eating or knocking.
3. Voice activates.

### Debug Logs

```
No crash.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by ryleu** [comment]
You've confirmed that the people on the other end can hear your eating or breathing noises? I've noticed sometimes in vanilla Discord that it'll turn green but no one can hear the annoying noises. I'm having no issues with noise reduction even with my incredibly clicky keyboard.

**Comment by Shrimp6387** [comment]
i double checked. its not working as intended. Original discord with vencord is working fine, while vesktop isn't.

**Comment by ImLvna** [comment]
vesktop uses discord web, theres nothing we can do

wait for discord to fix it

**Comment by Vendicated** [comment]
seems to work fine for me. either way, this would be a discord issue, nothing we can do
