### ISSUE TITLE
[Bug] Cursor is always visible on shared app/screen.

### ISSUE THREAD

**Issue by ydamga** [Vencord/Vesktop#645]
### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

Gnome on Wayland

### What happens when the bug or crash occurs?

The bug happens only on Wayland session when watching videos while screensharing. If I don't move my cursor while watching a video, it hides after a while. But screenshare always show a cursor on stream. I tried to move my cursor to my second monitor to hide it but this time it gets stuck on edge of the screen (again only visible on stream).

### What is the expected behaviour?

I expect Vesktop to follow the visibility settings of the cursor.

### How do you recreate this bug or crash?

1. Open a youtube video.
2. Start screensharing it.
3. Watch it for few seconds without moving your cursor.
4. Observe the cursor from stream.

### Debug Logs

```
No crash
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
vesktop doesn't control the screen capture. this is either an issue with chromium or your desktop environment
