### ISSUE TITLE
[Bug] Joining voice call or opening audio settings breaks audio 

### ISSUE THREAD

**Issue by Apricosma** [Vencord/Vesktop#646]
### Operating System

Arch

### Linux Only ~ Desktop Environment

KDE Wayland Plasma

### What happens when the bug or crash occurs?

Joining a channel with voice, or opening the audio settings of vesktop discord absolutely destroys the audio quality on my system. Some sort of device change happens, or the audio server breaks. Quality becomes practically unlistinable. Quality doesn't fix until I restart my system. Changing output device does not resolve the issue. 

### What is the expected behaviour?

Audio working as normal

### How do you recreate this bug or crash?

1. Open Vesktop
2. Join a server or join a call OR open discord voice settings

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```
No crash

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Curve** [comment]
How did you install Vesktop?
Which audio server are you running?

**Comment by Apricosma** [comment]
> How did you install Vesktop? Which audio server are you running?

I installed it via Discover because I was having issues compiling it 
I am using pipewire with pipewire-pulse. I'm not 100% about this to be honest - is there a command I can run to make 100% sure?

**Comment by Curve** [comment]
> I am using pipewire with pipewire-pulse. I'm not 100% about this to be honest - is there a command I can run to make 100% sure?

What does `pactl info` output?

**Comment by Apricosma** [comment]
> > I am using pipewire with pipewire-pulse. I'm not 100% about this to be honest - is there a command I can run to make 100% sure?
> 
> What does `pactl info` output?
```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 402
Tile Size: 65472
User Name: removed
Host Name: archlinux
Server Name: PulseAudio (on PipeWire 1.0.7)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: bluez_output.30_63_71_89_32_2A.1
Default Source: alsa_input.pci-0000_05_00.6.analog-stereo
Cookie: 4670:d97f
```

**Comment by Curve** [comment]
Latest pipewire it is, can you try the Vesktop aur version just to make sure this is not an issue with flatpak?

**Comment by Apricosma** [comment]
> Latest pipewire it is, can you try the Vesktop aur version just to make sure this is not an issue with flatpak?

I'm getting a target not found when I try to run `sudo pacman -S vesktop`

**Comment by Curve** [comment]
> > Latest pipewire it is, can you try the Vesktop aur version just to make sure this is not an issue with flatpak?
> 
> I'm getting a target not found when I try to run `sudo pacman -S vesktop`

There's also `vesktop-bin`, but can you please be more specific, what is the error?

**Comment by Apricosma** [comment]
> > > Latest pipewire it is, can you try the Vesktop aur version just to make sure this is not an issue with flatpak?
> > 
> > 
> > I'm getting a target not found when I try to run `sudo pacman -S vesktop`
> 
> There's also `vesktop-bin`, but can you please be more specific, what is the error?

I run `sudo pacman -S vesktop` or `vesktop-bin` and it returns
`error: target not found: vesktop`

**Comment by Curve** [comment]
> > > > Latest pipewire it is, can you try the Vesktop aur version just to make sure this is not an issue with flatpak?
> > > 
> > > 
> > > I'm getting a target not found when I try to run `sudo pacman -S vesktop`
> > 
> > 
> > There's also `vesktop-bin`, but can you please be more specific, what is the error?
> 
> I run `sudo pacman -S vesktop` or `vesktop-bin` and it returns `error: target not found: vesktop`

You have to use an AUR helper like [paru](https://github.com/Morganamilo/paru) or [yay](https://github.com/Jguer/yay) to use the AUR.

**Comment by Apricosma** [comment]
> > > > > Latest pipewire it is, can you try the Vesktop aur version just to make sure this is not an issue with flatpak?
> > > > 
> > > > 
> > > > I'm getting a target not found when I try to run `sudo pacman -S vesktop`
> > > 
> > > 
> > > There's also `vesktop-bin`, but can you please be more specific, what is the error?
> > 
> > 
> > I run `sudo pacman -S vesktop` or `vesktop-bin` and it returns `error: target not found: vesktop`
> 
> You have to use an AUR helper like [paru](https://github.com/Morganamilo/paru) or [yay](https://github.com/Jguer/yay) to use the AUR.

Thanks.. sorry, I'm a bit new to this. Got vesktop-bin installed and running.

When I open the options in Discord and go to voice options, I get a notifcation that my audio output has changed to something called high definition audio controller pro; it flashes away before I can really read it. During this time, the audio becomes utterly terrible, like it's running over a telephone. Then it reverts back

Inside of discord options I have an option to choose my headphones for input (default won't give me any sound input), but when I switch to my headphones, it changes back to the horrible audio quality.

**Comment by Curve** [comment]
Check your Audio Settings, you can use a tool like `pavucontrol` to disable devices and choose the right audio profile for certain devices.

![image](https://github.com/Vencord/Vesktop/assets/37805707/8eaf6ac5-6daf-4a2e-b5f5-982d9b7da5ea)

Disable all unwanted devices here and make sure you select the appropriate audio profile :)

**Comment by Apricosma** [comment]
![image](https://github.com/Vencord/Vesktop/assets/113317992/27f9c4fe-a3b6-4bd3-9443-919f8e648709)

Here's what I see in the config, when I disable the GA106 HDAC and the Family HDAC (this one is my laptop speakers I believe) I have no way to get audio to play from discord without getting awful quality 

I think it might have something to do with bypassing the sound card in my laptop as raw output? I have no idea. I screwed around with some various settings and on/off but none of them seemed to work

Messing around with different toggles I either have: 
1) Discord microphone input but horrible system audio across the board
2) No microphone input, but good system audio
3) No microphone input, good system audio, and no discord audio output

**Comment by Curve** [comment]
> No microphone input, but good system audio

I have this behavior with my bluetooth headphones, they seem to share the audio lanes for both input and output. I almost exclusively run them on output only and use my laptop microphone for input.

However, in your case it's the laptop speakers right? In that case it's weird that choosing one over the other sacrifices quality.
Maybe check if you need additional audio drivers?

**Comment by Apricosma** [comment]
> > No microphone input, but good system audio
> 
> I have this behavior with my bluetooth headphones, they seem to share the audio lanes for both input and output. I almost exclusively run them on output only and use my laptop microphone for input.
> 
> However, in your case it's the laptop speakers right? In that case it's weird that choosing one over the other sacrifices quality. Maybe check if you need additional audio drivers?

I am connected to my laptop with bluetooth headphones yes. When I open voice options and choose my headphones for input/output like so I get the shitty sound where it sounds like I'm hearing through a telephone. Weirdly choosing default fixes this, but I won't have a microphone input at all.  
![image](https://github.com/Vencord/Vesktop/assets/113317992/bd586140-7047-4dbe-9521-282ba25a0ad7)

**Comment by Curve** [comment]
> I am connected to my laptop with bluetooth headphones yes. When I open voice options and choose my headphones for input/output like so I get the shitty sound where it sounds like I'm hearing through a telephone.

That might be a limitation of your bluetooth headphones then. As I said earlier, mine are not able to both output and record at the same time without sacrificing audio quality - This also happens on mobile, so it's not a Vesktop/Linux issue

**Comment by Apricosma** [comment]
> That might be a limitation of your bluetooth headphones then. As I said earlier, mine are not able to both output and record at the same time without sacrificing audio quality - This also happens on mobile, so it's not a Vesktop and or Linux issue

Ahh, I'll take your word for it then. It seemed to work fine when I do it with my desktop pc but I might be misremembering. I'll try doing it cabled in and see if it makes a difference, I'll close the issue a bit later to see if anyone has additional ideas. Thank you for your help!

**Comment by YoinkedYoink** [comment]
Not to necro a closed issue, but what I found is that placing this config in ```~/.config/wireplumber/wireplumber.conf.d``` seems to remedy issues around headset/telephoney being auto enabled in any applications.

11-bluetooth-policy.conf
```
wireplumber.settings = {	
    bluetooth.autoswitch-to-headset-profile = false	
}
```
