### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Shazgul** [Vencord/Vesktop#648]
### Motivation

Is there an Feature, where i can add own Plugins like in BetterDiscord and so on? Can't find it.

### Solution

^

### Alternatives

^

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
issues are for development, not asking questions. please use our support channel
