### ISSUE TITLE
[Bug] Freezing when try to stream (Linux Mint)

### ISSUE THREAD

**Issue by TheMelancholyOfGigi198** [Vencord/Vesktop#652]
### Discord Account

xfp81zkzw86vw1se

### Operating System

Linux Mint

### Linux Only ~ Desktop Environment

Cinnamon on x11 (Xorg)

### What happens when the bug or crash occurs?

When I try to select the window or screen where I want to do the stream it passes to the next window, where Discord goes in complete freeze, to resume I have to forcely arrest Vesktop or wait for it to close. It could be the audio sources (who say they're loading (?) but I'm not sure)

### What is the expected behaviour?

That Vesktop does not go in freeze and that I am able to stream the screen

### How do you recreate this bug or crash?

- Join voice Channel
- Click the "Share your Screen" Button
- Click on a window/screen
- Vencord freeze

### Debug Logs

I'm not able to see the logs

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
switch to pipewire-pulse

**Comment by TheMelancholyOfGigi198** [comment]
Okay, thanks. I found a script in another report from another repository and I managed to fix the problem. I apologize for making a duplicate

**Comment by Curve** [comment]
What's your venmic version (should be stated in the terminal when starting via vesktop via the terminal)?

This should be fixed already
