### ISSUE TITLE
un able to resize vesktop to fit monitors unless using f11

### ISSUE THREAD

**Issue by testc2n14** [Vencord/Vesktop#653]
### Discord Account

c2n14_8042

### Operating System

fedora 40 kde

### Linux Only ~ Desktop Environment

wayland

### What happens when the bug or crash occurs?

baiclyu it is trying to be 9:16 on a 16:9 dispaly and cutting off the aprts that don;t fit verticaly

### What is the expected behaviour?

to fit my current window with out me using f11 and proably being able to drag it and move it from monitor to monitor with out fully closing it 

### How do you recreate this bug or crash?

launch vesktop 

### Debug Logs

no crases

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by PolisanTheEasyNick** [comment]
Do you have window transparency enabled?

**Comment by testc2n14** [comment]
> Do you have window transparency enabled?

what setting would that be under

**Comment by Vendicated** [comment]
disable transparency if you have it enabled. otherwise, system issue, nothing we can do

**Comment by testc2n14** [comment]
> disable transparency if you have it enabled. otherwise, system issue, nothing we can do

but where is the transparncy setting

**Comment by PolisanTheEasyNick** [comment]
> but where is the transparncy setting

In Vencord Settings
![image](https://github.com/Vencord/Vesktop/assets/39007846/b85b15e2-c5ec-4d4c-8891-81953fb183f7)

**Comment by testc2n14** [comment]
> > but where is the transparncy setting
> 
> In Vencord Settings ![image](https://private-user-images.githubusercontent.com/39007846/338565544-b85b15e2-c5ec-4d4c-8891-81953fb183f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDYyNjAsIm5iZiI6MTcxODEwNTk2MCwicGF0aCI6Ii8zOTAwNzg0Ni8zMzg1NjU1NDQtYjg1YjE1ZTItYzVlYy00ZDRjLTg4OTEtODE5NTNmYjE4M2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDExMzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMTQyMDM4YzZlN2M1Mjg3NTkxMDc5ZjI4MDU0YjU4NWFmMDE2OGU5YTdkZDliMmEwMGYwMWQxZWE3ZWNiOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._0WX56nmI21bneFos9LoPlpaQM2En4ytfWbT2pBGN-c)

yeah it's disabled

**Comment by testc2n14** [comment]
@Vendicated can you cahnage it back to a bug, i don;t have a nvidia card

**Comment by Vendicated** [comment]
no. it's an issue with your system, we cannot help you. layouting is done entirely by chromium and electron, we have no control over it.
