### ISSUE TITLE
[Feat?] Accept shortcut input when window not focused (Wayland)

### ISSUE THREAD

**Issue by zetaPRIME** [Vencord/Vesktop#654]
### Motivation

(this issue isn't obviously definitively in either category as it's relating to a compositor-side hack around missing functionality, so I'm using the feature template to be safe)

Hyprland v0.41 adds a new `sendshortcut` keybind dispatcher that allows sending of arbitrary keys to arbitrary windows; I've tested this with `wev` and it works as I'd expect, however Vencord in wayland mode doesn't seem to accept the input when the window isn't focused, even though Hyprland is sending keyboard focus enter and leave events to the window.

(note: my push to talk in-app is set to f12 as my actual PTT key of capslock doesn't work; the redirection works perfectly when the window is focused.)

### Solution

With the hyperland.conf line:  
`bindnit = , $capsLock, sendshortcut, , F12, class:^vesktop$`

hitting caps lock should operate the set push-to-talk key regardless of whether the window is focused.

### Alternatives

?

### Additional context

On x11 mode, Vencord correctly picks up the press event, but is stuck pressed until pressed and released with the window focused.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
probably not possible

**Comment by zetaPRIME** [comment]
electron limitation?

**Comment by queenbiscuit311** [comment]
> probably not possible

it wouldnt be a full solution since not everyone uses KDE, but i am aware that discord-screenaudio uses KDE's global shortcut system for this purpose and it works quite well. maybe such a solution could work for vesktop as well?

**Comment by Vendicated** [comment]
closing as dupe since there are other issues for tracking global keybind feature
