### ISSUE TITLE
[Bug] Pasting images doesn't work on Wayland

### ISSUE THREAD

**Issue by Reonu** [Vencord/Vesktop#656]
### Discord Account

reonu

### Operating System

EndeavourOS

### Linux Only ~ Desktop Environment

KDE on Wayland

### What happens when the bug or crash occurs?

Pasting an image copied from Spectacle onto Vesktop does nothing. Pasting it into other apps (example: Telegram Desktop) works as expected. This wasn't the case before I switched to wayland

### What is the expected behaviour?

I expect pasting an image to work, but it doesn't

### How do you recreate this bug or crash?

Use Wayland. Try to paste an image.

### Debug Logs

The console doesn't say anything when I attempt pasting. There's no crash either. Nothing happens.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
system / electron issue

if you're using flatpak, make sure you're not copying the file via your file explorer because it might copy the path and be denied read access (can be fixed by either not using flatpak or by granting it access to your whole system / specific folders)

**Comment by Reonu** [comment]
A simple reboot fixed it. Also, after opening the issue I noticed the issue was happening when copying between X apps and Wayland apps in general, not just Vesktop. So it wasn't a Vesktop issue, yeah. Sorry about that
