### ISSUE TITLE
[Bug] Screenshare shares call audio

### ISSUE THREAD

**Issue by skyH4PPY** [Vencord/Vesktop#657]
### Operating System

Linux Mint

### Linux Only ~ Desktop Environment

XFCE, Xorg

### What happens when the bug or crash occurs?

When screensharing, if I select Entire System as the audio source, my friend in the call can hear his own voice through the screenshare.

### What is the expected behaviour?

I expect Vesktop to filter out its own audio, and share all my system audio EXCEPT the call itself. My friend shouldn't be able to hear himself through the screenshare.

### How do you recreate this bug or crash?

1. Share screen with audio source set to System Audio

### Debug Logs

```
No crash
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by PolisanTheEasyNick** [comment]
Please, send screenshot of `qpwgraph` while streaming with sound; output of `pactl info` command and debug logs of Vesktop with `VENMIC_ENABLE_LOG=1` environment variable.

**Comment by Vendicated** [comment]
try building latest master from source, and also try #621

see if they fix it

**Comment by skyH4PPY** [comment]
I'm note sure what changed but after dealing with this issue for two or so days it suddenly went away a few days ago. I did mess with my pipewire config files a bit for an unrelated issue so maybe that's related? I'm not sure. I suppose I should close this issue
