### ISSUE TITLE
is this normal? 30-40% CPU usage

### ISSUE THREAD

**Issue by powerdollkirby** [Vencord/Vesktop#659]
![Screenshot_20240614_043140](https://github.com/Vencord/Vesktop/assets/105698999/1aebc50a-2976-4653-aaaf-73786c7fd4a5)

**Comment by Luna-devv** [comment]
This heavily depends on your installed cpu and what you are currently viewing in Discord/Vesktop, if you have any open streams, or big custom themes.

**Comment by Vendicated** [comment]
you have provided zero relevant info so there's no way to answer your question. open a new proper report with relevant info if you want help.
