### ISSUE TITLE
[Bug] Resizing Vencord fast creates temporary graphical glitches

### ISSUE THREAD

**Issue by a-usr** [Vencord/Vesktop#660]
### Operating System

NixOS

### Linux Only ~ Desktop Environment

Hyprland

### What happens when the bug or crash occurs?

I either resize Vencord very fast, or i un-minimize it from the tray

### What is the expected behaviour?

Vencord has no issues adapting to the new size

### How do you recreate this bug or crash?

1. Resize the vesktop window very fast (drag one border of the window around fast, or do it some other way)
2. Observe Vesktop being extremely zoomed in or not displaying content (only bg colors) for like 3 seconds

### Debug Logs

```
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
you haven't read any of the issue template

**Comment by a-usr** [comment]
I did read it, but Interestingly enough other discord clients (webcord for example) and other electron apps (like vscodium) dont have this issue.

**Comment by Koishukaze** [comment]
> I did read it, but Interestingly enough other discord clients (webcord for example) and other electron apps (like vscodium) dont have this issue.

![IMG_3041](https://github.com/Vencord/Vesktop/assets/47912135/94dc4695-f0e8-43d5-bc69-d0881b7fea05)
![IMG_3042](https://github.com/Vencord/Vesktop/assets/47912135/5a9d427d-2abf-4c9f-a411-adc2073f5f0f)

**Comment by a-usr** [comment]
> > I did read it, but Interestingly enough other discord clients (webcord for example) and other electron apps (like vscodium) dont have this issue.
> 
> [image]

Yes, that is what I read, but again, the fact that other applications (electron) applications dont suffer from this issue leads me to believe that this is, in fact, not an issue with my gpu or drivers.

**Comment by Vendicated** [comment]
all rendering stuff is done by chromium, not by us. it's impossible for it to be caused by vesktop.
