### ISSUE TITLE
[Bug] AppImage Crashes on Kubuntu 24.04

### ISSUE THREAD

**Issue by DatUub** [Vencord/Vesktop#666]
### Operating System

Kubuntu 24.04

### Linux Only ~ Desktop Environment

KDE on Wayland

### What happens when the bug or crash occurs?

Cannot run program. Crashes upon start

### What is the expected behaviour?

I expect it to open however it does not run

### How do you recreate this bug or crash?

1. Run AppImage
2. It Crashes

### Debug Logs

```
base) cartagena@kidrock:~/Desktop$ ./Vesktop-1.5.2.AppImage
[360575:0617/193832.256074:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_VesktoAtPqml/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
https://www.google.com/search?q=AppImage+The+SUID+sandbox+helper+binary+was+found%2C+but+is+not+configured+correctly.+Rather+than+run+without+sandboxing+I%27m+aborting+now
