### ISSUE TITLE
[Bug] A feature to make Vesktop not inject Vencord on launch

### ISSUE THREAD

**Issue by kekkodance** [Vencord/Vesktop#668]
### Discord Account

kekkodance

### Motivation

The current state of affairs is that Vesktop (or vencord too) is unusable even with all updates applied.

### Solution

A Safe Mode that doesn't inject any code that could crash Discord (including Vencord).

### Alternatives

None

### Request Agreement

- [x] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
vesktop requires vencord to function.

**Comment by kekkodance** [comment]
So, what's the current way to use Vesktop while Vencord makes it crash without having to install and switch to the stock client?

**Comment by PolisanTheEasyNick** [comment]
Why you think that Vencord makes crash?
Send please console output of Vesktop at least.

**Comment by AAGaming00** [comment]
update vencord and it shouldn't crash

**Comment by kekkodance** [comment]
There's so much to screenshot
![image](https://github.com/Vencord/Vesktop/assets/53054786/8d0b42c7-ef8f-4cd9-928c-4340ebc5cc09)
![image](https://github.com/Vencord/Vesktop/assets/53054786/6d1165e5-2334-461f-93e5-3ced1f085bda)

**Comment by kekkodance** [comment]
i am on the latest vencord commit.

**Comment by kekkodance** [comment]
![image](https://github.com/Vencord/Vesktop/assets/53054786/b526e9ae-5db8-4e64-8b9e-20aecfde5ab3)
![image](https://github.com/Vencord/Vesktop/assets/53054786/412b7624-1acf-4e4f-b331-065770ad07cc)

**Comment by Vendicated** [comment]
simply don't use vesktop for now. it will be fixed within the next 48 hours
