### ISSUE TITLE
VENCORD / VESKTOP BROKEN / CRASHING

### ISSUE THREAD

**Issue by Vendicated** [Vencord/Vesktop#669]
This issue has been resolved! Update to latest Vencord to fix it.

## If you are unable to update via normal means

Right click the vesktop tray icon > Update Vencord.
If you don't have a tray, you can run the following script in devtools (ctrl + shift i, then click on the console tab and paste):
```js
Vencord.Updater.update()
```

**Comment by RolandMarchand** [comment]
Fixed it, thanks!

**Comment by sedyh** [comment]
I can't update app via dev tools since I'm getting errors in .deb version:
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```
