### ISSUE TITLE
vesktop not minimizing to tray after update

### ISSUE THREAD

**Issue by 0xJsoul** [Vencord/Vesktop#67]
worked on previous version

**Comment by Vendicated** [comment]
made an oopsie https://github.com/Vencord/Vesktop/commit/2b4f7a07d220d6d1d8451dfa88f84dbfcb3961d1

**Comment by Vendicated** [comment]
as a temporary workaround until next release, switching off and on both switches should fix it

**Comment by 0xJsoul** [comment]
Thanks, I tried switching on and off the "minimize to tray" only, but it did not work, so I tried to toggle the "tray icon" too, and now it's working.
