### ISSUE TITLE
[Bug] screen sharing doesn't start

### ISSUE THREAD

**Issue by oneLEAM** [Vencord/Vesktop#672]
### Operating System

Arch Linux x86_64 with Linux 6.9.5-arch1-1 kernel

### Linux Only ~ Desktop Environment

Hyprland on wayland

### What happens when the bug or crash occurs?

screen sharing doesn't start at all

### What is the expected behaviour?

I expected screen sharing to start and work properly

### How do you recreate this bug or crash?

1. Start a call
2. Click on "Share Your Screen" button
3. Choose a monitor in "Screen" tab in MainPicker window
4. Select any settings in SCREENSHARE menu
5. Click on "Go Live" button

### Debug Logs

```
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by zastrixarundell** [comment]
Probably related to #669.

**Comment by jownyman** [comment]
Getting the same bug since yesterday. Streaming was working fine in the middle of the day but when I restarted the app to add a plugin it started doing this. Tried a fresh install but i'm still just getting the same issue where streams wont start :'(

**Comment by Vendicated** [comment]
![image](https://github.com/Vencord/Vesktop/assets/45497981/92d26861-5150-416b-a05f-e0ee1a101f0c)

**Comment by zastrixarundell** [comment]
Works for me via the flatpak, I don't have other issues as well anymore.

**Comment by Stazis555** [comment]
Works after updating via tray icon on NixOs (or after flake update)

**Comment by oneLEAM** [comment]
Started working after clicking "Update Vencord" in the tray
