### ISSUE TITLE
[Bug] Vesktop not showing on Windows 10

### ISSUE THREAD

**Issue by Wehrmachtserdbeere** [Vencord/Vesktop#676]
### Discord Account

Unable to Access

### Operating System

Windows 10

### What happens when the bug or crash occurs?

When Discord pushed its update, I windowed Vesktop. This caused the application to disappear and not return. Even after Updating and Reinstalling, it did not get fixed. While it doesn't show, it updates the icon with pings.

### What is the expected behaviour?

I expect Vesktop to open properly. Instead, it refuses to show.

### How do you recreate this bug or crash?

1. Launch the previous Vesktop version
2. When graphical bugs show up, press "window" (the button between "minimize to taskbar" and "exit")
3. Try to launch

### Debug Logs

```
Not applicable, not using linux.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
edit `%LOCALAPPDATA%/Vesktop/settings/settings.json` and change:
```diff
- "transparent": true,
+ "transparent": false
```

**Comment by Wehrmachtserdbeere** [comment]
This did not fix the issue.

**Comment by Vendicated** [comment]
can't help you then because you have provided no logs or other useful info like screenshots

**Comment by Wehrmachtserdbeere** [comment]
I cannot provide screenshots due to Windows hiding the relevant section, and I cannot provide logs as there are none, because I do not use linux nor run it from commandline.

**Comment by Vendicated** [comment]
use our support channel for further help.
