### ISSUE TITLE
[Feature Request] Remove "Reset Vesktop" from the tray icon right-click

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#677]
### Motivation

The option "Reset Vesktop" should not be present so easily to users. As I see it, someone may mistakenly click this option. In my opinion, it should be only possible through a terminal and from the "Vesktop Settings" menu (which it is currently).

For example: `vesktop --reset`.

### Solution

Described above.

### Alternatives

No alternatives.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
why? it already asks for confirmation
