### ISSUE TITLE
[Bug] Can't share screen

### ISSUE THREAD

**Issue by CoutHi** [Vencord/Vesktop#680]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

i3

### What happens when the bug or crash occurs?

I press share screen, select the screen and select go live. Go live not going live, nothing happens. Tried all resolutions and fps settings to no avail. Worked fine a couple days ago, dead now. Tried running with --unhandled-rejections=strict flags, didn't work either.

### What is the expected behaviour?

I expect to go live after pressing the button.

### How do you recreate this bug or crash?

1. press share screen
2. select the screen and select go live

### Debug Logs

Error during screenshare picker Aborted
(node:3) UnhandledPromiseRejectionWarning: TypeError: Video was requested, but no video stream was provided
    at AsyncFunction.<anonymous> (VCDMain:24:2653)
(Use `vesktop.bin --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
please read the issue template.
