### ISSUE TITLE
[Bug] vesktop defines itself as a browser, no game activities(the manual rpc thing), no keyboard shortcuts, also browser indicator

### ISSUE THREAD

**Issue by jojommeke** [Vencord/Vesktop#683]
### Discord Account

_.yojo._

### Operating System

Steamos/archlinux + kde

### Linux Only ~ Desktop Environment

KDE

### What happens when the bug or crash occurs?

![image](https://github.com/Vencord/Vesktop/assets/93141222/5ba5ff17-99e2-4d14-b394-14fd31e12031)
so there is no game activity tab, and i can't set custom shortcuts

### What is the expected behaviour?

vesktop defines itself as desktop app and has its features

### How do you recreate this bug or crash?

1. open vesktop
2. go to settings
3. no game activities
4. go to keyboard shortcuts
5. not able to set shortcuts
6. install platform indicators
7. defines as web

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [x] I have searched the existing issues and found no similar issue(this issue is not only for keyboard shortcuts but for why it defines as web)
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
have you bothered to read the README at all? + duplicate
