### ISSUE TITLE
[WRONG ACTIVITY SHARING] Activity sharing shows that I am playing a game that I don't even own

### ISSUE THREAD

**Issue by MeowFlyx** [Vencord/Vesktop#690]
### Discord Account

mflyx

### Operating System

Windows 11

### What happens when the bug or crash occurs?

This bug basically occurs all the time. It shows wrong activity in my profile, sometimes it shows an activity that is kinda right, but it should'nt show it, for example - FPS Monitor. It says that I am playing FPS Monitor. Sometimes it shows that I play "Last man standing" (I dont even know this game)
![k7n2wyoz](https://github.com/Vencord/Vesktop/assets/105730465/6f42d98a-5e64-4e65-bcae-676af01bdc93)

### What is the expected behaviour?

I expect it to work as it works in discord, just to show my spotify/game that I am playing right now.

### How do you recreate this bug or crash?

Just open vesktop.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by PolisanTheEasyNick** [comment]
All detections performing by arrpc, so directly in Vesktop there's nothing we can do.
Arrpc takes detectable games from [Discord API](https://discord.com/api/v9/applications/detectable) and in this list there is FPS Monitor:
![image](https://github.com/Vencord/Vesktop/assets/39007846/3c5f9f71-c27b-44f7-9c48-edcc6bc37a16)
So I'm assuming that `FPS Monitor` is detected earlier than game and shows first.

**Comment by MeowFlyx** [comment]
![image](https://github.com/Vencord/Vesktop/assets/105730465/6ab7f6a3-74c4-4823-bd5a-6f0aa7d4ba52)
okay I have found lms (I think so)
but is there a way to not display certain activities in vesktop, like we have in discord?

**Comment by Vendicated** [comment]
should already be fixed in latest master. try building from source
