### ISSUE TITLE
[Feature Request] Dynamic Venktop Tray Icon When Joining Voice Channels

### ISSUE THREAD

**Issue by Soham52** [Vencord/Vesktop#694]
### Discord Account

Soham52#0241

### Motivation

It's Hard to tell whether you're connected to a vc, and everytime you need to open the client to confirm it.

### Solution

Make the venktop tray icon change into the voice indicator similar to how the discord icon behaves in the tray.

### Alternatives

None

### Additional context

Here's how the Discord Tray Icon behaves - 

https://github.com/Vencord/Vesktop/assets/73898737/ba453199-29c2-47a5-aa6c-9a86bd6c6fb4

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by PolisanTheEasyNick** [comment]
Duplicate of #294 and #667
