### ISSUE TITLE
[Drag N Drop] Can't attach media by dragndropping it from files

### ISSUE THREAD

**Issue by dokanz** [Vencord/Vesktop#695]
### Discord Account

idontskid_ipaste

### Operating System

Fedora Linux 40

### Linux Only ~ Desktop Environment

Gnome

### What happens when the bug or crash occurs?

When im trying to attach files:
1. its not showing preview
2. when im trying to send it says "Upload Failed, Something went wrong, try again later"
![image](https://github.com/Vencord/Vesktop/assets/92729699/fee1ab28-8ab1-4a18-963a-4cc44268cbd9)
![image](https://github.com/Vencord/Vesktop/assets/92729699/c396e006-685e-4886-b602-c208f9c8730d)

### What is the expected behaviour?

Send media that was attached by drag n dropping from file explorer

### How do you recreate this bug or crash?

attach media by drag n dropping from file explorer (to be exact, default one that fedora uses)

### Debug Logs

```
no crash, so no crash logs :sob: 
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by rozbrajaczpoziomow** [comment]
![image](https://github.com/Vencord/Vesktop/assets/58668179/d1385940-4376-46d1-ab51-c102a5c98d32)
me when I lie
https://github.com/Vencord/Vesktop/issues?q=is%3Aissue+is%3Aclosed+dragging

**Comment by dokanz** [comment]
My vesktop doesnt freeze when im drag n dropping media, i just cant send it :pray:

**Comment by Luna-devv** [comment]
You can fix this using flatseal, you have to give Vesktop permission to access the files. (reason is electron being stupid and not supporting the portal)

**Comment by yani** [comment]
> You can fix this using flatseal, you have to give Vesktop permission to access the files. (reason is electron being stupid and not supporting the portal)

I also have this issue. I have `xdg-pictures:ro` under my "Other files" in Flatseal
