### ISSUE TITLE
[Bug] other people can see my game activity, but i cannot see my own

### ISSUE THREAD

**Issue by darkralts** [Vencord/Vesktop#696]
### Operating System

linux

### Linux Only ~ Desktop Environment

i3

### What happens when the bug or crash occurs?

if i play a game, others see my game activity, but to me it doesnt change anything, i cant see what game i am playing

### What is the expected behaviour?

i would expect it that i can see the game activity too, especially so i can check if its actually detecting my game properly

### How do you recreate this bug or crash?

open a game with vencord open

others can see your game activity but you cant see it

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
nothing to do with vesktop

**Comment by darkralts** [comment]
well i will take your word for it, but can you please elaborate? what do i need to do to fix this?

**Comment by Vendicated** [comment]
i don't know. you have provided 0 relevant info. use our support channel for support https://vencord.dev/support
