### ISSUE TITLE
[Bug] Vesktop volume gets automatically lowered with EarTrumpet

### ISSUE THREAD

**Issue by kekkodance** [Vencord/Vesktop#698]
### Discord Account

kekkodance

### Operating System

Windows 11

### What happens when the bug or crash occurs?

I use EarTrumpet, i periodically find Vesktop's volume lowered to around 50 to 66 percent for no reason, despite turning it back to 100

### What is the expected behaviour?

Volume staying at the specified level

### How do you recreate this bug or crash?

1. Start Vesktop and EarTrumpet
2. Get in a VC or do something with noise
3. open the EarTrumpet mixer

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by lewisakura** [comment]
Vesktop doesn't control its own audio output. Something on your system is changing it.

**Comment by kekkodance** [comment]
i tried with regular discord, all other apps including it are fine and hold up, uninstalling ear trumpet doesn't fix the issue, vesktop auto attenuates itself

**Comment by polluxau** [comment]
Im having this issue not with that tool this person is using but the audio is being lowered randomly i have noticed recently to around 70℅ 

Idk if its a pipewire issue or something to do with vesktop

**Comment by burgernado** [comment]
make sure you disable automatic gain control in voice & video, i had the same problem and that resolved it

**Comment by polluxau** [comment]
> make sure you disable automatic gain control in voice & video, i had the same problem and that resolved it

Yeah i did that and it does solve it, i had to disable krisp also as krisp pulls it down to 70℅ while auto gain only lowers for me to around 90 to 95℅
