### ISSUE TITLE
DiscardVirtualMemory[Bug] <title>

### ISSUE THREAD

**Issue by StraightWhbicookie** [Vencord/Vesktop#702]
### Discord Account

sk_happytreefriends_c_tres_bien

### Operating System

Windows 8.1

### What happens when the bug or crash occurs?

DiscradVirtualMemory is not located in AppData\Local\vesktop\Vesktop.exe 

### What is the expected behaviour?

Is work.

### How do you recreate this bug or crash?

Install Windows 8.1 on a VM and install the drivers wifi of Windows 8.1 install Vesktop and normally is dont work.

### Debug Logs

Is dont work too.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
upgrade to windows 10 or later.
