### ISSUE TITLE
[Feature Request] Windows ARM64 build

### ISSUE THREAD

**Issue by D2Lx0wse** [Vencord/Vesktop#704]
### Discord Account

everythingonarm

### Motivation

Discord itself doesn't provide any ARM builds, and Vesktop already has ARM builds for other operating systems, so it'd make sense to have a windows ARM build

### Solution

Have a windows arm build of vesktop available

### Alternatives

I usually use discord in firefox and have yet to try building vesktop myself

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
done via https://github.com/Vencord/Vesktop/commit/9e3d83a2ee3a05cf84040e84ef53252ae7e29a96

**Comment by D2Lx0wse** [comment]
cool thanks!

**Comment by D2Lx0wse** [comment]
also I built it without knowing you did that by git cloning 2 minutes after the commit lol
