### ISSUE TITLE
[Bug] Discord settings cannot be opened

### ISSUE THREAD

**Issue by F1R4NV4R** [Vencord/Vesktop#708]
### Operating System

Windows 10/11

### What happens when the bug or crash occurs?

When opening discord settings, the settings do not open and errors are displayed in the console
![image](https://github.com/Vencord/Vesktop/assets/138937804/f5317143-8aff-4837-a322-dad129de3d71)
![image](https://github.com/Vencord/Vesktop/assets/138937804/41029a15-a7c0-45c7-a6cb-16ad48148c25)

previously installed modules do not work

### What is the expected behaviour?

Discord settings open without problems. In the discord settings all settings are available including Vencord settings

### How do you recreate this bug or crash?

1. Open Discord application on the Win 10 and 11
2. Open console Ctrl+Shift+I
3. Click on the Setting icon (User Settings)

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/issues/669

**Comment by F1R4NV4R** [comment]
@Vendicated this method that you suggested https://github.com/Vencord/Vesktop/issues/669 did not help me

**Comment by Vendicated** [comment]
use our support channel
