### ISSUE TITLE
[Feature request] Ability to change tray & taskbar icon

### ISSUE THREAD

**Issue by Moonlumen** [Vencord/Vesktop#71]
vencord's icon looks pretty out of place and jarring next to windows' consistent white icons, i'd love if this was able to be changed

**Comment by Vendicated** [comment]
i don't understand this request. It does not look out of place in the slightest.

What "consistent white icons"?

**Comment by Vendicated** [comment]
it does not stand out compared to the other icons 🤷🏻‍♂️ 
![image](https://github.com/Vencord/Vesktop/assets/45497981/3d6ea6f1-303b-4638-8844-d218edfe0b7f)
![image](https://github.com/Vencord/Vesktop/assets/45497981/fbd7bd51-b4f8-41ff-9ef1-85472f8ab566)

**Comment by vojta-dev** [comment]
![image](https://github.com/Vencord/Vesktop/assets/65811166/b1127204-e325-4c5a-922a-5f81165b773c)

the pixelation does look a bit weird to be honest

**Comment by Vendicated** [comment]
lol why does it look so bad for you

**Comment by Moonlumen** [comment]
probably monitor scaling, i have the same issue

**Comment by vojta-dev** [comment]
it looks exactly the same as the screenshot you sent

**Comment by phisch** [comment]
> it does not stand out compared to the other icons 🤷🏻‍♂️

Did you see your own screenshot?
![image](https://github.com/Vencord/Vesktop/assets/1282767/57a6d661-c2f3-43ae-af45-ac50ba0632e4)
![image](https://github.com/Vencord/Vesktop/assets/1282767/6ca0118c-8720-439d-9e19-69852aaf55e1)

**Comment by Vendicated** [comment]
yes i saw my own screenshot. it does not stand out, it fits right in. it just scales poorly and thus looks weird

we do plan to fix the scaling issue, but it's not that easy because it's pixel art. the icon will likely have to be remade in specific dimensions for the smaller icons. feel free to contribute

no there won't be the ability to change the icon

**Comment by AftmostSeeker80** [comment]
Hello, I have resized the current Vesktop icon to a 64px one.
Sadly, although the icon does look more minimalistic, I had to remove Oneko from it because it wouldn't fit anymore.
There are 2 variants, with and without the inner shadow.
Hope this might be of help!
![icon 64x (shadow)](https://github.com/Vencord/Vesktop/assets/55350217/912e2d53-85fc-444f-9d82-45dfd3f34a8d)
![icon 64x (no shadow)](https://github.com/Vencord/Vesktop/assets/55350217/afa35cc3-d680-4598-83ef-ec4c9ee0f60f)

**Comment by phisch** [comment]
> no there won't be the ability to change the icon. you can build from source to change icons
Sad :(

> we do plan to fix the scaling issue, but it's not that easy because it's pixel art. the icon will likely have to be remade in specific dimensions for the smaller icons. feel free to contribute

What is the philosophy behind the logo being pixel art? And does it have to be pixel art, or can it be something more smooth?
Also, is it just the letters VC from [V]en[c]ord?
I assume cord comes from discord, and `ven` comes from your username `Vendicated`?
Are you open to a drastic change, away from the letters VC, towards something symbolic?

I'm not promising anything, but if there is a good idea I like, I don't mind making a logo.

**Comment by Vendicated** [comment]
> What is the philosophy behind the logo being pixel art? And does it have to be pixel art, or can it be something more smooth?

No particular reason, that's just how it was made

> Also, is it just the letters VC from [V]en[c]ord?
I assume cord comes from discord, and ven comes from your username Vendicated?

Correct

> Are you open to a drastic change, away from the letters VC, towards something symbolic?
> 
> I'm not promising anything, but if there is a good idea I like, I don't mind making a logo.

you should come discuss this in the development channel in our discord community! it's unlikely that the logo will be changed unless the majority agrees and most users prefer it. and we would have to discuss the exact details
(cc @lewisakura)

**Comment by lewisakura** [comment]
on this note, the VC logo is also the general mod logo, so it would need to be agnostic between the desktop client and the mod itself, if a new one was to be made. but yes, please come and join our discord community, open a modmail and request access to the dev channels and we can discuss this further!
