### ISSUE TITLE
[Bug] Add drag-maximize feature

### ISSUE THREAD

**Issue by keplerHaloxx** [Vencord/Vesktop#712]
### Discord Account

haloxx

### Operating System

Windows 11

### What happens when the bug or crash occurs?

Nothing happens

### What is the expected behaviour?

For the Vesktop window to maximize when being dragged to the top of the screen or pressing WIN + Up Arrow

### How do you recreate this bug or crash?

1. Drag Vesktop window to top of screen to try to maximize how you would any other application or press WIN + Up Arrow

### Debug Logs

```
No crash log
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Sqaaakoi** [comment]
your system is busted or more likely, you have transparent window enabled, which doesn't work well on windows
