### ISSUE TITLE
[Feature Request] QT File Picker

### ISSUE THREAD

**Issue by shvedes** [Vencord/Vesktop#713]
### Discord Account

-

### Motivation

I'm always frustrated when I have to use the default GTK File Picker, as it doesn't integrate well with my workflow and preferences. I think it would be better if there was an option to choose between GTK and QT File Pickers.

### Solution

I would like to have the ability to select between GTK and QT File Pickers in the settings. This would allow users who prefer QT's interface and features to use it instead of the default GTK File Picker.

### Alternatives

An alternative solution could be to allow users to configure custom file pickers through a plugin or extension system. This way, users can select their preferred file picker even if it's neither GTK nor QT.

### Additional context

Adding this feature would enhance user experience by providing more flexibility and catering to different user preferences. Screenshots of both GTK and QT File Pickers are provided for comparison:

![image](https://github.com/Vencord/Vesktop/assets/84767665/d37b4eab-4240-4d40-aea9-893662475ea5)
![image](https://github.com/Vencord/Vesktop/assets/84767665/57f27799-9e60-403c-b958-1f0a748fb40c)

Yes, this issue was written by AI, but it still conveys my idea.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by ImLvna** [comment]
we currently dont have a system for dedicating plugins to specific operating systems, so a rework in that area would be required before we could make this

**Comment by ImLvna** [comment]
> we currently dont have a system for dedicating plugins to specific operating systems, so a rework in that area would be required before we could make this

nvm im stupid and thought this was in normal vencord plugin requests, ignore me

**Comment by Vendicated** [comment]
vencord does not dictate the file picker. it's just electron, i think via portal

so system issues / electron issue
