### ISSUE TITLE
[Feature Request] Allow for the anime character in the loading screen to be configurable

### ISSUE THREAD

**Issue by tfinnegan937** [Vencord/Vesktop#716]
### Discord Account

flaffwaffle

### Motivation

I really like Vesktop, but in the spirit of configurability, I try to give my desktop a sleek/serious look. I'll actively replace the icons for various software if I don't like them/don't feel like they fit with the theme.

Anime characters are cool and all, but I would personally prefer the option to change that image when the software is loading. I very much prefer a sleek, minimalist look on my desktop...And given that Vesktop is the only stable discord client for Linux (I have had so many issues with the official client + wayland + updates breaking things), it's currently my only option.

### Solution

Obviously this is a bit of a silly request, and not something that you can do with most software on Windows. It's the application's mascot, and a lot of time and effort went into developing it. I have a lot of respect for the artist that took the time to create it, and the Vesktop team for developing a unique theme for their client.

It would be really nice to have some configurability here, though, either by replacing it with an image of my choosing, or disabling it altogether with only the "Vesktop is Loading" text showing. The design feels at odds with the rest of the discord UI, and the rest of the theme in my workspace.

### Alternatives

This is a pretty straightforward request without any real alternatives. 

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
tracked via https://github.com/Vencord/Vesktop/issues/667
