### ISSUE TITLE
[Feature Request] Support for XDG_ACTIVATION_TOKEN

### ISSUE THREAD

**Issue by Zerwin** [Vencord/Vesktop#717]
### Motivation

Background:
KDE 6.1
Kernel: 6.9.7-arch1-1
stable 306208 (159419c) Build Override: N/A
Vencord 5c05443 (Vesktop v1.5.2)
Electron 29.1.1
Chromium 122.0.6261.111

I noticed that when clicking a link in Vesktop, Firefox/Brave doesn't come to the foreground. After googling a bit, I found this thread https://forum.manjaro.org/t/firefox-doesnt-raise-window-after-clicking-a-link-on-wayland/154842/38 , which at the end points out that each application needs to build in to support raising windows with XDG_ACTIVATION_TOKEN, see wayland.app/protocols/xdg-activation-v1 . I am unsure if this is something that would have to be fixed upstream in Chromium or could be fixed in Vesktop specifically, but thought I would open the issue to get a discussion started on it.

### Solution

Either inbuild support for wayland.app/protocols/xdg-activation-v1 or, if it needs to be fixed upstream in chromium, a bug issue on their side.

### Alternatives

Raising a window manually whenever I click a link, which is a bit annoying.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
electron opens links with `xdg-open`. Thus, it's up to your system to dictate system focus.

**Comment by Zerwin** [comment]
I wonder where the issue lies then, as e.g. doing a web search in the KDE start menu brings the window to the front, Vesktop doesn't. By any chance, do you know where I could find information in electron about this ?

**Comment by Vendicated** [comment]
Works on my machine. It's an issue with your system / your DE. xdg-open just calls the DE specific url opener

You can see what command it ends up running to open the url via `sh -x xdg-open https://vencord.dev`. for me on gnome, that's `gio open https://vencord.dev`

**Comment by Zerwin** [comment]
Thanks for that command, just checked, it runs
```
kde-open https://vencord.dev
```
Same problem there, so I guess kde-open is the issue. Thanks, I'll try and find where to report that then.
