### ISSUE TITLE
[Bug] Vesktop just giving me a white screen

### ISSUE THREAD

**Issue by jharrison123** [Vencord/Vesktop#719]
### Discord Account

.j.r.h.

### Operating System

Ubuntu 24.04 LTS x86_64 

### Linux Only ~ Desktop Environment

GNOME 46.0 

### What happens when the bug or crash occurs?

On startup the window is just white with nothing to interact with
![Screenshot from 2024-07-02 14-16-07](https://github.com/Vencord/Vesktop/assets/78988905/a14d354a-d67c-4f9a-bbb9-6219d9789e3e)

### What is the expected behaviour?

I just expected it to work like it always had

### How do you recreate this bug or crash?

1 start program
2 wait a bit
3 white screen

### Debug Logs

jesse@Jbox:~$ flatpak run dev.vencord.Vesktop
Passing the following arguments to Electron: --ozone-platform-hint=auto
[3:0702/141724.140146:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 14:17:24.425: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:17:24.427: Failed to load module "canberra-gtk-module"
[3:0702/141724.451370:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0702/141724.451430:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
`[3:0702/141724.451430:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

https://google.it/search?q=Failed+to+connect+to+the+bus%3A+Failed+to+connect+to+socket+%2Frun%2Fdbus%2Fsystem_bus_socket%3A+No+such+file+or+directory
