### ISSUE TITLE
[Bug] Cannot connect accounts to Discord

### ISSUE THREAD

**Issue by SnowzNZ** [Vencord/Vesktop#72]
Auth page gets stuck loading

**Comment by Vendicated** [comment]
please provide more info

**Comment by SnowzNZ** [comment]
Literally all I can provide, I go to connect an account, it opens the auth tab and then gets stuck saying Connecting to discord

**Comment by HakuSystems** [comment]
Hi @SnowzNZ 

1. Clear the browser's cache and cookies.
2. Temporarily disable any browser extensions that might interfere with the authentication process.
3. Try using a different browser to see if there's a compatibility issue.
4. Check [Discord's status page](https://discordstatus.com/) to see if there are any ongoing issues that might be causing this.
5. If the account was previously connected to Discord, try revoking access from Discord's settings and then reconnect.

I hope this helps!

**Comment by SnowzNZ** [comment]
Has nothing to do with my browser, I can still connect with the normal client. This issue only occurs with Vesktop.

**Comment by Vendicated** [comment]
you have still provided no relevant info. please use our support channel instead so we can better help you
