### ISSUE TITLE
[Bug] "Complete" button to the right of "You must complete a few more steps before you can start talking in this server." text at the top of vesktop's window that displays when joining a new server doesn't do anything when clicking on it 

### ISSUE THREAD

**Issue by ComfortableMilk4454** [Vencord/Vesktop#720]
### Discord Account

comfortablemilk4454

### Operating System

macOS 14.5 (23F79), stable 307392 (6818046) Build Override: N/A Vencord 5c05443 (Vesktop v1.5.2) Electron 29.1.1 Chromium 122.0.6261.111

### What happens when the bug or crash occurs?

"Complete" button to the right of "You must complete a few more steps before you can start talking in this server." text at the top of vesktop's window that displays when joining a new server doesn't do anything when clicking on it

https://github.com/Vencord/Vesktop/assets/43555540/a101c5b1-8f48-4126-8f55-ae21821f91f4

^ notice that the complete button on the bottom right works

### What is the expected behaviour?

for the button to work

### How do you recreate this bug or crash?

1. join https://discord.gg/cs6bTDU
2. click on the "Complete" button to the right of "You must complete a few more steps before you can start talking in this server."

### Debug Logs

```
Last login: Wed Jul  3 17:19:27 on ttys000
mrbonk@aidans-MBP ~ % /Applications/Vesktop.app/Contents/MacOS/Vesktop
[arRPC > ipc] listening at /var/folders/ch/wcz8j0sd0lg713fyy7h_kspc0000gn/T/discord-ipc-0
[arRPC > websocket] listening on 6463
2024-07-03 17:23:31.605 Vesktop[41707:409102] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
2024-07-03 17:23:32.454 Vesktop Helper (Plugin)[41714:409198] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
#293
