### ISSUE TITLE
Vesktop being open causes performance loss on NVIDIA + Wayland

### ISSUE THREAD

**Issue by candroid-man** [Vencord/Vesktop#722]
### Discord Account

bigdankhank

### Operating System

Bazzite 40

### Linux Only ~ Desktop Environment

Wayland + NVIDIA

### What happens when the bug or crash occurs?

Vesktop simply being open causes overall frame lag regardless of current frame rate. For example, in Apex Legends it shows I have 120-150 FPS, however it feels like 60-75 FPS. Closing Vesktop and using the official Discord app fixes the issue, but I'd like to be able to use Vesktop for the helpful plugins.

### What is the expected behaviour?

I expect my system to run smoother while Vesktop is running.

### How do you recreate this bug or crash?

1. Run Vesktop on an NVIDIA + Wayland machine with the latest stable video drivers
2. Run a high performance game such as Apex Legends
3. See issue

### Debug Logs

```
Using NVIDIA on Wayland, disabling gpu sandbox
Passing the following arguments to Electron: --ozone-platform-hint=auto --disable-gpu-sandbox
[3:0704/003611.217444:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0704/003611.422872:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0704/003611.422915:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] 6463 in use!
[arRPC > websocket] listening on 6464
[arRPC > process] started
[3:0704/003611.681545:ERROR:browser_main_loop.cc(278)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by candroid-man** [comment]
Okay so I think I may have jumped the gun here. Something does slow down the system, however I am starting to think it is a plugin issue or something

![image](https://github.com/Vencord/Vesktop/assets/51019003/15d17d03-775a-4b4f-9b63-a45c3df5e00b)

**Comment by Vendicated** [comment]
this lacks any relevant info. it's very likely to be a system issue or electron/chromium

can't really help you unfortunately
