### ISSUE TITLE
[Bug] Vesktop hangs on loading accounts screen & logs out of account after unlocking the computer

### ISSUE THREAD

**Issue by xanning** [Vencord/Vesktop#723]
### Discord Account

@ht3n

### Operating System

Windows 11 23h2 Pro

### What happens when the bug or crash occurs?

After unlocking my computer after some time (windows +l) opening Vesktop hangs on some type of loading screen and often logs me out of my account
To get back to discord, i need to Relaunch it but it usually logs me out of my account too
For reference i have multiple accounts logged in + have IgnoreDevtoolsWarning plugin enabled
Tested if it was my computer's issue (internet not working for first few seconds), but no internet works fine while locked and unlocking etc
Vencord: v1.9.3 • [5c05443](https://github.com/Vendicated/Vencord/commit/5c05443) (Vesktop v1.5.2) - 29 Jun 2024
Client: stable ~ Vesktop v1.5.2
Platform: Win32
```
WebRichPresence (arRPC), BetterNotesBox, BiggerStreamPreview, ClearURLs, ClientTheme, CopyUserURLs, CrashHandler, Experiments, FakeProfileThemes, FixSpotifyEmbeds, GameActivityToggle, MemberCount, MessageLogger, MoreKaomoji, NoBlockedMessages, NoDevtoolsWarning, NoOnboardingDelay, NoPendingCount, NoTypingAnimation, PermissionsViewer, ServerInfo, SpotifyControls, TextReplace, Translate, USRBG, ValidUser, ViewIcons, VoiceDownload, VoiceMessages
```
![image](https://github.com/Vencord/Vesktop/assets/119341546/1809c5c3-2580-43a2-aa66-b7fd15f1dba3)

### What is the expected behaviour?

Expecting Vesktop to continue the session after unlocking the computer

### How do you recreate this bug or crash?

I lock my computer with Windows + L
After 10-15 minutes i come back to it, unlock it
Vesktop is hang on the loading screen

### Debug Logs

```
[arRPC > ipc] listening at \\?\pipe\discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```
(Works normally, but next time i'll run vesktop from cmd and reproduce this again)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
make sure you're not opening multiple instances somehow or have zombie processes. a reinstall might also help

can't help other than that
