### ISSUE TITLE
[Bug] Can't open links

### ISSUE THREAD

**Issue by AlephNought0** [Vencord/Vesktop#725]
### Operating System

NixOS

### Linux Only ~ Desktop Environment

Hyprland

### What happens when the bug or crash occurs?

The link fails to open, specifically I get this error when clicking on a link.

```
LaunchProcess: failed to execvp:
xdg-open
```

However, opening the link through xdg-open on the terminal works. I tried reinstalling Vesktop and the issue still persists.

### What is the expected behaviour?

Link gets opened

### How do you recreate this bug or crash?

1. Start Vesktop
2. Click link
3. Sadness (error comes out)

### Debug Logs

```
LaunchProcess: failed to execvp:
xdg-open
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
your xdg-open do be broken tho
