### ISSUE TITLE
[Bug] macOS: can't open devtools with ⌥ ⌘ i

### ISSUE THREAD

**Issue by ComfortableMilk4454** [Vencord/Vesktop#726]
### Discord Account

comfortablemilk4454

### Operating System

macOS 14.5 (23F79)

### What happens when the bug or crash occurs?

nothing

### What is the expected behaviour?

devtools to open. note that i can open my devtools by clicking `view` in the menu bar & `toggle developer tools`

### How do you recreate this bug or crash?

⌥ ⌘ i

### Debug Logs

```
Last login: Thu Jul  4 14:59:43 on console
mrbonk@aidans-MBP ~ % /Applications/Vesktop.app/Contents/MacOS/Vesktop
Checking for update
[arRPC > ipc] listening at /var/folders/ch/wcz8j0sd0lg713fyy7h_kspc0000gn/T/discord-ipc-0
[arRPC > websocket] listening on 6463
Update for version 1.5.3 is not available (latest version: 1.5.3, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
2024-07-04 18:13:42.574 Vesktop Helper (Plugin)[64717:702787] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
[64715:0704/181342.666084:ERROR:ffmpeg_common.cc(959)] Unsupported pixel format: -1
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by ImLvna** [comment]
cant reproduce on macos 14.0

**Comment by ComfortableMilk4454** [comment]
what abt macOS 14.5? thats what im on.

**Comment by Vendicated** [comment]
systen issue, can't help

**Comment by ComfortableMilk4454** [comment]
i see. is there any troubleshooting u can point me in so i can try to figure it out? thanks!

**Comment by toasterw** [comment]
ive got the same issue on 14.5 and 15.0. the keybind works for closing devtools but not opening it

**Comment by ComfortableMilk4454** [comment]
@Vendicated @toasterw i can also close devtools with the keybind, just checked. but i still can't open it with the keybind. vee are u sure this is a system issue?

**Comment by ComfortableMilk4454** [comment]
also note that this happened with vesktop 1.5.2, not just on the latest 1.5.3

**Comment by ImLvna** [comment]
we recently bumped electron, id ask there. otherwise, theres nothing we can do about it

**Comment by ImLvna** [comment]
oh, nvm then

**Comment by ComfortableMilk4454** [comment]
nws :)

**Comment by ComfortableMilk4454** [comment]
Could this be reopened pls?

**Comment by ComfortableMilk4454** [comment]
Could this be reopened pls?

**Comment by Vendicated** [comment]
no. we have no control over it functioning or not. if it doesn't work, it's an issue with electron or your system. can't help you unfortunately

**Comment by ComfortableMilk4454** [comment]
Oh I see, ty for telling me :).
