### ISSUE TITLE
Infinite loading bug

### ISSUE THREAD

**Issue by Yeetov** [Vencord/Vesktop#73]
Only shows the loading vesktop screen and never stops
![BUG Infinite Loading](https://github.com/Vencord/Vesktop/assets/69159547/4b9c93f3-9bbe-4ef9-9e4a-cfbdf9c124fc)

**Comment by Vendicated** [comment]
probably Internet issue

**Comment by Vendicated** [comment]
Closing because this is working fine for everyone else, so it's definitely your internet. Make sure you have a stable connection to github and discord

you can ping me in the support channel if you need further help
