### ISSUE TITLE
[Bug] Window size is bigger than it actually is

### ISSUE THREAD

**Issue by Commenter25** [Vencord/Vesktop#733]
### Discord Account

commenter25

### Operating System

Ultramarine 40

### Linux Only ~ Desktop Environment

GNOME 46 on Wayland

### What happens when the bug or crash occurs?

There appears to be a baked shadow which is considered a part of the whole window. This affects the grabbable resizing area, window snapping, and tiling. This is a regression in the latest version, v1.5.3, using the official package from Flathub.

https://github.com/Vencord/Vesktop/assets/35016761/97aafcf8-a949-40ca-8a24-a9486531e37d

The problem is much more obvious if you are using the Rounded Window Corners extension:

![Screenshot from 2024-07-05 11-18-34](https://github.com/Vencord/Vesktop/assets/35016761/cac6a475-0a5c-4314-8f91-5c1eeb074838)

All Vencord CSS and other GNOME extensions disabled for the sake of this report.

### What is the expected behaviour?

The window size should be consistent with reality.

### How do you recreate this bug or crash?

1. Update to v1.5.3
2. Open Vesktop
3. Notice a massive artificial gap when tiling the window

### Debug Logs

```
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto
[3:0705/113026.846010:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0705/113027.372566:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0705/113027.372607:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
can repro, but even normal chromium is affected by this. there's nothing we can do about it

![](https://github.com/Vencord/Vesktop/assets/45497981/22a1b83d-1c6e-452c-9f02-82d9569bc375)

**Comment by Vendicated** [comment]
uhh.. are you sure this is not intended gnome behaviour? happens for me on all windows
![image](https://github.com/Vencord/Vesktop/assets/45497981/f4a5caa7-fe4c-40fb-b021-64353d2e2588)
![image](https://github.com/Vencord/Vesktop/assets/45497981/edd832da-10db-4f8e-92c5-1252f1be0075)

**Comment by Commenter25** [comment]
I think there's a misunderstanding. The problem isn't how large the grabbable zone is, it's just noticeably larger; the big problem is the weird issues that happen with tiling and snapping. This wasn't happening before the update, and it definitely doesn't happen on any other application.

**Comment by Vendicated** [comment]
can't reproduce. works flawlessly on my system. disable transparency if you have it enabled
![image](https://github.com/Vencord/Vesktop/assets/45497981/6ea1f399-cbbf-4edb-8c8e-9ace9b84383c)

if that doesn't solve it, it's a system issue, nothing we can do

**Comment by Commenter25** [comment]
That option was already disabled.

There is clearly an issue here. The app was functioning perfectly fine before, and it only began with this update, and no other app does this. GNOME is not supposed to decorate windows on its own, so this must be an issue with how the app is decorating itself. Closing this immediately feels very dismissive, I am left with no idea how to fix this issue, along with anybody else who may be experiencing this.

**Comment by Commenter25** [comment]
I was able to reproduce the issue in a virtual machine with a fresh Ultramarine 40 install. All I did after install was update and install Vesktop.

**Comment by Vendicated** [comment]
figure out if it's a chrome or electron issue and report it there. this bug has nothing to do with our code and there's nothing we can do to help you, like I said.
