### ISSUE TITLE
[Bug] Crashes when receiving dms

### ISSUE THREAD

**Issue by CodTheFish** [Vencord/Vesktop#738]
### Discord Account

codrutl

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

KDE Plasma 6.1.2 x11

### What happens when the bug or crash occurs?

Vesktop (AppImage) crashes* whenever i'm getting dms from people.
*Application hangs and only way to fix is kill vesktop and restart it.
I want to add that it only happens when I'm **not** looking at the dm im receiving, if i look at the dm im getting then it doesnt crash. Probably something to do with notifs, doesnt happen when in do not disturb.

### What is the expected behaviour?

I expect vesktop not to crash.

### How do you recreate this bug or crash?

1. Get a DM
2. Crash

### Debug Logs

None provided as I'm force closing it i think, might also be that i dont know where to check.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
https://wiki.archlinux.org/title/Discord#Discord_freezes_after_getting_pinged_or_messaged
