### ISSUE TITLE
Windows: app.focus() causes already open window to flash

### ISSUE THREAD

**Issue by Vendicated** [Vencord/Vesktop#74]
Writing a working focus method on windows turned out to be very hard, i found the only working method was to first mainWin.minimize(), then restore and show

This works, but has the side effect that an already foregrounded window will first minimise then maximise again which causes an ugly flash

I'm not exactly sure how to fix this since the workaround was the only method i found to be working

## How to repro

- Open vesktop on windows
- Have it in the foreground then cause a focus, for example by clicking a message notification or launching an invite from the browser
- See how window flashes

**Comment by Vendicated** [comment]
this is so weird because I copied the logic from Discord Desktop and it doesn't work properly, yet for Discord it works flawlessly

**Comment by yourfriendoss** [comment]
Cannot reproduce.

```
Canary 245033 (8b6a6af)
Vencord 96126fa (Vesktop V0.4.3)
Electron 27.0.0
Chromium 118.0.5993.54
Linux 64-Bit
Hyprland, installed from AUR at vencord-desktop-git
```

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/commit/4f1615ecb3b849b61d030ee816cb790172f5371a
