### ISSUE TITLE
[Bug] Vesktop.exe is not a valid Win32

### ISSUE THREAD

**Issue by Syreyup** [Vencord/Vesktop#740]
### Operating System

Windows 7 Ultimate x64

### What happens when the bug or crash occurs?

The crash occurs when I attempt to open up the program.

### What is the expected behaviour?

For it to open the discord log in page

### How do you recreate this bug or crash?

- Install the program on Windows 7 Ultimate x64
- Open the program

### Debug Logs

```
Access is denied
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Syreyup** [comment]
I was told the Vesktop client worked on Windows 7, so that's why I'm filling this out, but if it just isn't supported, do let me know and if you want, close the issue, all's good! I already have an alternative, just was looking into trying this out.

By the way, after reading the command line saying "Access is denied", I tried running the program as an administrator, but it still did not work. Just so you know.

**Comment by Vendicated** [comment]
windows 7 is not supported.

**Comment by Sqaaakoi** [comment]
> Install the program Windows 7 Ultimate x64
Electron doesn't support Windows 7 anymore, nor does Microsoft
