### ISSUE TITLE
[Feature Request] Request version listing on Vencord

### ISSUE THREAD

**Issue by Articade** [Vencord/Vesktop#741]
### Motivation

I tried to update Vesktop via the update popup from 1.5.2 to 1.5.3.  Did not work.  I had originally downloaded Vesktop via Paru/AUR and I wasnt sure if Paru command updated Vesktop or not to 1.5.3.  Couldnt find what version this currently was within the settings, only the repo.

### Solution

It would be nice if within the Vesktop/Discord settings, you should what version is installed, not just the repo, like 1.5.3, etc.  This would help determine if I have to manually makepkg -i or if it is already good to go.

### Alternatives

N/A

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by PolisanTheEasyNick** [comment]
You already can see Vesktop version in settings:
![image](https://github.com/Vencord/Vesktop/assets/39007846/37747777-a40b-4309-87b8-4393fc6c26d7)

**Comment by Articade** [comment]
> You already can see Vesktop version in settings: ![image](https://private-user-images.githubusercontent.com/39007846/347023136-37747777-a40b-4309-87b8-4393fc6c26d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mzk4ODksIm5iZiI6MTcyMDUzOTU4OSwicGF0aCI6Ii8zOTAwNzg0Ni8zNDcwMjMxMzYtMzc3NDc3NzctYTQwYi00MzA5LTg3YjgtNDM5M2ZjNmMyNmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDE1Mzk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3M2EwZjFiNmZiMDc3OWEzYzA0NmUzZTRiM2NiODcxOWQzNzQ5MDI2YmE2NGM5ZGFjZDMxNzBmYmRhZTAyNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DeatyTiTrmFXuqG0FZsS2BckNf0F2l0A6hvlxwz3AhQ)

First off, thank you for being so quick! - Maybe I am confusing Vencord and Vesktop, as I'm not seeing it, or maybe I'm blind lol (Desktop App)

**Comment by Articade** [comment]
Nevermind, I found it... very bottom left.  I'm just blind.  Thank you PolisanTheEasyNick
