### ISSUE TITLE
[Bug] Vesktop logs me out every other day

### ISSUE THREAD

**Issue by HbmMods** [Vencord/Vesktop#742]
### Operating System

Linux Mint 19.3

### Linux Only ~ Desktop Environment

Cinnamon

### What happens when the bug or crash occurs?

Opening Vesktop has a roughly 50:50 chance of logging me out, requiring me to log back in (and do all the 2FA stuff again)

### What is the expected behaviour?

Ideally I should stay logged in until I explicitly log out, that's what stock Discord does at least

### How do you recreate this bug or crash?

1. Open Vesktop
2. Vesktop demands I log back in, although it does remember the previously logged in account

### Debug Logs

```
Running vesktop from command line right now doesn't replicate this, may have to try again tomorrow
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Sqaaakoi** [comment]
Enable NoDevtoolsWarning plugin
