### ISSUE TITLE
[Bug] Extremely laggy and unusable on Linux when using proprietary NVIDIA drivers on KDE Plasma

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [Vencord/Vesktop#746]
### Discord Account

ell_a

### Operating System

KDE Neon

### Linux Only ~ Desktop Environment

KDE Plasma on Wayland

### What happens when the bug or crash occurs?

When using Vesktop with the proprietary NVIDIA driver, Vesktop lags heavily, mainly when typing a message, it can take several seconds for it to actually show what you're typing, and on Plasma 6, it'll show what you're typing, hide it, then show it again. The app also constantly flickers black when using Plasma 6, making it basically unusable. I haven't tested with the official client. I've tried disabling hardware accel, no change.

I've tried 3 different Linux distros (Arch with Plasma 6, Debian Trixie with Plasma 5, and KDE Neon with Plasma 6), all have the same issue, I also tried two different NVIDIA GPUs (an Asus GTX 1060 Turbo 6GB, and an MSI GTX 1650 Gaming X 4GB), both have the same issue. No issue when using Nouveau or an AMD/Intel GPU.

### What is the expected behaviour?

I expect Vesktop to run usably.

### How do you recreate this bug or crash?

1. Install the proprietary NVIDIA drivers on a KDE Plasma system
2. Install Vesktop
3. Launch Vesktop and sign in
4. Extreme lag

### Debug Logs

```
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
Checking for update
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

Update for version 1.5.3 is not available (latest version: 1.5.3, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null

```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
gpu issue, disable hardware acceleration or run with --disable-gpu

**Comment by Lost-Entrepreneur439** [comment]
> gpu issue, disable hardware acceleration or run with --disable-gpu

I already said in the post that I tried disabling hardware accel. --disable-gpu does the same thing, and it is very unlikely that two different GPUs would have the exact same issue across multiple different distros.

**Comment by Sqaaakoi** [comment]
> > gpu issue, disable hardware acceleration or run with --disable-gpu
> 
> I already said in the post that I tried disabling hardware accel. --disable-gpu does the same thing, and it is very unlikely that two different GPUs would have the exact same issue across multiple different distros.

The problem is not your GPUs, it could be that the NVIDIA driver doesn't have support in Chromium when running with Wayland as the ozone platform, however I doubt that due to you saying the app flickers black, which I know is (usually) a symptom of NVIDIA and XWayland

You can safely ignore the logs; I get those too.

In other words, NVIDIA drivers are confusing and I don't confidently know how to solve this
