### ISSUE TITLE
[Feature Request] Pop out single screen share

### ISSUE THREAD

**Issue by JanEickholt** [Vencord/Vesktop#748]
### Motivation

It can be hard to view two screen-shares (or even three) in parallel, which is why it would be nice to scale them independently

### Solution

A possible solution to this problem would be to be able to pop out screen-shares independently, which would allow users more freedom in scaling

### Alternatives

And alternative would be to be able to scale the screen-shares in the "preview" itself, which would be a bit more inconvenient, but could also solve the problem of multiple horizontal streams

### Additional context

This is somewhat of a Vencord feature request, but I would still consider it a Vesktop feature request, due to the changes already made to and around screensharing and I imagine such a change to be easier to implement in Vesktop than Vencord. 

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
https://github.com/Vencord/plugin-requests
