### ISSUE TITLE
Use discord's top bar on Windows

### ISSUE THREAD

**Issue by rushiiMachine** [Vencord/Vesktop#75]
Looks even more jarring without the theme

Stock vs. Vesktop

![image](https://github.com/Vencord/Vesktop/assets/33725716/4366ca4f-3836-4a49-9cfe-4b0423afff1b)
![image](https://github.com/Vencord/Vesktop/assets/33725716/1e6af107-843a-465b-ab92-2e887e3864ef)

**Comment by rushiiMachine** [comment]
disabling window frame isn't really a solution

**Comment by hairyfred** [comment]
Or allow us to customize/theme it

**Comment by kckarnige** [comment]
This'd be epic

**Comment by Vendicated** [comment]
done

**Comment by rushiiMachine** [comment]
i love you ven
