### ISSUE TITLE
[Bug] as you approach the clips/nitro streaming quality icons on someone else's screen share with your mouse the clips/nitro streaming quality icons disappear

### ISSUE THREAD

**Issue by ComfortableMilk4454** [Vencord/Vesktop#754]
### Discord Account

comfortablemilk4454

### Operating System

macOS 14.5 (23F79)

### Package Type

n/a

### What happens when the bug or crash occurs?

clips/nitro streaming quality icons on someone else's screen share disappear

### What is the expected behaviour?

for the clips/nitro streaming quality icons to not disappear as you start to hover your mouse over them

### How do you recreate this bug or crash?

https://github.com/user-attachments/assets/6bb79441-b5b8-4a60-8551-e36a5d9686bd

### Debug Logs

```
Last login: Fri Jul 12 11:42:31 on console
mrbonk@estrobinks-MBP ~ % /Applications/Vesktop.app/Contents/MacOS/Vesktop
Checking for update
[arRPC > ipc] not available, trying again (attempt 1)
[arRPC > ipc] listening at /var/folders/s6/7hwqnnjj5d1f8kbhhnkyhjlw0000gn/T/discord-ipc-1
[arRPC > websocket] 6463 in use!
[arRPC > websocket] listening on 6464
Update for version 1.5.3 is not available (latest version: 1.5.3, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
2024-07-12 20:12:29.397 Vesktop Helper (Plugin)[22947:382982] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
[22945:0712/201229.445279:ERROR:ffmpeg_common.cc(959)] Unsupported pixel format: -1
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
can't reproduce.

**Comment by ComfortableMilk4454** [comment]
weird ill just switch back to vencord injected into stable discord.
