### ISSUE TITLE
[Bug] Can't connect to voice channels

### ISSUE THREAD

**Issue by sapsicle** [Vencord/Vesktop#756]
### Discord Account

sapling.

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

KDE Wayland

### Package Type

AUR (git version)

### What happens when the bug or crash occurs?

When trying to connect to a voice channel, the connection hangs on "DTLS Connecting" indefinitely.
![image](https://github.com/user-attachments/assets/b9aea6cf-d7ba-4229-b104-c4869060580d)

### What is the expected behaviour?

Expected behavior is that the user is connected to the voice channel.

### How do you recreate this bug or crash?

1. Start Vesktop
2. Navigate to a server
3. Click on a voice channel to join it
4. Wait

### Debug Logs

```
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[40290:0713/003226.310168:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[40290:0713/003232.849928:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[40290:0713/003232.857809:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by sapsicle** [comment]
This issue persists on all 4 AUR versions (vesktop, vesktop-bin, vesktop-git, vesktop_electron) as well as the Flatpak.

**Comment by Vendicated** [comment]
not a vesktop issue.
