### ISSUE TITLE
[Bug] IME not working only in flatpak

### ISSUE THREAD

**Issue by KAIYOHUGO** [Vencord/Vesktop#757]
### Operating System

Pop!_OS 22.04 LTS x86_64

### Linux Only ~ Desktop Environment

GNOME Mutter, Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

I know #420 has been closed, but this is a little different. IME work perfectly in .deb version, so in my case I think there is something wrong with flatpak wrapper instead of electron bug.

### What is the expected behaviour?

IME working in flatpak version

### How do you recreate this bug or crash?

1. try IME
2. It is not working

### Debug Logs

```
// no log
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
exactly same issue, and you haven't even provided the terminal log bruh
