### ISSUE TITLE
Detection of Input / Recording Devices

### ISSUE THREAD

**Issue by 0xhanyuu** [Vencord/Vesktop#760]
### Discord Account

hanyuu5192#9170

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Xorg

### Package Type

amd64 / x86_64 tarball

### What happens when the bug or crash occurs?

Occasionally, Vesktop asks to have access to my microphone, and says I do not have any input devices enabled. My microphone is plugged in, and Vesktop is not detecting it.

### What is the expected behaviour?

I am usually able to use my microphone fine without issue.

### How do you recreate this bug or crash?

I do not know how this issue occurs. When my Vesktop updates, sometimes it fixes itself, and on other updates, it comes back.

### Debug Logs

Running Vesktop through my terminal produces no output.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by 0xhanyuu** [comment]
I have reinstalled Vesktop, and changed my bash script to start my pipewire binaries to use wireplumber in place of pipewire-media-session, and even so with all of this, the error persists.

I realise it could be a pipewire issue, as pavucontrol is not detecting any input devices in the recording tab.

**Comment by Vendicated** [comment]
> When my Vesktop updates, sometimes it fixes itself, and on other updates, it comes back.

system issue then. input devices are handled by chromium, and if it sometimes works then it means it's something inconsistent in your system / chromium

likely nothing we can do

**Comment by 0xhanyuu** [comment]
I have been testing a lot of things; I have reset the config files for pipewire, I have even tried using the browser version of Discord, and I see that the issue persists. I think it's my system, unfortunately.
Thank you! :)
