### ISSUE TITLE
Multi Account Switcher not work

### ISSUE THREAD

**Issue by Schrotty74** [Vencord/Vesktop#763]
### Content

I have enables Multi Account Switcher but don't see any changes. Can not log in to a other account.

![grafik](https://github.com/user-attachments/assets/ff8b42d3-5294-411e-8182-e3950b4c65d5)

**Comment by Luna-devv** [comment]
1. Discord experiments are not Vesktop issues.
2. Your screenshot clearly states “Mobile” for both experiments.
