### ISSUE TITLE
[Feature Request] Add audio streams naming

### ISSUE THREAD

**Issue by Naezr** [Vencord/Vesktop#765]
### Motivation

![image](https://github.com/user-attachments/assets/e012998c-e79d-4c9c-a096-4b5d72944c6f)
Audio slider from `Quick Settings Audio Panel` GNOME extension
![image](https://github.com/user-attachments/assets/a3954c93-00cd-45f6-b25f-2a34e1a0ae8e)
Audio sliders from GNOME settings app

Vesktop audio streams are all referred to in the system as Chromium. This is essentially true, but it would be better to see that they are Vesktop audio streams. 

### Solution

Add proper icons and names for audio streams

### Alternatives

idk

### Additional context

Vesktop 1.5.3 flatpak version
OS: Fedora 40

### Request Agreement

- [x] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
https://github.com/electron/electron/issues/27581
