### ISSUE TITLE
[Bug] Black tearing on screenshare only in GNOME

### ISSUE THREAD

**Issue by Cherryda** [Vencord/Vesktop#766]
### Discord Account

robotta_cherry

### Operating System

Fedora Linux 40

### Linux Only ~ Desktop Environment

Gnome on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Checking the screen shared window on Vesktop displays random black tearing in the upper part of the screen.
This doesn't happen in KDE. Nvidia GPU, 555.58.02 driver, running on Wayland.

### What is the expected behaviour?

Clean looking screenshare with no tearing.

### How do you recreate this bug or crash?

1. Start Vesktop on Gnome
2. Screenshare a fullscreen application (preferably a game running with Proton)
3. Check the preview for tearing

Video of the issue: 

https://github.com/user-attachments/assets/dfb6bb35-b035-4f5b-b65b-81e28b63b02d

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Cherryda** [comment]
Pardon my insistance, but why was this labelled as system issue? 
This bug doesn't occur in KDE, which suggests that it's a Vesktop + Gnome issue. Can I ask for an explanation behind the reasoning of this automatic decline? I would like to switch back to Gnome but this Vesktop issue is holding me back.

**Comment by Vendicated** [comment]
works on one DE but not the other = definition of a system issue

also you havent read the issue template.
![image](https://github.com/user-attachments/assets/61269c91-df48-4e8f-8d34-5a2603458870)
