### ISSUE TITLE
[Bug] getaddrinfo on Start

### ISSUE THREAD

**Issue by Mondrethos** [Vencord/Vesktop#767]
### Operating System

Endeavour OS

### Linux Only ~ Desktop Environment

KDE6 Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

I start Vesktop and this appears:

![image](https://github.com/user-attachments/assets/f126de38-d777-4410-a727-24e1d3477984)

### What is the expected behaviour?

This does not appear.

### How do you recreate this bug or crash?

Start Vesktop

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
fix your internet

**Comment by Mondrethos** [comment]
> fix your internet

Several of my gaming buddies and I use Vesktop, and we all get the same error in different parts of the US. Is everyone all having Internet issues? lol. It's been like this off and on for a few weeks.

**Comment by Vendicated** [comment]
this error means DNS lookup of github.com timed out. It's a you issue. Change your DNS.
