### ISSUE TITLE
[Bug] Stuck on "DTLS Connecting"

### ISSUE THREAD

**Issue by bingbongboink** [Vencord/Vesktop#768]
### Discord Account

bingbongboink

### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

KDE on Wayland

### Package Type

Flatpak, RPM

### What happens when the bug or crash occurs?

When joining a VC channel, the status gets stuck on "DTLS connecting." Problem does not occur on firefox.
![image](https://github.com/user-attachments/assets/c174c019-6e6c-4c6f-b112-2cda8d959cdc)

### What is the expected behaviour?

Able to join voice channels and communicate with other members.

### How do you recreate this bug or crash?

1. Open a server
2. Click on a voice channel
3. Get stuck on "DTLS Connecting"

### Debug Logs

```
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto
[3:0718/203324.723888:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0718/203324.937055:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0718/203324.937089:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
system / discord issue

**Comment by zspher** [comment]
might be related to https://github.com/Legcord/Legcord/issues/1011 and https://github.com/tailscale/tailscale/issues/10396#issuecomment-3871203280
does not happen in 
- discord (web)
- discord (desktop)

**Comment by Zylanx** [comment]
@zspher I think I found a solution (at least for Vesktop) that might be interesting to both https://github.com/Legcord/Legcord/issues/1011 and https://github.com/tailscale/tailscale/issues/10396 too.
I think it works anyway.
Basically if you add a call to `win.webContents.setWebRTCIPHandlingPolicy("default_public_and_private_interfaces");`, it seems to resolve the issue.
It no longer checks the tailscale0 interface, but should still support internet VPNs like Mullvad, Surfshark or whatever else people use.

I just chucked it into `createMainWindow` inside `src/main/mainWindow.ts` near the `win.webContents.setUserAgent()` call and it seemed to work just fine. I am unsure of if there could be any other side effects though, and didn't do a whole lot of testing to make sure it works, just added a setting to turn it off and on, and restarted a couple times to see that it did what I expected.

**Comment by Zylanx** [comment]
I think the issue is that when you have tailscale, ICE tries to make a connection over it, but the response comes back on the normal network, which confuses ICE and gets it into a broken state. Just stopping it from using non-default routes seems to fix it.

**Comment by kodiitulip** [comment]
> I think the issue is that when you have tailscale, ICE tries to make a connection over it, but the response comes back on the normal network, which confuses ICE and gets it into a broken state. Just stopping it from using non-default routes seems to fix it.

how could i stop it from using non-default routes?
i've been having this issue of "DTLS Connecting" since i started using vesktop and could never figure it out
my pc is connected to a zerotier network with my partner

**Comment by Axlfc** [comment]
🐢

**Comment by Mrjello0** [comment]
I've this exact same issue and it's definitely vesktop specfic because the normal client works perfectly fine
