### ISSUE TITLE
[Bug] --enable-blink-features=MiddleClickAutoscroll causes vesktop flatpak to crash on startup

### ISSUE THREAD

**Issue by zany130** [Vencord/Vesktop#770]
### Discord Account

zany130

### Operating System

Bazzite

### Linux Only ~ Desktop Environment

KDE wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

vesktop crashes on startup with `--enable-blink-features=MiddleClickAutoscroll` 

### What is the expected behaviour?

vesktop loads with`--enable-blink-features=MiddleClickAutoscroll` which allows scroll on mouse scroll wheel press

### How do you recreate this bug or crash?

1. run `flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop --enable-blink-features=MiddleClickAutoscroll`
2. observe error output in terminal
3. run `flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop`
4. observe vesktop loads as normal

### Debug Logs

```
flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop --enable-blink-features=MiddleClickAutoscroll
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto
[3:0719/111019.722360:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory


#
# Fatal process out of memory: Failed to reserve virtual memory for CodeRange
#
----- Native stack trace -----

/app/bin/startvesktop: line 26:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
the error you're experiencing has nothing to do with the flag nor electron

it happens in all chromiums on some Linux distros. i have it too on Fedora. I suspect it's selinux, so try disabling selinux and it'll likely be fixed

**Comment by Vendicated** [comment]
https://issues.chromium.org/issues/335524387
https://bugzilla.redhat.com/show_bug.cgi?id=2275476

**Comment by zany130** [comment]
@Vendicated  Seems like this is indded not because of the flag.

disabling selinux doesn't fix it either though
