### ISSUE TITLE
[Feature Request] Vesktop changes audio output level globally

### ISSUE THREAD

**Issue by Kaputschii** [Vencord/Vesktop#775]
### Discord Account

Kaputschi

### Motivation

As a desktop environment I use Gnome 46 and Vesktop changes the output level of my microphone globally as I talk with someone.

### Solution

Is there already a way to turn that off? If not I would appreciate a feature like this.

### Alternatives

Maybe a toggle or something in the voice settings.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/issues/161
