### ISSUE TITLE
[Bug] unable to use Japanese/Chinese language keyboards in the Flatpak version of Vesktop 

### ISSUE THREAD

**Issue by hatosu** [Vencord/Vesktop#777]
### Discord Account

hatosu

### Operating System

Linux 6.9.10-arch1-1

### Linux Only ~ Desktop Environment

Hyprland on wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Whenever I try to use a language IME such as `fcitx5-mozc` or `fcitx5-pinyin-zhwiki`, the Flatpak version of Vesktop outright does not let me use these keyboards.

### What is the expected behaviour?

I assume it is because Flatpaks are sandboxed, and that I would have to use Flatseal in order to fix this. 

BUT even when I used Flatseal to give it every single permission, I was not able to use my keyboards whatsoever. Hence I had to resort to using the appimage.

So it would be nice if the Flatpak version of Vesktop supported any language IME out of the box. Much thanks :)

### How do you recreate this bug or crash?

1. Try to use a language IME on the Flatpak version of Vesktop
2. It doesn't work
3. Try to use Flatseal to make it work
4. It still does not work

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by lewisakura** [comment]
Can you try adding the flag `--enable-wayland-ime`?

**Comment by Vendicated** [comment]
duplicate of #420
