### ISSUE TITLE
[Bug] freezes with splash screen and removes accounts upon restart with NoDevtoolsWarning plugin

### ISSUE THREAD

**Issue by cvoges12** [Vencord/Vesktop#778]
### Operating System

NixOS 24.05 (stable)

### Linux Only ~ Desktop Environment

riverwm (not a DE. but close enough)

### Package Type

vesktop 1.5.2 from [nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/ve/vesktop/package.nix)

### What happens when the bug or crash occurs?

Vesktop randomly freezes/crashes with only a non-interactive splash screen displayed (see attatchment below). This will occur at least once a day and often after waking the system from sleep or hibernation. Vesktop will have to be killed by running `pkill vesktop` and `pkill electron` and restarted. The last command to kill the background parent process which Vesktop continues running after being killed. Upon running Vesktop again, a login page is shown with accounts removed. Either only one account will remain signed in or no account will remain signed in requiring the user to sign all but one or all of the user's accounts. This crash / freeze has never occurred while Vesktop was in operation. However, the crash / freeze has happened without putting the system to sleep or hibernation many times. Also, the `NoDevtoolsWarning` plugin has no effect after the crash / freeze has occurred. Per usual, it will work as intended when the system restarts as expected, but not whenever this crash / freeze happens.

![Crash picture](https://github.com/user-attachments/assets/c3c87d60-6e5f-4370-9a1c-036e787dbf59)

### What is the expected behaviour?

Do not crash / freeze and sign out the user's accounts.

### How do you recreate this bug or crash?

1. Put computer to sleep
2. Wait
3. Observe the bug

### Debug Logs

I will update logs after experiencing this issue after running vesktop from command line.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
can't reproduce and you're the only one experiencing this. try again on an official release. 
![image](https://github.com/user-attachments/assets/20159802-cfd2-441c-b3ab-f6a0ea7acc3f)

**Comment by cvoges12** [comment]
I'll send logs after I'm done. But you have an inherent misunderstanding of how nix works if you expect me to run the official package without repackaging it for nix.

Can we leave this open? I don't see the point in closing it just b/c we haven't found a direct source of the problem.

**Comment by cvoges12** [comment]
Also, where does vesktop store persistent data? I have a feeling that it might be writing to the nix store somehow. If that's the case then this would be able to be reproduced on *any* atomic style linux distribution including guix and fedora silverblue. So the only way around that would be to have some sort of flag/option to store the information elsewhere.
