### ISSUE TITLE
How does webcord compare to vencord in terms of privacy?

### ISSUE THREAD

**Issue by Abyssgrowth** [Vencord/Vesktop#78]
How does webcord compare to vencord in terms of privacy?
This one, https://github.com/SpacingBat3/WebCord

How does WEBCORD compare to VENCORD/VESKTOP in terms of privacy?

In webcord there are several privacy focused settings.
Microphone, camera, desktop capture, background synchronisation, typing indicator, telemetry and fingerprinting can all be BLOCKED.
There are advanced options to disable the built-in content security policy and third party websites.
Does vencord have the same privacy capabilities as webcord does?

Is vencord capable of blocking discord's spying on the memory/ram?
Disabling the game activity status DOES NOT STOP discord from spying on
what programs/applications you are using on your computer, however webcord does block this!

**Comment by somerandomcloud** [comment]
Vencord already blocks Discord trackers/telemetry by default, typing indicator can be blocked with a plugin, background sync can be blocked, and microphone and camera are opt-in (by using them).

Disabling the CSP is dumb/insecure, idk why you would want to do that

And what are you on about with the discord spying on the memory/ram?? If you are referring to game activity it can be disabled with one of the plugins.

Lastly, this is github issues. You should use this to report issues with the program itself, not to ask questions. To ask questions, use the support channel in the server

**Comment by Vendicated** [comment]
There are no relevant privacy differences between the two. They are both terrible in terms of privacy, because this is Discord we're talking about. if you care about privacy, use something like https://matrix.org/

> Microphone, camera, desktop capture, background synchronisation [...] can all be blocked [in webcord]

This is useless. Discord will not use these unless you do some action that specifically requires them, like voice chat.

Telemetry and such are force disabled by Vencord but Discord still tracks a shit ton which cannot be disabled

> Is vencord capable of blocking discord's spying on the memory/ram?
Disabling the game activity status DOES NOT STOP discord from spying on
what programs/applications you are using on your computer, however webcord does block this!

Webcord does not block this, it's just that it's an entire rewrite of Discord's native code so the code that does that is not even used. The same applies to Vesktop

**Comment by Abyssgrowth** [comment]
> Vencord already blocks Discord trackers/telemetry by default, typing indicator can be blocked with a plugin, background sync can be blocked, and microphone and camera are opt-in (by using them).
> 
> Disabling the CSP is dumb/insecure, idk why you would want to do that
> 
> And what are you on about with the discord spying on the memory/ram?? If you are referring to game activity it can be disabled with one of the plugins.

Because of the companys behind the CSP.
We already know what "content security" means when it comes from youtube. It's their term for censorship.
I'm not concerned over censorship on discord, that wouldn't make much sense, but i see no reason why i would need their CSP, i generally don't klick on attachments.
In the webcord settings there's a list of the third party CSP providers:
Google, youtube, paypal, reddit, spotify, twitch, and a few more. I hate all of these.

Well it's obvious, if discord can track what games you run on your machine, they can track any process running on your machine, and i see no reason why they wouldn't do that.
I would do it, and sell the data. Could easily spy on massive amounts of devices, keep track of what programs are mostly used and discover new trends, it would be stup!d if discord didn't do precisely that.

Disabling the gameactivity in the discord settings doesn't do anything.
This will only stop discord from showing other people what you do but it does not stop discord from tracking what you do.
In other words, discord doesn't show other discordusers you activity but they do still track your activites and that's exactly what i hate, so screw discord!!
To repeat my question, is it possible in vencord to block discord from spying on my ram/program useage and i mean block and not just hide status.

**Comment by Abyssgrowth** [comment]
> There are no relevant privacy differences between the two. They are both terrible in terms of privacy, because this is Discord we're talking about. if you care about privacy, use something like https://matrix.org/ . However, both of them use no native Discord code so they are both more private than the normal Discord desktop app, Discord is contained entirely in the Browser process (as if you were opening discord.com in chromium)
> 
> > Microphone, camera, desktop capture, background synchronisation [...] can all be blocked [in webcord]
> 
> This is useless. Discord will not use these unless you do some action that specifically requires them, like voice chat.
> 
> > telemetry and fingerprinting
> 
> Telemetry and such are force disabled by Vencord but Discord still tracks a shit ton which cannot be disabled
> 
> > There are advanced options to disable the built-in content security policy and third party websites.
> 
> This is also useless. content security policy is more of a security feature than a privacy feature. There is no gain from blocking more sites because they are never requested anyway
> 
> > Is vencord capable of blocking discord's spying on the memory/ram?
> > Disabling the game activity status DOES NOT STOP discord from spying on
> > what programs/applications you are using on your computer, however webcord does block this!
> 
> Webcord does not block this, it's just that it's an entire rewrite of Discord's native code so the code that does that is not even used. The same applies to Vesktop

You got me curious, if telemetry/fingerprinting is force disabled by vencord (as i have seen in the plugins settings) what specificaly does discord still track that cannot be disabled?
Obviously if i send a message through vencord, it will be stored on discord's servers.

Alright, so if i understod correctly what you said that means as long as i don't enable the activity status in vencord, discord will not be able to spy on the devices memory. But if i enable the activity status, the code spying on the memory will be executed untill i turn it off again?
I'm a bit suspicious about that one because on native discord as i have already said, you can disable the activity status but it's pretty much useless because the only thing it does is hide your activites from other discord users but it does not stop discord from tracking your activites.
I have tested this.
I've turned off the activity status in discord, launched a game and checked discord, guess what discord knew that i ran that game even when the activity status was disabled. I bet they sell the activity data to god knows who.

**Comment by ryanccn** [comment]
WebCord seems to have a very bad case of stupid marketing. It doesn't block "fingerprinting", it blocks requests that Discord uses to collect metrics, which is not fingerprinting. With regards to the permissions, you grant the app these permissions, and if you don't like the app you revoke them. I don't see why you would even be using Discord if you had such paranoid fears about it misusing your sensors. 

A content security policy is not "censorship", it's ensuring that your Discord client isn't able to run unauthorized scripts or fetch unauthorized resources in the event of it being compromised. Clicking attachments has nothing to do with this.

I took a look at the WebCord source code and I don't really see how it has any significant privacy improvement. There's no code in Vesktop that lists processes or gets system resource usage or some other bullshit you're afraid of. There is no code "spying on the memory", activity status relies on a consenting process sending information to the Discord/Vesktop app.

**Comment by Vendicated** [comment]
you seem to have very heavily misunderstood what a content security policy is.

It's a way for websites to tell the browser what sites specific content comes from. For example, discord only allows scripts from trusted sources. Trying to load scripts from other sites will lead to the browser refusing to load the script. This is solely a security measurement to prevent XSS vulnerabilities in sites and has nothing to do with censorship or privacy. the domain csp switches in webcord also don't at all mean use that provider, they mean whether requests to that provider should be allowed. For example, if you don't allow Spotify, Spotify embeds won't work. In any case there is no privacy benefit from doing this


As for process scanning, as already said, the code that does that only exists in the Discord desktop app. Custom clients like webcord or vesktop don't even have that code. And in the discord desktop app you can disable process scanning entirely via the no rpc plugin
