### ISSUE TITLE
[Bug] Screensharing a Steam game in borderless fullscreen causes the game to freeze upon being focused.

### ISSUE THREAD

**Issue by Red6785** [Vencord/Vesktop#780]
### Discord Account

red6785

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

KDE Plasma 6.1.3 on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

The issue is that when I screenshare a game on Steam in borderless fullscreen, the game freezes upon being focused. When I unfocus, it returns to normal. No input is accepted, and the game locks up until I tab out, with the only exception being the music.

### What is the expected behaviour?

The game should not freeze.

### How do you recreate this bug or crash?

1. Open a game on steam.
2. Join a call on Discord.
3. Attempt to screenshare the game in borderless fullscreen.

### Debug Logs

Only three unique lines are displayed.
```
[3:0726/144156.631259:ERROR:shared_x_display.cc(39)] Unable to open display
[54:0726/144157.776977:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE
[54:0726/144345.589165:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE
'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
```
The second line spams constantly, seemingly hundreds of times a second, while I'm streaming. Changing the window from borderless to bordered does not seem to change that. Changing the window to something besides a Steam game also does not stop the log spam.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Red6785** [comment]
Attached is a video example with the game "Risk of Rain 2".
You can see in the stream window that when the game is unfocused, it is animated, functioning normally. However, when I tab into the window and focus on it, it freezes.
https://github.com/user-attachments/assets/40e4a91e-4035-4234-8442-04c6cb12fede

**Comment by Vendicated** [comment]
nothing we can do about it, entirely out of vesktops control

**Comment by Red6785** [comment]
I believe the issue may actually be Proton games. Attached is a video of the same test on Dead Cells running under Proton. It freezes.
https://github.com/user-attachments/assets/6be68c8b-3c24-462b-9477-39c15f934462
However, when I run the Linux native version of the game, screensharing works, as seen below.
https://github.com/user-attachments/assets/88dba175-3f40-4e7f-9c61-cb9d9f75badb
I attempted to screenshare a windows app running under WINE in borderless fullscreen, and it works as intended.
https://github.com/user-attachments/assets/66190ca2-251d-46e8-8788-c0a980af2ad2
I think the log spam above is harmless and does not actually relate to the issue at hand, upon looking into the open issue report for it in upstream Chromium. Primarily because it also appears when streaming works as intended.

**Comment by Red6785** [comment]
@Vendicated where should I take this issue, since you've marked it as upstream?

**Comment by Curve** [comment]
> @Vendicated where should I take this issue, since you've marked it as upstream? I do think it is important to note that this wasn't an issue until about two weeks ago, when I updated my whole system.

Most likely chromium

**Comment by Red6785** [comment]
> Most likely chromium

I am unsure of how I would report this to the Chromium devs since I have no clue what is causing the issue. I didn't see anything in the commandline, nor the proton logs.

**Comment by Red6785** [comment]
Incredibly, my issue is solved. I was attempting to work around it by setting up a virtual camera with OBS instead, but while I was demonstrating why I was doing that to one of my friends, it started working as intended. Notably, the only change I made was installing the linux-headers package.
