### ISSUE TITLE
[Bug] Vesktop launches the default browser under Xwayland

### ISSUE THREAD

**Issue by Tecnio** [Vencord/Vesktop#782]
### Discord Account

tecnio

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Plasma 6.1.3 on Wayland

### Package Type

AUR, however I have replicated the issue on the AppImage

### What happens when the bug or crash occurs?

If Firefox is not currently running and a URL is clicked on Vesktop running under Xwayland, Firefox will even ignore "MOZ_ENABLE_WAYLAND=1" and will launch under Xwayland. This issue cannot be replicated when Vesktop is launched under Wayland using the --ozone-platform-hint=auto flag.

### What is the expected behaviour?

I expect Vesktop to launch Firefox under Wayland.

### How do you recreate this bug or crash?

Assuming the default browser is Firefox.

1. Launch Vesktop
2. Open a channel or a DM
3. Click a URL sent by anybody

### Debug Logs

```
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
Gtk-Message: 14:57:34.511: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:57:34.511: Failed to load module "window-decorations-gtk-module"
[19369:0728/145736.901734:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[19369:0728/145736.909671:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Tecnio** [comment]
https://github.com/user-attachments/assets/b2bb3f1a-086c-44d1-bd4c-6c86c74b080b

Here is a video showing the problem.

**Comment by Vendicated** [comment]
opening links just calls `xdg-open https://example.com`, which invokes your system's default browser. it's entirely controlled by your system. thus, this issue has nothing to do with Vesktop

**Comment by Tecnio** [comment]
https://github.com/user-attachments/assets/84a39781-16ed-4e34-b6ed-2a6fe17ac750

Issue cannot be replicated by running `xdg-open https://example.com`, only happens on Vesktop.

**Comment by Tecnio** [comment]
I have also just attempted this one on the AppImage version as well, same applies here like I have mentioned on the post.

**Comment by k26pl** [comment]
From what i can see in the replication the terminal is running under wayland, probably browser is opening under same session as parent app.
For a simple fix you can do something like `alias vesktop=vesktop --ozone-platform=wayland` or find .desktop file for firefox and modify it to always use wayland
