### ISSUE TITLE
[Feature Request] Remove Advertising Option

### ISSUE THREAD

**Issue by githubplanetarparrot** [Vencord/Vesktop#783]
### Motivation

I hate ads and dislike popups from Discord asking me to buy things, especially sponsored things. 

### Solution

Add an option to block the Shop and nitro buttons, along with popups. 
![image](https://github.com/user-attachments/assets/b6e42047-814a-49ee-9c60-aae23fdd460b)

### Alternatives

N/A

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Curve** [comment]
This is possible with just CSS, see utility themes like [complementary-discord-theme](https://github.com/D3SOX/complementary-discord-theme).

**Comment by Curve** [comment]
Also, closing this as it is a plugin request, see related issue #210
