### ISSUE TITLE
[Bug] Screen sharing broken on Hyprland

### ISSUE THREAD

**Issue by kito30** [Vencord/Vesktop#791]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Hyprland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Black screen when screen sharing, currently using xdg-desktop-hyprland-portal.

### What is the expected behaviour?

Expect to sharing the current screen

### How do you recreate this bug or crash?

1. Proceed screensharing
2. Select screen
3. Show up black screen

### Debug Logs

[3:0801/214905.356838:ERROR:egl_dmabuf.cc(608)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[3:0801/214905.356879:ERROR:shared_screencast_stream.cc(938)] Dropping DMA-BUF modifier: 72057594037927940 and trying to renegotiate stream parameters
[50:0801/214905.380385:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by kito30** [comment]
nvm, portal broken.

**Comment by kito30** [comment]
its hyprland portal

**Comment by AnonCYTO** [comment]
ohh i see now, for some reason it was broken for me too so i ran(not as root user) this script to restart `xdg-desktop-portal-hyprland` and `xdg-desktop-portal`

```sh
#!/bin/bash

sleep 1
# kill all possible running xdg-desktop-portals
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-gnome
killall -e xdg-desktop-portal-kde
killall -e xdg-desktop-portal-lxqt
killall -e xdg-desktop-portal-wlr
killall -e xdg-desktop-portal-gtk
killall -e xdg-desktop-portal
sleep 1
# start xdg-desktop-portal-hyprland
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
# start xdg-desktop-portal
/usr/lib/xdg-desktop-portal &
sleep 1
```

IT WORKS NOW! THANKS!

**Comment by Rattlyy** [comment]
Hello, tried the script above & still not working, will print xdph & vesktop logs below.

xdph
```
[LOG] [screencopy] SHAREDATA returned selection 0
[LOG] [screencopy] Start:
[LOG] [screencopy]  | /org/freedesktop/portal/desktop/request/1_438/webrtc502186565
[LOG] [screencopy]  | /org/freedesktop/portal/desktop/session/1_438/webrtc_session1828766388
[LOG] [screencopy]  | appid: 
[LOG] [screencopy]  | parent_window: 
[LOG] [pw] Building modifiers for dma
[LOG] [screencopy] Sharing initialized
```

vesktop
```
[87902:0827/005105.758681:ERROR:shared_screencast_stream.cc(215)] PipeWire stream state error: no more input formats
[87902:0827/005105.758708:ERROR:shared_screencast_stream.cc(178)] PipeWire remote error: no more input formats
```

**Comment by Rattlyy** [comment]
fixed: electron/chromium hate bitdepth 10 so you need to set bitdepth to 8 for it to work

**Comment by enderprism** [comment]
how do you change the bit depth?
