### ISSUE TITLE
[Bug] .XCompose doesn't work

### ISSUE THREAD

**Issue by carbeck** [Vencord/Vesktop#793]
### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

KDE Plasma 6 (Wayland)

### Package Type

Flatpak

### What happens when the bug or crash occurs?

The compose key function uses the default definitions in `/usr/share/X11/locale/en_US.UTF-8/Compose` instead of the ones in `~/.XCompose`. This means that additional, user-defined key macros for accented/special characters aren't accessible.

### What is the expected behaviour?

Instead of falling back to `/usr/share/X11/locale/en_US.UTF-8/Compose`, the definitions in `~/.XCompose` should be used. The container has permission to read the file:

```
$ flatpak info --show-permissions dev.vencord.Vesktop 
[Context]
filesystems=[…];/home/<username>/.XCompose:ro;[…]
```

### How do you recreate this bug or crash?

1. Type a key combination defined in `~/.XCompose` but not in the system file.
2. See it not work.
3. Type a key combination defined in the system file.
4. See it work.

### Debug Logs

```
$ flatpak run dev.vencord.Vesktop 
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto
[3:0802/193040.076417:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0802/193040.464744:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[3:0802/193040.464822:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
might be https://issues.chromium.org/issues/40272818

but also not a vesktop issue. it's somewhere upstream, nothing we can do

**Comment by miguilimzero** [comment]
@Vendicated So this is an issue related to chromium. I'm currently using Chrome as my default browser + different Chromium apps from Flathub, and Vesktop is the only one not respecting the `.XCompose`. 

Could it be related to something specific with Vesktop + Wayland? Is there a way to set Vesktop to run with the same composer compatibility as Chrome?

**Comment by RedSnt** [comment]
If .xcompose is important to you, which it is for me, then you can disable wayland support for Vesktop using flatseal, that makes Vencord load .xcompose correctly. I wonder if there are arguments to get the wayland version to correctly load .xcompose, would be really nice to not having to "downgrade" the experience to xwayland.
