### ISSUE TITLE
[Feature Request] Option to disable app icon and the furry child twerking gif

### ISSUE THREAD

**Issue by BrownNPC** [Vencord/Vesktop#794]
### Motivation

I don't like how a gif of a loli character twerking plays when I open this app. Also the icon is unnecessary. I'm not homophobic, But I don't want a pride flag in my taskbar either, since it's a sin. 

I know you are not allowed to use original discord icons because of copyright, But I know you CAN make it easier to disable the loading animation, and change the icon. 

### Solution

Just add an option in settings to have no loading animation

### Alternatives

Changing the icon on the flatpak is literally so difficult, I cannot figure it out, so now i'm using the RPM, and it's sorted. But still there's no way to disable the loading animation.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
hey at least you're self aware
![image](https://github.com/user-attachments/assets/270fbe91-f3b2-453f-9756-59a0d800ea35)
