### ISSUE TITLE
[Bug] It will automatically logout at a period of time.

### ISSUE THREAD

**Issue by blusewill** [Vencord/Vesktop#796]
### Discord Account

blusewill

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

dwm

### Package Type

Flatpak

### What happens when the bug or crash occurs?

When close the for a period of time and open it again. It will automatically logout.
![image](https://github.com/user-attachments/assets/e255a652-5f27-45e8-bbcc-3af95271df23)

### What is the expected behaviour?

I expect it to be login all the time.

### How do you recreate this bug or crash?

1. Login in to Discord.
2. Fully Close it
3. Wait for another 1 - 5 hours
4. Open it again

### Debug Logs

```
Passing the following arguments to Electron: --enable-speech-dispatcher
checkForUpdatesAndNotify called, downloadPromise is null
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Kisakay** [comment]
i have the same problem

**Comment by Vendicated** [comment]
Read the FAQ and search existing issues.
