### ISSUE TITLE
[Bug] Huge Empty Pixel Borders Around Flatpak Window

### ISSUE THREAD

**Issue by powerofthe69** [Vencord/Vesktop#798]
### Discord Account

powerofthe69

### Operating System

Fedora Silverblue 40

### Linux Only ~ Desktop Environment

Gnome on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

I noticed recently after deciding to try the Flatpak of Vesktop again after months of using the RPM, that the Flatpak version has really big empty pixel borders around the window when snapped to any position on the screen. The RPM version and the Appimage versions don't do this, and this is the only Flatpak application I've used with this unique issue.

### What is the expected behaviour?

I expect the window to use all available pixels when snapped to a position on the screen. I've included a screenshot of the application's RPM snapped to the left side of the monitor, and the application's Flatpak version snapped to the right.
![Screenshot from 2024-08-05 13-06-54](https://github.com/user-attachments/assets/11963d78-1f5c-478e-afde-5c5872f13888)

### How do you recreate this bug or crash?

1. Install the Flatpak version of Vesktop
2. Snap it to a corner or side of the screen

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by powerofthe69** [comment]
I... fail to see how this isn't following the template for issues when all fields have been filled out as templated...

**Comment by Vendicated** [comment]
the fact that you should not support graphical glitches because they are out of our control.
