### ISSUE TITLE
[Bug] Rich Presence shows that I am playing a game that is not even installed

### ISSUE THREAD

**Issue by dekkusudev** [Vencord/Vesktop#800]
### Discord Account

dekkusu

### Operating System

Windows 11 23H2 build 22631.3958

### Package Type

Setup.exe

### What happens when the bug or crash occurs?

Rich Presence shows that I am playing a game that is not even installed. At the same time, such a bug does not occur in the official PTB client. In addition, this has another interesting manifestation: when I actually open a game that should be considered in RPC, after closing, Vesktop still thinks it is open.
![image](https://github.com/user-attachments/assets/ff424c1c-fd9a-4e42-8ab0-43437b644909)

### What is the expected behaviour?

I except Vesktop will be correct to see the games supported by Rich Presence and stop the game session in correct time.

### How do you recreate this bug or crash?

1. Download and install Vesktop
2. Open it

### Debug Logs

```
[arRPC > ipc] not available, trying again (attempt 1)
[arRPC > ipc] listening at \\?\pipe\discord-ipc-1
[arRPC > websocket] 6463 in use!
[arRPC > websocket] listening on 6464
[arRPC > process] started
[arRPC > process] detected game! Last Man Standing
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by dekkusudev** [comment]
I'm sorry, maybe I should have contacted the arRPC repository, but I still hope for your help

**Comment by PolisanTheEasyNick** [comment]
https://github.com/OpenAsar/arrpc/issues/94

**Comment by dekkusudev** [comment]
> [OpenAsar/arrpc#94](https://github.com/OpenAsar/arrpc/issues/94)

Yes, thanks, that was the problem. But where can I find the detectable.json file in the case of Vesktop? Closing the process every time, which I'm not sure is safe, is somehow not very cool.

**Comment by PolisanTheEasyNick** [comment]
> But where can I find the detectable.json file in the case of Vesktop?

It must be in `node_modules/arrpc/src/process` folder, but I think easier for you will be just to use IgnoreActivities plugin.

**Comment by dekkusudev** [comment]
Okay, thank you, I got it. Problem resolved.
