### ISSUE TITLE
[Bug] Limited refresh rate when viewing a stream

### ISSUE THREAD

**Issue by QuantumOof** [Vencord/Vesktop#802]
### Operating System

Ubuntu 24.04 (Studio)

### Linux Only ~ Desktop Environment

Kde Plasma 5.27.11, both Xorg and Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Occurs when playing/sharing a game at high refresh rates while watching another person's stream on my second monitor, the game's framerate is limited to 60fps/ the rate of the viewed stream. Both monitors are 144hz, tested with both xorg and wayland, hardware encoding on and off.

### What is the expected behaviour?

Expected behavior is for the game to play at normal refresh rates (144fps, 1440p) regardless of 

### How do you recreate this bug or crash?

Play game while watching a stream on second monitor - impact depends on game, to a limited extent. Nothing goes past 60 fps, but games like for honor and sometimes overwatch can be lower.

### Debug Logs

N/A

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
not a vesktop issue. vesktop has no control over these aspects, it's a chromium or electron or system issue
