### ISSUE TITLE
[Bug] When I get pinged I freeze/gras

### ISSUE THREAD

**Issue by Rain-Gayming** [Vencord/Vesktop#804]
### Discord Account

RainGayming

### Operating System

Linux

### Linux Only ~ Desktop Environment

Endevour on KDE Plasma 6

### Package Type

Flatpak

### What happens when the bug or crash occurs?

When I'm pinged discord freezes, sometimes it will hard crash about a minute after sometimes it will unfreeze.

### What is the expected behaviour?

It doesn't freeze

### How do you recreate this bug or crash?

I just get pinged and it happens

### Debug Logs

No crash log as it stops responding then crashes

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
https://wiki.archlinux.org/title/Discord#Discord_freezes_after_getting_pinged_or_messaged
