### ISSUE TITLE
[Feature Request] Screenshare audio from JACK on Linux

### ISSUE THREAD

**Issue by ShawkMusic** [Vencord/Vesktop#806]
### Discord Account

shawkk

### Motivation

I want to play music for my friends on Discord, and I can screenshare with Pulseaudio (well, really Pipewire, but Reaper thinks it's Pulseaudio) and they can hear it, but the latency is terrible. And I don't know if you've ever played an instrument with a delay, but even just a couple ms of delay can completely throw your rhythm off. JACK is good and has low latency, but when I switch Reaper to using JACK, the audio doesn't play through the screenshare.

### Solution

Make screenshare audio also include audio sources from JACK, ideally by both including it in the audio used on the "Entire System" option and by showing the sources on the "Audio Sources" selector

### Alternatives

Playing through Pulseaudio works, but it has terrible latency for me.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
https://github.com/Vencord/venmic/issues/21
