### ISSUE TITLE
[Bug] Flatpak not opening without --disable-gpu flag - Failed to send GpuControl.CreateCommandBuffer.

### ISSUE THREAD

**Issue by relma2** [Vencord/Vesktop#807]
### Discord Account

Relma2

### Operating System

Endeavour OS

### Linux Only ~ Desktop Environment

KDE on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

The app does not open when I run it via flatpak normally - it reports an issue with the GPU (see below). However, it runs fine when I run Vesktop with the `--disable-gpu` flag

### What is the expected behaviour?

I expected the app to open

### How do you recreate this bug or crash?

1. `flatpak run dev.vencord.Vesktop`
2. Observe error message

### Debug Logs

```
flatpak run dev.vencord.Vesktop 
F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
Using NVIDIA on Wayland, disabling gpu sandbox
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --disable-gpu-sandbox --ozone-platform-hint=auto
[3:0808/173904.503007:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0808/173904.761280:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0808/173904.761323:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[64:0808/173905.065977:ERROR:command_buffer_proxy_impl.cc(132)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [x] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by relma2** [comment]
Nevermind Uppdating Vesktop via the devtools console resolved the issue

**Comment by MrQvest** [comment]
I have this issue too, though I've only had it in Arch Linux (using the flatpak) and now in Fedora Kinoite. In regular Fedora KDE this doesn't happen. Fully updated Vesktop and Vencord, as well as updated system and all necessary drivers (NVIDIA Optimus) installed

**Comment by demanuPL** [comment]
> Nevermind Uppdating Vesktop via the devtools console resolved the issue

Can you tell me how to do this via devtools console?

**Comment by relma2** [comment]
@demanuPL According to Issue #669 : In the Developer Console (Ctrl+Shift+I), type
```
await Vencord.Updater.checkForUpdates()
await Vencord.Updater.update()
VesktopNative.app.relaunch()
```
