### ISSUE TITLE
[Bug] flatpak not running on bazzite 

### ISSUE THREAD

**Issue by zany130** [Vencord/Vesktop#809]
### Discord Account

zany130

### Operating System

Bazzite

### Linux Only ~ Desktop Environment

KDE wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

vesktop does not fully launch (stuck on the shiggy loading vesktop)

### What is the expected behaviour?

vesktop launches

### How do you recreate this bug or crash?

run `flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop`

### Debug Logs

```
flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop                                                                                                   ─╯
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto
[3:0809/193810.758518:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0809/193810.961102:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0809/193810.961143:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(node:3) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, mkdir '/run/user/1000/doc/a306d307/dist'
    at mkdirSync (node:fs:1372:26)
    at j2 (VCDMain:13:813)
    at async Ln (VCDMain:15:4727)
(Use `vesktop.bin --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
^C[3 preload-host-spawn-strategy] Dropping 0x1e0c00240d80 (3) because of connection closed
[3:0809/193823.929698:FATAL:bus.cc(1246)] D-Bus connection was disconnected. Aborting.
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by zany130** [comment]
maybe related to https://github.com/Vencord/Vesktop/issues/770 but I currently have selinux set to permissive

**Comment by Vendicated** [comment]
for some reason it's not allowing vesktop to create (or ensure it exists) the vencord files directory
```
(node:3) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, mkdir '/run/user/1000/doc/a306d307/dist'
```

this is most likely to happen if you choose a custom vencord location that the flatpak has no access to (it will be temporary), so if that's the case, reset it to default

**Comment by zany130** [comment]
hmm for some reason my vecondDir was set to `/run/user/1000/doc/a306d307/dist` removing the line fixed it

I was using a custom directory (and added it to the flatpak permissions for vesktop) but it seems it somehow got set to `/run/user/1000/doc/a306d307/dist`

anyway, that was the issue. Thanks!
