### ISSUE TITLE
rich presence false positive

### ISSUE THREAD

**Issue by Licantropo3392** [Vencord/Vesktop#81]
i'm not playing any game but in the rich presence there is a game called "last man standing", i dont know what is it, i have tried to close completely the app and it and disappeared, when i opened again vesktop it returned

![Screenshot 2023-08-04 104152](https://github.com/Vencord/Vesktop/assets/104359791/1f2ec956-1daa-492d-bdfb-7d9e8223d8fe)

**Comment by BLANKE1** [comment]
Do you have any apps named "LMS.exe" opened on your PC? Seems to match the .exe of that game shown in that screenshot

**Comment by luximus-hunter** [comment]
The issue seems to come from the Intel Local Management Service.

![img-2023-08-03-14-48-52](https://github.com/Vencord/Vesktop/assets/49814847/4270b8a0-2aca-4904-bd0b-3af8dd553603)

Temp fix is to disable arRPC

**Comment by Vendicated** [comment]
known issue that has already been fixed in arrpc. just need to wait for next vesktop update. if you care a lot, you can disable vencord arrpc and instead run your own with the plugin
