### ISSUE TITLE
[Bug] Accounts logging out when shutting down laptop

### ISSUE THREAD

**Issue by i-am-zaidali** [Vencord/Vesktop#810]
### Discord Account

crayyy_zee

### Operating System

Ubuntu 22.04

### Linux Only ~ Desktop Environment

Gnome on wayland

### Package Type

Debian

### What happens when the bug or crash occurs?

Shutting down the laptop while vesktop is open and booting back up, logs out all accounts.

### What is the expected behaviour?

Expected that my account stays logged in.

### How do you recreate this bug or crash?

1. Open vencord on a system
2. Shut down the system while vesktop is open
3. Restart the system.

### Debug Logs

Can't find the logs since the PC is shutting down. If logs are stored in a file, please let me know and I will share them in a followup comment

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Sqaaakoi** [comment]
enable NoDevtoolsWarning

**Comment by i-am-zaidali** [comment]
That seemed to have worked. I'll observe a while before closing the issue, thanks!

**Comment by iTrooz** [comment]
Is there any explanation for why this happen ?

If this happens to all users of Vesktop, it may be a good idea to implement this in Vesktop/Install the plugin by default

**Comment by k26pl** [comment]
> Is there any explanation for why this happen ?

when showing the devtools warning discord tries to hide token, and sometimes it doesn't restore it.
> If this happens to all users of Vesktop, it may be a good idea to implement this in Vesktop/Install the plugin by default  

NoDevtoolsWarning fixes this and mentions this in its description

**Comment by iTrooz** [comment]
>  NoDevtoolsWarning fixes this and mentions this in its description

I understand this, but I had to look at the issues list here multiple times (I already checked like 2 weeks ago) to find this solution to the problem. this is why I think there should be an easier way to deal with it
