### ISSUE TITLE
[Bug] cursor change

### ISSUE THREAD

**Issue by vamtic** [Vencord/Vesktop#812]
### Discord Account

vamtic

### Operating System

Kubuntu 24.04

### Linux Only ~ Desktop Environment

KDE

### Package Type

Flatpak

### What happens when the bug or crash occurs?

I set the cursor to something in KDE and its a really old time cursor in vesktop (ugly as my shit) so fix it plz...

### What is the expected behaviour?

The cursor I setuped and that works in any other apps.

### How do you recreate this bug or crash?

It was already written down in the past.

### Debug Logs

No log.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by catgirlcataclysm** [comment]
It has been a long time so I cannot guarantee this is all I did to solve this, but the issue afaik is due to the flatpak sandbox disallowing access to the cursor files. I gave vesktop read-only access to ``~/.icons`` and ``~/.themes``, which I believe solved the issue.

**Comment by vamtic** [comment]
plz commands to give access

**Comment by vamtic** [comment]
i hate flatpak btw

**Comment by Vendicated** [comment]
please use our support channel if you need further help

**Comment by vamtic** [comment]
nah
