### ISSUE TITLE
[Feature Request] Sync the "plus" button behavior with the desktop app

### ISSUE THREAD

**Issue by ClangPan** [Vencord/Vesktop#814]
### Discord Account

frousties

### Motivation

Hi! 

I have noticed that the "plus" button on Vesktop directly opens the file explorer to put an attachment instead of giving the same options as the desktop app (I am aware this is due to Vesktop using Discord's browser version)
![image](https://github.com/user-attachments/assets/9edba781-4c9b-470f-8b04-852a88022eb9)

I wonder if it would be possible to sync the "plus" button behavior with how it works on the app side? Because currently there is no way (that I know of) to create polls in Vesktop

### Solution

Create a pop up mirroring the desktop bahavior for the "plus" icon

### Alternatives

Or at least add a button to create polls in the action bar

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
you have BetterUploadButton enabled on one client but not the other
