### ISSUE TITLE
[Feature Request] macOS notification sound should follow notification

### ISSUE THREAD

**Issue by jakjakob** [Vencord/Vesktop#815]
### Motivation

The notification sound is not connected with the actual notifications, making it so ignore focus modes (do not disturb, etc.) and the related setting to it

### Solution

The notification sound should be made via the macOS notification

### Alternatives

whenever I put any of my Apple devices into a focus mode that mutes Discord notifications, I need to go to open Vendicord and put discord in focus mode (thing that I mostly forget about to do)

### Additional context

(even though this could be considered a bug, this is the same behaviour as the vanilla client)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by jakjakob** [comment]
(I hope I described it in an understandable manner)

**Comment by Vendicated** [comment]
I have no idea what any of this means. Anyway notifications are handled by discord

**Comment by jakjakob** [comment]
What I am trying to say is that macOS notifications work (from a user perspective) the same way as notifications on iPhones; Discord (and so Vesktop) uses the standard macOS notifications to send notifications. The issue I am describing is that instead of making the message sound go with the notification, it is separate, made by the application itself and not the notification. This is an issue because when you silence the notifications (via for example macOS focus mode (do not disturb)), the message sound still happens; when it shouldn't because the notification isn't delivered/should be silent (suppressed by the OS).
Hope this explain its better. (I'm gonna in any case make an issue to Discord now, in case they would fix that, would that also affect Vesktop? In that case you can just close the issue)

**Comment by Vendicated** [comment]
vesktop just uses chromiums browser notification api which we have no control over

so i can't tell you how it works or why this happens, nor can we do anything to fix it

you should check if this also happens on chrome app and if yes report it to chromium
