### ISSUE TITLE
[Feature Request] add support for discord reactive image

### ISSUE THREAD

**Issue by Nyanpasu1** [Vencord/Vesktop#817]
### Motivation

discord reactive image (https://reactive.fugi.tech/) is not working properly when using vekstop, which is working on normal discord

### Solution

spoof the executable to be similar with dekstop

### Alternatives

add option to use normal discord instance in vekstop

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
not easily possible. use discord desktop app if you need this
