### ISSUE TITLE
[Bug] Fullscreen game stops rendering when screensharing

### ISSUE THREAD

**Issue by Ly-sec** [Vencord/Vesktop#818]
### Discord Account

Lysec

### Operating System

Nobara 40

### Linux Only ~ Desktop Environment

KDE Plasma 6

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Everytime I try to screenshare a fullscreen / borderless window game it seems like it stops rendering on my part however the stream is just fine (meaning I can not do anything inside the game while streaming)

### What is the expected behaviour?

Quite "simple" really, it should not freeze the game while screensharing.

### How do you recreate this bug or crash?

1. Start game in fullscreen or borderless windowed mode
2. Screenshare

### Debug Logs

```
[53:0817/134125.225025:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE
```
This is just being spammed in my terminal.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by benjamin051000** [comment]
FWIW I am currently experiencing the same issue. For some reason, running Vesktop from the command line made it magically start working again? Either that, or disabling fullscreen, streaming it in windowed mode, then re-enabling fullscreen fixed it for me. Weird.

**Comment by fin444** [comment]
Experiencing the same issue, Bazzite / KDE / Wayland / NVIDIA. Running games in windowed mode does work, but neither of the potential solutions given by @benjamin051000 had any effect.

Supposedly the log output [will be fixed](https://issues.chromium.org/issues/331796411) once Chromium 131 hits Electron (currently using Electron 33 / Chromium 130), though I don't know if that will fix this issue.
