### ISSUE TITLE
[Feature Request] Chrome extensions support

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [Vencord/Vesktop#824]
### Motivation

Since discord is based on chromium, it would be very cool if we are able to include chromium extensions when building. This can make the Experience better.
For example, a better spellcheck like LanguageTool or Grammarly can make correcting spelling easier and suggest better way to structure sentence in discord.
Currently, running discord in a browser is the only way to have these feature with discord at the same time.

### Solution

Allow the users to add chromium extensions when building Vesktop

### Alternatives

Ctrl+Shift+i
try to navigate to Chrome web store by editing the HTML of the page and adding a link
unable to add an extension :(

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by KotonBads** [comment]
would probably maybe hopefully enable passkey login with a password manager extension like bitwarden as well

**Comment by Vendicated** [comment]
it doesnt support most of the extension api which makes a lot of extensions not functional

this is technically already implemented in vencord (used for react devtools) but has no ui

**Comment by ImGGAAVVIINN** [comment]
> it doesnt support most of the extension api which makes a lot of extensions not functional
> 
> this is technically already implemented in vencord (used for react devtools) but has no ui

By vencord do you mean the version that patches the discord desktop client?
If so, how do I install chromium extensions in the original discord client with vencord?

**Comment by ImGGAAVVIINN** [comment]
Other wise patch discord them install vencord is the best option :/

**Comment by ftc2** [comment]
i tried googling things like 'chrome extension in electron app' and am seeing some conflicting info about what's actually possible, but it would be sweet to be able to install **uBlock Origin** in Vesktop.

CSS can only take you so far. in particular, CSS can't do selectors like `:has-text()`.

**Comment by Vendicated** [comment]
you can't. anyway i'll be closing this since there is not any real use case that can't be solved with a plugin. like i said above, most extensions straight up won't work so it's pointless

**Comment by beedell-roke** [comment]
> [`#issuecomment-2308957970`](https://github.com/Vencord/Vesktop/issues/824#issuecomment-2308957970)

@KotonBads, CTAP2 support depends upon [`issues/910#issuecomment-2420087666`](https://github.com/Vencord/Vesktop/issues/910#issuecomment-2420087666).

> [`#issuecomment-2484594128`](https://github.com/Vencord/Vesktop/issues/824#issuecomment-2484594128)

@ftc2, despite [`electron/electron/issues/532#issuecomment-61963205`](https://github.com/electron/electron/issues/532#issuecomment-61963205), [`ramboxapp/electron-chrome-extensions`](https://github.com/ramboxapp/electron-chrome-extensions/blob/d310f98cb7226640bab74953f01933dac06ae0b1/README.md#electron-chrome-extensions) indicates that shims exist, if one's willing to create a PR.
