### ISSUE TITLE
[Feature Request] Using Discord's Default Icon

### ISSUE THREAD

**Issue by xii69** [Vencord/Vesktop#827]
### Motivation

Hey, I've installed Vesktop on Arch because of Wayland (screenshare problem) but I don't like this Icon of the app, anyway to use Discord's official one?

### Solution

Adding an option in the setting to use the Discord's official icon

### Alternatives

Discord official app

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by xii69** [comment]
@Vendicated so where is the other issue?

**Comment by PolisanTheEasyNick** [comment]
> @Vendicated so where is the other issue?

#667, especially https://github.com/Vencord/Vesktop/issues/667#issuecomment-2198762577 :)

**Comment by PolisanTheEasyNick** [comment]
> Well I didn't asked to change it globaly for everyone, I just like to change it for my self, I don't like the colors.

Locally there is many ways to change application icon
IMO fastest way for you will be to clone the repo and change icons in `static` and/or `build` folder (but I doesn't changed icons for myself so I may be wrong)

**Comment by xii69** [comment]
> > Well I didn't asked to change it globaly for everyone, I just like to change it for my self, I don't like the colors.
> 
> Locally there is many ways to change application icon
> IMO fastest way for you will be to clone the repo and change icons in `static` and/or `build` folder (but I doesn't changed icons for myself so I may be wrong)

Yea but I have to build it on each update right?
