### ISSUE TITLE
[Bug] Discord Window Snapping Disabled on Windows After Installing Vencord

### ISSUE THREAD

**Issue by battincik** [Vencord/Vesktop#829]
### Content

Hi,

After installing Vencord on my Windows computer, I noticed that the window snapping functionality for Discord is no longer working. Specifically, I am unable to drag the Discord window to the left or right side of the screen to automatically resize and dock it. This is a standard feature in Windows, where dragging a window to the screen's edge resizes it to fit that side, but with Vencord installed, this functionality seems to be disabled for Discord.

**Steps to Reproduce:**

1. Install Vencord on a Windows computer.
2. Open Discord.
3. Try to drag the Discord window to the left or right side of the screen.
4. Notice that the window does not snap or dock to the side as expected.

**Expected Behavior:**
The Discord window should snap to the left or right side of the screen when dragged to the edge, resizing to fit that side.

**Actual Behavior:**
The Discord window does not snap or dock to the side of the screen when dragged.

**Additional Context:**
This issue seems to only occur after Vencord is installed. Before installing Vencord, the window snapping feature works as expected with Discord.

Is there any reason why this feature is disabled, or is there a workaround to restore the window snapping functionality?

Thank you for your help!

**Comment by Vendicated** [comment]
disable transparency
