### ISSUE TITLE
[Bug] Themes Tab failed to render

### ISSUE THREAD

**Issue by ToasterUwU** [Vencord/Vesktop#83]
Im on the newest version, already tried to reinstall.

This is the first time i encountered it, not sure if its a 2.8 issue or the updates since then did this. Or maybe its just a me issue for some reason.

![image](https://github.com/Vencord/Vesktop/assets/43654377/0050cee3-f31b-4297-a986-12b9de389a69)

**Comment by Vendicated** [comment]
shouldn't happen, make sure you fully restarted vesktop

**Comment by ToasterUwU** [comment]
@Vendicated I did.

I quit Vesktop completly, made sure its not running anymore, reinstalled the deb, started again, and same issue.

**Comment by Vendicated** [comment]
could you please try right clicking the tray icon > redownload vencord files

**Comment by ToasterUwU** [comment]
There is no such option, i only have the following:

![image](https://github.com/Vencord/Vesktop/assets/43654377/2909ad20-fd5e-4c18-90a2-32d251217f8b)

**Comment by Vendicated** [comment]
Update Vencord is what I meant!

**Comment by ToasterUwU** [comment]
That fixed it weirdly enough. Is that button doing something else than the "Updater" Tab? If so, that's really confusing, and one of them should probably be renamed.

**Comment by Vendicated** [comment]
it just force redownloads vencord's files, which likely means the updater somehow only partially upgraded your files

**Comment by ToasterUwU** [comment]
Weird, If something like this happens again, I will mention it here. Hopefully, it was a one-time thing.
