### ISSUE TITLE
[Bug] Vesktop doesn't show current activity on Windows

### ISSUE THREAD

**Issue by Tosh0kan** [Vencord/Vesktop#833]
### Discord Account

totetosh

### Operating System

Windows 10

### Package Type

Setup exe

### What happens when the bug or crash occurs?

Vesktop doesn't show current activity to friends.

### What is the expected behaviour?

Show current activity, like what game am I playing, to my friends.

### How do you recreate this bug or crash?

I start the game and the activity isn't there.

### Debug Logs

```powershell
[arRPC > ipc] listening at \\?\pipe\discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
Update for version 1.5.3 is not available (latest version: 1.5.3, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[8516:0901/120834.998:ERROR:ffmpeg_common.cc(959)] Unsupported pixel format: -1
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
use our support channel for help
