### ISSUE TITLE
White Screen opening

### ISSUE THREAD

**Issue by Loleirs** [Vencord/Vesktop#835]
### Operating System

Windows 11

### Package Type

Setup

### What happens when the bug or crash occurs?

Whenever i open Vesktop i only get a white screen and nothing happens.

### What is the expected behaviour?

to open normally

### How do you recreate this bug or crash?

1. Search for Vesktop
2. Click on it
3. Get a white screen

### Debug Logs

Failed to parse Vesktop state.json: SyntaxError: Unexpected token '', ""... is not valid JSON
    at JSON.parse (<anonymous>)
    at et (VCDMain:1:2605)
    at VCDMain:1:3398
    at VCDMain:1:225
    at VCDMain:1:4556
    at VCDMain:1:225
    at Object.<anonymous> (VCDMain:87:331)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
delete that file from AppData/Roaming/Vesktop
