### ISSUE TITLE
[Bug] Colors on camera and screenshare messed up

### ISSUE THREAD

**Issue by SuperZekes** [Vencord/Vesktop#837]
### Discord Account

superzekes

### Operating System

CachyOS 6.9.9

### Linux Only ~ Desktop Environment

Gnome with Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

When I screenshare the screenshare preview looks just fine on my end but my friends said the colors look very messed up. As if they went color blind in a way, same thing with my camera.

### What is the expected behaviour?

I expected that the colors on the page would be what they are and I have tested my camera on apps like zoom and it works and looks fine.

### How do you recreate this bug or crash?

1. Use Gnome & Wayland
2. Try to screenshare
3. Turn on camera
4. messed up colors for the other people in the call

### Debug Logs

I don't have any.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by barraIhsan** [comment]
Related issue: #997 , and yes indeed it does happen. Usually after we turned on screen sharing / camera. In my case, sometimes it have some sort of "black" overlay and sometimes the entire camera/screenshare have a "green" overlay on them
Arch, KDE Wayland

**Comment by barraIhsan** [comment]
https://github.com/user-attachments/assets/c32c1d14-6f3f-46c4-8cb1-4fb1ec69d64f

As you can see, the first test is from Vesktop (`vesktop-bin` AUR, `1.5.4-2`) and as you can see on my phone (official discord client from play store), it has some weird color artifact.
This issue doesn't seem to happen at all when screensharing from Firefox (`133.0.3-2`, pacman).

The same issue occur when using a camera.

**Comment by mohak34** [comment]
yes even i am facing this issue, whenever i stream there is a green overlay. This overlay does not appear for me but my friends can see this.

Operating System
Arch Linux

Desktop Environment
Hyprland

Package Type
AUR
