### ISSUE TITLE
[Bug] Horrible Mic Quality / Microphone cutting in and out

### ISSUE THREAD

**Issue by Arsimael** [Vencord/Vesktop#838]
### Discord Account

arsimael

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Plasma 6 on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Regular usage of vesktop. No spechialities

### What is the expected behaviour?

A clear and understandable Audio connection.

### How do you recreate this bug or crash?

1. Open Vesktop
2. Connect to any Audio channel or even giong to the settzings and doing a "self test"
3. hearing very bad audio quality

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Arsimael** [comment]
When I am using Vesktop, My mic is cutting in and out, causing people not being able to understand me.

**Comment by Arsimael** [comment]
Oh. Ok. Thanks for not helping then.

**Comment by lewisakura** [comment]
Your issue was closed because it's a duplicate, not that we don't want to help you. Please look at the other issues on the tracker.

**Comment by Arsimael** [comment]
Can you please point out where? I searched through all issues and couldn't find any bug that describes the same issue.

**Comment by VelamyGH** [comment]
> Can you please point out where? I searched through all open issues and couldn't find any bug that describes the same issue.

https://github.com/Vencord/Vesktop/issues/520
