### ISSUE TITLE
[Feature Request] Audio Positioning

### ISSUE THREAD

**Issue by DSVDiniz** [Vencord/Vesktop#839]
### Motivation

Teamspeak 3 had a very useful feature where you could position users around in a virtual 2D top-view space, making individual audio sources easier to distinguish in big crowds of users. They marketed it as [3D audio](https://teamspeakdocs.github.io/PluginAPI/client_html/ar01s20.html).

### Solution

A simple implementation that would position user audio sources around the listener on fixed angle intervals would be good enough.

### Alternatives

-

### Additional context

![image](https://github.com/user-attachments/assets/a4d2f5f4-6cc1-44af-857e-4c14d4b54c3d)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
way out of scope for vesktop. if anything, this could be a vencord plugin, but that would still be way too niche
