### ISSUE TITLE
Context menu not appearing in Text input box 

### ISSUE THREAD

**Issue by Eevee109** [Vencord/Vesktop#841]
### Content

I have the plugin enabled for adding WebContextMenus - but the context menus fail to appear still like it does in the native discord client. This is when right clicking in the Text input area as well. Image above is Vesktop image below is the discord client flatpak

Currently running wayland on Nobara 40

![image](https://github.com/user-attachments/assets/bb666b09-ef76-4613-8976-6df42712ecf6)
vs 
![image](https://github.com/user-attachments/assets/58d64315-77ac-4ca7-85af-f9fc0a8240c0)

**Comment by Vendicated** [comment]
not a vesktop issue. please use our support channel if you need support
