### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by neddey** [Vencord/Vesktop#844]
### Operating System

Artix Linux Openrc

### Linux Only ~ Desktop Environment

Hyprland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

On startup

### What is the expected behaviour?

Vesktop to open

### How do you recreate this bug or crash?

1. Try opening Vesktop
2. Fail

### Debug Logs

```
[user@artix ~]$ flatpak run dev.vencord.Vesktop
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto
[3 zypak-helper] Failed to connect to session bus: [org.freedesktop.DBus.Error.NotSupported] Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
[3 zypak-helper] src/helper/main.cc:42(DetermineZygoteStrategy): Assertion failed: bus
/app/bin/startvesktop: line 26:     3 Aborted                 zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
Read the stacktrace

**Comment by neddey** [comment]
I'm not 100% sure what to do as I don't have X11/Xorg
