### ISSUE TITLE
[Feature Request] press "X" is not closing it. it will let you change window size.

### ISSUE THREAD

**Issue by Guy8964** [Vencord/Vesktop#846]
### Discord Account

Zsolt1000_II

### Motivation

everytime i wanna minimize Vesktop, i would move my mouse, go to right and up corner very fast and click
it not going to close, its going to change size of Vesktop

https://github.com/user-attachments/assets/8cd594e4-f60a-4cf2-9d09-93134dd5ad8c

### Solution

An options to disable "change Vesktop window size" in Vesktop setting.

### Alternatives

make "X" hitbox bigger.

### Additional context

if its old chromium's problem, im so sorry.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
just disable the Discord Titlebar setting and it will use the Windows OS titlebar
