### ISSUE TITLE
[Bug] Game Activity is disabled by default

### ISSUE THREAD

**Issue by Arcitec** [Vencord/Vesktop#850]
### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

Gnome on Wayland

### Package Type

RPM

### What happens when the bug or crash occurs?

Vesktop is misconfigured internally, and is set to disable Game Activity by default on fresh installs.

### What is the expected behaviour?

Since Vesktop defaults to enabling "Rich Presence", it is very strange that the actual "Game Activity" is blocked by default.

This means that even though the built-in `arRPC` is active by default, users will see ZERO game activity in Vesktop.

### How do you recreate this bug or crash?

1. Everyone has been trying to figure out why Game Activity was broken in Vesktop.
2. I solved it here: https://github.com/OpenAsar/arrpc/issues/105#issuecomment-2342753781
3. In short: The user has to manually enable the `GameActivityToggle` plugin and enable Game Activity, since it's disabled by default in Vesktop.
4. After enabling Game Activity, that plugin can be removed again and Vesktop will remember that Game Activity = On after that.
5. This really strikes me as a default configuration accident. Presumably, the normal behavior in Vesktop's default (reset/blank) config should be changed so that Game Activity is ON by default, just like Rich Presence arRPC is already ON by default. Without both being enabled, the arRPC feature is useless.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by AutumnVN** [comment]
gameactivitytoggle is just a shortcut for this switch, and it ties to your account
![image](https://github.com/user-attachments/assets/7bad37b6-d98e-4b59-bbd6-d2b2bb68e58a)
im sure you just somehow disabled it yourself in the past and forgot about that

**Comment by Arcitec** [comment]
@AutumnVN Oh thank you for that information! I was actually looking for something like that but didn't find it. And now I know why I didn't see that setting!

When troubleshooting this, I searched for "Rich Presence" in the Settings search box. Which brought up this result with NOTHING else in the panel:

![image](https://github.com/user-attachments/assets/2db4ab0b-7eed-4c69-9ec7-90cca5067e32)

To see the setting you mentioned, the user cannot use the search box and must go to it manually via the sidebar instead:

![image](https://github.com/user-attachments/assets/48f9f653-9044-46f5-b3c8-cb7f4e774b9c)

Thanks for clarifying that it's a per-account setting and not a bug in Vesktop! :)
