### ISSUE TITLE
[Bug] Journal flooded with error messages due to software video decode

### ISSUE THREAD

**Issue by kode54** [Vencord/Vesktop#852]
### Discord Account

kode54

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

labwc

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Video calls cause the journal to be flooded with messages:

```
[55:0912/211527.751544:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE
```

Once per frame of video displayed.

### What is the expected behaviour?

No error message flood.

### How do you recreate this bug or crash?

1. Start the app
2. Log in
3. Start a voice call
4. Enable video

### Debug Logs

There is no crash.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by kode54** [comment]
The issue can be fixed by disabling an Electron feature, like YouTube Music desktop app does:

https://github.com/th-ch/youtube-music/issues/2248

I have worked around the feature with the AUR vesktop-bin package by creating a `~/.config/vesktop/vesktop-flags.conf` file containing at least:

```
--disable-features=UseMultiPlaneFormatForSoftwareVideo
```

**Comment by Vendicated** [comment]
i don't think disabling some feature just to prevent log spam is a good idea. it really doesn't matter, and disabling features might lead to negative side effects; chromium added it for a reason. people who want to observe the log and not have this noise can just filter it out using tools like grep

**Comment by Vendicated** [comment]
"UseMultiPlaneFormatForSoftwareVideo DISABLED on Chromium M120+ is causing pink H264 video tinting in WebRTC media streams for Windows devices with old GPUs"
https://issues.chromium.org/issues/41485883

**Comment by kode54** [comment]
The .desktop file has to be edited to control what messages are logged. My DE logs all stdout/stderr from every application to the systemd journal.

**Comment by Mikilio** [comment]
While I can understand not wanting to disable a feature that seems to be on in electron by default. The issue you referenced seems to be fixed. If it is preferred to fix that issue upstream, the issue should at least be kept open because GitHub's default filters only show open issues.

On that note, should the issue go to electron then?

**Comment by Mikilio** [comment]
It also seems like a fix has already been [merged](https://chromium-review.googlesource.com/c/chromium/src/+/5873796), so we just need to wait for upstream to update.
