### ISSUE TITLE
Cannot fullscreen or change window size

### ISSUE THREAD

**Issue by RiceWitch** [Vencord/Vesktop#855]
### Operating System

windows 10

### Package Type

setup

### What happens when the bug or crash occurs?

I cannot fullscreen or resize window

### What is the expected behaviour?

I can resize and fullscreen the window

### How do you recreate this bug or crash?

1. install vencord
2. open vencord

### Debug Logs

N/A

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Koishukaze** [comment]
Did you perhaps enable this?
![image](https://github.com/user-attachments/assets/66937a03-cb4f-440c-b02e-58cfb1847599)

**Comment by RiceWitch** [comment]
that doesn't show up at all on my vencord

**Comment by RiceWitch** [comment]
I restarted and it worked nvm
