### ISSUE TITLE
[Feature Request] Add Option for Starting in Tray

### ISSUE THREAD

**Issue by anders130** [Vencord/Vesktop#857]
### Motivation

Many Linux applications offer a `-t` flag or a settings option to start hidden in the tray. This feature is useful for managing applications that should run in the background without occupying screen space. Currently, for applications like `vesktop`, I have to manually open and close the window or use a script to achieve this, which adds unnecessary steps and complexity to the startup process.

### Solution

Add a `-t` flag to the `vesktop` executable that allows it to start hidden in the tray.

### Alternatives

Alternatively, an option in the application's settings to always start in the tray would also be effective.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
--start-minimized
