### ISSUE TITLE
Issue about arRPC bug persisting on Vesktop

### ISSUE THREAD

**Issue by kvba0000** [Vencord/Vesktop#861]
### Content

Hi, I recently pushed a commit for arRPC that fixes one of the annoying problems that because of not updated version of Vesktop - still shows up.

Mainly the problem is about not being able to connect any account to Discord while Vesktop is enabled (no matter if using browser in that time or not)

I fixed the problem by implementing workaround on arRPC side which just forces client to connect it using HTTP request instead of WebSocket. It should fix this annoying problem also on Vesktop if it will be updated to the newest version.

Would be more than happy if my issue would be considered!

**Comment by lockieluke** [comment]
arRPC sometimes reports programs that don't even have Discord RPC implemented such as [Lossless Scaling](https://store.steampowered.com/app/993090/Lossless_Scaling/), it's constantly saying "Playing Lossless Scaling" whenever it's open but that doesn't happen with the official Discord app
![{EC86A36A-C7AF-424A-8518-0A140419B4B9}](https://github.com/user-attachments/assets/cb39246d-1f4d-4f3a-a530-0773e12eb4b6)

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/commit/d008f903995c802cb5addd99bd759878c8a3491a
