### ISSUE TITLE
[Bug] <title> Vesktop crashing

### ISSUE THREAD

**Issue by TheSilverFoxes** [Vencord/Vesktop#862]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Gnome on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

It crashes every time I open it (via CLI/App Tray)

### What is the expected behaviour?

I expected it to launch

### How do you recreate this bug or crash?

This happened when I updated my Arch system.

### Debug Logs

dev.vencord.Vesktop 
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto
[3:0918/182114.905512:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
/app/bin/startvesktop: line 26:     3 Segmentation fault      (core dumped) zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
your stack trace has 0 relevant info, so we can't help you. additionally, this is an issue with your system or the way you installed vesktop and has nothing to do with vesktop itself, so we can't help you

i suggest inspecting the full command output and check the segfault with coredumpctl and googling any errors you might find, it will probably help you resolve your issue
