### ISSUE TITLE
Query Regarding Implementation

### ISSUE THREAD

**Issue by yofukashino** [Vencord/Vesktop#864]
### Content

I was experimenting with Vesktop and the Discord client on Linux. From what I understand, Vesktop uses a web version of Discord because it enables getUserMedia and getDisplayMedia. Why can’t we use something like discord_arch_linux? It’s essentially Discord with a custom Electron build that supports the required features. Additionally, it could be patched to support Krisp easily, and keybinds would work out of the box.

So, my question is: Are there any underlying issues with this approach, or is it feasible? If it is feasible, are there any plans to make the switch?

Note: I know this might seem like a silly question, but I’m curious—curiosity killed the cat, after all. The easiest way to understand is to just ask.

**Comment by AAGaming00** [comment]
because discord doesn't use electron's media apis on the desktop client, they have a custom native module that implements all of it

**Comment by Vendicated** [comment]
I think you seem to have misunderstood the goal of vesktop

Vesktop is aiming to be much more than just better Linux screenshare, its main objective is being a full reimplementation of the desktop app code, which is
- more performant
- privacy friendly
- libre / easily auditable

screenshare is just one feature among many

**Comment by yofukashino** [comment]
> because discord doesn't use electron's media apis on the desktop client, they have a custom native module that implements all of it

oh those are in modules. they get used when you use custom electron.
