### ISSUE TITLE
[Bug] Having video call causes flood of journal errors

### ISSUE THREAD

**Issue by Mikilio** [Vencord/Vesktop#866]
### Operating System

NixOS

### Linux Only ~ Desktop Environment

Hyperland

### Package Type

nixpkgs

### What happens when the bug or crash occurs?

journalctl spams the following line:
```
[586776:0921/004221.915185:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE
```

### What is the expected behaviour?

No errors

### How do you recreate this bug or crash?

I don't know a minimal way to reproduce this but what I did was:
1. Have a video call.
2. Watch it on Pop-Out screen

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Mikilio** [comment]
What is happening may be similar to [this](https://github.com/th-ch/youtube-music/pull/2254/)

And a solution is also documented: basically adding `UseMultiPlaneFormatForSoftwareVideo` to disabledFeatures.

**Comment by Vendicated** [comment]
duplicate and irrelevant

**Comment by Mikilio** [comment]
Can you please refer me to the issue in question, so I can understand why this isn't planned?
