### ISSUE TITLE
[Bug] Screensharing with Hardware Accel cuts game FPS significantly

### ISSUE THREAD

**Issue by fleepers** [Vencord/Vesktop#869]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Gnome - Wayland

### Package Type

AUR

### What happens when the bug or crash occurs?

The linux screensharing is smooth, but it seems to use significantly more system resources than the windows counterpart when hardware acceleration is on. This occurs on both the AUR and Flatpak versions.

When playing a game (in this case, death stranding) i will be playing at ~120fps. When i screenshare it drops down to about 30fps. Lighter loads i.e VLC streaming works fine, but all 3d titles i've tried have been impacted quite a lot.

I'm on a i7 11700k and a AMD RX6700XT - is it a hardware issue? I've tried lowering settings to the absolute lowest and it makes no difference, and it persists across titles.

### What is the expected behaviour?

I expect to lose a smaller amount of system resources than it does currently when screensharing with hardware acceleration. 

### How do you recreate this bug or crash?

1) Turn on hardware acceleration
2) Load up a game, and stream it (quality doesn't matter).
3) Game FPS will completely tank after 4-5 seconds.
4) Turning hardware acceleration off will fix the fps issue, but will break the stream.

### Debug Logs

```
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
not something we can fix, screenshare is provided by chromium
