### ISSUE TITLE
show unread message indicator

### ISSUE THREAD

**Issue by rhysdh540** [Vencord/Vesktop#87]
It would be cool if vesktop could have the `(.)` indicator for when there are unread messages (not pings) like the official client does

using vesktop 0.2.8 on intel macos 13.4.1

**Comment by Vap0r1ze** [comment]
i thought this existed already, it works for me if i have it on in the Notification settings and the Desktop Settings

**Comment by Vap0r1ze** [comment]
https://github.com/Vencord/Vesktop/assets/20448879/c498c70f-f155-42de-9736-2b662a0e51e4

**Comment by rhysdh540** [comment]
I have both settings on: 
<img width="720" alt="image" src="https://github.com/Vencord/Vesktop/assets/98863820/b783357d-a5b7-4819-8081-966be2ff5d64">
<img width="700" alt="image" src="https://github.com/Vencord/Vesktop/assets/98863820/a1d7fb60-12d5-46d3-a5c6-c1d72b1f2520">


yet it still doesn't show up:
<img width="82" alt="image" src="https://github.com/Vencord/Vesktop/assets/98863820/e6c550c0-bca0-4d27-b612-9f61885a0ee3">

**Comment by Vap0r1ze** [comment]
oh mac

**Comment by unknown134563** [comment]
> oh mac

you can add a upload plugins from a computer files for all version of vencord plssss

**Comment by Vendicated** [comment]
fixed in #88

**Comment by mrbigmouth502** [comment]
EndeavourOS KDE. I'm not getting a notification dot in the systray on my system. Using the Flatpak if that makes a difference.
