### ISSUE TITLE
[Feature Request] Enable the electron sandbox, or allow launching without cap sys_admin

### ISSUE THREAD

**Issue by odomingao** [Vencord/Vesktop#870]
### Motivation

vesktop doesn't use the electron sandbox (it's always launched with --no-sandbox), and yet denying the sys_admin capability results in a crash because it will "not run without sandboxing".

`[2:0923/135754.211316:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/lib/electron31/chrome-sandbox is owned by root and has mode 4755.`

### Solution

Enable the electron sandbox

### Alternatives

Allow vesktop to launch without these privileges, if possible

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by odomingao** [comment]
@Vendicated launching via flatpak, and looking through the running processes, it shows that vesktop is launched with --no-sandbox:

```
ps axZ | grep vesktop | grep no-sandbox
-                                871129 pts/0    S<l+   0:06 /app/bin/vesktop/vesktop.bin --type=renderer --enable-crash-reporter=1e0c24f5-c6f8-40cc-b07c-faab24c2b9b4,no_channel --user-data-dir=/home/user/.var/app/dev.vencord.Vesktop/config/vesktop --app-path=/app/bin/vesktop/resources/app.asar --no-sandbox --no-zygote --autoplay-policy=no-user-gesture-required --disable-background-timer-throttling --ozone-platform=wayland --lang=en-US --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=6 --time-ticks-at-unix-epoch=-1727099422334190 --launch-time-ticks=14670498479 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=3,i,13521630818923871438,8366015073558315631,262144 --enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,VaapiVideoEncoder --disable-features=HardwareMediaKeyHandling,MediaSessionService,SpareRendererForSitePerProcess,WinRetrieveSuggestionsOnlyOnDemand --variations-seed-version
```

**Comment by TheBjoel2** [comment]
Vanilla discord client is also not sandboxed btw

**Comment by Vendicated** [comment]
it's likely impossible for discord to enable sandboxing for their renderer.

**Comment by TheBjoel2** [comment]
@Vendicated on what platform the rendered is 100% confirmed to be sandboxed (i.e. running without ``--no-sandbox`` flag)?
Appimage? Debian? Fedora? aur?
