### ISSUE TITLE
[Bug] Vesktop logs me out randomly and frequently

### ISSUE THREAD

**Issue by khatharsis42** [Vencord/Vesktop#872]
### Discord Account

khatharsis

### Operating System

Manjaro Linux 6.1

### Linux Only ~ Desktop Environment

KDE on Wayland

### Package Type

AUR, AppImage

### What happens when the bug or crash occurs?

Sometimes, I'll close Vesktop, and when I open it again, I have to log in again. This happens even if I did not reboot my computer, or log out, or made an update. It's random.

### What is the expected behaviour?

I except Vesktop to work like the Discord client and not log me out randomly.

### How do you recreate this bug or crash?

Reboot your PC
Launch Vesktop
Sometimes it happens

### Debug Logs

```
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/issues/742
https://github.com/Vencord/Vesktop/issues/787
https://github.com/Vencord/Vesktop/issues/810

**Comment by saipheblue** [comment]
I had the same issue, **I think I solved this be logging out on browser.** Because Vesktop is behaving is another browser tab and if you are logged in two places at once it will log you out.  At least that's my assumption

I know this is closed but it might help someone in the future.

**Comment by Sqaaakoi** [comment]
> I had the same issue, **I think I solved this be logging out on browser.** Because Vesktop is behaving is another browser tab and if you are logged in two places at once it will log you out. At least that's my assumption
> 
> I know this is closed but it might help someone in the future.

This is wrong. Discord is incorrectly detecting the DevTools sidebar is open (specifically, the code to do it on web based clients is a bit broken, from what I can tell it has something to do with window inner/outer height/width) and it moves the token into memory to prevent users being scammed/hacked

Solution: Enable the NoDevtoolsWarning Vencord plugin, like is suggested in many other places.
(This should really be marked as required in Vencord when running the Vesktop build)

source: I looked at the code a few days ago

**Comment by saipheblue** [comment]
I have enabled said plugin but even after 3 restarts it did not help. After logging out on a browser it started to work, so either it got applied with some delay or  it was solved by logging out on browser.
