### ISSUE TITLE
[Bug] strange call behaviour when using VPN 

### ISSUE THREAD

**Issue by lenrik1589** [Vencord/Vesktop#876]
### Operating System

Frankenstein (kinda Arch Linux, but not really)

### Linux Only ~ Desktop Environment

Wayland

### Package Type

official AppImage, AUR (vesktop and vesktop-bin), running/built from source

### What happens when the bug or crash occurs?

When running vesktop with a VPN (in this case WireGuard through Tailscale) joining any call will hang on "DTLS Connecting" each and every time

### What is the expected behaviour?

Joining any call on official discord canary or;
Joining any call w/o VPN;
yields expected result of "call connects completely"

### How do you recreate this bug or crash?

(explained in prior parts, but just in-case)
1. use a VPN (probably related to WireGuard, but don't know how to check w/ any other)

### Debug Logs

potentially related to #756 and #768
"debug" logs include no relevant info, if any electron console logs would help, wei can provide those
checked that it is not DNS setup by restricting `*.discordapp.com` `*.discord.media` and `*.discord.gg` to `9.9.9.9` and then tried `1.1.1.1`

A friend suggested that the issue might be related to DAVE, but (at least officially?) it was released not more than a month ago (announcement 10 days ago), and this issue was present before that
looking @ Electron debug tools console, wei were not able to ascertain there are meaningful differences between pure Vesktop vs Vesktop + VPN output, besides that `peerConnectionState` never transitions into `connected`, but wei don't know what subsystem that is logged by

also, [a potentially relevant tailscale bug report](https://github.com/tailscale/tailscale/issues/10396)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
if it works without vpn, then this is not a vesktop issue and there's nothing we can do, sorry

either a you issue or a discord issue

**Comment by lenrik1589** [comment]
only one question, Are you serious?

> if it works without vpn

discord canary (also electron 32) works with VPN, so it's clearly not just a "discord issue"

are you not able to at least provide a pointer as to where or what could be going wrong?

**Comment by lewisakura** [comment]
We don't know. It's your VPN software or some system configuration issue (especially when you list your operating system as "Frankenstein", I'm going to bet this), but we can't tell you. If it works without the VPN, then it's not Vesktop.
