### ISSUE TITLE
[Feature Request] Revert to Proper Desktop Icon

### ISSUE THREAD

**Issue by LumiWasTaken** [Vencord/Vesktop#877]
### Motivation

The weird rainbow logo does not align with the general Aesthetics of someone's desktop.
Again, it pushes some kind of odd agenda on people who just want to enjoy the Vencord application

### Solution

Offer a alternative / solution to switch between the odd and original Logo.

### Alternatives

Revert to the Original Logo.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by adilaxmdv** [comment]
Is it possible to change it?
