### ISSUE TITLE
[Bug] Vesktop's main window will not open

### ISSUE THREAD

**Issue by Thepuppetqueen57** [Vencord/Vesktop#879]
### Discord Account

thepuppet57

### Operating System

Manjaro linux

### Linux Only ~ Desktop Environment

Gnome on wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

When I open vesktop I see the loading window normally but then it closes and nothing else appears. Vesktop is still in the dock or whatever its called on gnome but clicking it does nothing.

### What is the expected behaviour?

I expect the loading window to close and the main one to open

### How do you recreate this bug or crash?

For me my pc froze one time and I had to force restart it and then when I opened vesktop again the main window was all glitchy but then when I tried restarting it I got this bug

### Debug Logs

```
there isnt a vesktop command and I assume the command is just vesktop
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
you haven't provided any relevant debug log and this is 99.9% a system issue. please use our support channel if you need help.
