### ISSUE TITLE
[Feature Request] Bring Back arm64 binaries for mac

### ISSUE THREAD

**Issue by Git-North** [Vencord/Vesktop#883]
### Discord Account

northwastaken

### Motivation

With the recent update vesktop has removed the ability to install an arm64 binary. forcing users to use the intel binaries. This brings problems like having to install Rosetta-2, increased battery consumption, Increased Ram consumption.

### Solution

Simply bring back the arm binaries. if there isn't a motivation behind this change like a "simplified development process" which I can get behind. I'd love to see the arm binaries back for increased performance.

### Alternatives

Using an older release version of Vesktop or changing to another alternative like Armcord. however these aren't great solutions.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Git-North** [comment]
https://github.com/Vencord/Vesktop/issues/406

**Comment by Vendicated** [comment]
universal binaries are, like the name implies, universal. they contain BOTH Intel and Arm builds. this issue makes no sense

**Comment by Git-North** [comment]
Excuse my stupidness and lack of research please.
