### ISSUE TITLE
[Bug] <Full screen main window when the full screen pop out VC and stream launch window also open in the main window instead of the pop out VC.>

### ISSUE THREAD

**Issue by KIRUYXAN** [Vencord/Vesktop#884]
### Discord Account

KIRUYXAN

### Operating System

Windows 10

### Package Type

Setup exe

### What happens when the bug or crash occurs?

When I try to fullscreen a pop out VC window, the main vekstop window will be fullscreened.
And stream launch window also opend in main window instead of the pop out VC, when click "share your screen" in pop out VC.

### What is the expected behaviour?

A separate VC window will be fullscreened instead of the main one.
Stream launch window opened in pop out VC window.

### How do you recreate this bug or crash?

1. Open vekstop 
2. Log in VC 
3. Click pop out
4. 4.1. Click in a separate window to open full screen
4.2. Click "Share your screen"
5. 5.1. The main window will open full screen
5.2. Steam launch wiindow open in main window

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
closing in favour of https://github.com/Vencord/Vesktop/issues/964

**Comment by KIRUYXAN** [comment]
I don’t understand why you closed my issue and not his, mine was added earlier and more detailed

**Comment by KIRUYXAN** [comment]
@Vendicated

**Comment by Vendicated** [comment]
because the other issue is much cleaner due to being better worded and not being riddled with grammar & spelling mistakes.
