### ISSUE TITLE
[Feature Request] Option to start Vesktop minimised to tray

### ISSUE THREAD

**Issue by Ascend910** [Vencord/Vesktop#885]
### Motivation

It is annoying to set Vesktop to start with my PC and everytime I log in the full Vesktop window cover my screen and I have to manually click on the red X to minimise it to tray

### Solution

A option to start Vesktop minimised to tray so notification and calls can still be heard but the window will not show unless I open Vesktop

### Alternatives

A autohotkey script (and xdotool on Linux) to automaticly close Vesktop when it starts, making it minimise to tray

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/issues?q=is%3Aissue+start+minimized+tray
