### ISSUE TITLE
[Feature Request] Vesktop custom titlebar

### ISSUE THREAD

**Issue by chrrybmb64** [Vencord/Vesktop#886]
### Motivation

I want the custom titlebar to say Vesktop because I am using Vesktop, not the official Discord client, and the titlebar should reflect that. Also it would look nice I think.

### Solution

Replace the word Discord on the left end of the custom titlebar with the word Vesktop.

Some people may prefer to have it say Discord so I guess give us the option to choose between them.

### Alternatives

n/a

### Additional context

Here is a mockup I made

![titlebarconcept](https://github.com/user-attachments/assets/ff6e702e-4146-4698-92a7-9ac4f704893b)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
css

**Comment by chrrybmb64** [comment]
I didn't know the titlebar could be modified with css. My bad.

But a large amount of feature requests on Vencord repositories are things that can be done with css, and if there was a place where people could easily find css snippets and themes, like, I don't know, a [Theme Browser](https://github.com/Vencord/plugin-requests/issues/344), all these feature requests (which probably annoy you) would stop being made.
