### ISSUE TITLE
[Bug] transparent borders on window

### ISSUE THREAD

**Issue by SoiledBrush** [Vencord/Vesktop#893]
### Operating System

Linux

### Linux Only ~ Desktop Environment

Gnome on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Problems properly resizing vesktop window to corners when it's not on fullscreen or de's auto align mode. 
Some kind of transparent padding appears when aligning.
![vesktop](https://github.com/user-attachments/assets/983a3510-317a-4db0-8a6d-a8e5bfdf5e64)
[Screencast From 2024-10-06 22-31-16.webm](https://github.com/user-attachments/assets/42c1deba-4707-40c0-b865-7dc271179d74)

### What is the expected behaviour?

Proper windows alignment

### How do you recreate this bug or crash?

 Try to touch the gnome top bar with regular non-fullscreen window.

### Debug Logs

```
Not much to show after flatpak run dev.vencord.Vesktop
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
not a vesktop issue, nothing we can do. either electron/chromium or your system

**Comment by Vendicated** [comment]
because the layouting is done entirely by chromium. we have no control over it. it's impossible for this issue to be caused by vesktop. there is nothing we can do.
