### ISSUE TITLE
[Bug] Vesktop crashes after a few seconds after switching to IBus

### ISSUE THREAD

**Issue by qreativa** [Vencord/Vesktop#894]
### Discord Account

qreativa

### Operating System

Fedora Linux 40, KDE spin

### Linux Only ~ Desktop Environment

KDE on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

The app opens normally, but after clicking on any DM or server it crashes and returns SIGILL.

### What is the expected behaviour?

I expect the app to not crash and to continue working.

### How do you recreate this bug or crash?

1. Switch input method handler to IBus.
2. Launch Vesktop.
3. Log in if needed.
4. Click on any server or DM.
5. The app crashes after a few seconds.

### Debug Logs

```
qrea@box-of-xenia ~> flatpak run dev.vencord.Vesktop
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto --enable-wayland-ime
[3:1006/210114.659582:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:1006/210114.803534:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1006/210114.803558:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
/app/bin/startvesktop: line 27:     3 Illegal instruction     (core dumped) zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
qrea@box-of-xenia ~ [SIGILL]> 
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
not a vesktop issue

**Comment by qreativa** [comment]
Vesktop is the only app that crashes since changing to IBus. Every other app seems to work perfectly fine.

**Comment by tommydrum** [comment]
> not a vesktop issue

Technically this is true, but also doesn't mean it's out of the control of Vesktop to mitigate. https://github.com/flathub/dev.vencord.Vesktop/pull/34 is ultimately what introduced the crash (to all users of Wayland KDE + IBus), which leaves two options of fixing: revert and not use wayland's IME protocol, or pointing to the specific (or general area) upstream that needs to be contacted. Generally, dismissing is pretty bad practice.

(I am also affected.. as it affects everyone on Bazzite, due to the nature of them including and using KDE and IBus)

**Comment by tommydrum** [comment]
> not a vesktop issue

Technically true, but there is a fix available that would require Vesktop to update chromium/electron. Specifically, upstream fixed the issue between these two commits: https://chromium.googlesource.com/chromium/src/+/94af9d13a14b2dbfecb1f5de52969ef023c218a6 and https://chromium-review.googlesource.com/c/chromium/src/+/5598518

Basically, need to update to an electron build that is up to do date with these patches. Current stable electron releases are up to Chromium 130, with this patchset made it into 128 (see https://chromiumdash.appspot.com/commits?commit=715fcc5676f373ac953c468f60434a5f4b0c0fe6&platform=Linux )

**Comment by BugZappa** [comment]
+1 on this issue
