### ISSUE TITLE
[Feature Request] Add compatibility for discover overlay

### ISSUE THREAD

**Issue by SMGttv** [Vencord/Vesktop#899]
### Motivation

I use discover overlay for when i am in voice calls or in voice channels to display the people talking. I noticed that discover overlay does not work with vesktop like it does with the normal discord client. I checked the discover overlay github and people have submitted this request, however, the dev reports that vesktop needs to do something for it to work. I am not familiar with how it works I just know it doesn't work.

### Solution

Make vesktop compatible with discover overlay so that the chat overlay comes up while using it. 

### Alternatives

I switch back and forth between vesktop and discord depending on what I am doing.
Vesktop: Needing to share screen with audio
Discord: Everything else

### Additional context

![1728429398_grim](https://github.com/user-attachments/assets/79aa5782-be2d-4ed9-8c50-890e177ae2b5)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
no

**Comment by Vendicated** [comment]
duplicate of #105 #444
