### ISSUE TITLE
[Feature Request] So, discord now Banned in Russia and Turkey

### ISSUE THREAD

**Issue by K1LL3RPUNCH** [Vencord/Vesktop#900]
### Motivation

But instead of Discord Vesktop is working like a charm, except voice chats, it connecting for eternity.

### Solution

Redirect voice chats maybe or make some patch?

### Alternatives

Idk lol

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by keetsta** [comment]
+

**Comment by Vendicated** [comment]
out of scope, but try looking into it yourself, for example check https://x.com/endermanch/status/1843753877092323622

**Comment by Nepriyatnosti** [comment]
> [x] Это не запрос на функцию Vencord

ERR_CONNECTION_RESET
