### ISSUE TITLE
[Bug] Stuttering when typing on a lower refresh rate monitor.

### ISSUE THREAD

**Issue by 8D1** [Vencord/Vesktop#901]
### Discord Account

jacksons

### Operating System

Linux Gentoo 2.15

### Linux Only ~ Desktop Environment

Plasma on wayland

### Package Type

Flatpak & Unofficial Portage

### What happens when the bug or crash occurs?

The bug occurs when the window is open on a lower refresh rate monitor. It characters take a second to show up. I Hypothesize its because its trying to render the characters at the faster monitors refresh rate.

### What is the expected behaviour?

No stuttering

### How do you recreate this bug or crash?

Open vesktop on a lower refresh rate monitor
try and message someone / a server
observe

### Debug Logs

```
no errors or other notable logs.
```

### Request Agreement

- [x] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by 8D1** [comment]
Quick addendum: this happens when typing, Thought i mentioned that, No observable issue with message receiving

**Comment by Vendicated** [comment]
try to disable all your themes & css. if that doesn't fix it, then it's a chromium issue, nothing we can do

**Comment by 8D1** [comment]
Already were disabled, thats unfortunate, Thanks for your time.
