### ISSUE TITLE
[Bug] Segfault on startup

### ISSUE THREAD

**Issue by somichev-dev** [Vencord/Vesktop#904]
### Discord Account

somichev.dev

### Operating System

Manjaro Linux

### Linux Only ~ Desktop Environment

KDE on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Segmentation fault on startup after ~1 minute of nothing.

### What is the expected behaviour?

Vesktop starting properly

### How do you recreate this bug or crash?

1. Run vesktop
2. Wait for ~60-90 seconds
3. Segfault
![image](https://github.com/user-attachments/assets/6b2ea92b-5cf9-443f-ac25-3fe0d9b85b9a)

### Debug Logs

```
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto --enable-wayland-ime
[3:1010/214655.713337:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
/app/bin/startvesktop: line 27:     3 Segmentation fault      (core dumped) zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
something wrong with your system, nothing we can help with, sorry
