### ISSUE TITLE
[Bug] Replica of #147 "White Screen on Launch"

### ISSUE THREAD

**Issue by Dunkindude** [Vencord/Vesktop#907]
### Discord Account

Dunkin__

### Operating System

Windows 10

### Package Type

Setup Executable, still prevalent on portable.

### What happens when the bug or crash occurs?

Upon installing Vesktop, a white screen appears, and no information is given nor action allowed, except to close said window. This issue is an exact replica of issue #147. The proper solution there - to delete "vencordDesktopRenderer.css" - no longer functions because this file no longer exists in modern Vesktop builds.
This bug is occurring on a Thinkpad P50 with Nvidia Quadro M2000M graphics and Intel UHD 530 integrated graphics. However, Vesktop continues to function just fine on my desktop Arch install with an RTX 2060 and CPU w/o integrated graphics.

### What is the expected behaviour?

Vencord is expected to show it's first-time launch setup screen, displaying options like "copy config from preexisting installation" and "start Vesktop with system."

### How do you recreate this bug or crash?

1. Have a Japanese copy of Windows 10
2. Ensure you are connected to the internet.
3. Launch Vesktop off of it's executable or portable versions for Windows 10 after installing them for the first time.
4. horror

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
we can't help you without necessary information, specifically error logs. please use our support channel for easier debugging
