### ISSUE TITLE
Stuck on loading screen with the Wayland ozone platform

### ISSUE THREAD

**Issue by Insprill** [Vencord/Vesktop#91]
The loading screen never disappears when attempting to start Vesktop with the `--ozone-platform=wayland` flag. Everything else seems to initialize correctly, I can hear it join a VC if I was previously there, but the loading screen remains, and the rest of the applications fails to load. The flag works fine in normal Discord.

I'm running the Nvidia version of Hyprland  (`ab73183`) on Garuda Linux with the `6.4.9-zen` kernel, and `vencord-desktop-git` installed from the AUR.

**Comment by Vendicated** [comment]
that flag is for very old electron, you should use `--ozone-platform-hint=auto`

**Comment by Insprill** [comment]
The same behavior occurs when using that flag.

**Comment by Vendicated** [comment]
this is an issue with your system then, as it works fine for others. observe the terminal output for errors

**Comment by 1e1001** [comment]
also happens for me (although i am using a somewhat cursed build), however clicking on the tray icon makes the main window actually appear

**Comment by 1e1001** [comment]
idk much about electron stuff but it seems to be the same issue as in https://github.com/signalapp/Signal-Desktop/issues/6368, and i found https://github.com/electron/electron/issues/25253#issuecomment-691624779, which (while being an unrelated root issue) has a fix that seems to work on my machine

**Comment by Insprill** [comment]
I tried the fix mentioned in the comment on that electron issue, and it does appear to fix the problem, but it also occasionally results in a segfault when loading in. Can anyone else test it to see if the crash is reproducible?

**Comment by ItsRedlyXD** [comment]
I have the same error. When running vencord on terminal, I get ths.

[9489:0818/193802.709839:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: Não existe o ambiente “org.freedesktop.portal.FileChooser”
[9489:0818/193802.709894:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
(node:9489) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/vun0s/.config/VencordDesktop/VencordDesktop/vencordDist/vencordDesktopMain.js from /opt/vencord/resources/app.asar/dist/js/main.js not supported.
vencordDesktopMain.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename vencordDesktopMain.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/vun0s/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at VCDMain:27:4113
    at VCDMain:1:1024
    at le (VCDMain:27:3755)
(Use `vencord --trace-warnings ...` to show where the warning was created)
(node:9489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by Vendicated** [comment]
@ItsRedlyXD your error is pretty clear, delete `/home/vun0s/package.json`.

**Comment by ItsRedlyXD** [comment]
Aighty tysm

**Comment by Vendicated** [comment]
is this still happening on the latest version?

**Comment by Vendicated** [comment]
Closing as fixed. Please reopen if this is still an issue on 0.4.0

**Comment by Noobz4Life** [comment]
Same issue here on Arch 6.5.9-1 (only tested using vencord-desktop-bin as -git doesn't compile for whatever reason)

Adding '--disable-gpu' to the arguments fixes it, but obviously this isn't an ideal solution.

Might be an electron issue, as the same thing happens with VSCode for me.

**Comment by Vendicated** [comment]
if --disable-gpu fixes it, then that's an issue with your gpu driver

**Comment by Potajito** [comment]
Same issue here with Arch 6.5.9-1 (vencord-desktop-bin) on nvidia-dkms 535.113 (only tested using vencord-desktop-bin).
Clicking the tray a couple of times seems to bring the window just fine, but haven't tested it extensively.

**Comment by Vendicated** [comment]
should be fixed on latest main. please confirm
