### ISSUE TITLE
[Feature Request] Login with Yubikey

### ISSUE THREAD

**Issue by Kitki30** [Vencord/Vesktop#910]
### Discord Account

kitki30

### Motivation

My linux PC broke and i now can't use discord. I need to use raspberry pi 5 as my pc now and wanted to download discord. I downloaded armcord with vencord from pi-apps didnt accept my yubikey. Tried vesktop also didnt work. Now i cant login to discord.

### Solution

Fix login with passkey / security key

### Alternatives

Somehow login from browser.

### Additional context

![Screenshot_20241017_132339](https://github.com/user-attachments/assets/61603852-46e5-4d83-81fd-1fe699da8185)
![Screenshot_20241017_132543](https://github.com/user-attachments/assets/7b887735-4d04-4415-a2f7-07bb79eed2f5)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Kitki30** [comment]
> How does linux Discord Desktop handle the key?

On my PC with debian when i was creating the key i think it was implemented in app i dont think theres any system implementation of it like windows prompt, firefox also has its own prompt for security key. I now use discord in firefox and it works. I can login to vesktop with backup keys.

**Comment by Kitki30** [comment]
Now i logged in with backup key, it has no problem with creating new key, it just has problem with logging in.
When i pressed create security key, my yubikey led blinks. I don't know how about logging in on PC cause i only registered it on it. But now i can't check it cause cooler broke and i doesn't cool my CPU much

**Comment by Kitki30** [comment]
It also worked when i authenticated to add discord bot with it, looks like only the login is broken or atleast FIDO2 things

**Comment by beedell-roke** [comment]
@Covkie, CTAP1 supports exists, per [`electron/electron/issues/3226#event-5227928838`](https://github.com/electron/electron/issues/3226#event-5227928838).
