### ISSUE TITLE
[Bug] Autostart doesnt work

### ISSUE THREAD

**Issue by SussyGuy35** [Vencord/Vesktop#912]
### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

KDE 6.2.1 on Wayland

### Package Type

rpm

### What happens when the bug or crash occurs?

Autostart does not work
Log:
![image](https://github.com/user-attachments/assets/b658c11f-dd5f-431b-b820-e80ea659b7db)

### What is the expected behaviour?

Vesktop should be started with the system

### How do you recreate this bug or crash?

1. Enable Start with system
2. Start the system

### Debug Logs

```
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: rpm
Checking for update
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[4709:1019/201825.750918:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Update for version 1.5.3 is not available (latest version: 1.5.3, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[4709:1019/201827.026619:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[4709:1019/201836.071262:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
![image](https://github.com/user-attachments/assets/65edc38c-383e-4206-9dc1-72eb5458b39d)
