### ISSUE TITLE
[Bug] Screen blacked out and remains blacked out when using the search function in user settings.

### ISSUE THREAD

**Issue by Brandlil** [Vencord/Vesktop#914]
### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

GNOME Wayland 

### Package Type

Flatpak

### What happens when the bug or crash occurs?

The program has a blank screen when searching the user settings.

### What is the expected behaviour?

I expected to be able to search through my user settings.

### How do you recreate this bug or crash?

I simply opened user settings, clicked Vesktop settings, then clicked the search bar at the top almost immediately, and then the program simply remains blank with no UI at all. Restarting the program did not fix the issue. I haven't attempted restarting the computer.

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
vencord settings do not support search.

**Comment by Brandlil** [comment]
Okay, that's fair enough. However, I hope you are aware that by attempting this it caused the program to be unusable. Had to reboot to fix.
