### ISSUE TITLE
Double clicking on edge of custom titlebar does not restore window 

### ISSUE THREAD

**Issue by Poopooracoocoo** [Vencord/Vesktop#92]
STR:
1. Go to Desktop settings and enable Discord titlebar
2. Restart Vesktop
3. Maximize window
4. Double click on edge of title bar

Expected behaviour: 
Double clicking on the edge of the custom titlebar of a maximized window will restore the window

Actual behaviour: 
Double clicking on edge of custom titlebar of a maximized window does not restore window 

Version:
0.3.0

Operating system: 
Windows 10 22H2

Notes:
It's also not possible to do other actions with the titlebar from the edge such as dragging it or right clicking it. 
This behaviour is consistent with the official Discord app but not with other apps and native titlebars on Windows.

**Comment by Vendicated** [comment]
works fine for me 

https://github.com/Vencord/Vesktop/assets/45497981/b85b93af-3ec0-4743-8e5b-c28b2ee1093e

**Comment by Vendicated** [comment]
if this is actually an issue, it's likely fixed via https://github.com/Vencord/Vesktop/commit/e6e66e775c1e483449cbb03c0ed885536f0b18bc (soon to be released)

**Comment by totallyphysicallypossible** [comment]
not sure if this is related but setting transparency to anything other than none breaks maximizing

https://github.com/Vencord/Vesktop/assets/94307704/64d3cf43-6ec0-426f-9684-191e2695ab59

**Comment by Vendicated** [comment]
normal.
