### ISSUE TITLE
Windows - Vesktop incorrectly detecting existing installation

### ISSUE THREAD

**Issue by MagikGimp** [Vencord/Vesktop#922]
### Operating System

Windows 10

### Package Type

Setup

### What happens when the bug or crash occurs?

The following screenshot should be sufficient:
![Vesktop incorrectly detecting existing installation](https://github.com/user-attachments/assets/30856da8-8640-40a1-8350-2303f17684a7)

### What is the expected behaviour?

n/a

### How do you recreate this bug or crash?

n/a

### Debug Logs

```
n/a
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
this is the Nsis installer and not under our control. try manually deleting that folder or google the error
