### ISSUE TITLE
how do i call vesktop through the browser?

### ISSUE THREAD

**Issue by mcspidey95** [Vencord/Vesktop#923]
### Content

Hey, im working on a customizable new tab page for all browsers. One of its features is calling the app version of discord (if installed) instead of the web version. On windows, all i need to do is redirect to the discord protocol "discord://"

Im porting it to linux as well, and making it open vesktop instead of discord. So is there any other way to call vesktop through a protocol? Because discord:// doesnt open vesktop.

Thanks

**Comment by Vendicated** [comment]
it will support discord:// soon #813
