### ISSUE TITLE
[Bug] Text Right-Click Menu Missing

### ISSUE THREAD

**Issue by Abystus** [Vencord/Vesktop#926]
### Operating System

Linux (openSUSE)

### Linux Only ~ Desktop Environment

KDE on X11 or Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

When you misspell something, you see the usual red squiggly line, but you can't right-click it to access the text interaction and correction menu as you would in the standard client. In-fact, you can't even right-click the text entry at any point to access the menu.

Vesktop:

![image](https://github.com/user-attachments/assets/961ab58d-ff45-4c1b-bfc0-e50bc53b2280)

Normal Discord:

![image](https://github.com/user-attachments/assets/c739a102-f6b7-445a-aa87-dc34b076b7e6)

### What is the expected behaviour?

To show the text interaction menu when right-clicking text or the text entry area.

### How do you recreate this bug or crash?

1. Type anything that is misspelled to see the red squiggly line.
2. Try right-clicking the misspelled text to get suggested fixes.

Or, simply right-click the text entry field at any point and notice that no menu appears.

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
This feature works just fine. Your Vesktop / Vencord are outdated ~ update them. Use our support channel if you need more help

**Comment by acook** [comment]
For anyone else who has this same issue in 2026 with the most recent version (1.6.5):

1. Right click on the Vesktop system tray icon
2. Click `Repair Vencord` 

This resolved the problem for me.
