### ISSUE TITLE
[Bug] Animated emojis play regarless of the setting in Accessibilty

### ISSUE THREAD

**Issue by komaru21** [Vencord/Vesktop#927]
### Operating System

Ubuntu 24.04

### Linux Only ~ Desktop Environment

KDE

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Regardless of the setting in Accessibility, animated emojis are animating. I have disabled all Vencord plugins and the issue persists. I have logged into Discord via Firefox, and the emojis do not animate there. Vesktop is the only client not respecting this setting for some reason 

### What is the expected behaviour?

The Accessibility setting to be respected and animated emojis to be static

### How do you recreate this bug or crash?

Open Vesktop
Go to any channel that has a message containing an animated emoji
See it animated despite the setting to disabled them being set

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
happens for me on stock discord. discord issue
