### ISSUE TITLE
[Bug] <General sound when streaming window>

### ISSUE THREAD

**Issue by KIRUYXAN** [Vencord/Vesktop#928]
### Discord Account

KIRUYXAN

### Operating System

Windows 10

### Package Type

Setup exe

### What happens when the bug or crash occurs?

When I stream a separate window with sound, the stream shows the general sound of the computer

### What is the expected behaviour?

The sound will only come from the window

### How do you recreate this bug or crash?

1. log in VC
2. Start streaming a window with sound
3. The stream will have general computer sound

### Debug Logs

When I start a stream, there are these highlighted lines in the console
``` yellow
react_devtools_backend.js:4026 [UnifiedConnection(stream)] Attempting to create user 672765222553124874 with 0 audio SSRC
overrideMethod @ react_devtools_backend.js:4026
(anonymous) @ web.161851c3db4676e3dc01.js:12
(anonymous) @ web.161851c3db4676e3dc01.js:12
createUser @ web.161851c3db4676e3dc01.js:12
(anonymous) @ web.161851c3db4676e3dc01.js:12
_handleClientConnect @ web.161851c3db4676e3dc01.js:12
a.emit @ web.161851c3db4676e3dc01.js:1
emit @ web.161851c3db4676e3dc01.js:12
e.onmessage @ web.161851c3db4676e3dc01.js:12
```
``` red
1087462415802843256:1 Uncaught (in promise) OverconstrainedError: Cannot satisfy constraints
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by KIRUYXAN** [comment]
@Vendicated not planned because it’s duplicate or is it generally not planned?

**Comment by KIRUYXAN** [comment]
It seems to me that yes, but then can you link to the main issue on this topic

**Comment by Vendicated** [comment]
because it's a duplicate. if you spent even a minute checking existing issues you would easily find it
