### ISSUE TITLE
Mic doesn't output audio on Vesktop, but does on Discord

### ISSUE THREAD

**Issue by venturiq** [Vencord/Vesktop#931]
### Content

These are my discord inputs/outputs
![image](https://github.com/user-attachments/assets/d3072a15-7210-4ab4-9c1f-8723852b186f)

These are my vesktop inputs/outputs
![image](https://github.com/user-attachments/assets/8e7b85b4-cc5d-44dc-9194-f87d5f636b15)

I can't figure it out :c

**Comment by Vendicated** [comment]
use our support channel for help
