### ISSUE TITLE
[Bug] FYI: Chrome bug causing vesktop to spam logs (yep another one)

### ISSUE THREAD

**Issue by pallaswept** [Vencord/Vesktop#933]
### Operating System

openSUSE Tumbleweed

### Linux Only ~ Desktop Environment

KDE Wayland

### Package Type

AppImage

### What happens when the bug or crash occurs?

https://issues.chromium.org/issues/331796411

Sorry for the low quality bug report, I'm in a rush, and I assume you already know how best to handle stuff like this, once you know of it, so I'm just letting you know. Feel free to just close this without comment.

This upstream bug is effecting vesktop, the result are logs so huge they can't practically be opened (so we can't view them without the spam by means of grep etc), there is a workaround (`--disable-gpu-memory-buffer-video-frames`) and a fix in a patch.

It would be nice if we could get a fresh appimage with this patch as the workaround also has issues.

Thanks! I hope this is helpful.

### What is the expected behaviour?

Can open logs

### How do you recreate this bug or crash?

Screensharing

### Debug Logs

N/A

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by lewisakura** [comment]
this is reliant on an electron version that does not yet exist, it'll be fixed when that comes out
