### ISSUE TITLE
[Bug] <Mic not working in VC>

### ISSUE THREAD

**Issue by blunelsongamer** [Vencord/Vesktop#939]
### Discord Account

blunelson2

### Operating System

Arch

### Linux Only ~ Desktop Environment

KDE on Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

When I did the mic test, it was working okay. But when I join the VC, I haven't seen a greenlight pop up, implying that the microphone isn't working.

### What is the expected behaviour?

Either I am using Fifine Microphone Mono which may not have supported there or I am using Pipewire.

### How do you recreate this bug or crash?

1. Open Vesktop with default settings.
2. Login Discord and Mic Test.
3. Switch a input device to Fifine Microphone Mono, leaving Output device by default.
4. Create a new server for testing servers, join the VC and greenlight didn't show up.

### Debug Logs

No crash necessary.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
can't reproduce and wouldn't be a vesktop issue. something with your system / mic, no idea what, sorry! you'll have to figure it out yourself

**Comment by JTrenerry** [comment]
I have the exact same issue, I use the nixpkgs version though. I tried the exact same setup on offical discord client and it works fine.
