### ISSUE TITLE
[Bug] Joining a call forces HSP/HFP Bluetooth profile

### ISSUE THREAD

**Issue by OmriPH** [Vencord/Vesktop#943]
### Discord Account

omrih

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Gnome on Wayland

### Package Type

AUR, Same thing happens on Flatpak too.

### What happens when the bug or crash occurs?

I have two input devices on discord: My USB Blue Yeti Mic, And my bluetooth headphones' mic.

When entering a discord call, the bluetooth headphones switch from the A2DP profile (which is one way) to HSP/HFP (which is 2 way, used for mics). sound quality drops a LOT when HSP/HFP is the enabled profile.

When it's on this HSP/HFP mode, i have to use my headphones' microphone instead of the USB microphone or i cant hear people talking on discord.

If I manually switch to A2DP, the audio quality is fine again, but I can't hear anyone on discord, and no one can hear me no matter what mic I use.

I'm certain the bug is within discord, and I think the cause is it enabling all microphones including those not currently in use, which means my headphones' mic will be enabled, which enables HSP/HFP

The only situation where I can hear my friends on discord and they can hear me, is if i use the HSP mode (which has horrible sound quality) and use the headphones' mic (which has worse sound quality then my blue yeti)

### What is the expected behaviour?

If I have selected the Blue Yeti Microphone, or any mic that isn't the bluetooth headphones' mic, It should stay on the A2DP mode.

### How do you recreate this bug or crash?

1. Enter a call with bluetooth headphones connected and set as the output device.
2. Select an input device that isn't the headphones' mic.
3. The headphones will stay in HSP even though they should be in A2DP, and the Microphone you selected won't work.

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
I have no idea what this means but you could just blacklist your bluetooth headphone's mic on a system level and it will likely fix it

**Comment by thesaikis** [comment]
HSP/HFP is always a pain for me, if you have no need for it the following might be useful:
https://wiki.archlinux.org/title/Bluetooth_headset#Switch_between_HSP/HFP_and_A2DP_setting
