### ISSUE TITLE
[Bug] Unable to connect to Voice Channels

### ISSUE THREAD

**Issue by i-am-zaidali** [Vencord/Vesktop#944]
### Discord Account

crayyy_zee

### Operating System

Ubuntu 23.04

### Linux Only ~ Desktop Environment

Gnome on wayland

### Package Type

DEB

### What happens when the bug or crash occurs?

Well I dont know if it's entirely related to Vesktop but every since I update vesktop last week, I have been unable to join any VC because it gets stuck at DTLS connecting. I have tried multiple solutions such as rejoining the channel, restarting my client, restarting my system and using a VPN. Surprisingly, VCs work through the browser or through the official discord application in my mobile. If this is unrelated to vesktop, please relay me to the proper platform to report this. Thanks! 

### What is the expected behaviour?

Join the VC normally

### How do you recreate this bug or crash?

1. Launch discord
2. Join a vc
3. [ScreenRecording of VC not working](https://github.com/user-attachments/assets/d3d4750a-3bdf-46ab-895f-f9ef1240fc77)

### Debug Logs

```
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
Checking for update
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[16621:1103/162343.947658:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Update for version 1.5.3 is not available (latest version: 1.5.3, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[16621:1103/162358.341855:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[16621:1103/162358.346431:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
not a vesktop / vencord issue.

**Comment by i-am-zaidali** [comment]
> not a vesktop / vencord issue.

Sounds like it. I have the normal discord app installed too and I am able to join voice calls through that. It's the vesktop app that doesnt seem to work
