### ISSUE TITLE
[Bug] sound sharing takes up 2.76 more cores max

### ISSUE THREAD

**Issue by TheK0tYaRa** [Vencord/Vesktop#946]
### Discord Account

TheK0tYaRa#9322

### Operating System

Gentoo 2.17

### Linux Only ~ Desktop Environment

Sway, Wayland

### Package Type

.tar.gz release

### What happens when the bug or crash occurs?

The CPU load increases by 2.76 cores at max, from 18% to 40% of whole ryzen 5 2600.

### What is the expected behaviour?

A load on the CPU not doubling by enabling audio in screen share.

### How do you recreate this bug or crash?

1. Enable screen share.
2. Note down the CPU load of vesktop.
3. Enable whole system audio share in screen share.
4. Compare load.

### Debug Logs

```
none relevant
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
This doesn't really have any relevant information that would point to a flaw

Plus it's kinda expected that sharing audio also uses more CPU because it has to
1. record & encode it
2. mix it together with the video track
3. shares more data

Since no one else has reported anything like this I would say this is not a bug and likely not fixable

**Comment by TheK0tYaRa** [comment]
But how does audio mixing and encoding manage to use up more than video encoding?

**Comment by TheK0tYaRa** [comment]
I've compared the load of 720p with audio and OBS recording of 1080p with audio. OBS uses less cpu power. Why?

**Comment by Vendicated** [comment]
you could try opening an issue in the venmic repo instead, but unless you do some benchmarking / debugging to figure out which parts are taking the most cpu, it's unlikely that this can be fixed

**Comment by TheK0tYaRa** [comment]
It seems that the issue requires the call to estimate over an hour, quite an infuriating property to debug.
