### ISSUE TITLE
 Request to revert Vesktop to it's old icon design 

### ISSUE THREAD

**Issue by githlacker** [Vencord/Vesktop#948]
### Content

The current app icon feels less effective visually compared to the previous one. I (and perhaps other users) feel that the old icon was more recognizable, aesthetically pleasing, and aligned better with the app’s identity. Would you consider reverting to the original icon, or perhaps providing an option to choose between them?

![image](https://github.com/user-attachments/assets/c3355d3a-c10e-4d5f-bb3c-d43a7fd047f4)

this sucks

![image](https://github.com/user-attachments/assets/fcedb2ed-3ca4-4500-8e04-14902b36e8c3)

this nice

**Comment by AAGaming00** [comment]
icon cope issue #727274849392991
