### ISSUE TITLE
add compose key supports

### ISSUE THREAD

**Issue by Momma-Eltala** [Vencord/Vesktop#952]
### Discord Account

eltala

### Motivation

Hello! so im on linux, so i use vesktop so i can stream, and have themes, but i notice when i went to use my compose key to put in pi symbole, and notice it does nothing, could we have this has a feature? 

### Solution

i would like it if we could use compose keys like anywhere else

### Alternatives

the only one that worked is discord it self and web

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
nothing to do with vesktop itself + works on my machine. try googling like "electron compose key" and similar stuffs and look for solutions

**Comment by Momma-Eltala** [comment]
I see..
also i just tried something, the defaults works, so i must of messed something up, which is wierd as it works every where else????
