### ISSUE TITLE
[Bug] Getting logged out out after PC restart

### ISSUE THREAD

**Issue by ShadowOnWiiU** [Vencord/Vesktop#955]
### Discord Account

shadmew

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

KDE Wayland

### Package Type

AppImage

### What happens when the bug or crash occurs?

I'm not 100% sure if this is a Vesktop bug, Vencord bug, or if this is an issue with settings - I have reset my settings and it hasn't changed anything
When restarting my PC, or when Vencord updates, it requires me to re-log into my account every time. I have tested discord on the web (firefox) and the official discord package, which both don't have this issue. Is this maybe caused by me using the AppImage?

![image](https://github.com/user-attachments/assets/a5a44d2e-d786-4a5f-b69e-00a3c455add3)

### What is the expected behaviour?

I expect not to be logged out every time I start my PC

### How do you recreate this bug or crash?

1. Log into account
2. Close Vesktop
3. Restart PC
4. Open Vesktop

### Debug Logs

nothing relevant, only arRPC infos

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
please search the existing issues.

**Comment by AstralPhnx** [comment]
> please search the existing issues.

Dawg where is this issue you're referring to that this is a duplicate of because I've searched for it myself and I can't find anything in the issue reports that is either open or closed and of any use whatsoever. If you're going to be like that, please at least point people in the right direction

**Comment by Vendicated** [comment]
You could literally just copy paste the title of this issue in the search bar and get results. It's really not hard to find and you are expected to search existing issues yourself - the issue template explicitly tells you to. I have better things to do than search issues for you

https://github.com/Vencord/Vesktop/issues/346
https://github.com/Vencord/Vesktop/issues/375
https://github.com/Vencord/Vesktop/issues/537
https://github.com/Vencord/Vesktop/issues/742
https://github.com/Vencord/Vesktop/issues/787
https://github.com/Vencord/Vesktop/issues/810
https://github.com/Vencord/Vesktop/issues/872
