### ISSUE TITLE
[Scaling is broken] every button's hitbox is offset from its ui

### ISSUE THREAD

**Issue by aurora-1-2-3** [Vencord/Vesktop#957]
### Discord Account

aurora_123_

### Operating System

Nobara 40

### Linux Only ~ Desktop Environment

KDE plasma

### Package Type

Flatpak

### What happens when the bug or crash occurs?

The hitbox for button are offset from the ui 
e.g,
![image](https://github.com/user-attachments/assets/87c3209b-6a51-4096-be5d-0289aa52f257)
(the cursor is on the blue dot)

### What is the expected behaviour?

I expect vesktop's hitboxes to be on the ui on that button

### How do you recreate this bug or crash?

1. Install flatpak Vesktop
2. Open it
3. Try to click any button

### Debug Logs

```
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto --enable-wayland-ime
[3:1115/110244.923651:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:1115/110245.615451:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1115/110245.615527:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so init failed
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started


```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
Not a vesktop issue.

Try to disable hardware acceleration and make sure you don't have any themes or css that could cause this

**Comment by aurora-1-2-3** [comment]
i cant even open the settings and i have no custom css
