### ISSUE TITLE
[Feature Request] Showing Desktop status instead of Web

### ISSUE THREAD

**Issue by csskroubledev** [Vencord/Vesktop#958]
### Discord Account

csskrouble

### Motivation

It's not really a problem, but I think Vesktop should report the status as if you were on a Desktop client, not Web.

### Solution

Ability to change how Vesktop reports status to Discord

### Alternatives

Change Vesktop to report Desktop status

### Additional context

![image](https://github.com/user-attachments/assets/b6be9110-7183-447d-9020-279e976eb334)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
no.
