### ISSUE TITLE
[Bug] UK English language option is not respected by spellcheck

### ISSUE THREAD

**Issue by anUrbanGoose** [Vencord/Vesktop#959]
### Discord Account

theurbangoose

### Operating System

Linux Mint 22 Cinnamon

### Linux Only ~ Desktop Environment

Gnome on Xorg

### Package Type

Flatpak

### What happens when the bug or crash occurs?

I have selected UK English in both my system settings, and the Discord setting, but if I use UK English spelling in my discord messages, spellcheck marks it as incorrect, and suggests the US spelling:
![image](https://github.com/user-attachments/assets/eacbd72d-b900-4bc9-abe7-c6cde9f3aa38)
![image](https://github.com/user-attachments/assets/56a719e6-d639-4add-b8d6-872aed250cb4)
![image](https://github.com/user-attachments/assets/20106a3a-692f-4a40-9c52-be3b8159d378)

### What is the expected behaviour?

I expect Vesktop to accept only the UK spelling, or both spellings, when UK English is selected.

### How do you recreate this bug or crash?

1. Set Discord language to UK English
2. Type a word using UK spelling (example: US - color, UK - colour)
3. Vesktop will mark the UK spelling as incorrect.

### Debug Logs

N/A

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
right click chat box > Spellcheck Settings > Languages > only check en-GB

**Comment by anUrbanGoose** [comment]
Fair, I missed that.

**Comment by AAGaming00** [comment]
just dont be british

**Comment by anUrbanGoose** [comment]
I'm not, I just prefer traditional English to simplified English
