### ISSUE TITLE
Unable to pin Vesktop due to mismatched WMClass on Linux

### ISSUE THREAD

**Issue by iiPythonx** [Vencord/Vesktop#96]
Running 0.3.0 out of the box. Vesktop loads perfectly fine, icon loads, except I can't right click to pin Vesktop to my dock. This action works fine for every other app I have except Vesktop.

Digging into `/usr/share/applications/vencorddesktop.desktop` I see that:
```
StartupWMClass=Vesktop
```
However, running `xprop WM_CLASS` and selecting Vesktop gives me:
```> xprop WM_CLASS
WM_CLASS(STRING) = "vencorddesktop", "VencordDesktop"
```

Setting `StartupWMClass` to "vencorddesktop" and running `update-desktop-database` fixes the issue of being unable to pin Vesktop. However then the icon breaks (at least on my system, with no particular obvious reason as to why), however I fixed this just by manually setting `Icon` to `/usr/share/icons/hicolor/0x0/apps/vencorddesktop.png`.

Assuming that this is reproducible, it should just be a simple update to the .desktop file.

**Comment by lewisakura** [comment]
This is probably an artefact left over from the Vencord Desktop -> Vesktop rebranding. I'll PR the change to revert the WM class since we still use "VencordDesktop" internally in multiple places and I'm fairly certain our build process is the one setting this.
