### ISSUE TITLE
[Feature Request] Voice Chat Activities

### ISSUE THREAD

**Issue by carlos-planelles** [Vencord/Vesktop#962]
### Discord Account

gerlesh

### Motivation

Whenever I'm trying to join a voice chat activity (i.e. Farm Merge Valley) with my friends, I have to go on mobile or launch the browser client of Discord because on Vesktop I'll just get a black screen. 

### Solution

Voice chat activities work as expected on Vesktop (i.e. not a black screen).

### Alternatives

The browser client and mobile work fine, so if I want to open the activity I can launch there, but ideally I can just use my regular client (Vesktop).

### Additional context

I am on Arch Linux (hybrid AMD/NVidia graphics) and using the Hyprland compositor.
I'm not sure if this is more of a bug that just isn't working for me, so I tried troubleshooting a bit (hardware acceleration on/off, reboot, etc.) but wasn't able to get any improvements.
Also not sure whether this would be a Vencord or a Vesktop related request, so if this is the wrong place please let me know and I'll fix it.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
not a vesktop / vencord issue
