### ISSUE TITLE
[Bug] Audio No Longer Functions for Vesktop, Specifically

### ISSUE THREAD

**Issue by ThisNekoGuy** [Vencord/Vesktop#965]
### Operating System

Gentoo Linux (x86_64)

### Linux Only ~ Desktop Environment

KDE Plasma 6.1.5 (Wayland)

### Package Type

(Both) Flatpak and [Gentoo Package](https://github.com/gentoo/guru/blob/master/net-im/vesktop-bin/vesktop-bin-1.5.3.ebuild)

### What happens when the bug or crash occurs?

Launching Vesktop mutes effectively all audio within the app.
I did a Vesktop update before this happened, so I'm not sure if it had anything to do with it, but I deleted the entire `sessionData` folder and the issue still persists regardless of the installed version of Vesktop (both for the Flatpak and distro package).

### What is the expected behaviour?

Audio should not be muted across the entire app; this happening was very unexpected.

### How do you recreate this bug or crash?

1. Launch Vesktop
2. Click the `mute mic` button to check if it makes sounds (or alternatively join a stream, test the mic volume in the Discord settings, spam-click the Discord icon to attempt getting the Japanese Discord greeting, etc)

### Debug Logs

```
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto --enable-wayland-ime
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[130:1119/191611.891058:ERROR:ffmpeg_common.cc(959)] Unsupported pixel format: -1
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
system issue

**Comment by ThisNekoGuy** [comment]
Sorry about that; somehow it was because **Plasma** _muted_ Vesktop for some reason even though I swear I never did (because I have no reason to)...

**Comment by Vendicated** [comment]
lmao 😄 shit happens
