### ISSUE TITLE
[Feature Request] Add cmd option to run in background

### ISSUE THREAD

**Issue by theaino** [Vencord/Vesktop#974]
### Discord Account

theaino

### Motivation

I am running hyprland and I want to run vesktop at the start (to see all notifications, be marked as online etc)  but the only thing I can do is `flatpak run dev.vencord.Vesktop`, opening it fully.

### Solution

There should be a flag (like `--silent`) to run vesktop in the background.

### Alternatives

There does exist a "stay in tray" option, but it just doesn't seem to work/seem fitted for this problem.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/issues?q=sort%3Aupdated-desc+is%3Aissue+start+minimized+
