### ISSUE TITLE
[Feature Request] Custom Keyboard Shortcuts for Wayland Compatibility

### ISSUE THREAD

**Issue by NitramO-YT** [Vencord/Vesktop#975]
### Discord Account

nitramo

### Motivation

I noticed that Vesktop does not currently support adding custom keyboard shortcuts for actions like *toggle mute* or *toggle deaf*, which is something available in native Discord. Since i switched from native Discord to Vesktop because of issues under my KDE Neon Wayland (screen sharing bridge opens in loop and crashes, sound sharing is unsupported, etc...) it would be great to have this ability in Vesktop.  

I saw an existing request for custom shortcuts (#18), but it is closed, and the pull request linked to it (#326) seems to rely on *venbind*. From what I understand, *venbind* may not be fully compatible with Wayland, though I am not entirely sure.  

### Solution

A feature in Vesktop to configure custom keyboard shortcuts for actions like *toggle mute*, *toggle deaf*, ..., without relying on dependencies that might not work with Wayland.  

Ideally, this would involve:  
- A settings panel in Vesktop where users can assign shortcuts to common actions.  
- Ensuring compatibility with Wayland natively, or finding a workaround that allows these shortcuts to function properly.  

### Alternatives

- Using external tools, but this adds complexity and may not integrate well with my KDE/Wayland.  
- Leveraging existing solutions like *venbind*, though from what I understand, it may not work reliably under Wayland. (so using X11 everyday instead of Wayland just because of that)
- Falling back to native Discord, but that isn’t viable due to Wayland-related issues.  

### Additional context

I found this previous request: https://github.com/Vencord/Vesktop/issues/18. Since it is closed, I am unable to ask for clarification or confirm if the pull request (#326) fully resolves this issue for Wayland users.  

If this feature is already implemented or a solution exists, it would be great to have more information. Otherwise, I believe this could benefit Wayland users significantly, given the increasing adoption of Wayland among Linux users.  

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
duplicate of #18.

**Comment by NitramO-YT** [comment]
> duplicate of #18.

#18 is closed (so i couldn't ask for update on it) and don't seem to take take into account Wayland case!

**Comment by NitramO-YT** [comment]
Can you be more precise on your answer? Is it planned to be fixed? Is it currently being fixed?

**Comment by Vendicated** [comment]
yes, we are taking wayland into account. at this point, supporting wayland is impossible though. no, there is no ETA

**Comment by NitramO-YT** [comment]
Okay, thx for the info! Do you know any alternative way or something i could do by myself on my system to get as close as possible to this solution?
