### ISSUE TITLE
[Bug] Windows installer reports existing installation during first installation

### ISSUE THREAD

**Issue by Terrance** [Vencord/Vesktop#976]
### Operating System

Windows 10

### Package Type

Installer

### What happens when the bug or crash occurs?

Having downloaded this for the first time, I was surprised to find the installer claiming an installation already exists:

![Installer claiming per-user installation exists](https://github.com/user-attachments/assets/842a95e1-068d-4dc5-98c5-6f8f64e1a9b3)

Double-checked that path just in case I had encountered this project before, but alas: the path doesn't exist.

### What is the expected behaviour?

Assuming it is indeed a new installation, the description should read like the one for all users (e.g. "Fresh installation for $user.").

### How do you recreate this bug or crash?

Just opened the installer 🙂

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
Thanks for your report

The installer is just nsis configured by electron-builder, so there's nothing we can do about this. You could try to reproduce it with a minimal electron-builder setup and report it to them if you want

Anyway, this doesn't really seem like an important issue that needs fixing, so I'll be closing this
