### ISSUE TITLE
[Feature Request] Discord has moved browser bot invites in-app, support that webhook

### ISSUE THREAD

**Issue by Ast3risk-ops** [Vencord/Vesktop#977]
### Discord Account

@ast3riskinc

### Motivation

Bot invites don't work at all. You need the official app because Vesktop doesn't support them (when opened from browser)

### Solution

Support that webhook or thing it uses.

### Alternatives

The official app (🤮)

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
https://github.com/Vencord/Vesktop/pull/813
