### ISSUE TITLE
[Bug] Vesktop claims it has no microphone access on Windows

### ISSUE THREAD

**Issue by tbeest** [Vencord/Vesktop#978]
### Operating System

Windows 11

### Package Type

Setup exe

### What happens when the bug or crash occurs?

Vesktop says it has no microphone access, despite microphone access being generally allowed in Windows' settings.
I can even select one of various inputs, so it must detect something is there. Yet it doesn't work. It didn't give any pop-up after running the installer. 
Is this some sort of issue with the embedded web page I don't know how to fix?

![image](https://github.com/user-attachments/assets/1f253349-ac8b-4e48-9c7b-1c13614dcca3)
![image](https://github.com/user-attachments/assets/e70594ca-af30-4687-acf3-4828add96498)

### What is the expected behaviour?

I expect Vencord to allow for microphone input. Either by taking what's there, or prompting for access like webpages do.

### How do you recreate this bug or crash?

I installed Vencord on Windows 11

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
try reinstalling the app. if that doesn't fix it, we can't help you, it's an issue with your system

**Comment by tbeest** [comment]
I did try both a reinstall and a restart, unfortunately to no avail. Trying some commands in the console, it seems the permission somehow got rejected? JavaScript isn't my wheelhouse.

If you have any directions on where to search for more details, or a more fitting command to run for the permission pop-up, that'd be greatly appreciated.
Does Vesktop rely on Edge in any way on Windows?
![image](https://github.com/user-attachments/assets/a26cf129-e721-402e-8c22-51ac2582f70b)
```
navigator.mediaDevices.getUserMedia({audio:true}).then(function(stream){})
Promise {<pending>}[[Prototype]]: Promise[[PromiseState]]: "rejected"[[PromiseResult]]: DOMException: Could not start audio source
1012012195254636544:1 Uncaught (in promise) DOMException: Could not start audio source
```
