### ISSUE TITLE
[Feature Request] "--enable-low-end-device-mode" Launch command that reduces RAM by clearing memory cache of inactive tabs

### ISSUE THREAD

**Issue by CatchFirez** [Vencord/Vesktop#979]
### Discord Account

catchfirez

### Motivation

Discord RAM increases alot when switching servers/DMs.

### Solution

This could be added as an experimental option in Vesktop settings.

### Alternatives

An option that a user can toggle to freeze Discord process while also receiving notifications.

### Additional context

You must disable hardware acceleration in order for it to not enable 16 bit colors for images. The renderer uses less than 400MB of RAM for me.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
this option likely does nothing because there is always exactly one tab and no inactive tabs

if users really want to use it, they can just pass it to the vesktop binary when launching
