### ISSUE TITLE
[Bug] <UI Scaling Broken>

### ISSUE THREAD

**Issue by GleamingPulsar** [Vencord/Vesktop#980]
### Operating System

Linux Mint 22

### Linux Only ~ Desktop Environment

Cinnamon on Xorg

### Package Type

Flatpak

### What happens when the bug or crash occurs?

Even when hardware acceleration is disabled, vesktop's ui continues to not scale.

### What is the expected behaviour?

Vesktop's UI scales when it's corners are dragged.

### How do you recreate this bug or crash?

In this instance it just happened. I was tabbed out using Krita, and when I tabbed back into vesktop the ui was small. I have encountered the bug in an instance where I accidentally dragged part of the ui, and it shrunk, and it couldn't be scaled back, but this seems to be a different example.

### Debug Logs

```
~$ flatpak run dev.vencord.Vesktop
Passing the following arguments to Electron: --enable-speech-dispatcher
[3:1130/135958.320375:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
Gtk-Message: 13:59:58.559: Failed to load module "xapp-gtk3-module"
[3:1130/135958.664861:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1130/135958.664993:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started

```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by GleamingPulsar** [comment]
I'm using a supported branch (xorg with the flatpak?)? This is a system issue, and the template was inaccurate (The issue was not resolved the way you said it was.). Please don't just ignore this when I'm using a supported branch and your template doesn't account for this situation.

**Comment by Vendicated** [comment]
it's not a vesktop issue. it's either related to your system or to electron / chromium.
