### ISSUE TITLE
[Bug] Bottom of Screen Won't Update

### ISSUE THREAD

**Issue by EvantheGrump** [Vencord/Vesktop#981]
### Discord Account

EvantheGrump

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Hyprland with Wayland

### Package Type

AppImage

### What happens when the bug or crash occurs?

The bottom of the window will not update if the mouse is anywhere on the window. I can scroll, and the top of the interface will scroll, while the bottom remains as what it was when I first moused over the Vesktop window. This happens consistently on both of my monitors, though this issue does not occur while the window is in fullscreen mode/the only window on the monitor. Below is a video example of this occurring.

https://github.com/user-attachments/assets/2c94e2b1-d6ba-4715-9723-74ab90b66f8d

This video was taken with hardware acceleration **off**, as well as with all themes/plugins enabled/disabled.

### What is the expected behaviour?

I expect the window to update correctly.

### How do you recreate this bug or crash?

I installed the latest version of Vesktop, I sign in, open a window beside Vesktop, and scroll in any interface.

### Debug Logs

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Checking for update
[128067:1130/200302.113640:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[128067:1130/200302.113669:ERROR:select_file_dialog_linux_portal.cc(291)] Failed to read portal version property
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
Update for version 1.5.3 is not available (latest version: 1.5.3, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
not a vesktop issue. please read the issue template more carefully

![image](https://github.com/user-attachments/assets/9ec31dcf-9899-4d42-864b-33489e6e2abd)

![image](https://github.com/user-attachments/assets/e8f576d8-182d-450d-9b01-d2c1a478574d)

**Comment by EvantheGrump** [comment]
I did read it. The recommended fix failed, and so I thought it suitable to post.

**Comment by EvantheGrump** [comment]
Thanks, I appreciate your advice. It seems that xWayland and electron are extremely prone to extemporaneous graphical issues, so I'll keep looking down those paths.
