### ISSUE TITLE
[Bug] Surround client not handled correctly

### ISSUE THREAD

**Issue by pallaswept** [Vencord/Vesktop#982]
### Operating System

openSUSE Tumbleweed

### Linux Only ~ Desktop Environment

KDE Wayland

### Package Type

AppImage

### What happens when the bug or crash occurs?

My system is configured to use surround audio (5.1) by default. Accordingly, the audio I attempt to capture with vencord, have nodes with 6 ports.

The vencord-screen-share node has only two input ports. Normally, connections from 6 ports to 2, would require some kind of mixdown, but none is performed. Rather, only the first two channels are captured.

### What is the expected behaviour?

Capture all channels of selected audio stream.

### How do you recreate this bug or crash?

1. Play audio to a surround device (application's client node will become surround)
2. Capture audio with vencord
3. Check connections eg with qpwgraph to confirm that not all channels are captured

### Debug Logs

No crash occurs

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
If you are reporting that the screenshare audio is mono, then yes that is known. Otherwise, you should open this issue in https://github.com/Vencord/venmic instead
