### ISSUE TITLE
I want to help fix bugs but I don't have the ability to refile them

### ISSUE THREAD

**Issue by pallaswept** [Vencord/Vesktop#983]
### Content

https://github.com/Vencord/venmic/issues/35

https://github.com/Vencord/venmic/issues/36

Sorry guys my hands are busted up (I'm disabled) I can't do this again. Feel free to re-file these appropriately if you'd like to fix them.

**Comment by Curve** [comment]
venmic#35 and #982 are not related, vee told you to file #982 in the venmic repo instead as that's actually related to audio sharing.

Mixdown for multi channel can get a little cumbersome and I don't like the idea of venmic handling that itself - instead as the audio share is made mono on discords server side anyways, I could make the Venmic node mono as well and simply link all ports there which would circumvent the need for any special multi channel handling

**Comment by Vendicated** [comment]
I transferred your surround issue to the venmic repo
