### ISSUE TITLE
[Bug] Unable to screenshare

### ISSUE THREAD

**Issue by fromtheeast710** [Vencord/Vesktop#985]
### Discord Account

east710#yeast710

### Operating System

Artix Linux 6.12.1-artix1-1

### Linux Only ~ Desktop Environment

Hyprland on Wayland

### Package Type

vesktop_1.5.3_amd64.deb

### What happens when the bug or crash occurs?

When I join a voice channel and click on the screen share button, nothing happens and this message is outputted to the terminal.

### What is the expected behaviour?

A window pop up showing a preview of my current screen and allow me to start sharing.

### How do you recreate this bug or crash?

1. Join a voice channel.
2. Press the screen sharing button.

### Debug Logs

```
[20238:1203/120830.239101:ERROR:screen_capture_portal_interface.cc(28)] Failed to get a proxy for the portal: Unknown or unsupported transport “disabled” for address “disabled:”
[20238:1203/120830.239130:ERROR:base_capturer_pipewire.cc(81)] ScreenCastPortal failed: 3
Error during screenshare picker Failed to get sources.
(node:20238) UnhandledPromiseRejectionWarning: TypeError: Video was requested, but no video stream was provided
    at AsyncFunction.<anonymous> (VCDMain:87:5244)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:20238) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
issue with your system. we can't help you
