### ISSUE TITLE
[Bug] <title> Cant hear ppl in voice chat while turn on cloudflare

### ISSUE THREAD

**Issue by tommy3210** [Vencord/Vesktop#986]
### Operating System

Window 11

### Package Type

Setup.exe

### What happens when the bug or crash occurs?

Can't hear anythings or say anythings after turning on Cloudflare

### What is the expected behaviour?

When i have a normal voice chat with friends, i turn on Cloudflare and everything's become silend. i can't hear anythings or say anythings. after that i turn off cloudflare and it's become normal

### How do you recreate this bug or crash?

1. open discord
2. join a voice chat
3. turn on cloudflare

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
not a vesktop issue
