### ISSUE TITLE
[Feature Request] Support `HTTP_PROXY` environment variables

### ISSUE THREAD

**Issue by winstxnhdw** [Vencord/Vesktop#987]
### Motivation

When trying to run Vesktop under a company proxy, I get a TLS handshake error.

```
Failed to fetch https://api.github.com/repos/Vendicated/Vencord/releases/latest. Gonna retry with backoff.
```

Obviously, this is happening because Vesktop doesn't inherit the `HTTP_PROXY` environment variables from the shell or the OS.

### Solution

Just let `fetch` or whatever lib you are using inherit the `HTTP_PROXY` environment.

### Alternatives

There is none.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [ ] This is not a plugin request
- [ ] This is not a Vencord feature request

**Comment by Vendicated** [comment]
https://www.electronjs.org/docs/latest/api/command-line-switches#--proxy-serveraddressport

**Comment by winstxnhdw** [comment]
Does the Vesktop binary even inherit the electron switches?

**Comment by Taner314** [comment]
@winstxnhdw using flatpack version, starting discord with this works:
`flatpak run dev.vencord.Vesktop --proxy-server=socks5://192.168.0.1:39441`

**Comment by winstxnhdw** [comment]
Doesn't work on the standard binary.
