### ISSUE TITLE
[Feature Request] Improved support for streaming on Wayland

### ISSUE THREAD

**Issue by VolRencs** [Vencord/Vesktop#989]
### Discord Account

volrencs

### Motivation

At the moment the streams on wayland are quite poor quality, to put it mildly they are pixilated. And if you switch to the quality of the stream, it hangs. I would like to get the same quality as on Windows.

### Solution

After adding experimental support for streaming on wayland in Discord, will this somehow improve the quality of streaming in vesktop after this feature comes out of experimental?

### Alternatives

I don't think there are any alternatives here.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
fixed in 1.5.4

**Comment by VolRencs** [comment]
Tested it on several systems. With different people. And what can I say, after a few minutes the stream looks like this:

![Image](https://github.com/user-attachments/assets/4be9e1de-e052-455b-aadb-d4f69c840461)

There is even more blurring in motion.

**Comment by VolRencs** [comment]
@Vendicated 
Or worse:

![Image](https://github.com/user-attachments/assets/3fdc6319-c9d5-4cda-bd88-781a09fc5ae7)

This is the only thing that is so discouraging about using Vesktop under linux.

**Comment by vannotz** [comment]
Any updates on these?
