### ISSUE TITLE
[Bug] White screen, javascript error.

### ISSUE THREAD

**Issue by Kangie** [Vencord/Vesktop#992]
### Operating System

Gentoo Linux

### Linux Only ~ Desktop Environment

Plasma 6 Wayland

### Package Type

-deb

### What happens when the bug or crash occurs?

Attempting to open vesktop results in a white screen. When run from the terminal the following errer and trace are output.

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
    at fileURLToPath (node:internal/url:1487:11)
    at VCDMain:11:786
    at VCDMain:1:225
    at VCDMain:11:1959
    at VCDMain:1:225
    at VCDMain:11:4432
    at VCDMain:1:225
    at VCDMain:15:5118
    at VCDMain:1:225
    at Object.<anonymous> (VCDMain:87:336)
```

### What is the expected behaviour?

I expect the app to launch.

### How do you recreate this bug or crash?

open vesktop-bin.

### Debug Logs

See above.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
this issue happens because you are building from source incorrectly. use one of our official builds and it will work fine

**Comment by Kangie** [comment]
I _am_ using your deb package.

**Comment by Kangie** [comment]
This is your prebuilt source. I was able to resolve via right-clicking on the system tray icon and selecting `repair Vencord` but I figured reporting a valid bug against your binary package would be appreciated. I guess not.

**Comment by Kangie** [comment]
@Vendicated Please don't see "Gentoo" and assume "They compiled it wrong".

**Comment by Vendicated** [comment]
Your stacktrace mentions `fileURLToPath`. The only thing using this function in Vencord & Vesktop is arRPC, which we specifically patch to remove this call. As such, it's impossible for this error to happen on an official build. It can only occur if you build from source without applying the patch. Yes, you compiled it wrong.

https://github.com/Vencord/Vesktop/blob/6c4ecc0d64a843ec942b4fa645c0bfe617b21257/patches/arrpc%403.5.0.patch#L1-L14

Anyway it doesn't really matter, happy you managed to solve it! :)

**Comment by Kangie** [comment]
@Vendicated . This is _your official deb_. Here is my packaging.

I use the official deb package as my source:

https://github.com/Kangie/kangie-tools/blob/554c033df8788ef634ec3a5cdd92a1d69ad6378e/net-im/vesktop-bin/vesktop-bin-1.5.4.ebuild#L11

I unpack and install the files.

https://github.com/Kangie/kangie-tools/blob/554c033df8788ef634ec3a5cdd92a1d69ad6378e/net-im/vesktop-bin/vesktop-bin-1.5.4.ebuild#L59-L66

If someone is compiling this wrong it can't possibly be me.

**Comment by Kangie** [comment]
I did once have a compiled vesktop that I was playing with, a while ago. Is it possible that vesktop and vesktop-bin store/cache stuff outside of their install locations?

**Comment by Vendicated** [comment]
i don't really know how gentoo packages work - are you copying the `resources` folder over from the Vesktop deb package? Specifically `resources/app.asar`, that's what contains all of Vesktop's code. you don't seem to specify it in `QA_PREBUILT`

if you don't, it might have still been using your custom built app.asar

for reference, app.asar contains the entire application logic, the main binary is simply rebranded electron (that's how every electron app works)

**Comment by Vendicated** [comment]
why are you using the .deb anyway? using the tarball build should be much less cursed

**Comment by Kangie** [comment]
> why are you using the .deb anyway? using the tarball build should be much less cursed

I needed something quick and assumed that the `tgz` wasn't compiled, tbh. I'll take a peek inside and maybe switch it over, however the deb is smaller.

I have to package up `node_modules` for offline (from-source) builds as our non-vcs build process is sandboxed. It's on my todo among a ton of other projects, not that it makes a huge difference for electron!

> i don't really know how gentoo packages work - are you copying the `resources` folder over from the Vesktop deb package? Specifically `resources/app.asar`, that's what contains all of Vesktop's code. you don't seem to specify it in `QA_PREBUILT`

Yes, everything gets installed (copied from the unpacked `.deb`) to `/opt/Vesktop`. 

```
 ls /opt/Vesktop/resources -la
total 9280
drwxr-xr-x 1 root root      68 Dec  7 09:05 .
drwxr-xr-x 1 root root     598 Dec  7 09:05 ..
-rw-r--r-- 1 root root 9494233 Dec  6 05:50 app.asar
-rw-r--r-- 1 root root      83 Dec  6 05:53 app-update.yml
-rw-r--r-- 1 root root       3 Dec  6 05:53 package-type
```

> for reference, app.asar contains the entire application logic, the main binary is simply rebranded electron (that's how every electron app works)

Indeed. No idea where it got confused here. Thanks for your work!

**Comment by Vendicated** [comment]
well no clue why it happened then. considering a repair fixed it, the file likely got corrupted in some way. probably not something worth investigating

the [`vesktop-1.5.4.tar.gz`](https://github.com/Vencord/Vesktop/releases/download/v1.5.4/vesktop-1.5.4.tar.gz) file is a compiled build that you just extract and it's good to go. it would be best to switch to it considering the `.deb` includes auto-update logic which might behave weirdly for you (honestly not sure). Not sure why the .deb would be smaller since the contents should be the same. Perhaps, deb compresses better

alternatively, it might actually be better to extract the AppImage file since it contains a `.desktop` file you can use. See our [flatpak build](https://github.com/flathub/dev.vencord.Vesktop/blob/b55f7ec286f070143b3c9f9048cf043817aebba2/dev.vencord.Vesktop.yml#L33-L44) for how to do that
