### ISSUE TITLE
[Bug] 1.5.4 drops Catalina support and keeps trying to update to the unsupported version from 1.5.3

### ISSUE THREAD

**Issue by FanACYT** [Vencord/Vesktop#994]
### Operating System

macOS Catalina 10.15.7

### Package Type

n/a

### What happens when the bug or crash occurs?

Every startup it keeps trying to update to 1.5.4 which doesn't support Catalina anymore

### What is the expected behaviour?

I expect it to detect that its running on Catalina and not try to update to the latest version
### How do you recreate this bug or crash?

1: Open Vesktop
2: Wait for the update to be detected
3: Close Vesktop

### Debug Logs

```
none needed
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by FanACYT** [comment]
update: seems like doing show package contents, going to the Contents/Resources and deleting the app_update.yml file gets it to stop updating for now

**Comment by Vendicated** [comment]
Catalina is no longer supported by Apple and Chromium officially dropped support for it now. 1.5.4 updates to the latest chromium version so as a consequence it also drops Catalina support

https://www.electronjs.org/docs/latest/breaking-changes#removed-macos-1015-support

You should really consider updating your system.

For now, you can keep using 1.5.3 or [build from source](https://github.com/Vencord/Vesktop?tab=readme-ov-file#building-from-source) and downgrade electron to v32: Run `pnpm i electron@32` after the `pnpm i`

Vesktop will most likely not support Catalina anymore unless there is a lot of demand
