### ISSUE TITLE
[Bug] Vesktop crashes

### ISSUE THREAD

**Issue by UsernameFurkanIsNotAvailable** [Vencord/Vesktop#995]
### Content

Hi, there's a problem with vesktop. I don't know what the issue is, but I have a screenshot below
![Screenshot 2024-12-07 215355](https://github.com/user-attachments/assets/8b579574-e120-4d8b-a727-9a8dbd1bced7)

**Comment by Vendicated** [comment]
you have provided zero information. try to reinstall vesktop or repair vencord

if it still happens, use our support channel for help

**Comment by Vendicated** [comment]
**if it still happens, use our support channel for help**
