### ISSUE TITLE
[Bug] Weird artifacts and low quality when screensharing from Vesktop to official client

### ISSUE THREAD

**Issue by Skeletonek** [Vencord/Vesktop#997]
### Discord Account

skeletonek

### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

KDE Plasma 6.2

### Package Type

AppImage

### What happens when the bug or crash occurs?

Users on official discord client are seing weird color artifacts and a very low stream quality

Screenshot from my friend when I (on Vesktop) was streaming Serious Sam: Siberian Mayhem to him

![image](https://github.com/user-attachments/assets/9c31c98e-dae9-4bf1-9547-5e22af07c883)

Comparison between screenshare and OBS Virtual Camera
![image](https://github.com/user-attachments/assets/f7953664-c99e-47da-bb39-e8a93cdb616e)

This bug doesn't occur when viewer is using the web client

I have used the custom built appimage and a package from this repo. No difference

### What is the expected behaviour?

Proper colors with decent video quality

### How do you recreate this bug or crash?

1. Launch Vesktop and connect with someone who uses official client
2. Start screenshare on Vesktop
3. Start watching on official client
4. After a couple of seconds or minutes, on official client the stream should start having color artifacts

### Debug Logs

```
No crash log
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by UmJammerRammy** [comment]
Same issue on Archlinux with amd GPU on hyprland. doesn't seem to be an issue with my encoding though as im able to stream to the web client, official discord linux client, and vesktop on windows just fine, only the official windows client has artifacting when receiving the stream. probably still upstream but seems to be an issue with the receiving client, not the stream itself
